In [1]:
from catboost import CatBoostClassifier
from category_encoders import TargetEncoder
from pandas import read_csv

df = read_csv("ml-fundamentals-and-applications-2025-10/final_proj_data.csv")
df.head()

,Var1,Var2,Var3,Var4,Var5,Var6,Var7,Var8,Var9,Var10,...,Var222,Var223,Var224,Var225,Var226,Var227,Var228,Var229,Var230,y
0,NaN,NaN,NaN,NaN,NaN,812.0,14.0,NaN,NaN,NaN,...,catzS2D,jySVZNlOJy,NaN,xG3x,Aoh3,ZI9m,ib5G6X1eUxUn6,mj86,NaN,0
1,NaN,NaN,NaN,NaN,NaN,2688.0,7.0,NaN,NaN,NaN,...,i06ocsg,LM8l689qOp,NaN,kG3k,WqMG,RAYp,55YFVY9,mj86,NaN,0
2,NaN,NaN,NaN,NaN,NaN,1015.0,14.0,NaN,NaN,NaN,...,P6pu4Vl,LM8l689qOp,NaN,kG3k,Aoh3,ZI9m,R4y5gQQWY8OodqDV,am7c,NaN,0
3,NaN,NaN,NaN,NaN,NaN,168.0,0.0,NaN,NaN,NaN,...,BNrD3Yd,LM8l689qOp,NaN,NaN,FSa2,RAYp,F2FyR07IdsN7I,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,14.0,0.0,NaN,NaN,NaN,...,3B1QowC,LM8l689qOp,NaN,NaN,WqMG,RAYp,F2FyR07IdsN7I,NaN,NaN,0

In [2]:
from home_works.machine_learning.final_project.util import get_nan_percentage

allowed_columns = df.loc[:, get_nan_percentage(df) <= 50].columns.tolist()

df_cleaned = df[allowed_columns]
df_cleaned.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228,y
0,812.0,14.0,1252.0,156.0,195.0,0.0,40.0,286.96,0.0,4850466.0,...,cJvF,AU8_WTd,4UxGlow,zCkv,catzS2D,jySVZNlOJy,Aoh3,ZI9m,ib5G6X1eUxUn6,0
1,2688.0,7.0,8820.0,364.0,455.0,4.0,288.0,200.00,0.0,132072.0,...,UYBR,AU8pNoi,GpvRJ5l,oslk,i06ocsg,LM8l689qOp,WqMG,RAYp,55YFVY9,0
2,1015.0,14.0,1784.0,136.0,170.0,2.0,40.0,294.48,0.0,3223524.0,...,cJvF,FzaX,ch2oGfM,zCkv,P6pu4Vl,LM8l689qOp,Aoh3,ZI9m,R4y5gQQWY8OodqDV,0
3,168.0,0.0,0.0,24.0,30.0,0.0,0.0,644.24,0.0,2135430.0,...,cJvF,FzaX,kH5mFX7,oslk,BNrD3Yd,LM8l689qOp,FSa2,RAYp,F2FyR07IdsN7I,0
4,14.0,0.0,0.0,36.0,45.0,0.0,0.0,239.84,0.0,3110400.0,...,cJvF,FzaX,x_lYlW4,oslk,3B1QowC,LM8l689qOp,WqMG,RAYp,F2FyR07IdsN7I,0

In [3]:
num_cols = df_cleaned.select_dtypes(include=["number"]).columns.tolist()
num_cols.remove("y")
num_cols

['Var6',
 'Var7',
 'Var13',
 'Var21',
 'Var22',
 'Var24',
 'Var25',
 'Var28',
 'Var35',
 'Var38',
 'Var44',
 'Var57',
 'Var65',
 'Var72',
 'Var73',
 'Var74',
 'Var76',
 'Var78',
 'Var81',
 'Var83',
 'Var85',
 'Var94',
 'Var109',
 'Var112',
 'Var113',
 'Var119',
 'Var123',
 'Var125',
 'Var126',
 'Var132',
 'Var133',
 'Var134',
 'Var140',
 'Var143',
 'Var144',
 'Var149',
 'Var153',
 'Var160',
 'Var163',
 'Var173',
 'Var181']

In [4]:
cat_cols = df_cleaned.drop(columns=num_cols).columns.tolist()
cat_cols.remove("y")
cat_cols

['Var192',
 'Var193',
 'Var195',
 'Var196',
 'Var197',
 'Var198',
 'Var199',
 'Var200',
 'Var202',
 'Var203',
 'Var204',
 'Var205',
 'Var206',
 'Var207',
 'Var208',
 'Var210',
 'Var211',
 'Var212',
 'Var214',
 'Var216',
 'Var217',
 'Var218',
 'Var219',
 'Var220',
 'Var221',
 'Var222',
 'Var223',
 'Var226',
 'Var227',
 'Var228']

In [5]:
from home_works.machine_learning.final_project.util import split_df_to_x_y

X, y = split_df_to_x_y(df_cleaned, "y")

In [6]:
from home_works.machine_learning.final_project.util import VarMeanEstimator
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

num_data_prep = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("var_mean", VarMeanEstimator(col_name="VarMean", cols_to_mean=num_cols))
])

num_data_prep.set_output(transform="pandas")

X_num = num_data_prep.fit_transform(X[num_cols])

X_num.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var140,Var143,Var144,Var149,Var153,Var160,Var163,Var173,Var181,VarMean
0,-0.212337,1.192359,0.017317,-0.142524,-0.140019,-0.488119,-0.263571,0.641706,-0.228852,0.817387,...,-0.291121,-0.085463,1.354143,-0.389478,1.040498,-0.086067,-0.553093,-0.046956,-0.225677,0.238947
1,0.617608,0.020968,2.832081,0.253591,0.255808,-0.024392,0.943577,-0.252876,-0.228852,-0.804485,...,-0.408379,-0.085463,-0.223836,0.216229,-0.984923,-0.198993,0.063617,-0.046956,-0.225677,0.081564
2,-0.122530,1.192359,0.215183,-0.180612,-0.178080,-0.256256,-0.263571,0.719067,-0.228852,0.258152,...,1.487849,-0.085463,1.354143,0.454210,1.007088,-0.131238,0.611261,-0.046956,-0.225677,0.228111
3,-0.497243,-1.150423,-0.448339,-0.393904,-0.391218,-0.488119,-0.458272,4.317150,-0.228852,-0.115863,...,-0.428480,-0.085463,-0.223836,-0.389478,1.202683,-0.379674,-0.553093,-0.046956,-0.225677,0.028790
4,-0.565373,-1.150423,-0.448339,-0.371052,-0.368381,-0.488119,-0.458272,0.156969,-0.228852,0.219268,...,-0.428480,-0.085463,-1.012826,-0.389478,-0.840864,-0.402259,-0.553093,-0.046956,-0.225677,-0.383421

In [7]:
from home_works.machine_learning.final_project.util import concat_dfs

X_final = concat_dfs(X_num, X[cat_cols])
X_final.head()

,Var6,Var7,Var13,Var21,Var22,Var24,Var25,Var28,Var35,Var38,...,Var217,Var218,Var219,Var220,Var221,Var222,Var223,Var226,Var227,Var228
0,-0.212337,1.192359,0.017317,-0.142524,-0.140019,-0.488119,-0.263571,0.641706,-0.228852,0.817387,...,G8WR,cJvF,AU8_WTd,4UxGlow,zCkv,catzS2D,jySVZNlOJy,Aoh3,ZI9m,ib5G6X1eUxUn6
1,0.617608,0.020968,2.832081,0.253591,0.255808,-0.024392,0.943577,-0.252876,-0.228852,-0.804485,...,5smi,UYBR,AU8pNoi,GpvRJ5l,oslk,i06ocsg,LM8l689qOp,WqMG,RAYp,55YFVY9
2,-0.122530,1.192359,0.215183,-0.180612,-0.178080,-0.256256,-0.263571,0.719067,-0.228852,0.258152,...,8m7I,cJvF,FzaX,ch2oGfM,zCkv,P6pu4Vl,LM8l689qOp,Aoh3,ZI9m,R4y5gQQWY8OodqDV
3,-0.497243,-1.150423,-0.448339,-0.393904,-0.391218,-0.488119,-0.458272,4.317150,-0.228852,-0.115863,...,d4ij,cJvF,FzaX,kH5mFX7,oslk,BNrD3Yd,LM8l689qOp,FSa2,RAYp,F2FyR07IdsN7I
4,-0.565373,-1.150423,-0.448339,-0.371052,-0.368381,-0.488119,-0.458272,0.156969,-0.228852,0.219268,...,NEOV,cJvF,FzaX,x_lYlW4,oslk,3B1QowC,LM8l689qOp,WqMG,RAYp,F2FyR07IdsN7I

In [8]:
from home_works.machine_learning.final_project.util import HyperParametersOptimizer

best_params = HyperParametersOptimizer(X_final, y, cat_cols=cat_cols).get_catboost_best_params(n_trials=100)

best_params

[I 2025-11-24 19:42:33,434] A new study created in memory with name: no-name-3bdd85a1-b67d-433d-b4b8-4e54278abf7c

0:	learn: 0.7801393	total: 63ms	remaining: 28.5s
50:	learn: 0.9792249	total: 362ms	remaining: 2.85s
100:	learn: 0.9996729	total: 641ms	remaining: 2.23s
150:	learn: 1.0000000	total: 943ms	remaining: 1.89s
200:	learn: 1.0000000	total: 1.25s	remaining: 1.57s
250:	learn: 1.0000000	total: 1.59s	remaining: 1.28s
300:	learn: 1.0000000	total: 1.87s	remaining: 944ms
350:	learn: 1.0000000	total: 2.14s	remaining: 622ms
400:	learn: 1.0000000	total: 2.41s	remaining: 312ms
450:	learn: 1.0000000	total: 2.71s	remaining: 12ms
452:	learn: 1.0000000	total: 2.73s	remaining: 0us
0:	learn: 0.7807919	total: 3.79ms	remaining: 1.71s
50:	learn: 0.9781109	total: 300ms	remaining: 2.36s
100:	learn: 0.9988963	total: 613ms	remaining: 2.14s
150:	learn: 1.0000000	total: 913ms	remaining: 1.83s
200:	learn: 1.0000000	total: 1.2s	remaining: 1.5s
250:	learn: 1.0000000	total: 1.49s	remaining: 1.2s
300:	learn: 1.0000000	total: 1.78s	remaining: 901ms
350:	learn: 1.0000000	total: 2.06s	remaining: 598ms
400:	learn: 1.0000000	total: 2.5s	remaining: 324ms
450:	learn: 1.0000000	total: 2.86s	remaining: 12.7ms
452:	learn: 1.0000000	total: 2.87s	remaining: 0us
0:	learn: 0.7785418	total: 3.97ms	remaining: 1.79s
50:	learn: 0.9724732	total: 329ms	remaining: 2.6s
100:	learn: 0.9997819	total: 633ms	remaining: 2.21s
150:	learn: 1.0000000	total: 936ms	remaining: 1.87s
200:	learn: 1.0000000	total: 1.34s	remaining: 1.69s
250:	learn: 1.0000000	total: 1.8s	remaining: 1.45s
300:	learn: 1.0000000	total: 2.2s	remaining: 1.11s
350:	learn: 1.0000000	total: 2.52s	remaining: 731ms
400:	learn: 1.0000000	total: 2.83s	remaining: 367ms
450:	learn: 1.0000000	total: 3.18s	remaining: 14.1ms
452:	learn: 1.0000000	total: 3.2s	remaining: 0us
0:	learn: 0.7584879	total: 3.9ms	remaining: 1.76s
50:	learn: 0.9790069	total: 431ms	remaining: 3.4s
100:	learn: 0.9993325	total: 828ms	remaining: 2.88s
150:	learn: 1.0000000	total: 1.13s	remaining: 2.27s
200:	learn: 1.0000000	total: 1.46s	remaining: 1.83s
250:	learn: 1.0000000	total: 1.75s	remaining: 1.41s
300:	learn: 1.0000000	total: 2.06s	remaining: 1.04s
350:	learn: 1.0000000	total: 2.39s	remaining: 695ms
400:	learn: 1.0000000	total: 2.68s	remaining: 348ms
450:	learn: 1.0000000	total: 3.29s	remaining: 14.6ms
452:	learn: 1.0000000	total: 3.3s	remaining: 0us
0:	learn: 0.7732843	total: 3.69ms	remaining: 1.67s
50:	learn: 0.9790894	total: 324ms	remaining: 2.56s
100:	learn: 0.9988963	total: 633ms	remaining: 2.21s
150:	learn: 1.0000000	total: 948ms	remaining: 1.9s
200:	learn: 1.0000000	total: 1.25s	remaining: 1.57s
250:	learn: 1.0000000	total: 1.57s	remaining: 1.26s
300:	learn: 1.0000000	total: 1.94s	remaining: 981ms
350:	learn: 1.0000000	total: 2.23s	remaining: 649ms
400:	learn: 1.0000000	total: 2.88s	remaining: 373ms

[I 2025-11-24 19:42:49,373] Trial 0 finished with value: 0.6176156599889608 and parameters: {'weight_pos': 2.1216837525449996, 'iterations': 453, 'learning_rate': 0.2708003467071874, 'depth': 8, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.0054820779948554325, 'bagging_temperature': 0.08865721759942813, 'rsm': 0.07541828191300892, 'min_data_in_leaf': 99, 'leaf_estimation_iterations': 8}. Best is trial 0 with value: 0.6176156599889608.

450:	learn: 1.0000000	total: 3.24s	remaining: 14.4ms
452:	learn: 1.0000000	total: 3.25s	remaining: 0us
0:	learn: 0.8719839	total: 4.31ms	remaining: 3.63s
50:	learn: 0.9051697	total: 1.02s	remaining: 15.9s
100:	learn: 0.9440828	total: 2.04s	remaining: 15s
150:	learn: 0.9467027	total: 3.01s	remaining: 13.8s
200:	learn: 0.9499643	total: 4.14s	remaining: 13.3s
250:	learn: 0.9527775	total: 5.43s	remaining: 12.9s
300:	learn: 0.9560846	total: 7.58s	remaining: 13.7s
350:	learn: 0.9584038	total: 9.82s	remaining: 13.8s
400:	learn: 0.9605298	total: 12.1s	remaining: 13.4s
450:	learn: 0.9622478	total: 13.4s	remaining: 11.7s
500:	learn: 0.9643523	total: 14.6s	remaining: 10s
550:	learn: 0.9669936	total: 16s	remaining: 8.53s
600:	learn: 0.9695491	total: 17.2s	remaining: 7s
650:	learn: 0.9719113	total: 18.5s	remaining: 5.52s
700:	learn: 0.9743165	total: 20.1s	remaining: 4.13s
750:	learn: 0.9764210	total: 21.5s	remaining: 2.69s
800:	learn: 0.9784396	total: 23.1s	remaining: 1.27s
844:	learn: 0.9800716	total: 24.2s	remaining: 0us
0:	learn: 0.8706133	total: 3.89ms	remaining: 3.29s
50:	learn: 0.9276119	total: 993ms	remaining: 15.5s
100:	learn: 0.9422575	total: 1.91s	remaining: 14.1s
150:	learn: 0.9471107	total: 2.98s	remaining: 13.7s
200:	learn: 0.9499012	total: 4.14s	remaining: 13.3s
250:	learn: 0.9529278	total: 5.44s	remaining: 12.9s
300:	learn: 0.9549679	total: 6.65s	remaining: 12s
350:	learn: 0.9573731	total: 7.9s	remaining: 11.1s
400:	learn: 0.9598426	total: 9.08s	remaining: 10.1s
450:	learn: 0.9621404	total: 10.4s	remaining: 9.07s
500:	learn: 0.9640516	total: 11.7s	remaining: 8.06s
550:	learn: 0.9661991	total: 14s	remaining: 7.49s
600:	learn: 0.9692485	total: 17.1s	remaining: 6.95s
650:	learn: 0.9724482	total: 19.3s	remaining: 5.76s
700:	learn: 0.9753043	total: 20.7s	remaining: 4.26s
750:	learn: 0.9775162	total: 22.3s	remaining: 2.79s
800:	learn: 0.9794703	total: 23.7s	remaining: 1.3s
844:	learn: 0.9808018	total: 25.1s	remaining: 0us
0:	learn: 0.9058543	total: 8.43ms	remaining: 7.11s
50:	learn: 0.9296747	total: 916ms	remaining: 14.3s
100:	learn: 0.9425165	total: 2.4s	remaining: 17.7s
150:	learn: 0.9458665	total: 4.8s	remaining: 22s
200:	learn: 0.9498355	total: 7.08s	remaining: 22.7s
250:	learn: 0.9518970	total: 8.97s	remaining: 21.2s
300:	learn: 0.9542378	total: 10.3s	remaining: 18.6s
350:	learn: 0.9562349	total: 11.5s	remaining: 16.2s
400:	learn: 0.9581676	total: 12.8s	remaining: 14.2s
450:	learn: 0.9603365	total: 14.1s	remaining: 12.3s
500:	learn: 0.9623551	total: 15.2s	remaining: 10.5s
550:	learn: 0.9647388	total: 16.4s	remaining: 8.77s
600:	learn: 0.9672728	total: 17.8s	remaining: 7.23s
650:	learn: 0.9703222	total: 19.2s	remaining: 5.71s
700:	learn: 0.9731354	total: 20.8s	remaining: 4.27s
750:	learn: 0.9751969	total: 22.3s	remaining: 2.79s
800:	learn: 0.9774088	total: 23.7s	remaining: 1.3s
844:	learn: 0.9790409	total: 24.9s	remaining: 0us
0:	learn: 0.8705716	total: 4.2ms	remaining: 3.54s
50:	learn: 0.9235557	total: 1.08s	remaining: 16.8s
100:	learn: 0.9482262	total: 2.17s	remaining: 16s
150:	learn: 0.9496220	total: 3.38s	remaining: 15.5s
200:	learn: 0.9510179	total: 5.03s	remaining: 16.1s
250:	learn: 0.9541519	total: 8.45s	remaining: 20s
300:	learn: 0.9566859	total: 10.8s	remaining: 19.5s
350:	learn: 0.9592199	total: 13s	remaining: 18.2s
400:	learn: 0.9619686	total: 14.4s	remaining: 15.9s
450:	learn: 0.9636007	total: 15.8s	remaining: 13.8s
500:	learn: 0.9659629	total: 17.3s	remaining: 11.9s
550:	learn: 0.9681962	total: 18.6s	remaining: 9.95s
600:	learn: 0.9705155	total: 20s	remaining: 8.11s
650:	learn: 0.9731998	total: 21.4s	remaining: 6.37s
700:	learn: 0.9755405	total: 22.8s	remaining: 4.68s
750:	learn: 0.9772370	total: 24.2s	remaining: 3.02s
800:	learn: 0.9789335	total: 25.9s	remaining: 1.42s
844:	learn: 0.9803938	total: 27.2s	remaining: 0us
0:	learn: 0.9082114	total: 4.17ms	remaining: 3.52s
50:	learn: 0.9317122	total: 994ms	remaining: 15.5s
100:	learn: 0.9457364	total: 2.06s	remaining: 15.2s
150:	learn: 0.9482906	total: 3.23s	remaining: 14.8s
200:	learn: 0.9506515	total: 4.5s	remaining: 14.4s
250:	learn: 0.9527560	total: 5.85s	remaining: 13.8s
300:	learn: 0.9554403	total: 7.14s	remaining: 12.9s
350:	learn: 0.9580173	total: 8.46s	remaining: 11.9s
400:	learn: 0.9601433	total: 9.81s	remaining: 10.9s
450:	learn: 0.9618398	total: 11s	remaining: 9.64s
500:	learn: 0.9640302	total: 12.2s	remaining: 8.34s
550:	learn: 0.9661132	total: 13.4s	remaining: 7.13s
600:	learn: 0.9684110	total: 14.7s	remaining: 5.96s
650:	learn: 0.9708591	total: 16.1s	remaining: 4.79s
700:	learn: 0.9733072	total: 17.6s	remaining: 3.62s
750:	learn: 0.9759915	total: 19s	remaining: 2.38s
800:	learn: 0.9783322	total: 20.6s	remaining: 1.13s

[I 2025-11-24 19:44:53,708] Trial 1 finished with value: 0.6036151063743931 and parameters: {'weight_pos': 37.94136822732985, 'iterations': 845, 'learning_rate': 0.014480453832860733, 'depth': 9, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.0012287054579885955, 'bagging_temperature': 0.8874073819965811, 'rsm': 0.6208510822443597, 'min_data_in_leaf': 61, 'leaf_estimation_iterations': 2}. Best is trial 0 with value: 0.6176156599889608.

844:	learn: 0.9793415	total: 21.8s	remaining: 0us
0:	learn: 0.8469486	total: 7.67ms	remaining: 1.4s
50:	learn: 0.9595125	total: 346ms	remaining: 902ms
100:	learn: 0.9784273	total: 699ms	remaining: 575ms
150:	learn: 0.9881299	total: 1.05s	remaining: 231ms
183:	learn: 0.9914329	total: 1.28s	remaining: 0us
0:	learn: 0.8536584	total: 11.2ms	remaining: 2.04s
50:	learn: 0.9595641	total: 335ms	remaining: 874ms
100:	learn: 0.9792789	total: 698ms	remaining: 574ms
150:	learn: 0.9878460	total: 1.08s	remaining: 237ms
183:	learn: 0.9920522	total: 1.34s	remaining: 0us
0:	learn: 0.8566332	total: 7.22ms	remaining: 1.32s
50:	learn: 0.9565450	total: 324ms	remaining: 845ms
100:	learn: 0.9771113	total: 673ms	remaining: 553ms
150:	learn: 0.9871235	total: 1.02s	remaining: 224ms
183:	learn: 0.9910716	total: 1.26s	remaining: 0us
0:	learn: 0.8563819	total: 6.49ms	remaining: 1.19s
50:	learn: 0.9594609	total: 312ms	remaining: 814ms
100:	learn: 0.9797176	total: 711ms	remaining: 584ms
150:	learn: 0.9887750	total: 1.33s	remaining: 291ms
183:	learn: 0.9923618	total: 1.6s	remaining: 0us
0:	learn: 0.8542681	total: 7.43ms	remaining: 1.36s
50:	learn: 0.9597964	total: 354ms	remaining: 923ms
100:	learn: 0.9787886	total: 764ms	remaining: 628ms
150:	learn: 0.9882331	total: 1.12s	remaining: 245ms

[I 2025-11-24 19:45:00,940] Trial 2 finished with value: 0.6430465921414551 and parameters: {'weight_pos': 30.456645943375847, 'iterations': 184, 'learning_rate': 0.14304835666088433, 'depth': 7, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.0005422210432749966, 'bagging_temperature': 0.3950373481074303, 'rsm': 0.968081967879577, 'min_data_in_leaf': 12, 'leaf_estimation_iterations': 7}. Best is trial 2 with value: 0.6430465921414551.

183:	learn: 0.9916909	total: 1.37s	remaining: 0us
0:	total: 5.54ms	remaining: 1.04s
50:	total: 223ms	remaining: 598ms
100:	total: 415ms	remaining: 358ms
150:	total: 629ms	remaining: 154ms
187:	total: 766ms	remaining: 0us
0:	total: 3.13ms	remaining: 586ms
50:	total: 187ms	remaining: 503ms
100:	total: 369ms	remaining: 318ms
150:	total: 564ms	remaining: 138ms
187:	total: 704ms	remaining: 0us
0:	total: 3.33ms	remaining: 622ms
50:	total: 204ms	remaining: 548ms
100:	total: 391ms	remaining: 336ms
150:	total: 572ms	remaining: 140ms
187:	total: 705ms	remaining: 0us
0:	total: 4.37ms	remaining: 818ms
50:	total: 204ms	remaining: 548ms
100:	total: 380ms	remaining: 327ms
150:	total: 569ms	remaining: 139ms
187:	total: 701ms	remaining: 0us
0:	total: 3.69ms	remaining: 691ms
50:	total: 191ms	remaining: 513ms
100:	total: 378ms	remaining: 326ms

[I 2025-11-24 19:45:04,884] Trial 3 finished with value: 0.6756591486545107 and parameters: {'weight_pos': 10.459847519695195, 'iterations': 188, 'learning_rate': 0.16944234526553842, 'depth': 6, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.20401231744087994, 'bagging_temperature': 0.09629872788638572, 'rsm': 0.28570404559563944, 'min_data_in_leaf': 25, 'leaf_estimation_iterations': 10}. Best is trial 3 with value: 0.6756591486545107.

150:	total: 566ms	remaining: 139ms
187:	total: 723ms	remaining: 0us
0:	learn: 0.8538372	total: 9.28ms	remaining: 7.64s
50:	learn: 0.9458367	total: 645ms	remaining: 9.78s
100:	learn: 0.9619538	total: 1.38s	remaining: 9.86s
150:	learn: 0.9734148	total: 2.19s	remaining: 9.78s
200:	learn: 0.9806891	total: 2.98s	remaining: 9.23s
250:	learn: 0.9850589	total: 3.91s	remaining: 8.92s
300:	learn: 0.9895857	total: 4.73s	remaining: 8.22s
350:	learn: 0.9924117	total: 5.54s	remaining: 7.46s
400:	learn: 0.9946359	total: 6.38s	remaining: 6.73s
450:	learn: 0.9960227	total: 7.16s	remaining: 5.92s
500:	learn: 0.9973572	total: 7.94s	remaining: 5.12s
550:	learn: 0.9979067	total: 8.7s	remaining: 4.31s
600:	learn: 0.9987440	total: 9.47s	remaining: 3.51s
650:	learn: 0.9992412	total: 10.2s	remaining: 2.72s
700:	learn: 0.9994505	total: 11s	remaining: 1.92s
750:	learn: 0.9997383	total: 11.8s	remaining: 1.14s
800:	learn: 0.9998430	total: 12.7s	remaining: 366ms
823:	learn: 0.9999215	total: 13.1s	remaining: 0us
0:	learn: 0.8606227	total: 6.12ms	remaining: 5.04s
50:	learn: 0.9490276	total: 4.33s	remaining: 1m 5s
100:	learn: 0.9635238	total: 5.01s	remaining: 35.9s
150:	learn: 0.9750371	total: 5.77s	remaining: 25.7s
200:	learn: 0.9812909	total: 6.53s	remaining: 20.2s
250:	learn: 0.9855561	total: 7.37s	remaining: 16.8s
300:	learn: 0.9887222	total: 8.18s	remaining: 14.2s
350:	learn: 0.9913127	total: 9.06s	remaining: 12.2s
400:	learn: 0.9936154	total: 12.8s	remaining: 13.5s
450:	learn: 0.9952115	total: 14.1s	remaining: 11.6s
500:	learn: 0.9968862	total: 14.9s	remaining: 9.6s
550:	learn: 0.9977758	total: 15.7s	remaining: 7.8s
600:	learn: 0.9983515	total: 16.7s	remaining: 6.19s
650:	learn: 0.9990057	total: 17.6s	remaining: 4.67s
700:	learn: 0.9995290	total: 18.4s	remaining: 3.23s
750:	learn: 0.9997383	total: 19.3s	remaining: 1.87s
800:	learn: 0.9998430	total: 20.1s	remaining: 577ms
823:	learn: 0.9998953	total: 20.5s	remaining: 0us
0:	learn: 0.8622988	total: 6.21ms	remaining: 5.11s
50:	learn: 0.9471174	total: 692ms	remaining: 10.5s
100:	learn: 0.9618753	total: 2s	remaining: 14.3s
150:	learn: 0.9730223	total: 2.89s	remaining: 12.9s
200:	learn: 0.9797209	total: 3.78s	remaining: 11.7s
250:	learn: 0.9858439	total: 4.58s	remaining: 10.5s
300:	learn: 0.9895595	total: 5.55s	remaining: 9.64s
350:	learn: 0.9923594	total: 6.32s	remaining: 8.52s
400:	learn: 0.9941387	total: 7.15s	remaining: 7.54s
450:	learn: 0.9955779	total: 7.96s	remaining: 6.58s
500:	learn: 0.9970693	total: 8.73s	remaining: 5.63s
550:	learn: 0.9978805	total: 9.65s	remaining: 4.78s
600:	learn: 0.9986655	total: 10.6s	remaining: 3.92s
650:	learn: 0.9991627	total: 11.4s	remaining: 3.03s
700:	learn: 0.9996337	total: 12.5s	remaining: 2.2s
750:	learn: 0.9998168	total: 13.4s	remaining: 1.3s
800:	learn: 0.9998953	total: 14.3s	remaining: 411ms
823:	learn: 0.9999215	total: 14.6s	remaining: 0us
0:	learn: 0.8602144	total: 6.75ms	remaining: 5.56s
50:	learn: 0.9490552	total: 640ms	remaining: 9.7s
100:	learn: 0.9643088	total: 1.33s	remaining: 9.56s
150:	learn: 0.9747231	total: 2.09s	remaining: 9.33s
200:	learn: 0.9808461	total: 2.86s	remaining: 8.87s
250:	learn: 0.9847711	total: 3.62s	remaining: 8.25s
300:	learn: 0.9884606	total: 4.4s	remaining: 7.64s
350:	learn: 0.9917052	total: 5.15s	remaining: 6.94s
400:	learn: 0.9937200	total: 5.89s	remaining: 6.21s
450:	learn: 0.9952639	total: 6.73s	remaining: 5.57s
500:	learn: 0.9965983	total: 7.82s	remaining: 5.04s
550:	learn: 0.9977497	total: 8.59s	remaining: 4.26s
600:	learn: 0.9987178	total: 9.48s	remaining: 3.52s
650:	learn: 0.9991627	total: 10.3s	remaining: 2.75s
700:	learn: 0.9996860	total: 12.8s	remaining: 2.24s
750:	learn: 0.9998692	total: 13.7s	remaining: 1.33s
800:	learn: 0.9999215	total: 14.5s	remaining: 416ms
823:	learn: 0.9999477	total: 14.9s	remaining: 0us
0:	learn: 0.8564000	total: 4.78ms	remaining: 3.93s
50:	learn: 0.9473021	total: 784ms	remaining: 11.9s
100:	learn: 0.9611427	total: 1.52s	remaining: 10.9s
150:	learn: 0.9729700	total: 2.44s	remaining: 10.9s
200:	learn: 0.9791453	total: 3.21s	remaining: 9.96s
250:	learn: 0.9847187	total: 4s	remaining: 9.13s
300:	learn: 0.9885129	total: 4.84s	remaining: 8.4s
350:	learn: 0.9909202	total: 5.6s	remaining: 7.55s
400:	learn: 0.9930659	total: 6.42s	remaining: 6.78s
450:	learn: 0.9950284	total: 7.21s	remaining: 5.96s
500:	learn: 0.9963890	total: 8.01s	remaining: 5.17s
550:	learn: 0.9976973	total: 8.78s	remaining: 4.35s
600:	learn: 0.9984823	total: 9.54s	remaining: 3.54s
650:	learn: 0.9991103	total: 10.3s	remaining: 2.75s
700:	learn: 0.9995028	total: 11.1s	remaining: 1.95s
750:	learn: 0.9997645	total: 12.2s	remaining: 1.18s
800:	learn: 0.9998430	total: 13.1s	remaining: 375ms

[I 2025-11-24 19:46:22,481] Trial 4 finished with value: 0.696199809355684 and parameters: {'weight_pos': 29.943233047521925, 'iterations': 824, 'learning_rate': 0.10195931835399046, 'depth': 7, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.0019459852017353367, 'bagging_temperature': 0.24966439210218938, 'rsm': 0.8266966979744417, 'min_data_in_leaf': 74, 'leaf_estimation_iterations': 3}. Best is trial 4 with value: 0.696199809355684.

823:	learn: 0.9998692	total: 13.4s	remaining: 0us
0:	total: 15.9ms	remaining: 8.17s
50:	total: 720ms	remaining: 6.56s
100:	total: 1.41s	remaining: 5.79s
150:	total: 2.13s	remaining: 5.15s
200:	total: 2.85s	remaining: 4.46s
250:	total: 3.63s	remaining: 3.83s
300:	total: 4.34s	remaining: 3.1s
350:	total: 5.05s	remaining: 2.37s
400:	total: 5.75s	remaining: 1.65s
450:	total: 6.46s	remaining: 931ms
500:	total: 7.21s	remaining: 216ms
515:	total: 7.42s	remaining: 0us
0:	total: 9.63ms	remaining: 4.96s
50:	total: 843ms	remaining: 7.68s
100:	total: 1.6s	remaining: 6.59s
150:	total: 2.34s	remaining: 5.65s
200:	total: 3.08s	remaining: 4.83s
250:	total: 3.82s	remaining: 4.03s
300:	total: 4.53s	remaining: 3.23s
350:	total: 5.27s	remaining: 2.48s
400:	total: 6.2s	remaining: 1.78s
450:	total: 7.05s	remaining: 1.01s
500:	total: 7.81s	remaining: 234ms
515:	total: 8.07s	remaining: 0us
0:	total: 11.3ms	remaining: 5.83s
50:	total: 756ms	remaining: 6.89s
100:	total: 1.48s	remaining: 6.07s
150:	total: 2.21s	remaining: 5.33s
200:	total: 3.12s	remaining: 4.89s
250:	total: 3.88s	remaining: 4.09s
300:	total: 4.61s	remaining: 3.29s
350:	total: 5.42s	remaining: 2.55s
400:	total: 6.15s	remaining: 1.76s
450:	total: 6.86s	remaining: 989ms
500:	total: 7.61s	remaining: 228ms
515:	total: 7.83s	remaining: 0us
0:	total: 13.1ms	remaining: 6.76s
50:	total: 868ms	remaining: 7.91s
100:	total: 1.87s	remaining: 7.7s
150:	total: 2.77s	remaining: 6.69s
200:	total: 3.5s	remaining: 5.48s
250:	total: 4.24s	remaining: 4.48s
300:	total: 5.22s	remaining: 3.73s
350:	total: 6.22s	remaining: 2.93s
400:	total: 7.04s	remaining: 2.02s
450:	total: 7.75s	remaining: 1.12s
500:	total: 8.43s	remaining: 252ms
515:	total: 8.66s	remaining: 0us
0:	total: 12.1ms	remaining: 6.23s
50:	total: 702ms	remaining: 6.4s
100:	total: 1.37s	remaining: 5.62s
150:	total: 2.04s	remaining: 4.92s
200:	total: 2.72s	remaining: 4.26s
250:	total: 3.44s	remaining: 3.63s
300:	total: 4.14s	remaining: 2.96s
350:	total: 4.86s	remaining: 2.28s
400:	total: 5.62s	remaining: 1.61s
450:	total: 6.65s	remaining: 959ms
500:	total: 7.38s	remaining: 221ms

[I 2025-11-24 19:47:02,670] Trial 5 finished with value: 0.6875748165909729 and parameters: {'weight_pos': 3.1547882984944358, 'iterations': 516, 'learning_rate': 0.16432882315144384, 'depth': 7, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0005835141128032044, 'bagging_temperature': 0.5090410546919334, 'rsm': 0.7471525939917412, 'min_data_in_leaf': 14, 'leaf_estimation_iterations': 2}. Best is trial 4 with value: 0.696199809355684.

515:	total: 7.63s	remaining: 0us
0:	total: 5.8ms	remaining: 5.08s
50:	total: 225ms	remaining: 3.65s
100:	total: 472ms	remaining: 3.63s
150:	total: 771ms	remaining: 3.71s
200:	total: 1.05s	remaining: 3.52s
250:	total: 1.3s	remaining: 3.25s
300:	total: 1.53s	remaining: 2.93s
350:	total: 1.75s	remaining: 2.62s
400:	total: 2.01s	remaining: 2.39s
450:	total: 2.26s	remaining: 2.14s
500:	total: 2.48s	remaining: 1.86s
550:	total: 2.69s	remaining: 1.59s
600:	total: 2.9s	remaining: 1.33s
650:	total: 3.13s	remaining: 1.09s
700:	total: 3.36s	remaining: 843ms
750:	total: 3.57s	remaining: 599ms
800:	total: 3.78s	remaining: 359ms
850:	total: 3.99s	remaining: 122ms
876:	total: 4.1s	remaining: 0us
0:	total: 4.37ms	remaining: 3.82s
50:	total: 199ms	remaining: 3.22s
100:	total: 441ms	remaining: 3.39s
150:	total: 655ms	remaining: 3.15s
200:	total: 856ms	remaining: 2.88s
250:	total: 1.06s	remaining: 2.65s
300:	total: 1.28s	remaining: 2.46s
350:	total: 1.5s	remaining: 2.24s
400:	total: 1.7s	remaining: 2.02s
450:	total: 1.92s	remaining: 1.81s
500:	total: 2.14s	remaining: 1.6s
550:	total: 2.35s	remaining: 1.39s
600:	total: 2.59s	remaining: 1.19s
650:	total: 2.8s	remaining: 973ms
700:	total: 3.01s	remaining: 756ms
750:	total: 3.22s	remaining: 540ms
800:	total: 3.43s	remaining: 326ms
850:	total: 3.65s	remaining: 111ms
876:	total: 3.91s	remaining: 0us
0:	total: 5.21ms	remaining: 4.56s
50:	total: 206ms	remaining: 3.34s
100:	total: 412ms	remaining: 3.17s
150:	total: 622ms	remaining: 2.99s
200:	total: 843ms	remaining: 2.83s
250:	total: 1.13s	remaining: 2.81s
300:	total: 1.35s	remaining: 2.59s
350:	total: 1.56s	remaining: 2.34s
400:	total: 1.79s	remaining: 2.13s
450:	total: 2.01s	remaining: 1.9s
500:	total: 2.22s	remaining: 1.67s
550:	total: 2.43s	remaining: 1.44s
600:	total: 2.65s	remaining: 1.22s
650:	total: 2.89s	remaining: 1s
700:	total: 3.1s	remaining: 778ms
750:	total: 3.31s	remaining: 555ms
800:	total: 3.52s	remaining: 334ms
850:	total: 3.72s	remaining: 114ms
876:	total: 3.83s	remaining: 0us
0:	total: 4.44ms	remaining: 3.89s
50:	total: 209ms	remaining: 3.38s
100:	total: 486ms	remaining: 3.73s
150:	total: 749ms	remaining: 3.6s
200:	total: 1s	remaining: 3.37s
250:	total: 1.21s	remaining: 3.01s
300:	total: 1.41s	remaining: 2.7s
350:	total: 1.62s	remaining: 2.43s
400:	total: 1.83s	remaining: 2.17s
450:	total: 2.04s	remaining: 1.93s
500:	total: 2.27s	remaining: 1.7s
550:	total: 2.56s	remaining: 1.51s
600:	total: 2.78s	remaining: 1.28s
650:	total: 3s	remaining: 1.04s
700:	total: 3.21s	remaining: 806ms
750:	total: 3.44s	remaining: 577ms
800:	total: 3.65s	remaining: 347ms
850:	total: 3.85s	remaining: 118ms
876:	total: 3.97s	remaining: 0us
0:	total: 4.07ms	remaining: 3.56s
50:	total: 239ms	remaining: 3.87s
100:	total: 553ms	remaining: 4.25s
150:	total: 770ms	remaining: 3.7s
200:	total: 978ms	remaining: 3.29s
250:	total: 1.18s	remaining: 2.94s
300:	total: 1.39s	remaining: 2.66s
350:	total: 1.61s	remaining: 2.41s
400:	total: 1.99s	remaining: 2.36s
450:	total: 2.45s	remaining: 2.31s
500:	total: 2.77s	remaining: 2.08s
550:	total: 3.02s	remaining: 1.79s
600:	total: 3.26s	remaining: 1.5s
650:	total: 3.52s	remaining: 1.22s
700:	total: 3.76s	remaining: 944ms
750:	total: 4s	remaining: 671ms
800:	total: 4.26s	remaining: 404ms

[I 2025-11-24 19:47:23,725] Trial 6 finished with value: 0.7332649520968162 and parameters: {'weight_pos': 2.3874421146553955, 'iterations': 877, 'learning_rate': 0.042090715189262384, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.046931553645877075, 'bagging_temperature': 0.4541498521447469, 'rsm': 0.8607221776394451, 'min_data_in_leaf': 21, 'leaf_estimation_iterations': 2}. Best is trial 6 with value: 0.7332649520968162.

850:	total: 4.53s	remaining: 138ms
876:	total: 4.66s	remaining: 0us
0:	learn: 0.8836010	total: 3.96ms	remaining: 892ms
50:	learn: 0.9304077	total: 407ms	remaining: 1.4s
100:	learn: 0.9473391	total: 887ms	remaining: 1.1s
150:	learn: 0.9534480	total: 2.08s	remaining: 1.03s
200:	learn: 0.9557483	total: 3.23s	remaining: 401ms
225:	learn: 0.9566344	total: 3.63s	remaining: 0us
0:	learn: 0.8871022	total: 3.38ms	remaining: 760ms
50:	learn: 0.9131557	total: 628ms	remaining: 2.15s
100:	learn: 0.9493000	total: 1.36s	remaining: 1.69s
150:	learn: 0.9545227	total: 2.23s	remaining: 1.11s
200:	learn: 0.9563705	total: 3.06s	remaining: 381ms
225:	learn: 0.9574263	total: 4.17s	remaining: 0us
0:	learn: 0.8864182	total: 10.5ms	remaining: 2.36s
50:	learn: 0.9178317	total: 518ms	remaining: 1.78s
100:	learn: 0.9463398	total: 1.42s	remaining: 1.75s
150:	learn: 0.9542399	total: 2.34s	remaining: 1.16s
200:	learn: 0.9566910	total: 3.07s	remaining: 382ms
225:	learn: 0.9574263	total: 3.39s	remaining: 0us
0:	learn: 0.8861165	total: 7.86ms	remaining: 1.77s
50:	learn: 0.9338204	total: 467ms	remaining: 1.6s
100:	learn: 0.9511100	total: 996ms	remaining: 1.23s
150:	learn: 0.9555220	total: 1.52s	remaining: 757ms
200:	learn: 0.9569549	total: 2.03s	remaining: 252ms
225:	learn: 0.9581994	total: 2.35s	remaining: 0us
0:	learn: 0.8820470	total: 3.64ms	remaining: 818ms
50:	learn: 0.9225642	total: 419ms	remaining: 1.44s
100:	learn: 0.9521847	total: 946ms	remaining: 1.17s
150:	learn: 0.9556728	total: 1.53s	remaining: 760ms
200:	learn: 0.9569927	total: 2.15s	remaining: 267ms

[I 2025-11-24 19:47:40,236] Trial 7 finished with value: 0.4756534632903061 and parameters: {'weight_pos': 44.13932606819878, 'iterations': 226, 'learning_rate': 0.013140138556673077, 'depth': 10, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.04991203703453417, 'bagging_temperature': 0.20571807504062822, 'rsm': 0.32475344087887703, 'min_data_in_leaf': 15, 'leaf_estimation_iterations': 7}. Best is trial 6 with value: 0.7332649520968162.

225:	learn: 0.9577468	total: 2.44s	remaining: 0us
0:	total: 14.5ms	remaining: 3.13s
50:	total: 381ms	remaining: 1.23s
100:	total: 1.07s	remaining: 1.22s
150:	total: 1.7s	remaining: 732ms
200:	total: 2.31s	remaining: 173ms
215:	total: 2.49s	remaining: 0us
0:	total: 15.8ms	remaining: 3.41s
50:	total: 391ms	remaining: 1.26s
100:	total: 846ms	remaining: 963ms
150:	total: 1.33s	remaining: 571ms
200:	total: 1.96s	remaining: 146ms
215:	total: 2.11s	remaining: 0us
0:	total: 14.2ms	remaining: 3.06s
50:	total: 422ms	remaining: 1.36s
100:	total: 1.11s	remaining: 1.27s
150:	total: 1.68s	remaining: 724ms
200:	total: 2.16s	remaining: 161ms
215:	total: 2.31s	remaining: 0us
0:	total: 15.7ms	remaining: 3.38s
50:	total: 509ms	remaining: 1.65s
100:	total: 984ms	remaining: 1.12s
150:	total: 1.46s	remaining: 630ms
200:	total: 2.04s	remaining: 153ms
215:	total: 2.23s	remaining: 0us
0:	total: 14.8ms	remaining: 3.19s
50:	total: 469ms	remaining: 1.52s
100:	total: 1.03s	remaining: 1.17s
150:	total: 1.64s	remaining: 705ms
200:	total: 2.15s	remaining: 161ms
215:	total: 2.34s	remaining: 0us

[I 2025-11-24 19:47:52,135] Trial 8 finished with value: 0.5007034318869961 and parameters: {'weight_pos': 32.38299884958125, 'iterations': 216, 'learning_rate': 0.017764571226326843, 'depth': 10, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.00010413548629507758, 'bagging_temperature': 0.2271254562365077, 'rsm': 0.294359559477677, 'min_data_in_leaf': 73, 'leaf_estimation_iterations': 4}. Best is trial 6 with value: 0.7332649520968162.

0:	total: 1.51ms	remaining: 474ms
50:	total: 79.6ms	remaining: 410ms
100:	total: 162ms	remaining: 341ms
150:	total: 245ms	remaining: 265ms
200:	total: 323ms	remaining: 181ms
250:	total: 403ms	remaining: 101ms
300:	total: 483ms	remaining: 20.9ms
313:	total: 501ms	remaining: 0us
0:	total: 1.2ms	remaining: 374ms
50:	total: 86.7ms	remaining: 447ms
100:	total: 167ms	remaining: 352ms
150:	total: 253ms	remaining: 273ms
200:	total: 338ms	remaining: 190ms
250:	total: 417ms	remaining: 105ms
300:	total: 500ms	remaining: 21.6ms
313:	total: 516ms	remaining: 0us
0:	total: 1.45ms	remaining: 455ms
50:	total: 86.7ms	remaining: 447ms
100:	total: 172ms	remaining: 364ms
150:	total: 256ms	remaining: 276ms
200:	total: 378ms	remaining: 212ms
250:	total: 479ms	remaining: 120ms
300:	total: 555ms	remaining: 24ms
313:	total: 578ms	remaining: 0us
0:	total: 1.22ms	remaining: 381ms
50:	total: 86.5ms	remaining: 446ms
100:	total: 170ms	remaining: 358ms
150:	total: 265ms	remaining: 287ms
200:	total: 342ms	remaining: 192ms
250:	total: 417ms	remaining: 105ms
300:	total: 492ms	remaining: 21.3ms
313:	total: 510ms	remaining: 0us
0:	total: 2.4ms	remaining: 750ms
50:	total: 84.2ms	remaining: 434ms
100:	total: 166ms	remaining: 349ms
150:	total: 248ms	remaining: 268ms

[I 2025-11-24 19:47:55,084] Trial 9 finished with value: 0.4987787927029458 and parameters: {'weight_pos': 11.674238388263367, 'iterations': 314, 'learning_rate': 0.05427995198410835, 'depth': 6, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0014521730358446581, 'bagging_temperature': 0.38202831863676134, 'rsm': 0.011557916096965992, 'min_data_in_leaf': 3, 'leaf_estimation_iterations': 5}. Best is trial 6 with value: 0.7332649520968162.

200:	total: 320ms	remaining: 180ms
250:	total: 395ms	remaining: 99.1ms
300:	total: 473ms	remaining: 20.4ms
313:	total: 490ms	remaining: 0us
0:	total: 4.91ms	remaining: 4.85s
50:	total: 201ms	remaining: 3.7s
100:	total: 423ms	remaining: 3.72s
150:	total: 650ms	remaining: 3.61s
200:	total: 868ms	remaining: 3.41s
250:	total: 1.07s	remaining: 3.15s
300:	total: 1.27s	remaining: 2.91s
350:	total: 1.48s	remaining: 2.69s
400:	total: 1.68s	remaining: 2.47s
450:	total: 1.88s	remaining: 2.25s
500:	total: 2.09s	remaining: 2.04s
550:	total: 2.3s	remaining: 1.83s
600:	total: 2.52s	remaining: 1.63s
650:	total: 2.72s	remaining: 1.42s
700:	total: 2.93s	remaining: 1.21s
750:	total: 3.14s	remaining: 998ms
800:	total: 3.34s	remaining: 789ms
850:	total: 3.55s	remaining: 580ms
900:	total: 3.76s	remaining: 371ms
950:	total: 3.96s	remaining: 163ms
989:	total: 4.13s	remaining: 0us
0:	total: 4.55ms	remaining: 4.5s
50:	total: 201ms	remaining: 3.71s
100:	total: 407ms	remaining: 3.58s
150:	total: 640ms	remaining: 3.55s
200:	total: 876ms	remaining: 3.44s
250:	total: 1.15s	remaining: 3.39s
300:	total: 1.61s	remaining: 3.7s
350:	total: 1.88s	remaining: 3.43s
400:	total: 2.09s	remaining: 3.07s
450:	total: 2.29s	remaining: 2.74s
500:	total: 2.59s	remaining: 2.53s
550:	total: 2.8s	remaining: 2.23s
600:	total: 3s	remaining: 1.94s
650:	total: 3.2s	remaining: 1.67s
700:	total: 3.42s	remaining: 1.41s
750:	total: 3.63s	remaining: 1.16s
800:	total: 3.84s	remaining: 907ms
850:	total: 4.05s	remaining: 662ms
900:	total: 4.25s	remaining: 420ms
950:	total: 4.46s	remaining: 183ms
989:	total: 4.62s	remaining: 0us
0:	total: 5.1ms	remaining: 5.04s
50:	total: 201ms	remaining: 3.7s
100:	total: 423ms	remaining: 3.72s
150:	total: 644ms	remaining: 3.58s
200:	total: 897ms	remaining: 3.52s
250:	total: 1.1s	remaining: 3.26s
300:	total: 1.31s	remaining: 3.01s
350:	total: 1.53s	remaining: 2.78s
400:	total: 1.73s	remaining: 2.55s
450:	total: 1.95s	remaining: 2.33s
500:	total: 2.15s	remaining: 2.1s
550:	total: 2.37s	remaining: 1.89s
600:	total: 2.58s	remaining: 1.67s
650:	total: 2.78s	remaining: 1.45s
700:	total: 2.98s	remaining: 1.23s
750:	total: 3.19s	remaining: 1.01s
800:	total: 3.39s	remaining: 799ms
850:	total: 3.58s	remaining: 585ms
900:	total: 3.79s	remaining: 375ms
950:	total: 3.99s	remaining: 164ms
989:	total: 4.15s	remaining: 0us
0:	total: 4.26ms	remaining: 4.21s
50:	total: 193ms	remaining: 3.55s
100:	total: 391ms	remaining: 3.44s
150:	total: 598ms	remaining: 3.32s
200:	total: 816ms	remaining: 3.2s
250:	total: 1.05s	remaining: 3.09s
300:	total: 1.25s	remaining: 2.86s
350:	total: 1.46s	remaining: 2.65s
400:	total: 1.66s	remaining: 2.44s
450:	total: 1.87s	remaining: 2.23s
500:	total: 2.08s	remaining: 2.03s
550:	total: 2.3s	remaining: 1.83s
600:	total: 2.74s	remaining: 1.77s
650:	total: 2.95s	remaining: 1.53s
700:	total: 3.15s	remaining: 1.3s
750:	total: 3.36s	remaining: 1.07s
800:	total: 3.58s	remaining: 844ms
850:	total: 3.78s	remaining: 618ms
900:	total: 4.01s	remaining: 396ms
950:	total: 4.24s	remaining: 174ms
989:	total: 4.41s	remaining: 0us
0:	total: 4.87ms	remaining: 4.81s
50:	total: 211ms	remaining: 3.89s
100:	total: 426ms	remaining: 3.75s
150:	total: 635ms	remaining: 3.53s
200:	total: 844ms	remaining: 3.31s
250:	total: 1.05s	remaining: 3.1s
300:	total: 1.26s	remaining: 2.89s
350:	total: 1.47s	remaining: 2.67s
400:	total: 1.7s	remaining: 2.5s
450:	total: 1.9s	remaining: 2.27s
500:	total: 2.11s	remaining: 2.06s
550:	total: 2.31s	remaining: 1.84s
600:	total: 2.52s	remaining: 1.63s
650:	total: 2.73s	remaining: 1.42s
700:	total: 2.93s	remaining: 1.21s
750:	total: 3.14s	remaining: 1s
800:	total: 3.35s	remaining: 790ms
850:	total: 3.58s	remaining: 585ms
900:	total: 3.78s	remaining: 374ms

[I 2025-11-24 19:48:17,066] Trial 10 finished with value: 0.6556551614433721 and parameters: {'weight_pos': 1.1798565691935015, 'iterations': 990, 'learning_rate': 0.03472334698211004, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 20.40652553636586, 'bagging_temperature': 0.7056432935618342, 'rsm': 0.9844198707118939, 'min_data_in_leaf': 39, 'leaf_estimation_iterations': 1}. Best is trial 6 with value: 0.7332649520968162.

950:	total: 3.99s	remaining: 164ms
989:	total: 4.14s	remaining: 0us
0:	learn: 0.7866751	total: 4.88ms	remaining: 3.63s
50:	learn: 0.8498587	total: 207ms	remaining: 2.81s
100:	learn: 0.8702464	total: 409ms	remaining: 2.6s
150:	learn: 0.8850398	total: 616ms	remaining: 2.42s
200:	learn: 0.9013771	total: 831ms	remaining: 2.24s
250:	learn: 0.9069538	total: 1.04s	remaining: 2.05s
300:	learn: 0.9107384	total: 1.25s	remaining: 1.84s
350:	learn: 0.9177237	total: 1.45s	remaining: 1.63s
400:	learn: 0.9237315	total: 1.67s	remaining: 1.43s
450:	learn: 0.9278132	total: 1.88s	remaining: 1.22s
500:	learn: 0.9326616	total: 2.1s	remaining: 1.02s
550:	learn: 0.9353544	total: 2.31s	remaining: 808ms
600:	learn: 0.9410080	total: 2.52s	remaining: 599ms
650:	learn: 0.9440072	total: 2.73s	remaining: 390ms
700:	learn: 0.9463259	total: 2.94s	remaining: 181ms
743:	learn: 0.9477055	total: 3.13s	remaining: 0us
0:	learn: 0.7855240	total: 5.43ms	remaining: 4.04s
50:	learn: 0.8488635	total: 212ms	remaining: 2.87s
100:	learn: 0.8711959	total: 555ms	remaining: 3.53s
150:	learn: 0.8866221	total: 778ms	remaining: 3.06s
200:	learn: 0.8962129	total: 992ms	remaining: 2.68s
250:	learn: 0.9064655	total: 1.21s	remaining: 2.38s
300:	learn: 0.9118791	total: 1.43s	remaining: 2.1s
350:	learn: 0.9145521	total: 1.72s	remaining: 1.93s
400:	learn: 0.9196591	total: 1.95s	remaining: 1.66s
450:	learn: 0.9222272	total: 2.17s	remaining: 1.41s
500:	learn: 0.9269894	total: 2.38s	remaining: 1.15s
550:	learn: 0.9297777	total: 2.6s	remaining: 911ms
600:	learn: 0.9323936	total: 2.83s	remaining: 673ms
650:	learn: 0.9370696	total: 3.04s	remaining: 434ms
700:	learn: 0.9388710	total: 3.27s	remaining: 201ms
743:	learn: 0.9419087	total: 3.47s	remaining: 0us
0:	learn: 0.7830805	total: 5.34ms	remaining: 3.96s
50:	learn: 0.8489882	total: 207ms	remaining: 2.82s
100:	learn: 0.8691556	total: 410ms	remaining: 2.61s
150:	learn: 0.8882417	total: 661ms	remaining: 2.6s
200:	learn: 0.8971334	total: 893ms	remaining: 2.41s
250:	learn: 0.9032076	total: 1.1s	remaining: 2.16s
300:	learn: 0.9100299	total: 1.31s	remaining: 1.93s
350:	learn: 0.9141023	total: 1.51s	remaining: 1.69s
400:	learn: 0.9194202	total: 1.72s	remaining: 1.47s
450:	learn: 0.9240577	total: 1.92s	remaining: 1.25s
500:	learn: 0.9258778	total: 2.14s	remaining: 1.04s
550:	learn: 0.9305922	total: 2.37s	remaining: 829ms
600:	learn: 0.9341088	total: 2.6s	remaining: 619ms
650:	learn: 0.9365907	total: 2.83s	remaining: 405ms
700:	learn: 0.9384014	total: 3.06s	remaining: 188ms
743:	learn: 0.9399441	total: 3.24s	remaining: 0us
0:	learn: 0.6973103	total: 5.5ms	remaining: 4.08s
50:	learn: 0.8499647	total: 215ms	remaining: 2.92s
100:	learn: 0.8753837	total: 436ms	remaining: 2.77s
150:	learn: 0.8872454	total: 641ms	remaining: 2.52s
200:	learn: 0.8957818	total: 851ms	remaining: 2.3s
250:	learn: 0.9058142	total: 1.07s	remaining: 2.1s
300:	learn: 0.9093016	total: 1.28s	remaining: 1.88s
350:	learn: 0.9161623	total: 1.55s	remaining: 1.74s
400:	learn: 0.9218346	total: 1.8s	remaining: 1.54s
450:	learn: 0.9256960	total: 2.02s	remaining: 1.31s
500:	learn: 0.9296822	total: 2.24s	remaining: 1.09s
550:	learn: 0.9335821	total: 2.47s	remaining: 865ms
600:	learn: 0.9365044	total: 2.68s	remaining: 639ms
650:	learn: 0.9422442	total: 2.9s	remaining: 415ms
700:	learn: 0.9446492	total: 3.11s	remaining: 191ms
743:	learn: 0.9475238	total: 3.29s	remaining: 0us
0:	learn: 0.7853037	total: 5.18ms	remaining: 3.85s
50:	learn: 0.8475888	total: 394ms	remaining: 5.35s
100:	learn: 0.8710048	total: 640ms	remaining: 4.08s
150:	learn: 0.8834795	total: 844ms	remaining: 3.31s
200:	learn: 0.8972103	total: 1.07s	remaining: 2.9s
250:	learn: 0.9049717	total: 1.31s	remaining: 2.58s
300:	learn: 0.9126177	total: 1.56s	remaining: 2.3s
350:	learn: 0.9168335	total: 1.78s	remaining: 2s
400:	learn: 0.9215572	total: 2.02s	remaining: 1.73s
450:	learn: 0.9273354	total: 2.25s	remaining: 1.46s
500:	learn: 0.9305164	total: 2.61s	remaining: 1.26s
550:	learn: 0.9318576	total: 2.89s	remaining: 1.01s
600:	learn: 0.9346553	total: 3.14s	remaining: 748ms
650:	learn: 0.9372805	total: 3.37s	remaining: 481ms
700:	learn: 0.9403181	total: 3.6s	remaining: 221ms
743:	learn: 0.9444383	total: 3.8s	remaining: 0us

[I 2025-11-24 19:48:34,484] Trial 11 finished with value: 0.7016444366342987 and parameters: {'weight_pos': 4.445869002430134, 'iterations': 744, 'learning_rate': 0.06746612174625574, 'depth': 3, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.7336998321820944, 'bagging_temperature': 0.6006823646802691, 'rsm': 0.7831549697585605, 'min_data_in_leaf': 85, 'leaf_estimation_iterations': 3}. Best is trial 6 with value: 0.7332649520968162.

0:	learn: 0.8087945	total: 5.38ms	remaining: 3.75s
50:	learn: 0.8357737	total: 252ms	remaining: 3.19s
100:	learn: 0.8505324	total: 466ms	remaining: 2.75s
150:	learn: 0.8622395	total: 672ms	remaining: 2.43s
200:	learn: 0.8747093	total: 868ms	remaining: 2.14s
250:	learn: 0.8829675	total: 1.05s	remaining: 1.87s
300:	learn: 0.8877391	total: 1.24s	remaining: 1.63s
350:	learn: 0.8941988	total: 1.43s	remaining: 1.41s
400:	learn: 0.8993591	total: 1.62s	remaining: 1.2s
450:	learn: 0.9053373	total: 1.82s	remaining: 993ms
500:	learn: 0.9083423	total: 2.15s	remaining: 843ms
550:	learn: 0.9129137	total: 2.4s	remaining: 636ms
600:	learn: 0.9169195	total: 2.6s	remaining: 415ms
650:	learn: 0.9192284	total: 2.83s	remaining: 200ms
696:	learn: 0.9215373	total: 3.01s	remaining: 0us
0:	learn: 0.8056939	total: 6.46ms	remaining: 4.5s
50:	learn: 0.8334705	total: 189ms	remaining: 2.39s
100:	learn: 0.8537925	total: 444ms	remaining: 2.62s
150:	learn: 0.8673734	total: 810ms	remaining: 2.93s
200:	learn: 0.8746165	total: 990ms	remaining: 2.44s
250:	learn: 0.8815287	total: 1.18s	remaining: 2.1s
300:	learn: 0.8891893	total: 1.37s	remaining: 1.81s
350:	learn: 0.8933257	total: 1.56s	remaining: 1.54s
400:	learn: 0.8989297	total: 1.75s	remaining: 1.29s
450:	learn: 0.9029210	total: 1.94s	remaining: 1.06s
500:	learn: 0.9062626	total: 2.13s	remaining: 831ms
550:	learn: 0.9093053	total: 2.32s	remaining: 614ms
600:	learn: 0.9122640	total: 2.49s	remaining: 398ms
650:	learn: 0.9150776	total: 2.67s	remaining: 189ms
696:	learn: 0.9175316	total: 2.85s	remaining: 0us
0:	learn: 0.7940324	total: 5.38ms	remaining: 3.74s
50:	learn: 0.8285162	total: 295ms	remaining: 3.74s
100:	learn: 0.8499317	total: 494ms	remaining: 2.92s
150:	learn: 0.8616852	total: 670ms	remaining: 2.42s
200:	learn: 0.8700131	total: 848ms	remaining: 2.09s
250:	learn: 0.8804264	total: 1.04s	remaining: 1.85s
300:	learn: 0.8882176	total: 1.24s	remaining: 1.63s
350:	learn: 0.8940131	total: 1.43s	remaining: 1.41s
400:	learn: 0.8988224	total: 1.62s	remaining: 1.19s
450:	learn: 0.9013227	total: 1.81s	remaining: 989ms
500:	learn: 0.9043278	total: 2s	remaining: 782ms
550:	learn: 0.9080668	total: 2.19s	remaining: 581ms
600:	learn: 0.9108572	total: 2.5s	remaining: 400ms
650:	learn: 0.9135026	total: 2.68s	remaining: 189ms
696:	learn: 0.9152459	total: 2.85s	remaining: 0us
0:	learn: 0.8126317	total: 4.22ms	remaining: 2.94s
50:	learn: 0.8403828	total: 184ms	remaining: 2.33s
100:	learn: 0.8551848	total: 363ms	remaining: 2.14s
150:	learn: 0.8679246	total: 542ms	remaining: 1.96s
200:	learn: 0.8793473	total: 717ms	remaining: 1.77s
250:	learn: 0.8869558	total: 892ms	remaining: 1.58s
300:	learn: 0.8912691	total: 1.08s	remaining: 1.42s
350:	learn: 0.8964525	total: 1.29s	remaining: 1.27s
400:	learn: 0.9029964	total: 1.51s	remaining: 1.11s
450:	learn: 0.9064830	total: 1.69s	remaining: 924ms
500:	learn: 0.9090065	total: 1.88s	remaining: 734ms
550:	learn: 0.9115910	total: 2.05s	remaining: 543ms
600:	learn: 0.9159565	total: 2.23s	remaining: 356ms
650:	learn: 0.9178680	total: 2.42s	remaining: 171ms
696:	learn: 0.9200928	total: 2.59s	remaining: 0us
0:	learn: 0.8011572	total: 4.46ms	remaining: 3.11s
50:	learn: 0.8287046	total: 205ms	remaining: 2.59s
100:	learn: 0.8506831	total: 392ms	remaining: 2.32s
150:	learn: 0.8655780	total: 581ms	remaining: 2.1s
200:	learn: 0.8709384	total: 759ms	remaining: 1.87s
250:	learn: 0.8812676	total: 933ms	remaining: 1.66s
300:	learn: 0.8872314	total: 1.11s	remaining: 1.46s
350:	learn: 0.8928963	total: 1.29s	remaining: 1.27s
400:	learn: 0.8992342	total: 1.49s	remaining: 1.1s
450:	learn: 0.9022161	total: 1.68s	remaining: 914ms
500:	learn: 0.9055809	total: 1.93s	remaining: 756ms
550:	learn: 0.9093575	total: 2.18s	remaining: 578ms
600:	learn: 0.9141203	total: 2.4s	remaining: 383ms
650:	learn: 0.9165366	total: 2.59s	remaining: 183ms

[I 2025-11-24 19:48:49,054] Trial 12 finished with value: 0.6812272485973018 and parameters: {'weight_pos': 4.723968337534382, 'iterations': 697, 'learning_rate': 0.0368818076937599, 'depth': 3, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.5716527534450284, 'bagging_temperature': 0.6514103789782583, 'rsm': 0.5681094422002346, 'min_data_in_leaf': 99, 'leaf_estimation_iterations': 4}. Best is trial 6 with value: 0.7332649520968162.

696:	learn: 0.9193038	total: 2.78s	remaining: 0us
0:	total: 62.8ms	remaining: 42.7s
50:	total: 6.22s	remaining: 1m 16s
100:	total: 10.6s	remaining: 1m
150:	total: 14s	remaining: 48.9s
200:	total: 20.1s	remaining: 48s
250:	total: 24.6s	remaining: 42s
300:	total: 27.6s	remaining: 34.8s
350:	total: 30.9s	remaining: 28.9s
400:	total: 34.2s	remaining: 23.8s
450:	total: 37.5s	remaining: 19s
500:	total: 40.7s	remaining: 14.6s
550:	total: 44.4s	remaining: 10.4s
600:	total: 48.2s	remaining: 6.33s
650:	total: 51.4s	remaining: 2.29s
679:	total: 53.6s	remaining: 0us
0:	total: 69.4ms	remaining: 47.1s
50:	total: 2.73s	remaining: 33.7s
100:	total: 5.34s	remaining: 30.6s
150:	total: 11.9s	remaining: 41.7s
200:	total: 16.3s	remaining: 38.8s
250:	total: 20.3s	remaining: 34.7s
300:	total: 23.8s	remaining: 30s
350:	total: 27.4s	remaining: 25.7s
400:	total: 31s	remaining: 21.6s
450:	total: 34.4s	remaining: 17.5s
500:	total: 38s	remaining: 13.6s
550:	total: 41.5s	remaining: 9.71s
600:	total: 44.9s	remaining: 5.9s
650:	total: 48.7s	remaining: 2.17s
679:	total: 50.7s	remaining: 0us
0:	total: 61.8ms	remaining: 41.9s
50:	total: 3.17s	remaining: 39.1s
100:	total: 6.25s	remaining: 35.9s
150:	total: 9.57s	remaining: 33.5s
200:	total: 12.6s	remaining: 29.9s
250:	total: 18.4s	remaining: 31.5s
300:	total: 24.5s	remaining: 30.8s
350:	total: 28.9s	remaining: 27.1s
400:	total: 32.5s	remaining: 22.6s
450:	total: 35.9s	remaining: 18.2s
500:	total: 39.9s	remaining: 14.3s
550:	total: 44s	remaining: 10.3s
600:	total: 48s	remaining: 6.31s
650:	total: 51.9s	remaining: 2.31s
679:	total: 54.2s	remaining: 0us
0:	total: 11.8ms	remaining: 8.02s
50:	total: 3.6s	remaining: 44.5s
100:	total: 7.18s	remaining: 41.2s
150:	total: 10.9s	remaining: 38.1s
200:	total: 14.1s	remaining: 33.7s
250:	total: 17.3s	remaining: 29.6s
300:	total: 20.8s	remaining: 26.2s
350:	total: 24.6s	remaining: 23.1s
400:	total: 31.2s	remaining: 21.7s
450:	total: 36.2s	remaining: 18.4s
500:	total: 40.1s	remaining: 14.3s
550:	total: 44.1s	remaining: 10.3s
600:	total: 47.9s	remaining: 6.3s
650:	total: 52.9s	remaining: 2.36s
679:	total: 55.3s	remaining: 0us
0:	total: 16.9ms	remaining: 11.5s
50:	total: 3.13s	remaining: 38.6s
100:	total: 7.68s	remaining: 44.1s
150:	total: 14s	remaining: 49.1s
200:	total: 20.1s	remaining: 47.8s
250:	total: 23.4s	remaining: 40s
300:	total: 27.2s	remaining: 34.2s
350:	total: 31.1s	remaining: 29.2s
400:	total: 35.4s	remaining: 24.6s
450:	total: 39.5s	remaining: 20.1s
500:	total: 43.1s	remaining: 15.4s
550:	total: 47.2s	remaining: 11.1s
600:	total: 51.3s	remaining: 6.74s
650:	total: 54.8s	remaining: 2.44s

[I 2025-11-24 19:53:21,659] Trial 13 finished with value: 0.7056655404695069 and parameters: {'weight_pos': 1.5137514135573764, 'iterations': 680, 'learning_rate': 0.06877859912868968, 'depth': 12, 'eval_metric': 'AUC', 'l2_leaf_reg': 5.399282325436614, 'bagging_temperature': 0.6409989274123424, 'rsm': 0.7651869683489323, 'min_data_in_leaf': 48, 'leaf_estimation_iterations': 1}. Best is trial 6 with value: 0.7332649520968162.

679:	total: 57.1s	remaining: 0us
0:	total: 18.2ms	remaining: 11.6s
50:	total: 1.13s	remaining: 13s
100:	total: 2.93s	remaining: 15.6s
150:	total: 4.93s	remaining: 15.9s
200:	total: 7.49s	remaining: 16.3s
250:	total: 10.4s	remaining: 16.1s
300:	total: 13.5s	remaining: 15.1s
350:	total: 17.4s	remaining: 14.3s
400:	total: 21.1s	remaining: 12.5s
450:	total: 24.1s	remaining: 10s
500:	total: 26.9s	remaining: 7.41s
550:	total: 30.1s	remaining: 4.81s
600:	total: 33.2s	remaining: 2.1s
638:	total: 36.5s	remaining: 0us
0:	total: 25.1ms	remaining: 16s
50:	total: 1.39s	remaining: 16s
100:	total: 3.85s	remaining: 20.5s
150:	total: 6.58s	remaining: 21.3s
200:	total: 9.53s	remaining: 20.8s
250:	total: 12.7s	remaining: 19.6s
300:	total: 15.8s	remaining: 17.8s
350:	total: 18.9s	remaining: 15.5s
400:	total: 25.8s	remaining: 15.3s
450:	total: 30.6s	remaining: 12.8s
500:	total: 34.1s	remaining: 9.4s
550:	total: 38.1s	remaining: 6.08s
600:	total: 41.6s	remaining: 2.63s
638:	total: 44.5s	remaining: 0us
0:	total: 19.2ms	remaining: 12.2s
50:	total: 1.36s	remaining: 15.7s
100:	total: 3.44s	remaining: 18.3s
150:	total: 6.36s	remaining: 20.6s
200:	total: 9.5s	remaining: 20.7s
250:	total: 13.1s	remaining: 20.3s
300:	total: 16.1s	remaining: 18.1s
350:	total: 19.7s	remaining: 16.2s
400:	total: 23s	remaining: 13.6s
450:	total: 27.1s	remaining: 11.3s
500:	total: 31.4s	remaining: 8.64s
550:	total: 35s	remaining: 5.59s
600:	total: 39.2s	remaining: 2.48s
638:	total: 42.9s	remaining: 0us
0:	total: 13.5ms	remaining: 8.62s
50:	total: 2.9s	remaining: 33.4s
100:	total: 7.24s	remaining: 38.6s
150:	total: 11.8s	remaining: 38.3s
200:	total: 14.9s	remaining: 32.5s
250:	total: 20.2s	remaining: 31.2s
300:	total: 26.4s	remaining: 29.6s
350:	total: 30.3s	remaining: 24.9s
400:	total: 33.8s	remaining: 20s
450:	total: 37.3s	remaining: 15.6s
500:	total: 41.1s	remaining: 11.3s
550:	total: 49.8s	remaining: 7.95s
600:	total: 54.2s	remaining: 3.42s
638:	total: 57.9s	remaining: 0us
0:	total: 30.8ms	remaining: 19.6s
50:	total: 1.75s	remaining: 20.2s
100:	total: 3.96s	remaining: 21.1s
150:	total: 6.71s	remaining: 21.7s
200:	total: 14.1s	remaining: 30.8s
250:	total: 19.2s	remaining: 29.7s
300:	total: 22.7s	remaining: 25.5s
350:	total: 27.3s	remaining: 22.4s
400:	total: 32.8s	remaining: 19.5s
450:	total: 36.8s	remaining: 15.3s
500:	total: 41.3s	remaining: 11.4s
550:	total: 46.4s	remaining: 7.41s
600:	total: 51.5s	remaining: 3.25s
638:	total: 54.2s	remaining: 0us

[I 2025-11-24 19:57:19,600] Trial 14 finished with value: 0.6613386389349342 and parameters: {'weight_pos': 1.131246307411411, 'iterations': 639, 'learning_rate': 0.025080961990878656, 'depth': 12, 'eval_metric': 'AUC', 'l2_leaf_reg': 47.83859942408928, 'bagging_temperature': 0.8426378205590068, 'rsm': 0.6788940028509742, 'min_data_in_leaf': 43, 'leaf_estimation_iterations': 1}. Best is trial 6 with value: 0.7332649520968162.

0:	total: 124ms	remaining: 1m 59s
50:	total: 4.46s	remaining: 1m 19s
100:	total: 13s	remaining: 1m 50s
150:	total: 20.8s	remaining: 1m 51s
200:	total: 25.9s	remaining: 1m 37s
250:	total: 31.1s	remaining: 1m 27s
300:	total: 36.4s	remaining: 1m 19s
350:	total: 40.8s	remaining: 1m 10s
400:	total: 46.8s	remaining: 1m 5s
450:	total: 51.5s	remaining: 58s
500:	total: 57.2s	remaining: 52.3s
550:	total: 1m 2s	remaining: 46.1s
600:	total: 1m 8s	remaining: 40.7s
650:	total: 1m 13s	remaining: 34.6s
700:	total: 1m 18s	remaining: 28.8s
750:	total: 1m 24s	remaining: 23.4s
800:	total: 1m 29s	remaining: 17.6s
850:	total: 1m 34s	remaining: 12s
900:	total: 1m 38s	remaining: 6.36s
950:	total: 1m 43s	remaining: 873ms
958:	total: 1m 44s	remaining: 0us
0:	total: 117ms	remaining: 1m 52s
50:	total: 4.32s	remaining: 1m 16s
100:	total: 9.55s	remaining: 1m 21s
150:	total: 15s	remaining: 1m 20s
200:	total: 23.8s	remaining: 1m 29s
250:	total: 29.3s	remaining: 1m 22s
300:	total: 34.4s	remaining: 1m 15s
350:	total: 39.8s	remaining: 1m 8s
400:	total: 44.8s	remaining: 1m 2s
450:	total: 53.9s	remaining: 1m
500:	total: 59s	remaining: 53.9s
550:	total: 1m 4s	remaining: 47.5s
600:	total: 1m 9s	remaining: 41.1s
650:	total: 1m 13s	remaining: 34.9s
700:	total: 1m 18s	remaining: 29s
750:	total: 1m 23s	remaining: 23.2s
800:	total: 1m 28s	remaining: 17.5s
850:	total: 1m 33s	remaining: 11.9s
900:	total: 1m 38s	remaining: 6.31s
950:	total: 1m 43s	remaining: 873ms
958:	total: 1m 44s	remaining: 0us
0:	total: 8.16ms	remaining: 7.82s
50:	total: 5.68s	remaining: 1m 41s
100:	total: 9.99s	remaining: 1m 24s
150:	total: 15.7s	remaining: 1m 24s
200:	total: 20.2s	remaining: 1m 16s
250:	total: 25.6s	remaining: 1m 12s
300:	total: 33.8s	remaining: 1m 13s
350:	total: 40s	remaining: 1m 9s
400:	total: 44.5s	remaining: 1m 1s
450:	total: 49.3s	remaining: 55.5s
500:	total: 54.4s	remaining: 49.7s
550:	total: 59.2s	remaining: 43.8s
600:	total: 1m 4s	remaining: 38.2s
650:	total: 1m 8s	remaining: 32.4s
700:	total: 1m 12s	remaining: 26.8s
750:	total: 1m 17s	remaining: 21.5s
800:	total: 1m 22s	remaining: 16.2s
850:	total: 1m 26s	remaining: 11s
900:	total: 1m 30s	remaining: 5.85s
950:	total: 1m 35s	remaining: 805ms
958:	total: 1m 36s	remaining: 0us
0:	total: 98.4ms	remaining: 1m 34s
50:	total: 7.09s	remaining: 2m 6s
100:	total: 12.7s	remaining: 1m 48s
150:	total: 18.8s	remaining: 1m 40s
200:	total: 24.7s	remaining: 1m 33s
250:	total: 29.8s	remaining: 1m 24s
300:	total: 37.8s	remaining: 1m 22s
350:	total: 43.9s	remaining: 1m 16s
400:	total: 52.7s	remaining: 1m 13s
450:	total: 59.6s	remaining: 1m 7s
500:	total: 1m 4s	remaining: 58.7s
550:	total: 1m 9s	remaining: 51.2s
600:	total: 1m 13s	remaining: 43.9s
650:	total: 1m 19s	remaining: 37.5s
700:	total: 1m 27s	remaining: 32.1s
750:	total: 1m 32s	remaining: 25.7s
800:	total: 1m 37s	remaining: 19.3s
850:	total: 1m 42s	remaining: 13s
900:	total: 1m 47s	remaining: 6.94s
950:	total: 1m 53s	remaining: 952ms
958:	total: 1m 53s	remaining: 0us
0:	total: 8.99ms	remaining: 8.61s
50:	total: 5.36s	remaining: 1m 35s
100:	total: 9.33s	remaining: 1m 19s
150:	total: 15.6s	remaining: 1m 23s
200:	total: 21.8s	remaining: 1m 22s
250:	total: 25.7s	remaining: 1m 12s
300:	total: 29.7s	remaining: 1m 4s
350:	total: 33.9s	remaining: 58.7s
400:	total: 38.8s	remaining: 54s
450:	total: 43.9s	remaining: 49.5s
500:	total: 48.6s	remaining: 44.4s
550:	total: 53.2s	remaining: 39.4s
600:	total: 57.3s	remaining: 34.1s
650:	total: 1m 2s	remaining: 29.4s
700:	total: 1m 6s	remaining: 24.4s
750:	total: 1m 10s	remaining: 19.6s
800:	total: 1m 15s	remaining: 14.9s
850:	total: 1m 20s	remaining: 10.2s
900:	total: 1m 25s	remaining: 5.5s
950:	total: 1m 30s	remaining: 757ms
958:	total: 1m 30s	remaining: 0us

[I 2025-11-24 20:05:52,656] Trial 15 finished with value: 0.7090923599179866 and parameters: {'weight_pos': 1.9479644706838402, 'iterations': 959, 'learning_rate': 0.06962681841224753, 'depth': 12, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.5956151194960446, 'bagging_temperature': 0.7319914454951855, 'rsm': 0.8609052411234451, 'min_data_in_leaf': 38, 'leaf_estimation_iterations': 1}. Best is trial 6 with value: 0.7332649520968162.

0:	total: 7.41ms	remaining: 7.33s
50:	total: 335ms	remaining: 6.17s
100:	total: 875ms	remaining: 7.7s
150:	total: 1.23s	remaining: 6.81s
200:	total: 1.56s	remaining: 6.13s
250:	total: 1.91s	remaining: 5.62s
300:	total: 2.26s	remaining: 5.16s
350:	total: 2.58s	remaining: 4.69s
400:	total: 2.97s	remaining: 4.36s
450:	total: 3.36s	remaining: 4.02s
500:	total: 3.73s	remaining: 3.64s
550:	total: 4.16s	remaining: 3.31s
600:	total: 4.59s	remaining: 2.97s
650:	total: 4.96s	remaining: 2.58s
700:	total: 5.31s	remaining: 2.19s
750:	total: 5.71s	remaining: 1.82s
800:	total: 6.12s	remaining: 1.44s
850:	total: 6.53s	remaining: 1.07s
900:	total: 6.95s	remaining: 687ms
950:	total: 7.4s	remaining: 303ms
989:	total: 7.86s	remaining: 0us
0:	total: 8.69ms	remaining: 8.6s
50:	total: 388ms	remaining: 7.15s
100:	total: 773ms	remaining: 6.8s
150:	total: 1.18s	remaining: 6.57s
200:	total: 1.65s	remaining: 6.48s
250:	total: 2.19s	remaining: 6.43s
300:	total: 2.83s	remaining: 6.47s
350:	total: 3.2s	remaining: 5.83s
400:	total: 3.53s	remaining: 5.19s
450:	total: 3.88s	remaining: 4.63s
500:	total: 4.29s	remaining: 4.19s
550:	total: 4.61s	remaining: 3.67s
600:	total: 4.98s	remaining: 3.22s
650:	total: 5.33s	remaining: 2.78s
700:	total: 5.68s	remaining: 2.34s
750:	total: 6.04s	remaining: 1.92s
800:	total: 6.39s	remaining: 1.51s
850:	total: 6.76s	remaining: 1.1s
900:	total: 7.11s	remaining: 703ms
950:	total: 7.45s	remaining: 305ms
989:	total: 7.7s	remaining: 0us
0:	total: 7.17ms	remaining: 7.09s
50:	total: 305ms	remaining: 5.62s
100:	total: 612ms	remaining: 5.39s
150:	total: 1.04s	remaining: 5.77s
200:	total: 1.39s	remaining: 5.47s
250:	total: 1.74s	remaining: 5.13s
300:	total: 2.09s	remaining: 4.79s
350:	total: 2.4s	remaining: 4.38s
400:	total: 2.72s	remaining: 4s
450:	total: 3.05s	remaining: 3.65s
500:	total: 3.41s	remaining: 3.33s
550:	total: 3.75s	remaining: 2.99s
600:	total: 4.08s	remaining: 2.64s
650:	total: 4.4s	remaining: 2.29s
700:	total: 4.93s	remaining: 2.03s
750:	total: 5.3s	remaining: 1.69s
800:	total: 5.65s	remaining: 1.33s
850:	total: 6.01s	remaining: 983ms
900:	total: 6.35s	remaining: 627ms
950:	total: 6.7s	remaining: 275ms
989:	total: 6.97s	remaining: 0us
0:	total: 6.58ms	remaining: 6.51s
50:	total: 346ms	remaining: 6.37s
100:	total: 680ms	remaining: 5.99s
150:	total: 1.02s	remaining: 5.66s
200:	total: 1.44s	remaining: 5.64s
250:	total: 1.77s	remaining: 5.2s
300:	total: 2.08s	remaining: 4.76s
350:	total: 2.42s	remaining: 4.41s
400:	total: 2.8s	remaining: 4.11s
450:	total: 3.15s	remaining: 3.77s
500:	total: 3.53s	remaining: 3.44s
550:	total: 3.89s	remaining: 3.1s
600:	total: 4.25s	remaining: 2.75s
650:	total: 4.64s	remaining: 2.42s
700:	total: 5.04s	remaining: 2.08s
750:	total: 5.49s	remaining: 1.75s
800:	total: 5.94s	remaining: 1.4s
850:	total: 6.74s	remaining: 1.1s
900:	total: 7.27s	remaining: 718ms
950:	total: 8.12s	remaining: 333ms
989:	total: 8.5s	remaining: 0us
0:	total: 7.25ms	remaining: 7.17s
50:	total: 418ms	remaining: 7.69s
100:	total: 869ms	remaining: 7.65s
150:	total: 1.28s	remaining: 7.11s
200:	total: 1.69s	remaining: 6.63s
250:	total: 2.11s	remaining: 6.22s
300:	total: 2.52s	remaining: 5.77s
350:	total: 3.17s	remaining: 5.76s
400:	total: 3.67s	remaining: 5.39s
450:	total: 4.12s	remaining: 4.93s
500:	total: 4.58s	remaining: 4.47s
550:	total: 5.01s	remaining: 3.99s
600:	total: 5.45s	remaining: 3.52s
650:	total: 5.9s	remaining: 3.07s
700:	total: 6.44s	remaining: 2.66s
750:	total: 6.91s	remaining: 2.2s
800:	total: 7.35s	remaining: 1.73s
850:	total: 7.82s	remaining: 1.28s
900:	total: 8.28s	remaining: 818ms
950:	total: 8.7s	remaining: 357ms

[I 2025-11-24 20:06:33,904] Trial 16 finished with value: 0.7404863910277388 and parameters: {'weight_pos': 2.2251937977925387, 'iterations': 990, 'learning_rate': 0.043521575312755724, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.6361802237432617, 'bagging_temperature': 0.9737877539995844, 'rsm': 0.43468229033874983, 'min_data_in_leaf': 31, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

989:	total: 9.29s	remaining: 0us
0:	total: 12.4ms	remaining: 11.1s
50:	total: 431ms	remaining: 7.14s
100:	total: 905ms	remaining: 7.12s
150:	total: 1.38s	remaining: 6.81s
200:	total: 1.89s	remaining: 6.52s
250:	total: 2.44s	remaining: 6.28s
300:	total: 3.01s	remaining: 5.95s
350:	total: 3.6s	remaining: 5.59s
400:	total: 4.16s	remaining: 5.14s
450:	total: 4.69s	remaining: 4.63s
500:	total: 5.18s	remaining: 4.09s
550:	total: 5.67s	remaining: 3.55s
600:	total: 6.16s	remaining: 3.02s
650:	total: 6.69s	remaining: 2.52s
700:	total: 7.34s	remaining: 2.04s
750:	total: 7.88s	remaining: 1.52s
800:	total: 8.44s	remaining: 1s
850:	total: 8.93s	remaining: 472ms
895:	total: 9.51s	remaining: 0us
0:	total: 11.1ms	remaining: 9.91s
50:	total: 360ms	remaining: 5.96s
100:	total: 781ms	remaining: 6.14s
150:	total: 1.13s	remaining: 5.59s
200:	total: 1.46s	remaining: 5.06s
250:	total: 1.84s	remaining: 4.74s
300:	total: 2.2s	remaining: 4.35s
350:	total: 2.54s	remaining: 3.94s
400:	total: 2.88s	remaining: 3.55s
450:	total: 3.22s	remaining: 3.17s
500:	total: 3.58s	remaining: 2.83s
550:	total: 3.93s	remaining: 2.46s
600:	total: 4.3s	remaining: 2.11s
650:	total: 4.67s	remaining: 1.76s
700:	total: 5.16s	remaining: 1.43s
750:	total: 5.54s	remaining: 1.07s
800:	total: 5.91s	remaining: 701ms
850:	total: 6.32s	remaining: 334ms
895:	total: 6.71s	remaining: 0us
0:	total: 8.77ms	remaining: 7.85s
50:	total: 370ms	remaining: 6.13s
100:	total: 721ms	remaining: 5.67s
150:	total: 1.07s	remaining: 5.31s
200:	total: 1.42s	remaining: 4.9s
250:	total: 1.8s	remaining: 4.62s
300:	total: 2.19s	remaining: 4.34s
350:	total: 2.57s	remaining: 3.99s
400:	total: 3.11s	remaining: 3.84s
450:	total: 3.44s	remaining: 3.4s
500:	total: 3.81s	remaining: 3s
550:	total: 4.17s	remaining: 2.61s
600:	total: 4.57s	remaining: 2.25s
650:	total: 4.93s	remaining: 1.86s
700:	total: 5.29s	remaining: 1.47s
750:	total: 5.66s	remaining: 1.09s
800:	total: 6.03s	remaining: 716ms
850:	total: 6.39s	remaining: 338ms
895:	total: 6.71s	remaining: 0us
0:	total: 6.61ms	remaining: 5.92s
50:	total: 353ms	remaining: 5.85s
100:	total: 708ms	remaining: 5.57s
150:	total: 1.04s	remaining: 5.15s
200:	total: 1.4s	remaining: 4.84s
250:	total: 1.74s	remaining: 4.47s
300:	total: 2.09s	remaining: 4.13s
350:	total: 2.43s	remaining: 3.77s
400:	total: 2.82s	remaining: 3.48s
450:	total: 3.18s	remaining: 3.14s
500:	total: 3.52s	remaining: 2.77s
550:	total: 3.87s	remaining: 2.42s
600:	total: 4.22s	remaining: 2.07s
650:	total: 4.57s	remaining: 1.72s
700:	total: 4.99s	remaining: 1.39s
750:	total: 5.45s	remaining: 1.05s
800:	total: 5.87s	remaining: 697ms
850:	total: 6.43s	remaining: 340ms
895:	total: 6.79s	remaining: 0us
0:	total: 8.73ms	remaining: 7.82s
50:	total: 385ms	remaining: 6.38s
100:	total: 796ms	remaining: 6.27s
150:	total: 1.15s	remaining: 5.68s
200:	total: 1.53s	remaining: 5.3s
250:	total: 1.91s	remaining: 4.91s
300:	total: 2.24s	remaining: 4.43s
350:	total: 2.58s	remaining: 4s
400:	total: 2.91s	remaining: 3.59s
450:	total: 3.27s	remaining: 3.22s
500:	total: 3.61s	remaining: 2.85s
550:	total: 3.95s	remaining: 2.47s
600:	total: 4.3s	remaining: 2.11s
650:	total: 4.71s	remaining: 1.77s
700:	total: 5.07s	remaining: 1.41s
750:	total: 5.42s	remaining: 1.05s
800:	total: 5.77s	remaining: 685ms
850:	total: 6.11s	remaining: 323ms

[I 2025-11-24 20:07:10,815] Trial 17 finished with value: 0.7249387242709343 and parameters: {'weight_pos': 2.8663501627169663, 'iterations': 896, 'learning_rate': 0.03820425069451065, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.019745818186706274, 'bagging_temperature': 0.48142704951773774, 'rsm': 0.4615279160836098, 'min_data_in_leaf': 27, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

895:	total: 6.43s	remaining: 0us
0:	total: 5.25ms	remaining: 4.31s
50:	total: 226ms	remaining: 3.41s
100:	total: 462ms	remaining: 3.29s
150:	total: 698ms	remaining: 3.1s
200:	total: 925ms	remaining: 2.85s
250:	total: 1.15s	remaining: 2.62s
300:	total: 1.39s	remaining: 2.39s
350:	total: 1.62s	remaining: 2.17s
400:	total: 1.91s	remaining: 2s
450:	total: 2.15s	remaining: 1.77s
500:	total: 2.56s	remaining: 1.64s
550:	total: 2.82s	remaining: 1.38s
600:	total: 3.08s	remaining: 1.13s
650:	total: 3.35s	remaining: 875ms
700:	total: 3.61s	remaining: 618ms
750:	total: 3.87s	remaining: 360ms
800:	total: 4.13s	remaining: 103ms
820:	total: 4.23s	remaining: 0us
0:	total: 6.73ms	remaining: 5.52s
50:	total: 338ms	remaining: 5.11s
100:	total: 591ms	remaining: 4.21s
150:	total: 830ms	remaining: 3.68s
200:	total: 1.07s	remaining: 3.29s
250:	total: 1.3s	remaining: 2.96s
300:	total: 1.54s	remaining: 2.66s
350:	total: 1.78s	remaining: 2.39s
400:	total: 2.04s	remaining: 2.14s
450:	total: 2.29s	remaining: 1.88s
500:	total: 2.52s	remaining: 1.61s
550:	total: 2.75s	remaining: 1.35s
600:	total: 2.99s	remaining: 1.09s
650:	total: 3.32s	remaining: 867ms
700:	total: 3.64s	remaining: 623ms
750:	total: 3.89s	remaining: 363ms
800:	total: 4.13s	remaining: 103ms
820:	total: 4.24s	remaining: 0us
0:	total: 6.68ms	remaining: 5.47s
50:	total: 250ms	remaining: 3.77s
100:	total: 483ms	remaining: 3.44s
150:	total: 737ms	remaining: 3.27s
200:	total: 1.18s	remaining: 3.63s
250:	total: 1.43s	remaining: 3.24s
300:	total: 1.67s	remaining: 2.89s
350:	total: 1.93s	remaining: 2.59s
400:	total: 2.18s	remaining: 2.28s
450:	total: 2.43s	remaining: 1.99s
500:	total: 2.67s	remaining: 1.71s
550:	total: 2.92s	remaining: 1.43s
600:	total: 3.17s	remaining: 1.16s
650:	total: 3.47s	remaining: 906ms
700:	total: 3.93s	remaining: 672ms
750:	total: 4.23s	remaining: 395ms
800:	total: 4.47s	remaining: 112ms
820:	total: 4.57s	remaining: 0us
0:	total: 7.49ms	remaining: 6.14s
50:	total: 228ms	remaining: 3.45s
100:	total: 461ms	remaining: 3.29s
150:	total: 695ms	remaining: 3.08s
200:	total: 934ms	remaining: 2.88s
250:	total: 1.19s	remaining: 2.7s
300:	total: 1.45s	remaining: 2.51s
350:	total: 1.74s	remaining: 2.33s
400:	total: 2s	remaining: 2.09s
450:	total: 2.24s	remaining: 1.84s
500:	total: 2.5s	remaining: 1.59s
550:	total: 2.74s	remaining: 1.34s
600:	total: 2.99s	remaining: 1.09s
650:	total: 3.23s	remaining: 845ms
700:	total: 3.48s	remaining: 596ms
750:	total: 3.73s	remaining: 348ms
800:	total: 3.97s	remaining: 99.2ms
820:	total: 4.07s	remaining: 0us
0:	total: 5.92ms	remaining: 4.86s
50:	total: 305ms	remaining: 4.6s
100:	total: 543ms	remaining: 3.87s
150:	total: 797ms	remaining: 3.54s
200:	total: 1.04s	remaining: 3.21s
250:	total: 1.27s	remaining: 2.9s
300:	total: 1.52s	remaining: 2.63s
350:	total: 1.76s	remaining: 2.36s
400:	total: 2.05s	remaining: 2.15s
450:	total: 2.33s	remaining: 1.91s
500:	total: 2.6s	remaining: 1.66s
550:	total: 2.85s	remaining: 1.4s
600:	total: 3.1s	remaining: 1.13s
650:	total: 3.42s	remaining: 892ms
700:	total: 3.69s	remaining: 633ms
750:	total: 3.97s	remaining: 370ms

[I 2025-11-24 20:07:32,903] Trial 18 finished with value: 0.6591424263523726 and parameters: {'weight_pos': 6.437356050489013, 'iterations': 821, 'learning_rate': 0.022235969835191063, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.06710268118907575, 'bagging_temperature': 0.9858060117959179, 'rsm': 0.4375523303356585, 'min_data_in_leaf': 25, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

800:	total: 4.22s	remaining: 106ms
820:	total: 4.32s	remaining: 0us
0:	total: 6.92ms	remaining: 6.86s
50:	total: 221ms	remaining: 4.07s
100:	total: 585ms	remaining: 5.17s
150:	total: 794ms	remaining: 4.43s
200:	total: 996ms	remaining: 3.92s
250:	total: 1.19s	remaining: 3.51s
300:	total: 1.39s	remaining: 3.19s
350:	total: 1.69s	remaining: 3.09s
400:	total: 2.01s	remaining: 2.96s
450:	total: 2.33s	remaining: 2.8s
500:	total: 2.58s	remaining: 2.54s
550:	total: 2.81s	remaining: 2.26s
600:	total: 3.04s	remaining: 1.98s
650:	total: 3.3s	remaining: 1.73s
700:	total: 3.56s	remaining: 1.48s
750:	total: 3.79s	remaining: 1.22s
800:	total: 4.01s	remaining: 961ms
850:	total: 4.22s	remaining: 705ms
900:	total: 4.45s	remaining: 454ms
950:	total: 4.66s	remaining: 206ms
992:	total: 4.84s	remaining: 0us
0:	total: 5.29ms	remaining: 5.25s
50:	total: 199ms	remaining: 3.68s
100:	total: 393ms	remaining: 3.47s
150:	total: 644ms	remaining: 3.59s
200:	total: 921ms	remaining: 3.63s
250:	total: 1.14s	remaining: 3.37s
300:	total: 1.35s	remaining: 3.1s
350:	total: 1.55s	remaining: 2.83s
400:	total: 1.76s	remaining: 2.59s
450:	total: 1.95s	remaining: 2.34s
500:	total: 2.15s	remaining: 2.11s
550:	total: 2.36s	remaining: 1.9s
600:	total: 2.57s	remaining: 1.67s
650:	total: 2.78s	remaining: 1.46s
700:	total: 2.98s	remaining: 1.24s
750:	total: 3.18s	remaining: 1.02s
800:	total: 3.37s	remaining: 808ms
850:	total: 3.58s	remaining: 597ms
900:	total: 3.78s	remaining: 386ms
950:	total: 3.98s	remaining: 176ms
992:	total: 4.15s	remaining: 0us
0:	total: 5.11ms	remaining: 5.07s
50:	total: 204ms	remaining: 3.76s
100:	total: 391ms	remaining: 3.45s
150:	total: 580ms	remaining: 3.23s
200:	total: 772ms	remaining: 3.04s
250:	total: 1s	remaining: 2.96s
300:	total: 1.4s	remaining: 3.22s
350:	total: 1.6s	remaining: 2.92s
400:	total: 1.81s	remaining: 2.68s
450:	total: 2.04s	remaining: 2.45s
500:	total: 2.25s	remaining: 2.21s
550:	total: 2.45s	remaining: 1.96s
600:	total: 2.64s	remaining: 1.72s
650:	total: 2.83s	remaining: 1.49s
700:	total: 3.03s	remaining: 1.26s
750:	total: 3.23s	remaining: 1.04s
800:	total: 3.43s	remaining: 823ms
850:	total: 3.65s	remaining: 608ms
900:	total: 3.85s	remaining: 393ms
950:	total: 4.07s	remaining: 180ms
992:	total: 4.25s	remaining: 0us
0:	total: 5.33ms	remaining: 5.28s
50:	total: 198ms	remaining: 3.65s
100:	total: 396ms	remaining: 3.49s
150:	total: 584ms	remaining: 3.25s
200:	total: 784ms	remaining: 3.09s
250:	total: 985ms	remaining: 2.91s
300:	total: 1.18s	remaining: 2.72s
350:	total: 1.39s	remaining: 2.55s
400:	total: 1.61s	remaining: 2.38s
450:	total: 1.85s	remaining: 2.22s
500:	total: 2.07s	remaining: 2.03s
550:	total: 2.29s	remaining: 1.84s
600:	total: 2.56s	remaining: 1.67s
650:	total: 3.28s	remaining: 1.72s
700:	total: 3.72s	remaining: 1.55s
750:	total: 3.98s	remaining: 1.28s
800:	total: 4.22s	remaining: 1.01s
850:	total: 4.49s	remaining: 750ms
900:	total: 4.77s	remaining: 488ms
950:	total: 5.02s	remaining: 222ms
992:	total: 5.21s	remaining: 0us
0:	total: 5.5ms	remaining: 5.45s
50:	total: 212ms	remaining: 3.91s
100:	total: 424ms	remaining: 3.74s
150:	total: 648ms	remaining: 3.61s
200:	total: 851ms	remaining: 3.35s
250:	total: 1.05s	remaining: 3.12s
300:	total: 1.46s	remaining: 3.35s
350:	total: 2.08s	remaining: 3.8s
400:	total: 2.32s	remaining: 3.42s
450:	total: 2.54s	remaining: 3.05s
500:	total: 2.74s	remaining: 2.69s
550:	total: 2.96s	remaining: 2.38s
600:	total: 3.18s	remaining: 2.07s
650:	total: 3.38s	remaining: 1.78s
700:	total: 3.59s	remaining: 1.5s
750:	total: 3.8s	remaining: 1.22s
800:	total: 4s	remaining: 960ms
850:	total: 4.24s	remaining: 708ms
900:	total: 4.45s	remaining: 454ms
950:	total: 4.67s	remaining: 206ms
992:	total: 4.85s	remaining: 0us

[I 2025-11-24 20:07:56,880] Trial 19 finished with value: 0.6553607986623291 and parameters: {'weight_pos': 14.439889997972607, 'iterations': 993, 'learning_rate': 0.04776590678508611, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 3.4794167346877174, 'bagging_temperature': 0.3519140150083816, 'rsm': 0.16814427488681516, 'min_data_in_leaf': 59, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 7.08ms	remaining: 2.97s
50:	total: 278ms	remaining: 2.02s
100:	total: 569ms	remaining: 1.8s
150:	total: 866ms	remaining: 1.55s
200:	total: 1.19s	remaining: 1.3s
250:	total: 1.46s	remaining: 992ms
300:	total: 1.79s	remaining: 714ms
350:	total: 2.1s	remaining: 419ms
400:	total: 2.58s	remaining: 129ms
420:	total: 2.87s	remaining: 0us
0:	total: 12.9ms	remaining: 5.43s
50:	total: 411ms	remaining: 2.98s
100:	total: 849ms	remaining: 2.69s
150:	total: 1.25s	remaining: 2.24s
200:	total: 1.65s	remaining: 1.8s
250:	total: 2.04s	remaining: 1.38s
300:	total: 2.35s	remaining: 938ms
350:	total: 2.66s	remaining: 531ms
400:	total: 2.97s	remaining: 148ms
420:	total: 3.08s	remaining: 0us
0:	total: 7.21ms	remaining: 3.03s
50:	total: 464ms	remaining: 3.37s
100:	total: 751ms	remaining: 2.38s
150:	total: 1.05s	remaining: 1.88s
200:	total: 1.39s	remaining: 1.52s
250:	total: 1.79s	remaining: 1.21s
300:	total: 2.14s	remaining: 852ms
350:	total: 2.46s	remaining: 491ms
400:	total: 2.86s	remaining: 143ms
420:	total: 3.02s	remaining: 0us
0:	total: 6.27ms	remaining: 2.63s
50:	total: 330ms	remaining: 2.39s
100:	total: 633ms	remaining: 2s
150:	total: 932ms	remaining: 1.67s
200:	total: 1.26s	remaining: 1.38s
250:	total: 1.73s	remaining: 1.17s
300:	total: 2.11s	remaining: 840ms
350:	total: 2.4s	remaining: 480ms
400:	total: 2.7s	remaining: 135ms
420:	total: 2.82s	remaining: 0us
0:	total: 7.73ms	remaining: 3.25s
50:	total: 328ms	remaining: 2.38s
100:	total: 656ms	remaining: 2.08s
150:	total: 940ms	remaining: 1.68s
200:	total: 1.29s	remaining: 1.41s
250:	total: 1.62s	remaining: 1.1s
300:	total: 1.92s	remaining: 767ms
350:	total: 2.21s	remaining: 440ms

[I 2025-11-24 20:08:11,797] Trial 20 finished with value: 0.698551362272646 and parameters: {'weight_pos': 3.412551155311821, 'iterations': 421, 'learning_rate': 0.02946055074555456, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 4.037203567451007e-05, 'bagging_temperature': 0.8023986042282495, 'rsm': 0.5444565540095874, 'min_data_in_leaf': 1, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

400:	total: 2.49s	remaining: 124ms
420:	total: 2.61s	remaining: 0us
0:	total: 15.3ms	remaining: 13.7s
50:	total: 372ms	remaining: 6.17s
100:	total: 716ms	remaining: 5.64s
150:	total: 1.03s	remaining: 5.08s
200:	total: 1.35s	remaining: 4.67s
250:	total: 1.84s	remaining: 4.72s
300:	total: 2.16s	remaining: 4.27s
350:	total: 2.52s	remaining: 3.91s
400:	total: 2.89s	remaining: 3.56s
450:	total: 3.22s	remaining: 3.18s
500:	total: 3.54s	remaining: 2.79s
550:	total: 3.95s	remaining: 2.47s
600:	total: 4.31s	remaining: 2.12s
650:	total: 4.67s	remaining: 1.76s
700:	total: 5.01s	remaining: 1.39s
750:	total: 5.35s	remaining: 1.03s
800:	total: 5.67s	remaining: 672ms
850:	total: 5.99s	remaining: 317ms
895:	total: 6.29s	remaining: 0us
0:	total: 8.78ms	remaining: 7.86s
50:	total: 374ms	remaining: 6.2s
100:	total: 754ms	remaining: 5.94s
150:	total: 1.12s	remaining: 5.54s
200:	total: 1.5s	remaining: 5.17s
250:	total: 1.82s	remaining: 4.67s
300:	total: 2.14s	remaining: 4.23s
350:	total: 2.46s	remaining: 3.81s
400:	total: 2.79s	remaining: 3.45s
450:	total: 3.13s	remaining: 3.08s
500:	total: 3.44s	remaining: 2.71s
550:	total: 3.75s	remaining: 2.35s
600:	total: 4.07s	remaining: 2s
650:	total: 4.46s	remaining: 1.68s
700:	total: 4.78s	remaining: 1.33s
750:	total: 5.26s	remaining: 1.02s
800:	total: 5.6s	remaining: 664ms
850:	total: 5.96s	remaining: 315ms
895:	total: 6.25s	remaining: 0us
0:	total: 8.65ms	remaining: 7.75s
50:	total: 382ms	remaining: 6.33s
100:	total: 766ms	remaining: 6.03s
150:	total: 1.13s	remaining: 5.58s
200:	total: 1.48s	remaining: 5.13s
250:	total: 1.83s	remaining: 4.71s
300:	total: 2.17s	remaining: 4.3s
350:	total: 2.53s	remaining: 3.92s
400:	total: 2.96s	remaining: 3.66s
450:	total: 3.35s	remaining: 3.31s
500:	total: 3.68s	remaining: 2.9s
550:	total: 4.03s	remaining: 2.52s
600:	total: 4.37s	remaining: 2.14s
650:	total: 4.72s	remaining: 1.78s
700:	total: 5.06s	remaining: 1.41s
750:	total: 5.38s	remaining: 1.04s
800:	total: 5.72s	remaining: 679ms
850:	total: 6.06s	remaining: 320ms
895:	total: 6.35s	remaining: 0us
0:	total: 11.5ms	remaining: 10.3s
50:	total: 342ms	remaining: 5.66s
100:	total: 661ms	remaining: 5.2s
150:	total: 974ms	remaining: 4.81s
200:	total: 1.27s	remaining: 4.4s
250:	total: 1.63s	remaining: 4.18s
300:	total: 1.99s	remaining: 3.93s
350:	total: 2.52s	remaining: 3.92s
400:	total: 2.85s	remaining: 3.51s
450:	total: 3.19s	remaining: 3.15s
500:	total: 3.62s	remaining: 2.86s
550:	total: 4.11s	remaining: 2.57s
600:	total: 4.89s	remaining: 2.4s
650:	total: 5.67s	remaining: 2.13s
700:	total: 6.24s	remaining: 1.74s
750:	total: 6.79s	remaining: 1.31s
800:	total: 7.34s	remaining: 871ms
850:	total: 7.87s	remaining: 416ms
895:	total: 8.31s	remaining: 0us
0:	total: 8.47ms	remaining: 7.58s
50:	total: 602ms	remaining: 9.98s
100:	total: 1.12s	remaining: 8.83s
150:	total: 1.77s	remaining: 8.74s
200:	total: 2.26s	remaining: 7.8s
250:	total: 2.69s	remaining: 6.93s
300:	total: 3.16s	remaining: 6.24s
350:	total: 3.94s	remaining: 6.12s
400:	total: 4.66s	remaining: 5.75s
450:	total: 5.22s	remaining: 5.15s
500:	total: 5.73s	remaining: 4.52s
550:	total: 6.22s	remaining: 3.9s
600:	total: 6.78s	remaining: 3.33s
650:	total: 7.47s	remaining: 2.81s
700:	total: 8.01s	remaining: 2.23s
750:	total: 8.49s	remaining: 1.64s
800:	total: 8.94s	remaining: 1.06s
850:	total: 9.4s	remaining: 497ms

[I 2025-11-24 20:08:49,644] Trial 21 finished with value: 0.7279749586871771 and parameters: {'weight_pos': 2.492130132474664, 'iterations': 896, 'learning_rate': 0.04387686485107591, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.01531813088212887, 'bagging_temperature': 0.5184202012943984, 'rsm': 0.4277714125760026, 'min_data_in_leaf': 29, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

895:	total: 9.92s	remaining: 0us
0:	total: 9.81ms	remaining: 9.05s
50:	total: 460ms	remaining: 7.88s
100:	total: 925ms	remaining: 7.54s
150:	total: 1.36s	remaining: 6.96s
200:	total: 1.77s	remaining: 6.36s
250:	total: 2.13s	remaining: 5.72s
300:	total: 2.45s	remaining: 5.06s
350:	total: 2.9s	remaining: 4.73s
400:	total: 3.49s	remaining: 4.56s
450:	total: 4.2s	remaining: 4.41s
500:	total: 4.5s	remaining: 3.8s
550:	total: 4.82s	remaining: 3.26s
600:	total: 5.16s	remaining: 2.77s
650:	total: 5.46s	remaining: 2.29s
700:	total: 5.74s	remaining: 1.83s
750:	total: 6.05s	remaining: 1.39s
800:	total: 6.38s	remaining: 980ms
850:	total: 6.69s	remaining: 574ms
900:	total: 6.99s	remaining: 179ms
923:	total: 7.13s	remaining: 0us
0:	total: 8.27ms	remaining: 7.63s
50:	total: 298ms	remaining: 5.11s
100:	total: 596ms	remaining: 4.85s
150:	total: 902ms	remaining: 4.62s
200:	total: 1.19s	remaining: 4.27s
250:	total: 1.47s	remaining: 3.95s
300:	total: 1.75s	remaining: 3.62s
350:	total: 2.04s	remaining: 3.33s
400:	total: 2.32s	remaining: 3.03s
450:	total: 2.62s	remaining: 2.75s
500:	total: 2.91s	remaining: 2.46s
550:	total: 3.22s	remaining: 2.18s
600:	total: 3.51s	remaining: 1.89s
650:	total: 3.8s	remaining: 1.59s
700:	total: 4.1s	remaining: 1.3s
750:	total: 4.39s	remaining: 1.01s
800:	total: 4.69s	remaining: 720ms
850:	total: 4.98s	remaining: 428ms
900:	total: 5.28s	remaining: 135ms
923:	total: 5.41s	remaining: 0us
0:	total: 6.95ms	remaining: 6.42s
50:	total: 320ms	remaining: 5.48s
100:	total: 605ms	remaining: 4.93s
150:	total: 1.05s	remaining: 5.36s
200:	total: 1.34s	remaining: 4.83s
250:	total: 1.62s	remaining: 4.35s
300:	total: 1.9s	remaining: 3.93s
350:	total: 2.29s	remaining: 3.75s
400:	total: 2.66s	remaining: 3.47s
450:	total: 2.98s	remaining: 3.13s
500:	total: 3.29s	remaining: 2.78s
550:	total: 3.67s	remaining: 2.48s
600:	total: 3.99s	remaining: 2.15s
650:	total: 4.35s	remaining: 1.82s
700:	total: 4.68s	remaining: 1.49s
750:	total: 5.02s	remaining: 1.16s
800:	total: 5.37s	remaining: 824ms
850:	total: 5.7s	remaining: 489ms
900:	total: 6.05s	remaining: 154ms
923:	total: 6.19s	remaining: 0us
0:	total: 6.9ms	remaining: 6.37s
50:	total: 303ms	remaining: 5.18s
100:	total: 629ms	remaining: 5.12s
150:	total: 924ms	remaining: 4.73s
200:	total: 1.24s	remaining: 4.47s
250:	total: 1.6s	remaining: 4.29s
300:	total: 1.89s	remaining: 3.91s
350:	total: 2.23s	remaining: 3.63s
400:	total: 2.58s	remaining: 3.36s
450:	total: 2.89s	remaining: 3.04s
500:	total: 3.2s	remaining: 2.7s
550:	total: 3.49s	remaining: 2.36s
600:	total: 3.79s	remaining: 2.04s
650:	total: 4.09s	remaining: 1.72s
700:	total: 4.59s	remaining: 1.46s
750:	total: 4.92s	remaining: 1.13s
800:	total: 5.32s	remaining: 817ms
850:	total: 5.79s	remaining: 497ms
900:	total: 6.24s	remaining: 159ms
923:	total: 6.39s	remaining: 0us
0:	total: 7.36ms	remaining: 6.79s
50:	total: 335ms	remaining: 5.74s
100:	total: 636ms	remaining: 5.18s
150:	total: 947ms	remaining: 4.85s
200:	total: 1.24s	remaining: 4.46s
250:	total: 1.54s	remaining: 4.12s
300:	total: 1.86s	remaining: 3.85s
350:	total: 2.15s	remaining: 3.51s
400:	total: 2.44s	remaining: 3.19s
450:	total: 2.79s	remaining: 2.93s
500:	total: 3.1s	remaining: 2.61s
550:	total: 3.48s	remaining: 2.35s
600:	total: 3.86s	remaining: 2.08s
650:	total: 4.24s	remaining: 1.78s
700:	total: 4.58s	remaining: 1.46s
750:	total: 4.9s	remaining: 1.13s
800:	total: 5.2s	remaining: 798ms
850:	total: 5.52s	remaining: 473ms

[I 2025-11-24 20:09:21,580] Trial 22 finished with value: 0.729490726539454 and parameters: {'weight_pos': 2.2651253789103345, 'iterations': 924, 'learning_rate': 0.04586267223317678, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.010229265530023955, 'bagging_temperature': 0.9956071776156719, 'rsm': 0.4003419529022233, 'min_data_in_leaf': 33, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 5.89s	remaining: 150ms
923:	total: 6.04s	remaining: 0us
0:	total: 5.28ms	remaining: 4.11s
50:	total: 216ms	remaining: 3.08s
100:	total: 414ms	remaining: 2.78s
150:	total: 629ms	remaining: 2.62s
200:	total: 836ms	remaining: 2.4s
250:	total: 1.04s	remaining: 2.19s
300:	total: 1.25s	remaining: 1.99s
350:	total: 1.46s	remaining: 1.77s
400:	total: 1.84s	remaining: 1.73s
450:	total: 2.23s	remaining: 1.63s
500:	total: 2.44s	remaining: 1.35s
550:	total: 2.65s	remaining: 1.1s
600:	total: 2.85s	remaining: 843ms
650:	total: 3.05s	remaining: 600ms
700:	total: 3.26s	remaining: 363ms
750:	total: 3.5s	remaining: 130ms
778:	total: 3.61s	remaining: 0us
0:	total: 4.2ms	remaining: 3.27s
50:	total: 199ms	remaining: 2.84s
100:	total: 392ms	remaining: 2.63s
150:	total: 610ms	remaining: 2.53s
200:	total: 816ms	remaining: 2.35s
250:	total: 1.03s	remaining: 2.17s
300:	total: 1.24s	remaining: 1.97s
350:	total: 1.5s	remaining: 1.83s
400:	total: 1.71s	remaining: 1.61s
450:	total: 1.92s	remaining: 1.4s
500:	total: 2.14s	remaining: 1.19s
550:	total: 2.36s	remaining: 977ms
600:	total: 2.57s	remaining: 762ms
650:	total: 2.79s	remaining: 548ms
700:	total: 3.01s	remaining: 335ms
750:	total: 3.22s	remaining: 120ms
778:	total: 3.34s	remaining: 0us
0:	total: 3.94ms	remaining: 3.06s
50:	total: 201ms	remaining: 2.87s
100:	total: 404ms	remaining: 2.71s
150:	total: 622ms	remaining: 2.59s
200:	total: 828ms	remaining: 2.38s
250:	total: 1.03s	remaining: 2.17s
300:	total: 1.24s	remaining: 1.97s
350:	total: 1.45s	remaining: 1.77s
400:	total: 1.67s	remaining: 1.57s
450:	total: 1.89s	remaining: 1.38s
500:	total: 2.1s	remaining: 1.16s
550:	total: 2.32s	remaining: 959ms
600:	total: 2.55s	remaining: 755ms
650:	total: 2.75s	remaining: 541ms
700:	total: 2.98s	remaining: 331ms
750:	total: 3.38s	remaining: 126ms
778:	total: 3.61s	remaining: 0us
0:	total: 5.87ms	remaining: 4.57s
50:	total: 242ms	remaining: 3.45s
100:	total: 480ms	remaining: 3.23s
150:	total: 683ms	remaining: 2.84s
200:	total: 1.04s	remaining: 3s
250:	total: 1.3s	remaining: 2.73s
300:	total: 1.52s	remaining: 2.41s
350:	total: 1.72s	remaining: 2.1s
400:	total: 1.96s	remaining: 1.85s
450:	total: 2.23s	remaining: 1.62s
500:	total: 2.52s	remaining: 1.4s
550:	total: 2.77s	remaining: 1.15s
600:	total: 3.01s	remaining: 891ms
650:	total: 3.22s	remaining: 634ms
700:	total: 3.48s	remaining: 387ms
750:	total: 3.7s	remaining: 138ms
778:	total: 3.86s	remaining: 0us
0:	total: 5.22ms	remaining: 4.06s
50:	total: 263ms	remaining: 3.76s
100:	total: 476ms	remaining: 3.19s
150:	total: 702ms	remaining: 2.92s
200:	total: 957ms	remaining: 2.75s
250:	total: 1.18s	remaining: 2.48s
300:	total: 1.4s	remaining: 2.22s
350:	total: 1.61s	remaining: 1.96s
400:	total: 1.82s	remaining: 1.71s
450:	total: 2.02s	remaining: 1.47s
500:	total: 2.23s	remaining: 1.24s
550:	total: 2.44s	remaining: 1.01s
600:	total: 2.64s	remaining: 783ms
650:	total: 2.85s	remaining: 561ms
700:	total: 3.19s	remaining: 355ms

[I 2025-11-24 20:09:40,268] Trial 23 finished with value: 0.7252877945548908 and parameters: {'weight_pos': 1.560849113550387, 'iterations': 779, 'learning_rate': 0.08958661631075587, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.18065962549915204, 'bagging_temperature': 0.9853753702107262, 'rsm': 0.3528944875437947, 'min_data_in_leaf': 32, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

750:	total: 3.47s	remaining: 129ms
778:	total: 3.62s	remaining: 0us
0:	total: 6.72ms	remaining: 6.09s
50:	total: 306ms	remaining: 5.14s
100:	total: 572ms	remaining: 4.56s
150:	total: 865ms	remaining: 4.33s
200:	total: 1.12s	remaining: 3.95s
250:	total: 1.4s	remaining: 3.66s
300:	total: 1.65s	remaining: 3.32s
350:	total: 1.92s	remaining: 3.05s
400:	total: 2.32s	remaining: 2.93s
450:	total: 2.6s	remaining: 2.63s
500:	total: 2.86s	remaining: 2.31s
550:	total: 3.25s	remaining: 2.1s
600:	total: 3.49s	remaining: 1.78s
650:	total: 3.74s	remaining: 1.47s
700:	total: 3.99s	remaining: 1.17s
750:	total: 4.25s	remaining: 882ms
800:	total: 4.5s	remaining: 596ms
850:	total: 4.76s	remaining: 313ms
900:	total: 5.04s	remaining: 33.6ms
906:	total: 5.08s	remaining: 0us
0:	total: 4.81ms	remaining: 4.36s
50:	total: 252ms	remaining: 4.23s
100:	total: 558ms	remaining: 4.45s
150:	total: 846ms	remaining: 4.24s
200:	total: 1.11s	remaining: 3.9s
250:	total: 1.37s	remaining: 3.58s
300:	total: 1.63s	remaining: 3.29s
350:	total: 1.91s	remaining: 3.03s
400:	total: 2.18s	remaining: 2.75s
450:	total: 2.44s	remaining: 2.47s
500:	total: 2.71s	remaining: 2.2s
550:	total: 2.98s	remaining: 1.93s
600:	total: 3.27s	remaining: 1.67s
650:	total: 3.55s	remaining: 1.4s
700:	total: 3.82s	remaining: 1.12s
750:	total: 4.12s	remaining: 856ms
800:	total: 4.39s	remaining: 581ms
850:	total: 4.69s	remaining: 308ms
900:	total: 4.96s	remaining: 33ms
906:	total: 4.99s	remaining: 0us
0:	total: 5.87ms	remaining: 5.32s
50:	total: 259ms	remaining: 4.34s
100:	total: 513ms	remaining: 4.09s
150:	total: 763ms	remaining: 3.82s
200:	total: 1.05s	remaining: 3.69s
250:	total: 1.32s	remaining: 3.45s
300:	total: 1.59s	remaining: 3.2s
350:	total: 1.83s	remaining: 2.9s
400:	total: 2.17s	remaining: 2.74s
450:	total: 2.48s	remaining: 2.51s
500:	total: 2.91s	remaining: 2.36s
550:	total: 3.16s	remaining: 2.04s
600:	total: 3.43s	remaining: 1.75s
650:	total: 3.69s	remaining: 1.45s
700:	total: 3.96s	remaining: 1.16s
750:	total: 4.24s	remaining: 880ms
800:	total: 4.51s	remaining: 596ms
850:	total: 4.81s	remaining: 317ms
900:	total: 5.09s	remaining: 33.9ms
906:	total: 5.13s	remaining: 0us
0:	total: 7.24ms	remaining: 6.56s
50:	total: 265ms	remaining: 4.45s
100:	total: 585ms	remaining: 4.67s
150:	total: 863ms	remaining: 4.32s
200:	total: 1.13s	remaining: 3.96s
250:	total: 1.39s	remaining: 3.62s
300:	total: 1.67s	remaining: 3.36s
350:	total: 1.95s	remaining: 3.08s
400:	total: 2.2s	remaining: 2.78s
450:	total: 2.46s	remaining: 2.48s
500:	total: 2.71s	remaining: 2.19s
550:	total: 2.97s	remaining: 1.92s
600:	total: 3.22s	remaining: 1.64s
650:	total: 3.48s	remaining: 1.37s
700:	total: 3.74s	remaining: 1.1s
750:	total: 4s	remaining: 831ms
800:	total: 4.29s	remaining: 568ms
850:	total: 4.57s	remaining: 301ms
900:	total: 4.83s	remaining: 32.2ms
906:	total: 4.86s	remaining: 0us
0:	total: 6.86ms	remaining: 6.21s
50:	total: 270ms	remaining: 4.53s
100:	total: 574ms	remaining: 4.58s
150:	total: 873ms	remaining: 4.37s
200:	total: 1.15s	remaining: 4.05s
250:	total: 1.44s	remaining: 3.76s
300:	total: 1.73s	remaining: 3.48s
350:	total: 2.09s	remaining: 3.31s
400:	total: 2.98s	remaining: 3.76s
450:	total: 3.25s	remaining: 3.28s
500:	total: 3.5s	remaining: 2.84s
550:	total: 3.77s	remaining: 2.43s
600:	total: 4.11s	remaining: 2.09s
650:	total: 4.41s	remaining: 1.73s
700:	total: 4.69s	remaining: 1.38s
750:	total: 4.96s	remaining: 1.03s
800:	total: 5.29s	remaining: 700ms
850:	total: 5.59s	remaining: 368ms

[I 2025-11-24 20:10:06,922] Trial 24 finished with value: 0.6631267124693129 and parameters: {'weight_pos': 4.572546466466946, 'iterations': 907, 'learning_rate': 0.01055840720983813, 'depth': 6, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.008080681713272857, 'bagging_temperature': 0.9479305112490403, 'rsm': 0.2014399918278536, 'min_data_in_leaf': 18, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 5.87s	remaining: 39.1ms
906:	total: 5.9s	remaining: 0us
0:	total: 6.22ms	remaining: 5.75s
50:	total: 297ms	remaining: 5.08s
100:	total: 641ms	remaining: 5.23s
150:	total: 989ms	remaining: 5.06s
200:	total: 1.32s	remaining: 4.76s
250:	total: 1.66s	remaining: 4.45s
300:	total: 2.09s	remaining: 4.32s
350:	total: 2.66s	remaining: 4.34s
400:	total: 3.01s	remaining: 3.93s
450:	total: 3.36s	remaining: 3.52s
500:	total: 3.71s	remaining: 3.14s
550:	total: 4.06s	remaining: 2.75s
600:	total: 4.39s	remaining: 2.36s
650:	total: 4.7s	remaining: 1.97s
700:	total: 5s	remaining: 1.59s
750:	total: 5.3s	remaining: 1.22s
800:	total: 5.61s	remaining: 862ms
850:	total: 5.91s	remaining: 507ms
900:	total: 6.24s	remaining: 159ms
923:	total: 6.63s	remaining: 0us
0:	total: 8.5ms	remaining: 7.84s
50:	total: 327ms	remaining: 5.59s
100:	total: 609ms	remaining: 4.97s
150:	total: 917ms	remaining: 4.7s
200:	total: 1.2s	remaining: 4.32s
250:	total: 1.48s	remaining: 3.97s
300:	total: 1.76s	remaining: 3.65s
350:	total: 2.21s	remaining: 3.62s
400:	total: 2.53s	remaining: 3.3s
450:	total: 2.86s	remaining: 3s
500:	total: 3.18s	remaining: 2.69s
550:	total: 3.58s	remaining: 2.42s
600:	total: 4s	remaining: 2.15s
650:	total: 4.32s	remaining: 1.81s
700:	total: 4.65s	remaining: 1.48s
750:	total: 4.95s	remaining: 1.14s
800:	total: 5.28s	remaining: 811ms
850:	total: 5.61s	remaining: 482ms
900:	total: 5.92s	remaining: 151ms
923:	total: 6.06s	remaining: 0us
0:	total: 6.54ms	remaining: 6.04s
50:	total: 284ms	remaining: 4.86s
100:	total: 595ms	remaining: 4.85s
150:	total: 888ms	remaining: 4.55s
200:	total: 1.19s	remaining: 4.3s
250:	total: 1.49s	remaining: 4.01s
300:	total: 1.81s	remaining: 3.75s
350:	total: 2.12s	remaining: 3.46s
400:	total: 2.43s	remaining: 3.17s
450:	total: 2.7s	remaining: 2.83s
500:	total: 2.98s	remaining: 2.51s
550:	total: 3.42s	remaining: 2.31s
600:	total: 3.75s	remaining: 2.02s
650:	total: 4.04s	remaining: 1.7s
700:	total: 4.33s	remaining: 1.38s
750:	total: 4.64s	remaining: 1.07s
800:	total: 4.98s	remaining: 764ms
850:	total: 5.35s	remaining: 459ms
900:	total: 5.8s	remaining: 148ms
923:	total: 6.01s	remaining: 0us
0:	total: 8.9ms	remaining: 8.21s
50:	total: 342ms	remaining: 5.86s
100:	total: 654ms	remaining: 5.33s
150:	total: 971ms	remaining: 4.97s
200:	total: 1.29s	remaining: 4.63s
250:	total: 1.59s	remaining: 4.28s
300:	total: 1.93s	remaining: 4s
350:	total: 2.24s	remaining: 3.66s
400:	total: 2.59s	remaining: 3.38s
450:	total: 2.96s	remaining: 3.1s
500:	total: 3.37s	remaining: 2.84s
550:	total: 3.81s	remaining: 2.58s
600:	total: 4.16s	remaining: 2.23s
650:	total: 4.49s	remaining: 1.88s
700:	total: 4.8s	remaining: 1.53s
750:	total: 5.11s	remaining: 1.18s
800:	total: 5.41s	remaining: 831ms
850:	total: 5.71s	remaining: 490ms
900:	total: 6.02s	remaining: 154ms
923:	total: 6.2s	remaining: 0us
0:	total: 8.61ms	remaining: 7.94s
50:	total: 406ms	remaining: 6.94s
100:	total: 699ms	remaining: 5.69s
150:	total: 1.22s	remaining: 6.26s
200:	total: 1.6s	remaining: 5.75s
250:	total: 1.92s	remaining: 5.16s
300:	total: 2.25s	remaining: 4.67s
350:	total: 2.59s	remaining: 4.23s
400:	total: 2.97s	remaining: 3.87s
450:	total: 3.55s	remaining: 3.72s
500:	total: 3.86s	remaining: 3.26s
550:	total: 4.21s	remaining: 2.85s
600:	total: 4.53s	remaining: 2.44s
650:	total: 4.86s	remaining: 2.04s
700:	total: 5.21s	remaining: 1.66s
750:	total: 5.54s	remaining: 1.27s
800:	total: 5.85s	remaining: 898ms
850:	total: 6.23s	remaining: 535ms

[I 2025-11-24 20:10:39,364] Trial 25 finished with value: 0.6695073389331595 and parameters: {'weight_pos': 6.821554975919271, 'iterations': 924, 'learning_rate': 0.02626134582286559, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.7646113831768094, 'bagging_temperature': 0.7801033991144167, 'rsm': 0.6395822448366824, 'min_data_in_leaf': 55, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 6.56s	remaining: 167ms
923:	total: 6.71s	remaining: 0us
0:	total: 7.7ms	remaining: 4.94s
50:	total: 340ms	remaining: 3.94s
100:	total: 688ms	remaining: 3.69s
150:	total: 1.02s	remaining: 3.34s
200:	total: 1.37s	remaining: 3.02s
250:	total: 1.74s	remaining: 2.72s
300:	total: 2.08s	remaining: 2.37s
350:	total: 2.43s	remaining: 2.02s
400:	total: 2.84s	remaining: 1.71s
450:	total: 3.23s	remaining: 1.37s
500:	total: 3.57s	remaining: 1.01s
550:	total: 4.07s	remaining: 680ms
600:	total: 4.44s	remaining: 311ms
642:	total: 4.75s	remaining: 0us
0:	total: 7.77ms	remaining: 4.99s
50:	total: 375ms	remaining: 4.36s
100:	total: 845ms	remaining: 4.53s
150:	total: 1.39s	remaining: 4.52s
200:	total: 1.86s	remaining: 4.09s
250:	total: 2.24s	remaining: 3.5s
300:	total: 2.59s	remaining: 2.94s
350:	total: 2.93s	remaining: 2.44s
400:	total: 3.32s	remaining: 2.01s
450:	total: 3.69s	remaining: 1.57s
500:	total: 4.03s	remaining: 1.14s
550:	total: 4.39s	remaining: 733ms
600:	total: 4.81s	remaining: 336ms
642:	total: 5.18s	remaining: 0us
0:	total: 7.77ms	remaining: 4.99s
50:	total: 347ms	remaining: 4.03s
100:	total: 703ms	remaining: 3.77s
150:	total: 1.05s	remaining: 3.42s
200:	total: 1.4s	remaining: 3.08s
250:	total: 1.75s	remaining: 2.73s
300:	total: 2.09s	remaining: 2.37s
350:	total: 2.44s	remaining: 2.03s
400:	total: 2.78s	remaining: 1.68s
450:	total: 3.18s	remaining: 1.35s
500:	total: 3.79s	remaining: 1.07s
550:	total: 4.4s	remaining: 735ms
600:	total: 4.77s	remaining: 334ms
642:	total: 5.06s	remaining: 0us
0:	total: 10.9ms	remaining: 6.98s
50:	total: 589ms	remaining: 6.84s
100:	total: 1.04s	remaining: 5.6s
150:	total: 1.51s	remaining: 4.93s
200:	total: 1.9s	remaining: 4.17s
250:	total: 2.25s	remaining: 3.52s
300:	total: 2.62s	remaining: 2.98s
350:	total: 2.98s	remaining: 2.48s
400:	total: 3.35s	remaining: 2.02s
450:	total: 3.71s	remaining: 1.58s
500:	total: 4.08s	remaining: 1.16s
550:	total: 4.42s	remaining: 737ms
600:	total: 4.76s	remaining: 333ms
642:	total: 5.05s	remaining: 0us
0:	total: 7.49ms	remaining: 4.81s
50:	total: 348ms	remaining: 4.04s
100:	total: 677ms	remaining: 3.63s
150:	total: 992ms	remaining: 3.23s
200:	total: 1.32s	remaining: 2.9s
250:	total: 1.65s	remaining: 2.57s
300:	total: 1.98s	remaining: 2.25s
350:	total: 2.31s	remaining: 1.92s
400:	total: 2.64s	remaining: 1.59s
450:	total: 2.98s	remaining: 1.27s
500:	total: 3.32s	remaining: 941ms
550:	total: 3.85s	remaining: 643ms
600:	total: 4.21s	remaining: 294ms

[I 2025-11-24 20:11:04,546] Trial 26 finished with value: 0.7186748027755698 and parameters: {'weight_pos': 1.6885330965410792, 'iterations': 643, 'learning_rate': 0.0937631515992347, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.109216865459314, 'bagging_temperature': 0.9138564809488345, 'rsm': 0.5153553408737542, 'min_data_in_leaf': 35, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

642:	total: 4.52s	remaining: 0us
0:	total: 4.22ms	remaining: 2.43s
50:	total: 168ms	remaining: 1.74s
100:	total: 379ms	remaining: 1.78s
150:	total: 550ms	remaining: 1.55s
200:	total: 725ms	remaining: 1.36s
250:	total: 895ms	remaining: 1.16s
300:	total: 1.09s	remaining: 997ms
350:	total: 1.27s	remaining: 816ms
400:	total: 1.44s	remaining: 633ms
450:	total: 1.65s	remaining: 461ms
500:	total: 1.88s	remaining: 285ms
550:	total: 2.06s	remaining: 97.2ms
576:	total: 2.15s	remaining: 0us
0:	total: 4.38ms	remaining: 2.52s
50:	total: 161ms	remaining: 1.66s
100:	total: 335ms	remaining: 1.58s
150:	total: 507ms	remaining: 1.43s
200:	total: 682ms	remaining: 1.27s
250:	total: 858ms	remaining: 1.11s
300:	total: 1.04s	remaining: 956ms
350:	total: 1.21s	remaining: 782ms
400:	total: 1.39s	remaining: 609ms
450:	total: 1.56s	remaining: 436ms
500:	total: 1.73s	remaining: 263ms
550:	total: 1.93s	remaining: 91.3ms
576:	total: 2.03s	remaining: 0us
0:	total: 4.33ms	remaining: 2.49s
50:	total: 166ms	remaining: 1.72s
100:	total: 340ms	remaining: 1.6s
150:	total: 552ms	remaining: 1.56s
200:	total: 742ms	remaining: 1.39s
250:	total: 916ms	remaining: 1.19s
300:	total: 1.09s	remaining: 1000ms
350:	total: 1.26s	remaining: 815ms
400:	total: 1.45s	remaining: 635ms
450:	total: 1.63s	remaining: 454ms
500:	total: 1.81s	remaining: 274ms
550:	total: 1.99s	remaining: 93.7ms
576:	total: 2.07s	remaining: 0us
0:	total: 4.79ms	remaining: 2.76s
50:	total: 195ms	remaining: 2.01s
100:	total: 374ms	remaining: 1.76s
150:	total: 551ms	remaining: 1.55s
200:	total: 735ms	remaining: 1.38s
250:	total: 923ms	remaining: 1.2s
300:	total: 1.12s	remaining: 1.03s
350:	total: 1.32s	remaining: 848ms
400:	total: 1.5s	remaining: 659ms
450:	total: 1.7s	remaining: 475ms
500:	total: 1.89s	remaining: 287ms
550:	total: 2.06s	remaining: 97.4ms
576:	total: 2.24s	remaining: 0us
0:	total: 8.6ms	remaining: 4.95s
50:	total: 223ms	remaining: 2.3s
100:	total: 395ms	remaining: 1.86s
150:	total: 577ms	remaining: 1.63s
200:	total: 787ms	remaining: 1.47s
250:	total: 968ms	remaining: 1.26s
300:	total: 1.14s	remaining: 1.05s
350:	total: 1.31s	remaining: 847ms
400:	total: 1.49s	remaining: 652ms
450:	total: 1.65s	remaining: 460ms
500:	total: 1.81s	remaining: 275ms
550:	total: 1.98s	remaining: 93.5ms

[I 2025-11-24 20:11:15,687] Trial 27 finished with value: 0.5980193315761351 and parameters: {'weight_pos': 1.041574517591861, 'iterations': 577, 'learning_rate': 0.01968086749691821, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 9.075828485723175, 'bagging_temperature': 0.8604157517742261, 'rsm': 0.3912983442669043, 'min_data_in_leaf': 21, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

576:	total: 2.07s	remaining: 0us
0:	total: 3.91ms	remaining: 2.97s
50:	total: 176ms	remaining: 2.45s
100:	total: 344ms	remaining: 2.24s
150:	total: 508ms	remaining: 2.05s
200:	total: 677ms	remaining: 1.88s
250:	total: 858ms	remaining: 1.74s
300:	total: 1.02s	remaining: 1.55s
350:	total: 1.19s	remaining: 1.38s
400:	total: 1.36s	remaining: 1.21s
450:	total: 1.53s	remaining: 1.04s
500:	total: 1.69s	remaining: 873ms
550:	total: 1.86s	remaining: 702ms
600:	total: 2.03s	remaining: 533ms
650:	total: 2.2s	remaining: 365ms
700:	total: 2.37s	remaining: 196ms
750:	total: 2.53s	remaining: 27ms
758:	total: 2.56s	remaining: 0us
0:	total: 4.51ms	remaining: 3.42s
50:	total: 171ms	remaining: 2.37s
100:	total: 333ms	remaining: 2.17s
150:	total: 495ms	remaining: 1.99s
200:	total: 673ms	remaining: 1.87s
250:	total: 842ms	remaining: 1.7s
300:	total: 1.02s	remaining: 1.55s
350:	total: 1.18s	remaining: 1.37s
400:	total: 1.35s	remaining: 1.21s
450:	total: 1.51s	remaining: 1.03s
500:	total: 1.68s	remaining: 865ms
550:	total: 1.84s	remaining: 695ms
600:	total: 2s	remaining: 527ms
650:	total: 2.17s	remaining: 360ms
700:	total: 2.34s	remaining: 193ms
750:	total: 2.51s	remaining: 26.7ms
758:	total: 2.53s	remaining: 0us
0:	total: 3.41ms	remaining: 2.58s
50:	total: 167ms	remaining: 2.31s
100:	total: 335ms	remaining: 2.18s
150:	total: 495ms	remaining: 1.99s
200:	total: 658ms	remaining: 1.83s
250:	total: 884ms	remaining: 1.79s
300:	total: 1.05s	remaining: 1.6s
350:	total: 1.22s	remaining: 1.41s
400:	total: 1.38s	remaining: 1.24s
450:	total: 1.54s	remaining: 1.05s
500:	total: 1.71s	remaining: 879ms
550:	total: 1.89s	remaining: 712ms
600:	total: 2.05s	remaining: 539ms
650:	total: 2.22s	remaining: 368ms
700:	total: 2.54s	remaining: 210ms
750:	total: 2.72s	remaining: 29ms
758:	total: 2.75s	remaining: 0us
0:	total: 3.73ms	remaining: 2.83s
50:	total: 233ms	remaining: 3.24s
100:	total: 437ms	remaining: 2.84s
150:	total: 670ms	remaining: 2.7s
200:	total: 860ms	remaining: 2.39s
250:	total: 1.03s	remaining: 2.08s
300:	total: 1.2s	remaining: 1.82s
350:	total: 1.36s	remaining: 1.58s
400:	total: 1.53s	remaining: 1.37s
450:	total: 1.75s	remaining: 1.19s
500:	total: 1.95s	remaining: 1s
550:	total: 2.13s	remaining: 802ms
600:	total: 2.36s	remaining: 620ms
650:	total: 2.58s	remaining: 429ms
700:	total: 2.84s	remaining: 235ms
750:	total: 3.02s	remaining: 32.1ms
758:	total: 3.05s	remaining: 0us
0:	total: 5.05ms	remaining: 3.83s
50:	total: 181ms	remaining: 2.52s
100:	total: 372ms	remaining: 2.42s
150:	total: 559ms	remaining: 2.25s
200:	total: 735ms	remaining: 2.04s
250:	total: 897ms	remaining: 1.82s
300:	total: 1.06s	remaining: 1.62s
350:	total: 1.23s	remaining: 1.43s
400:	total: 1.39s	remaining: 1.24s
450:	total: 1.56s	remaining: 1.07s
500:	total: 1.73s	remaining: 888ms
550:	total: 1.91s	remaining: 720ms
600:	total: 2.07s	remaining: 546ms
650:	total: 2.24s	remaining: 372ms
700:	total: 2.42s	remaining: 200ms

[I 2025-11-24 20:11:29,727] Trial 28 finished with value: 0.7283727867598079 and parameters: {'weight_pos': 2.445095315699074, 'iterations': 759, 'learning_rate': 0.05040458580547684, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.00015577850440614115, 'bagging_temperature': 0.580624228788284, 'rsm': 0.2130637397762883, 'min_data_in_leaf': 49, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

750:	total: 2.58s	remaining: 27.5ms
758:	total: 2.61s	remaining: 0us
0:	total: 9.47ms	remaining: 8.13s
50:	total: 427ms	remaining: 6.78s
100:	total: 828ms	remaining: 6.22s
150:	total: 1.32s	remaining: 6.2s
200:	total: 1.72s	remaining: 5.64s
250:	total: 2.12s	remaining: 5.15s
300:	total: 2.52s	remaining: 4.68s
350:	total: 3.02s	remaining: 4.37s
400:	total: 3.47s	remaining: 3.97s
450:	total: 4.07s	remaining: 3.69s
500:	total: 4.49s	remaining: 3.21s
550:	total: 4.92s	remaining: 2.76s
600:	total: 5.41s	remaining: 2.33s
650:	total: 5.85s	remaining: 1.88s
700:	total: 6.46s	remaining: 1.47s
750:	total: 7.05s	remaining: 1.02s
800:	total: 7.55s	remaining: 556ms
850:	total: 8.02s	remaining: 84.8ms
859:	total: 8.1s	remaining: 0us
0:	total: 8.39ms	remaining: 7.21s
50:	total: 442ms	remaining: 7s
100:	total: 848ms	remaining: 6.37s
150:	total: 1.24s	remaining: 5.8s
200:	total: 1.63s	remaining: 5.33s
250:	total: 2.02s	remaining: 4.92s
300:	total: 2.42s	remaining: 4.5s
350:	total: 2.92s	remaining: 4.24s
400:	total: 3.36s	remaining: 3.84s
450:	total: 3.79s	remaining: 3.44s
500:	total: 4.21s	remaining: 3.02s
550:	total: 4.66s	remaining: 2.61s
600:	total: 5.08s	remaining: 2.19s
650:	total: 5.65s	remaining: 1.81s
700:	total: 6.09s	remaining: 1.38s
750:	total: 6.52s	remaining: 947ms
800:	total: 6.95s	remaining: 512ms
850:	total: 7.37s	remaining: 78ms
859:	total: 7.45s	remaining: 0us
0:	total: 8.09ms	remaining: 6.95s
50:	total: 398ms	remaining: 6.32s
100:	total: 909ms	remaining: 6.83s
150:	total: 1.48s	remaining: 6.96s
200:	total: 2.05s	remaining: 6.71s
250:	total: 2.47s	remaining: 6s
300:	total: 2.94s	remaining: 5.46s
350:	total: 3.44s	remaining: 4.99s
400:	total: 3.87s	remaining: 4.43s
450:	total: 4.29s	remaining: 3.89s
500:	total: 4.73s	remaining: 3.39s
550:	total: 5.19s	remaining: 2.91s
600:	total: 5.66s	remaining: 2.44s
650:	total: 6.13s	remaining: 1.97s
700:	total: 6.59s	remaining: 1.49s
750:	total: 7.03s	remaining: 1.02s
800:	total: 7.47s	remaining: 550ms
850:	total: 8.13s	remaining: 85.9ms
859:	total: 8.24s	remaining: 0us
0:	total: 9.51ms	remaining: 8.17s
50:	total: 615ms	remaining: 9.76s
100:	total: 1.16s	remaining: 8.7s
150:	total: 1.77s	remaining: 8.3s
200:	total: 2.38s	remaining: 7.82s
250:	total: 2.84s	remaining: 6.9s
300:	total: 3.34s	remaining: 6.2s
350:	total: 3.82s	remaining: 5.53s
400:	total: 4.29s	remaining: 4.91s
450:	total: 4.8s	remaining: 4.35s
500:	total: 5.24s	remaining: 3.76s
550:	total: 5.69s	remaining: 3.19s
600:	total: 6.14s	remaining: 2.65s
650:	total: 6.61s	remaining: 2.12s
700:	total: 7.09s	remaining: 1.61s
750:	total: 7.54s	remaining: 1.09s
800:	total: 7.98s	remaining: 588ms
850:	total: 8.45s	remaining: 89.4ms
859:	total: 8.54s	remaining: 0us
0:	total: 8.6ms	remaining: 7.38s
50:	total: 591ms	remaining: 9.37s
100:	total: 1.18s	remaining: 8.86s
150:	total: 1.67s	remaining: 7.83s
200:	total: 2.23s	remaining: 7.3s
250:	total: 2.7s	remaining: 6.56s
300:	total: 3.57s	remaining: 6.63s
350:	total: 4.14s	remaining: 6s
400:	total: 4.72s	remaining: 5.41s
450:	total: 5.42s	remaining: 4.92s
500:	total: 5.9s	remaining: 4.23s
550:	total: 6.35s	remaining: 3.56s
600:	total: 6.84s	remaining: 2.95s
650:	total: 7.33s	remaining: 2.35s
700:	total: 7.8s	remaining: 1.77s
750:	total: 8.4s	remaining: 1.22s
800:	total: 8.93s	remaining: 658ms

[I 2025-11-24 20:12:12,435] Trial 29 finished with value: 0.6594420054319328 and parameters: {'weight_pos': 2.1103870002527163, 'iterations': 860, 'learning_rate': 0.030770086432464767, 'depth': 8, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.004590811802277429, 'bagging_temperature': 0.45463059251077026, 'rsm': 0.12582685763790497, 'min_data_in_leaf': 8, 'leaf_estimation_iterations': 10}. Best is trial 16 with value: 0.7404863910277388.

850:	total: 9.4s	remaining: 99.4ms
859:	total: 9.48s	remaining: 0us
0:	total: 18ms	remaining: 16.9s
50:	total: 926ms	remaining: 16.2s
100:	total: 1.83s	remaining: 15.3s
150:	total: 2.63s	remaining: 13.8s
200:	total: 3.34s	remaining: 12.4s
250:	total: 4.04s	remaining: 11.2s
300:	total: 4.72s	remaining: 10.1s
350:	total: 5.46s	remaining: 9.22s
400:	total: 6.16s	remaining: 8.34s
450:	total: 6.8s	remaining: 7.43s
500:	total: 7.45s	remaining: 6.59s
550:	total: 8.12s	remaining: 5.79s
600:	total: 8.76s	remaining: 5s
650:	total: 9.45s	remaining: 4.25s
700:	total: 10.2s	remaining: 3.54s
750:	total: 11s	remaining: 2.83s
800:	total: 11.7s	remaining: 2.09s
850:	total: 12.4s	remaining: 1.35s
900:	total: 13.1s	remaining: 623ms
943:	total: 13.7s	remaining: 0us
0:	total: 9.46ms	remaining: 8.93s
50:	total: 624ms	remaining: 10.9s
100:	total: 1.3s	remaining: 10.8s
150:	total: 1.94s	remaining: 10.2s
200:	total: 2.63s	remaining: 9.71s
250:	total: 3.34s	remaining: 9.23s
300:	total: 4.07s	remaining: 8.7s
350:	total: 5.69s	remaining: 9.61s
400:	total: 7.14s	remaining: 9.67s
450:	total: 8.49s	remaining: 9.28s
500:	total: 9.84s	remaining: 8.7s
550:	total: 10.6s	remaining: 7.59s
600:	total: 12s	remaining: 6.86s
650:	total: 13s	remaining: 5.86s
700:	total: 13.7s	remaining: 4.76s
750:	total: 14.5s	remaining: 3.71s
800:	total: 15.2s	remaining: 2.71s
850:	total: 16s	remaining: 1.75s
900:	total: 16.8s	remaining: 802ms
943:	total: 17.8s	remaining: 0us
0:	total: 14ms	remaining: 13.2s
50:	total: 655ms	remaining: 11.5s
100:	total: 1.35s	remaining: 11.3s
150:	total: 2.07s	remaining: 10.9s
200:	total: 3.01s	remaining: 11.1s
250:	total: 3.88s	remaining: 10.7s
300:	total: 4.6s	remaining: 9.83s
350:	total: 5.29s	remaining: 8.93s
400:	total: 6s	remaining: 8.13s
450:	total: 6.75s	remaining: 7.37s
500:	total: 7.72s	remaining: 6.83s
550:	total: 8.57s	remaining: 6.12s
600:	total: 9.63s	remaining: 5.5s
650:	total: 10.4s	remaining: 4.66s
700:	total: 11s	remaining: 3.83s
750:	total: 11.8s	remaining: 3.02s
800:	total: 12.6s	remaining: 2.25s
850:	total: 13.3s	remaining: 1.45s
900:	total: 14.1s	remaining: 674ms
943:	total: 14.7s	remaining: 0us
0:	total: 11.9ms	remaining: 11.2s
50:	total: 668ms	remaining: 11.7s
100:	total: 1.34s	remaining: 11.2s
150:	total: 2.21s	remaining: 11.6s
200:	total: 3.05s	remaining: 11.3s
250:	total: 3.88s	remaining: 10.7s
300:	total: 4.82s	remaining: 10.3s
350:	total: 5.5s	remaining: 9.3s
400:	total: 6.31s	remaining: 8.54s
450:	total: 7.07s	remaining: 7.73s
500:	total: 7.86s	remaining: 6.95s
550:	total: 8.54s	remaining: 6.09s
600:	total: 9.23s	remaining: 5.27s
650:	total: 9.9s	remaining: 4.45s
700:	total: 10.6s	remaining: 3.68s
750:	total: 11.3s	remaining: 2.9s
800:	total: 11.9s	remaining: 2.13s
850:	total: 12.5s	remaining: 1.37s
900:	total: 13.2s	remaining: 630ms
943:	total: 13.8s	remaining: 0us
0:	total: 14.7ms	remaining: 13.8s
50:	total: 815ms	remaining: 14.3s
100:	total: 1.49s	remaining: 12.4s
150:	total: 2.12s	remaining: 11.1s
200:	total: 2.82s	remaining: 10.4s
250:	total: 3.54s	remaining: 9.77s
300:	total: 4.31s	remaining: 9.21s
350:	total: 5.06s	remaining: 8.55s
400:	total: 5.79s	remaining: 7.84s
450:	total: 6.52s	remaining: 7.12s
500:	total: 7.21s	remaining: 6.37s
550:	total: 7.9s	remaining: 5.63s
600:	total: 8.62s	remaining: 4.92s
650:	total: 9.29s	remaining: 4.18s
700:	total: 9.95s	remaining: 3.45s
750:	total: 10.8s	remaining: 2.78s
800:	total: 11.5s	remaining: 2.05s
850:	total: 12.2s	remaining: 1.33s
900:	total: 12.8s	remaining: 612ms

[I 2025-11-24 20:13:26,702] Trial 30 finished with value: 0.7068124287827018 and parameters: {'weight_pos': 3.7665400943621172, 'iterations': 944, 'learning_rate': 0.27331472438446774, 'depth': 6, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.2306264102350113, 'bagging_temperature': 0.014770712925990193, 'rsm': 0.8886768542723329, 'min_data_in_leaf': 43, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

943:	total: 13.4s	remaining: 0us
0:	total: 4.25ms	remaining: 3.26s
50:	total: 169ms	remaining: 2.38s
100:	total: 335ms	remaining: 2.22s
150:	total: 513ms	remaining: 2.1s
200:	total: 687ms	remaining: 1.94s
250:	total: 864ms	remaining: 1.78s
300:	total: 1.03s	remaining: 1.6s
350:	total: 1.19s	remaining: 1.42s
400:	total: 1.36s	remaining: 1.25s
450:	total: 1.56s	remaining: 1.1s
500:	total: 1.74s	remaining: 928ms
550:	total: 1.91s	remaining: 756ms
600:	total: 2.08s	remaining: 582ms
650:	total: 2.26s	remaining: 409ms
700:	total: 2.44s	remaining: 237ms
750:	total: 2.62s	remaining: 62.8ms
768:	total: 2.68s	remaining: 0us
0:	total: 4.76ms	remaining: 3.66s
50:	total: 171ms	remaining: 2.41s
100:	total: 331ms	remaining: 2.19s
150:	total: 490ms	remaining: 2.01s
200:	total: 678ms	remaining: 1.92s
250:	total: 874ms	remaining: 1.8s
300:	total: 1.05s	remaining: 1.64s
350:	total: 1.23s	remaining: 1.46s
400:	total: 1.44s	remaining: 1.32s
450:	total: 1.71s	remaining: 1.21s
500:	total: 1.98s	remaining: 1.06s
550:	total: 2.25s	remaining: 891ms
600:	total: 2.48s	remaining: 692ms
650:	total: 2.7s	remaining: 489ms
700:	total: 2.88s	remaining: 279ms
750:	total: 3.06s	remaining: 73.5ms
768:	total: 3.13s	remaining: 0us
0:	total: 20.5ms	remaining: 15.7s
50:	total: 237ms	remaining: 3.34s
100:	total: 401ms	remaining: 2.65s
150:	total: 731ms	remaining: 2.99s
200:	total: 961ms	remaining: 2.71s
250:	total: 1.13s	remaining: 2.33s
300:	total: 1.29s	remaining: 2.01s
350:	total: 1.47s	remaining: 1.75s
400:	total: 1.66s	remaining: 1.52s
450:	total: 1.86s	remaining: 1.31s
500:	total: 2.11s	remaining: 1.13s
550:	total: 2.3s	remaining: 912ms
600:	total: 2.47s	remaining: 692ms
650:	total: 2.64s	remaining: 478ms
700:	total: 2.81s	remaining: 273ms
750:	total: 3s	remaining: 71.8ms
768:	total: 3.06s	remaining: 0us
0:	total: 4.04ms	remaining: 3.1s
50:	total: 178ms	remaining: 2.51s
100:	total: 366ms	remaining: 2.42s
150:	total: 545ms	remaining: 2.23s
200:	total: 735ms	remaining: 2.08s
250:	total: 897ms	remaining: 1.85s
300:	total: 1.08s	remaining: 1.67s
350:	total: 1.26s	remaining: 1.5s
400:	total: 1.47s	remaining: 1.35s
450:	total: 1.65s	remaining: 1.16s
500:	total: 1.82s	remaining: 976ms
550:	total: 2.12s	remaining: 841ms
600:	total: 2.3s	remaining: 642ms
650:	total: 2.51s	remaining: 454ms
700:	total: 2.74s	remaining: 266ms
750:	total: 2.95s	remaining: 70.8ms
768:	total: 3.03s	remaining: 0us
0:	total: 5.13ms	remaining: 3.94s
50:	total: 218ms	remaining: 3.06s
100:	total: 461ms	remaining: 3.05s
150:	total: 665ms	remaining: 2.72s
200:	total: 849ms	remaining: 2.4s
250:	total: 1.03s	remaining: 2.12s
300:	total: 1.21s	remaining: 1.88s
350:	total: 1.39s	remaining: 1.66s
400:	total: 1.58s	remaining: 1.45s
450:	total: 1.76s	remaining: 1.24s
500:	total: 1.93s	remaining: 1.03s
550:	total: 2.1s	remaining: 830ms
600:	total: 2.28s	remaining: 636ms
650:	total: 2.45s	remaining: 444ms
700:	total: 2.63s	remaining: 255ms

[I 2025-11-24 20:13:42,033] Trial 31 finished with value: 0.7327602830819496 and parameters: {'weight_pos': 2.3009601213116477, 'iterations': 769, 'learning_rate': 0.05680154728449899, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0001288402526047258, 'bagging_temperature': 0.5814640334751346, 'rsm': 0.2241084391822153, 'min_data_in_leaf': 49, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

750:	total: 2.8s	remaining: 67ms
768:	total: 2.86s	remaining: 0us
0:	total: 4.94ms	remaining: 4.22s
50:	total: 239ms	remaining: 3.78s
100:	total: 458ms	remaining: 3.43s
150:	total: 681ms	remaining: 3.18s
200:	total: 918ms	remaining: 2.99s
250:	total: 1.15s	remaining: 2.78s
300:	total: 1.54s	remaining: 2.85s
350:	total: 1.77s	remaining: 2.55s
400:	total: 2s	remaining: 2.27s
450:	total: 2.25s	remaining: 2.02s
500:	total: 2.49s	remaining: 1.77s
550:	total: 2.74s	remaining: 1.51s
600:	total: 3s	remaining: 1.27s
650:	total: 3.23s	remaining: 1.02s
700:	total: 3.48s	remaining: 769ms
750:	total: 3.72s	remaining: 520ms
800:	total: 3.97s	remaining: 273ms
850:	total: 4.21s	remaining: 24.8ms
855:	total: 4.24s	remaining: 0us
0:	total: 4.89ms	remaining: 4.18s
50:	total: 230ms	remaining: 3.64s
100:	total: 460ms	remaining: 3.44s
150:	total: 701ms	remaining: 3.27s
200:	total: 941ms	remaining: 3.07s
250:	total: 1.17s	remaining: 2.82s
300:	total: 1.39s	remaining: 2.57s
350:	total: 1.62s	remaining: 2.33s
400:	total: 1.89s	remaining: 2.15s
450:	total: 2.17s	remaining: 1.95s
500:	total: 2.42s	remaining: 1.72s
550:	total: 2.65s	remaining: 1.47s
600:	total: 2.89s	remaining: 1.23s
650:	total: 3.13s	remaining: 985ms
700:	total: 3.36s	remaining: 743ms
750:	total: 3.62s	remaining: 506ms
800:	total: 3.91s	remaining: 269ms
850:	total: 4.18s	remaining: 24.6ms
855:	total: 4.21s	remaining: 0us
0:	total: 5.85ms	remaining: 5s
50:	total: 262ms	remaining: 4.14s
100:	total: 542ms	remaining: 4.05s
150:	total: 790ms	remaining: 3.69s
200:	total: 1.03s	remaining: 3.37s
250:	total: 1.27s	remaining: 3.07s
300:	total: 1.53s	remaining: 2.82s
350:	total: 1.77s	remaining: 2.54s
400:	total: 2.02s	remaining: 2.3s
450:	total: 2.26s	remaining: 2.03s
500:	total: 2.49s	remaining: 1.77s
550:	total: 2.92s	remaining: 1.62s
600:	total: 3.16s	remaining: 1.34s
650:	total: 3.4s	remaining: 1.07s
700:	total: 3.63s	remaining: 803ms
750:	total: 3.87s	remaining: 541ms
800:	total: 4.11s	remaining: 282ms
850:	total: 4.4s	remaining: 25.9ms
855:	total: 4.43s	remaining: 0us
0:	total: 6.21ms	remaining: 5.31s
50:	total: 228ms	remaining: 3.59s
100:	total: 469ms	remaining: 3.5s
150:	total: 689ms	remaining: 3.22s
200:	total: 923ms	remaining: 3.01s
250:	total: 1.17s	remaining: 2.81s
300:	total: 1.39s	remaining: 2.57s
350:	total: 1.62s	remaining: 2.33s
400:	total: 1.84s	remaining: 2.09s
450:	total: 2.07s	remaining: 1.86s
500:	total: 2.29s	remaining: 1.62s
550:	total: 2.51s	remaining: 1.39s
600:	total: 2.73s	remaining: 1.16s
650:	total: 2.97s	remaining: 936ms
700:	total: 3.23s	remaining: 715ms
750:	total: 3.49s	remaining: 488ms
800:	total: 3.72s	remaining: 256ms
850:	total: 3.95s	remaining: 23.2ms
855:	total: 3.98s	remaining: 0us
0:	total: 6.16ms	remaining: 5.27s
50:	total: 247ms	remaining: 3.9s
100:	total: 477ms	remaining: 3.56s
150:	total: 715ms	remaining: 3.34s
200:	total: 955ms	remaining: 3.11s
250:	total: 1.18s	remaining: 2.85s
300:	total: 1.43s	remaining: 2.63s
350:	total: 1.67s	remaining: 2.4s
400:	total: 1.92s	remaining: 2.17s
450:	total: 2.15s	remaining: 1.93s
500:	total: 2.38s	remaining: 1.69s
550:	total: 2.62s	remaining: 1.45s
600:	total: 2.86s	remaining: 1.21s
650:	total: 3.09s	remaining: 974ms
700:	total: 3.35s	remaining: 741ms
750:	total: 3.59s	remaining: 502ms
800:	total: 3.84s	remaining: 264ms

[I 2025-11-24 20:14:04,365] Trial 32 finished with value: 0.7188123352257617 and parameters: {'weight_pos': 1.4512701615712598, 'iterations': 856, 'learning_rate': 0.0414923091919612, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 4.426724441934781e-05, 'bagging_temperature': 0.9301232973621829, 'rsm': 0.264531551631983, 'min_data_in_leaf': 66, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

850:	total: 4.81s	remaining: 28.3ms
855:	total: 4.84s	remaining: 0us
0:	total: 4.77ms	remaining: 4.76s
50:	total: 189ms	remaining: 3.52s
100:	total: 329ms	remaining: 2.92s
150:	total: 457ms	remaining: 2.57s
200:	total: 583ms	remaining: 2.32s
250:	total: 699ms	remaining: 2.08s
300:	total: 816ms	remaining: 1.9s
350:	total: 930ms	remaining: 1.72s
400:	total: 1.04s	remaining: 1.56s
450:	total: 1.16s	remaining: 1.41s
500:	total: 1.27s	remaining: 1.26s
550:	total: 1.38s	remaining: 1.12s
600:	total: 1.49s	remaining: 989ms
650:	total: 1.59s	remaining: 854ms
700:	total: 1.72s	remaining: 732ms
750:	total: 1.82s	remaining: 604ms
800:	total: 1.93s	remaining: 480ms
850:	total: 2.04s	remaining: 357ms
900:	total: 2.17s	remaining: 238ms
950:	total: 2.28s	remaining: 118ms
999:	total: 2.41s	remaining: 0us
0:	total: 2.73ms	remaining: 2.73s
50:	total: 110ms	remaining: 2.04s
100:	total: 216ms	remaining: 1.93s
150:	total: 326ms	remaining: 1.83s
200:	total: 433ms	remaining: 1.72s
250:	total: 544ms	remaining: 1.62s
300:	total: 657ms	remaining: 1.52s
350:	total: 762ms	remaining: 1.41s
400:	total: 865ms	remaining: 1.29s
450:	total: 970ms	remaining: 1.18s
500:	total: 1.07s	remaining: 1.07s
550:	total: 1.18s	remaining: 962ms
600:	total: 1.29s	remaining: 855ms
650:	total: 1.39s	remaining: 744ms
700:	total: 1.49s	remaining: 636ms
750:	total: 1.59s	remaining: 529ms
800:	total: 1.71s	remaining: 424ms
850:	total: 1.83s	remaining: 321ms
900:	total: 1.94s	remaining: 213ms
950:	total: 2.05s	remaining: 106ms
999:	total: 2.16s	remaining: 0us
0:	total: 2.62ms	remaining: 2.61s
50:	total: 107ms	remaining: 2s
100:	total: 239ms	remaining: 2.13s
150:	total: 348ms	remaining: 1.95s
200:	total: 450ms	remaining: 1.79s
250:	total: 556ms	remaining: 1.66s
300:	total: 662ms	remaining: 1.54s
350:	total: 766ms	remaining: 1.42s
400:	total: 878ms	remaining: 1.31s
450:	total: 989ms	remaining: 1.2s
500:	total: 1.1s	remaining: 1.1s
550:	total: 1.21s	remaining: 983ms
600:	total: 1.31s	remaining: 868ms
650:	total: 1.41s	remaining: 758ms
700:	total: 1.52s	remaining: 647ms
750:	total: 1.63s	remaining: 540ms
800:	total: 1.76s	remaining: 437ms
850:	total: 1.87s	remaining: 328ms
900:	total: 2.01s	remaining: 221ms
950:	total: 2.14s	remaining: 110ms
999:	total: 2.29s	remaining: 0us
0:	total: 2.71ms	remaining: 2.7s
50:	total: 153ms	remaining: 2.85s
100:	total: 277ms	remaining: 2.47s
150:	total: 397ms	remaining: 2.23s
200:	total: 516ms	remaining: 2.05s
250:	total: 637ms	remaining: 1.9s
300:	total: 752ms	remaining: 1.75s
350:	total: 879ms	remaining: 1.63s
400:	total: 987ms	remaining: 1.47s
450:	total: 1.1s	remaining: 1.33s
500:	total: 1.2s	remaining: 1.19s
550:	total: 1.3s	remaining: 1.06s
600:	total: 1.41s	remaining: 933ms
650:	total: 1.51s	remaining: 810ms
700:	total: 1.64s	remaining: 698ms
750:	total: 1.97s	remaining: 654ms
800:	total: 2.21s	remaining: 550ms
850:	total: 2.35s	remaining: 412ms
900:	total: 2.49s	remaining: 274ms
950:	total: 2.61s	remaining: 134ms
999:	total: 2.72s	remaining: 0us
0:	total: 2.78ms	remaining: 2.77s
50:	total: 124ms	remaining: 2.31s
100:	total: 238ms	remaining: 2.12s
150:	total: 354ms	remaining: 1.99s
200:	total: 468ms	remaining: 1.86s
250:	total: 581ms	remaining: 1.73s
300:	total: 692ms	remaining: 1.61s
350:	total: 803ms	remaining: 1.48s
400:	total: 914ms	remaining: 1.36s
450:	total: 1.02s	remaining: 1.24s
500:	total: 1.13s	remaining: 1.13s
550:	total: 1.24s	remaining: 1.01s
600:	total: 1.37s	remaining: 911ms
650:	total: 1.51s	remaining: 811ms
700:	total: 1.68s	remaining: 717ms
750:	total: 1.79s	remaining: 592ms
800:	total: 1.9s	remaining: 472ms
850:	total: 2.01s	remaining: 352ms
900:	total: 2.12s	remaining: 232ms
950:	total: 2.21s	remaining: 114ms

[I 2025-11-24 20:14:16,860] Trial 33 finished with value: 0.7217912615394713 and parameters: {'weight_pos': 2.112187278970362, 'iterations': 1000, 'learning_rate': 0.06254649865880908, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.2073872690867165e-05, 'bagging_temperature': 0.30684194652818675, 'rsm': 0.04742749341829555, 'min_data_in_leaf': 43, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

999:	total: 2.32s	remaining: 0us
0:	learn: 0.7148070	total: 2.68ms	remaining: 2.09s
50:	learn: 0.8680026	total: 84.2ms	remaining: 1.21s
100:	learn: 0.8856038	total: 163ms	remaining: 1.1s
150:	learn: 0.8979816	total: 239ms	remaining: 999ms
200:	learn: 0.9113685	total: 315ms	remaining: 909ms
250:	learn: 0.9202788	total: 394ms	remaining: 832ms
300:	learn: 0.9248148	total: 470ms	remaining: 750ms
350:	learn: 0.9330135	total: 547ms	remaining: 670ms
400:	learn: 0.9340058	total: 620ms	remaining: 588ms
450:	learn: 0.9369065	total: 706ms	remaining: 517ms
500:	learn: 0.9436148	total: 786ms	remaining: 439ms
550:	learn: 0.9474948	total: 868ms	remaining: 362ms
600:	learn: 0.9491728	total: 958ms	remaining: 287ms
650:	learn: 0.9528615	total: 1.06s	remaining: 212ms
700:	learn: 0.9565371	total: 1.14s	remaining: 130ms
750:	learn: 0.9600678	total: 1.24s	remaining: 49.4ms
780:	learn: 0.9633346	total: 1.28s	remaining: 0us
0:	learn: 0.7109398	total: 2.69ms	remaining: 2.09s
50:	learn: 0.8654232	total: 92.3ms	remaining: 1.32s
100:	learn: 0.8892925	total: 177ms	remaining: 1.19s
150:	learn: 0.9026458	total: 293ms	remaining: 1.22s
200:	learn: 0.9091757	total: 391ms	remaining: 1.13s
250:	learn: 0.9177664	total: 506ms	remaining: 1.07s
300:	learn: 0.9237463	total: 639ms	remaining: 1.02s
350:	learn: 0.9323500	total: 729ms	remaining: 894ms
400:	learn: 0.9366388	total: 828ms	remaining: 785ms
450:	learn: 0.9401993	total: 921ms	remaining: 674ms
500:	learn: 0.9431762	total: 1.01s	remaining: 566ms
550:	learn: 0.9469243	total: 1.1s	remaining: 460ms
600:	learn: 0.9505275	total: 1.2s	remaining: 358ms
650:	learn: 0.9527593	total: 1.29s	remaining: 257ms
700:	learn: 0.9576743	total: 1.37s	remaining: 157ms
750:	learn: 0.9604599	total: 1.46s	remaining: 58.4ms
780:	learn: 0.9616269	total: 1.51s	remaining: 0us
0:	learn: 0.7109398	total: 2.95ms	remaining: 2.3s
50:	learn: 0.8635576	total: 89.8ms	remaining: 1.28s
100:	learn: 0.8867411	total: 169ms	remaining: 1.14s
150:	learn: 0.8971380	total: 249ms	remaining: 1.04s
200:	learn: 0.9072710	total: 328ms	remaining: 947ms
250:	learn: 0.9153210	total: 406ms	remaining: 857ms
300:	learn: 0.9211987	total: 484ms	remaining: 771ms
350:	learn: 0.9270039	total: 563ms	remaining: 690ms
400:	learn: 0.9294828	total: 640ms	remaining: 606ms
450:	learn: 0.9355481	total: 720ms	remaining: 527ms
500:	learn: 0.9400543	total: 796ms	remaining: 445ms
550:	learn: 0.9438619	total: 875ms	remaining: 365ms
600:	learn: 0.9471585	total: 950ms	remaining: 285ms
650:	learn: 0.9509493	total: 1.02s	remaining: 205ms
700:	learn: 0.9534747	total: 1.1s	remaining: 126ms
750:	learn: 0.9568140	total: 1.18s	remaining: 47.2ms
780:	learn: 0.9577041	total: 1.23s	remaining: 0us
0:	learn: 0.7114638	total: 2.57ms	remaining: 2s
50:	learn: 0.8679784	total: 84.1ms	remaining: 1.2s
100:	learn: 0.8904984	total: 166ms	remaining: 1.12s
150:	learn: 0.9035992	total: 245ms	remaining: 1.02s
200:	learn: 0.9142432	total: 323ms	remaining: 933ms
250:	learn: 0.9207304	total: 399ms	remaining: 842ms
300:	learn: 0.9266378	total: 475ms	remaining: 757ms
350:	learn: 0.9332903	total: 552ms	remaining: 676ms
400:	learn: 0.9383801	total: 625ms	remaining: 592ms
450:	learn: 0.9404075	total: 699ms	remaining: 511ms
500:	learn: 0.9460082	total: 778ms	remaining: 435ms
550:	learn: 0.9493773	total: 857ms	remaining: 358ms
600:	learn: 0.9514771	total: 932ms	remaining: 279ms
650:	learn: 0.9551527	total: 1.01s	remaining: 201ms
700:	learn: 0.9568735	total: 1.08s	remaining: 124ms
750:	learn: 0.9593524	total: 1.16s	remaining: 46.3ms
780:	learn: 0.9601700	total: 1.21s	remaining: 0us
0:	learn: 0.7154499	total: 3.5ms	remaining: 2.73s
50:	learn: 0.8626712	total: 83.7ms	remaining: 1.2s
100:	learn: 0.8833034	total: 163ms	remaining: 1.1s
150:	learn: 0.8969336	total: 241ms	remaining: 1s
200:	learn: 0.9043276	total: 319ms	remaining: 920ms
250:	learn: 0.9115599	total: 394ms	remaining: 832ms
300:	learn: 0.9210407	total: 469ms	remaining: 748ms
350:	learn: 0.9266415	total: 545ms	remaining: 668ms
400:	learn: 0.9333628	total: 620ms	remaining: 588ms
450:	learn: 0.9369660	total: 698ms	remaining: 510ms
500:	learn: 0.9402755	total: 773ms	remaining: 432ms
550:	learn: 0.9439976	total: 954ms	remaining: 398ms
600:	learn: 0.9466512	total: 1.08s	remaining: 323ms
650:	learn: 0.9510850	total: 1.18s	remaining: 235ms
700:	learn: 0.9529674	total: 1.3s	remaining: 148ms

[I 2025-11-24 20:14:24,019] Trial 34 finished with value: 0.728023043876207 and parameters: {'weight_pos': 2.7090348095453893, 'iterations': 781, 'learning_rate': 0.12294817872239766, 'depth': 3, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.0002971243114463922, 'bagging_temperature': 0.7468148929492151, 'rsm': 0.10796375775596373, 'min_data_in_leaf': 21, 'leaf_estimation_iterations': 1}. Best is trial 16 with value: 0.7404863910277388.

750:	learn: 0.9567155	total: 1.38s	remaining: 55.1ms
780:	learn: 0.9579847	total: 1.43s	remaining: 0us
0:	total: 11.2ms	remaining: 9.32s
50:	total: 571ms	remaining: 8.76s
100:	total: 1.32s	remaining: 9.55s
150:	total: 1.98s	remaining: 8.95s
200:	total: 2.58s	remaining: 8.11s
250:	total: 3.14s	remaining: 7.27s
300:	total: 3.71s	remaining: 6.56s
350:	total: 4.31s	remaining: 5.92s
400:	total: 4.95s	remaining: 5.33s
450:	total: 5.54s	remaining: 4.69s
500:	total: 6.13s	remaining: 4.06s
550:	total: 6.73s	remaining: 3.44s
600:	total: 7.37s	remaining: 2.85s
650:	total: 7.92s	remaining: 2.21s
700:	total: 8.49s	remaining: 1.6s
750:	total: 9.05s	remaining: 989ms
800:	total: 9.78s	remaining: 391ms
832:	total: 10.1s	remaining: 0us
0:	total: 11.1ms	remaining: 9.27s
50:	total: 811ms	remaining: 12.4s
100:	total: 1.55s	remaining: 11.3s
150:	total: 2.17s	remaining: 9.8s
200:	total: 2.75s	remaining: 8.64s
250:	total: 3.27s	remaining: 7.59s
300:	total: 3.8s	remaining: 6.71s
350:	total: 4.39s	remaining: 6.03s
400:	total: 5.23s	remaining: 5.63s
450:	total: 5.93s	remaining: 5.02s
500:	total: 6.52s	remaining: 4.32s
550:	total: 7.09s	remaining: 3.63s
600:	total: 7.71s	remaining: 2.98s
650:	total: 8.25s	remaining: 2.31s
700:	total: 8.85s	remaining: 1.67s
750:	total: 9.67s	remaining: 1.05s
800:	total: 10.2s	remaining: 408ms
832:	total: 10.6s	remaining: 0us
0:	total: 10.3ms	remaining: 8.56s
50:	total: 545ms	remaining: 8.35s
100:	total: 1.04s	remaining: 7.58s
150:	total: 1.58s	remaining: 7.14s
200:	total: 2.1s	remaining: 6.61s
250:	total: 2.6s	remaining: 6.03s
300:	total: 3.11s	remaining: 5.5s
350:	total: 3.63s	remaining: 4.98s
400:	total: 4.17s	remaining: 4.49s
450:	total: 4.71s	remaining: 3.99s
500:	total: 5.27s	remaining: 3.49s
550:	total: 5.89s	remaining: 3.01s
600:	total: 6.44s	remaining: 2.48s
650:	total: 6.99s	remaining: 1.96s
700:	total: 7.54s	remaining: 1.42s
750:	total: 8.08s	remaining: 882ms
800:	total: 8.85s	remaining: 353ms
832:	total: 9.18s	remaining: 0us
0:	total: 10.8ms	remaining: 9.01s
50:	total: 527ms	remaining: 8.07s
100:	total: 1s	remaining: 7.28s
150:	total: 1.56s	remaining: 7.07s
200:	total: 2.1s	remaining: 6.61s
250:	total: 2.61s	remaining: 6.04s
300:	total: 3.12s	remaining: 5.52s
350:	total: 3.65s	remaining: 5.01s
400:	total: 4.21s	remaining: 4.53s
450:	total: 4.81s	remaining: 4.07s
500:	total: 5.39s	remaining: 3.58s
550:	total: 5.97s	remaining: 3.05s
600:	total: 6.5s	remaining: 2.51s
650:	total: 7.07s	remaining: 1.98s
700:	total: 7.62s	remaining: 1.43s
750:	total: 8.15s	remaining: 890ms
800:	total: 8.71s	remaining: 348ms
832:	total: 9.31s	remaining: 0us
0:	total: 11.4ms	remaining: 9.48s
50:	total: 544ms	remaining: 8.34s
100:	total: 1.13s	remaining: 8.16s
150:	total: 1.63s	remaining: 7.36s
200:	total: 2.39s	remaining: 7.53s
250:	total: 3.01s	remaining: 6.98s
300:	total: 3.58s	remaining: 6.32s
350:	total: 4.13s	remaining: 5.67s
400:	total: 4.68s	remaining: 5.04s
450:	total: 5.26s	remaining: 4.46s
500:	total: 5.88s	remaining: 3.9s
550:	total: 6.45s	remaining: 3.3s
600:	total: 7s	remaining: 2.7s
650:	total: 7.56s	remaining: 2.11s
700:	total: 8.1s	remaining: 1.52s
750:	total: 8.64s	remaining: 944ms
800:	total: 9.22s	remaining: 368ms

[I 2025-11-24 20:15:13,828] Trial 35 finished with value: 0.713758796772013 and parameters: {'weight_pos': 5.570773057578676, 'iterations': 833, 'learning_rate': 0.05748953568997996, 'depth': 6, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0035595628982831454, 'bagging_temperature': 0.14419010224390466, 'rsm': 0.5929778085995433, 'min_data_in_leaf': 53, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

832:	total: 9.87s	remaining: 0us
0:	learn: 0.7912901	total: 10.8ms	remaining: 10.2s
50:	learn: 0.8914343	total: 568ms	remaining: 9.97s
100:	learn: 0.9249078	total: 1.26s	remaining: 10.6s
150:	learn: 0.9565025	total: 1.96s	remaining: 10.3s
200:	learn: 0.9734117	total: 2.63s	remaining: 9.78s
250:	learn: 0.9833700	total: 3.27s	remaining: 9.08s
300:	learn: 0.9882029	total: 4.02s	remaining: 8.64s
350:	learn: 0.9924717	total: 4.67s	remaining: 7.94s
400:	learn: 0.9962823	total: 5.29s	remaining: 7.21s
450:	learn: 0.9976765	total: 6.07s	remaining: 6.68s
500:	learn: 0.9987918	total: 6.88s	remaining: 6.12s
550:	learn: 0.9995353	total: 7.91s	remaining: 5.68s
600:	learn: 0.9999071	total: 8.85s	remaining: 5.09s
650:	learn: 1.0000000	total: 9.65s	remaining: 4.39s
700:	learn: 1.0000000	total: 10.4s	remaining: 3.65s
750:	learn: 1.0000000	total: 11.1s	remaining: 2.9s
800:	learn: 1.0000000	total: 11.7s	remaining: 2.14s
850:	learn: 1.0000000	total: 12.3s	remaining: 1.39s
900:	learn: 1.0000000	total: 13s	remaining: 663ms
946:	learn: 1.0000000	total: 13.6s	remaining: 0us
0:	learn: 0.7940686	total: 10.9ms	remaining: 10.3s
50:	learn: 0.8960886	total: 733ms	remaining: 12.9s
100:	learn: 0.9244632	total: 1.29s	remaining: 10.8s
150:	learn: 0.9523067	total: 1.84s	remaining: 9.71s
200:	learn: 0.9709154	total: 2.47s	remaining: 9.17s
250:	learn: 0.9810264	total: 3.06s	remaining: 8.49s
300:	learn: 0.9882959	total: 3.69s	remaining: 7.92s
350:	learn: 0.9934343	total: 4.34s	remaining: 7.36s
400:	learn: 0.9963753	total: 4.99s	remaining: 6.79s
450:	learn: 0.9979553	total: 6.15s	remaining: 6.76s
500:	learn: 0.9985129	total: 7.06s	remaining: 6.29s
550:	learn: 0.9994423	total: 7.76s	remaining: 5.58s
600:	learn: 0.9995353	total: 8.59s	remaining: 4.94s
650:	learn: 0.9999071	total: 10.3s	remaining: 4.69s
700:	learn: 0.9999071	total: 11.2s	remaining: 3.93s
750:	learn: 1.0000000	total: 11.9s	remaining: 3.12s
800:	learn: 1.0000000	total: 12.9s	remaining: 2.36s
850:	learn: 1.0000000	total: 13.6s	remaining: 1.54s
900:	learn: 1.0000000	total: 14.3s	remaining: 732ms
946:	learn: 1.0000000	total: 14.9s	remaining: 0us
0:	learn: 0.7909850	total: 12.3ms	remaining: 11.6s
50:	learn: 0.8942163	total: 813ms	remaining: 14.3s
100:	learn: 0.9207255	total: 1.63s	remaining: 13.6s
150:	learn: 0.9532229	total: 2.39s	remaining: 12.6s
200:	learn: 0.9729204	total: 3.12s	remaining: 11.6s
250:	learn: 0.9820422	total: 3.76s	remaining: 10.4s
300:	learn: 0.9881698	total: 4.45s	remaining: 9.56s
350:	learn: 0.9936799	total: 5.11s	remaining: 8.68s
400:	learn: 0.9961894	total: 5.75s	remaining: 7.82s
450:	learn: 0.9973047	total: 6.35s	remaining: 6.98s
500:	learn: 0.9987918	total: 6.98s	remaining: 6.21s
550:	learn: 0.9996282	total: 7.63s	remaining: 5.48s
600:	learn: 1.0000000	total: 8.31s	remaining: 4.79s
650:	learn: 1.0000000	total: 9.18s	remaining: 4.17s
700:	learn: 1.0000000	total: 9.87s	remaining: 3.46s
750:	learn: 1.0000000	total: 10.9s	remaining: 2.84s
800:	learn: 1.0000000	total: 11.8s	remaining: 2.15s
850:	learn: 1.0000000	total: 12.5s	remaining: 1.41s
900:	learn: 1.0000000	total: 13.1s	remaining: 669ms
946:	learn: 1.0000000	total: 13.7s	remaining: 0us
0:	learn: 0.8010290	total: 6.08ms	remaining: 5.75s
50:	learn: 0.8923906	total: 597ms	remaining: 10.5s
100:	learn: 0.9251801	total: 1.22s	remaining: 10.2s
150:	learn: 0.9579498	total: 1.79s	remaining: 9.46s
200:	learn: 0.9732590	total: 2.45s	remaining: 9.09s
250:	learn: 0.9819890	total: 3.17s	remaining: 8.8s
300:	learn: 0.9866295	total: 3.91s	remaining: 8.39s
350:	learn: 0.9929696	total: 4.57s	remaining: 7.76s
400:	learn: 0.9958176	total: 5.19s	remaining: 7.07s
450:	learn: 0.9974906	total: 6.11s	remaining: 6.72s
500:	learn: 0.9986988	total: 7.24s	remaining: 6.45s
550:	learn: 0.9992565	total: 7.97s	remaining: 5.72s
600:	learn: 0.9995353	total: 8.68s	remaining: 5s
650:	learn: 0.9998141	total: 9.4s	remaining: 4.28s
700:	learn: 1.0000000	total: 10.1s	remaining: 3.53s
750:	learn: 1.0000000	total: 10.8s	remaining: 2.81s
800:	learn: 1.0000000	total: 11.5s	remaining: 2.1s
850:	learn: 1.0000000	total: 12.2s	remaining: 1.38s
900:	learn: 1.0000000	total: 12.9s	remaining: 660ms
946:	learn: 1.0000000	total: 13.6s	remaining: 0us
0:	learn: 0.7961628	total: 14.3ms	remaining: 13.6s
50:	learn: 0.8930813	total: 702ms	remaining: 12.3s
100:	learn: 0.9197297	total: 1.4s	remaining: 11.7s
150:	learn: 0.9514902	total: 2.08s	remaining: 11s
200:	learn: 0.9691761	total: 2.79s	remaining: 10.3s
250:	learn: 0.9791078	total: 3.83s	remaining: 10.6s
300:	learn: 0.9872735	total: 4.55s	remaining: 9.78s
350:	learn: 0.9923190	total: 5.26s	remaining: 8.93s
400:	learn: 0.9951670	total: 6s	remaining: 8.16s
450:	learn: 0.9974906	total: 6.73s	remaining: 7.41s
500:	learn: 0.9978623	total: 7.46s	remaining: 6.64s
550:	learn: 0.9987918	total: 8.18s	remaining: 5.88s
600:	learn: 0.9992565	total: 8.9s	remaining: 5.12s
650:	learn: 0.9996282	total: 9.6s	remaining: 4.37s
700:	learn: 0.9999071	total: 10.4s	remaining: 3.65s
750:	learn: 1.0000000	total: 11.1s	remaining: 2.89s
800:	learn: 1.0000000	total: 11.8s	remaining: 2.16s
850:	learn: 1.0000000	total: 12.6s	remaining: 1.43s
900:	learn: 1.0000000	total: 13.7s	remaining: 701ms

[I 2025-11-24 20:16:25,068] Trial 36 finished with value: 0.7258406177678871 and parameters: {'weight_pos': 3.643103522851845, 'iterations': 947, 'learning_rate': 0.08508234570902254, 'depth': 7, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.2941100623006584, 'bagging_temperature': 0.8720590186859853, 'rsm': 0.4834394993398678, 'min_data_in_leaf': 34, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

946:	learn: 1.0000000	total: 14.5s	remaining: 0us
0:	total: 7.79ms	remaining: 6.81s
50:	total: 336ms	remaining: 5.44s
100:	total: 697ms	remaining: 5.34s
150:	total: 1.16s	remaining: 5.56s
200:	total: 1.57s	remaining: 5.29s
250:	total: 1.93s	remaining: 4.81s
300:	total: 2.3s	remaining: 4.4s
350:	total: 2.7s	remaining: 4.04s
400:	total: 3.09s	remaining: 3.67s
450:	total: 3.52s	remaining: 3.32s
500:	total: 3.9s	remaining: 2.92s
550:	total: 4.29s	remaining: 2.53s
600:	total: 4.67s	remaining: 2.13s
650:	total: 5.01s	remaining: 1.73s
700:	total: 5.42s	remaining: 1.35s
750:	total: 5.79s	remaining: 964ms
800:	total: 6.18s	remaining: 579ms
850:	total: 6.58s	remaining: 193ms
875:	total: 6.77s	remaining: 0us
0:	total: 8.86ms	remaining: 7.75s
50:	total: 358ms	remaining: 5.8s
100:	total: 758ms	remaining: 5.82s
150:	total: 1.1s	remaining: 5.28s
200:	total: 1.69s	remaining: 5.66s
250:	total: 2.04s	remaining: 5.08s
300:	total: 2.39s	remaining: 4.56s
350:	total: 2.75s	remaining: 4.12s
400:	total: 3.23s	remaining: 3.83s
450:	total: 3.6s	remaining: 3.39s
500:	total: 3.96s	remaining: 2.96s
550:	total: 4.3s	remaining: 2.54s
600:	total: 4.74s	remaining: 2.17s
650:	total: 5.15s	remaining: 1.78s
700:	total: 5.5s	remaining: 1.37s
750:	total: 5.85s	remaining: 973ms
800:	total: 6.19s	remaining: 580ms
850:	total: 6.54s	remaining: 192ms
875:	total: 6.72s	remaining: 0us
0:	total: 7.28ms	remaining: 6.37s
50:	total: 348ms	remaining: 5.62s
100:	total: 682ms	remaining: 5.23s
150:	total: 1s	remaining: 4.81s
200:	total: 1.33s	remaining: 4.48s
250:	total: 1.73s	remaining: 4.3s
300:	total: 2.08s	remaining: 3.98s
350:	total: 2.42s	remaining: 3.62s
400:	total: 2.77s	remaining: 3.28s
450:	total: 3.13s	remaining: 2.95s
500:	total: 3.5s	remaining: 2.62s
550:	total: 3.85s	remaining: 2.27s
600:	total: 4.21s	remaining: 1.93s
650:	total: 4.88s	remaining: 1.69s
700:	total: 5.25s	remaining: 1.31s
750:	total: 5.62s	remaining: 936ms
800:	total: 5.98s	remaining: 560ms
850:	total: 6.35s	remaining: 187ms
875:	total: 6.54s	remaining: 0us
0:	total: 9.36ms	remaining: 8.19s
50:	total: 422ms	remaining: 6.83s
100:	total: 908ms	remaining: 6.96s
150:	total: 1.38s	remaining: 6.63s
200:	total: 1.74s	remaining: 5.86s
250:	total: 2.12s	remaining: 5.28s
300:	total: 2.49s	remaining: 4.75s
350:	total: 2.83s	remaining: 4.23s
400:	total: 3.19s	remaining: 3.78s
450:	total: 3.54s	remaining: 3.34s
500:	total: 3.9s	remaining: 2.92s
550:	total: 4.25s	remaining: 2.51s
600:	total: 4.58s	remaining: 2.1s
650:	total: 4.95s	remaining: 1.71s
700:	total: 5.35s	remaining: 1.34s
750:	total: 5.72s	remaining: 952ms
800:	total: 6.18s	remaining: 579ms
850:	total: 6.54s	remaining: 192ms
875:	total: 6.72s	remaining: 0us
0:	total: 8.92ms	remaining: 7.8s
50:	total: 377ms	remaining: 6.1s
100:	total: 738ms	remaining: 5.67s
150:	total: 1.35s	remaining: 6.47s
200:	total: 1.7s	remaining: 5.7s
250:	total: 2.07s	remaining: 5.17s
300:	total: 2.45s	remaining: 4.69s
350:	total: 2.81s	remaining: 4.2s
400:	total: 3.17s	remaining: 3.75s
450:	total: 3.53s	remaining: 3.33s
500:	total: 3.92s	remaining: 2.93s
550:	total: 4.3s	remaining: 2.54s
600:	total: 4.68s	remaining: 2.14s
650:	total: 5.01s	remaining: 1.73s
700:	total: 5.37s	remaining: 1.34s
750:	total: 5.73s	remaining: 954ms
800:	total: 6.09s	remaining: 570ms
850:	total: 6.46s	remaining: 190ms
875:	total: 6.63s	remaining: 0us

[I 2025-11-24 20:16:59,296] Trial 37 finished with value: 0.7001524385633826 and parameters: {'weight_pos': 1.864330514437286, 'iterations': 876, 'learning_rate': 0.11211925175404237, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0007766150713653337, 'bagging_temperature': 0.8116202196969632, 'rsm': 0.38749781588740245, 'min_data_in_leaf': 9, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 7.7ms	remaining: 5.56s
50:	total: 341ms	remaining: 4.49s
100:	total: 686ms	remaining: 4.22s
150:	total: 1.11s	remaining: 4.2s
200:	total: 1.57s	remaining: 4.09s
250:	total: 1.93s	remaining: 3.63s
300:	total: 2.29s	remaining: 3.21s
350:	total: 2.64s	remaining: 2.8s
400:	total: 3.01s	remaining: 2.41s
450:	total: 3.47s	remaining: 2.09s
500:	total: 3.85s	remaining: 1.71s
550:	total: 4.55s	remaining: 1.42s
600:	total: 4.97s	remaining: 1.01s
650:	total: 5.41s	remaining: 598ms
700:	total: 5.83s	remaining: 183ms
722:	total: 6.04s	remaining: 0us
0:	total: 7.9ms	remaining: 5.7s
50:	total: 368ms	remaining: 4.85s
100:	total: 726ms	remaining: 4.47s
150:	total: 1.09s	remaining: 4.12s
200:	total: 1.49s	remaining: 3.86s
250:	total: 1.9s	remaining: 3.58s
300:	total: 2.27s	remaining: 3.18s
350:	total: 2.64s	remaining: 2.79s
400:	total: 2.99s	remaining: 2.4s
450:	total: 3.35s	remaining: 2.02s
500:	total: 3.69s	remaining: 1.64s
550:	total: 4.1s	remaining: 1.28s
600:	total: 4.53s	remaining: 920ms
650:	total: 4.96s	remaining: 549ms
700:	total: 5.34s	remaining: 167ms
722:	total: 5.53s	remaining: 0us
0:	total: 8.66ms	remaining: 6.25s
50:	total: 390ms	remaining: 5.13s
100:	total: 758ms	remaining: 4.67s
150:	total: 1.1s	remaining: 4.16s
200:	total: 1.47s	remaining: 3.81s
250:	total: 1.81s	remaining: 3.41s
300:	total: 2.23s	remaining: 3.13s
350:	total: 2.77s	remaining: 2.93s
400:	total: 3.13s	remaining: 2.51s
450:	total: 3.48s	remaining: 2.1s
500:	total: 3.85s	remaining: 1.71s
550:	total: 4.21s	remaining: 1.31s
600:	total: 4.59s	remaining: 932ms
650:	total: 4.95s	remaining: 547ms
700:	total: 5.34s	remaining: 167ms
722:	total: 5.52s	remaining: 0us
0:	total: 7.51ms	remaining: 5.42s
50:	total: 357ms	remaining: 4.71s
100:	total: 734ms	remaining: 4.52s
150:	total: 1.09s	remaining: 4.14s
200:	total: 1.45s	remaining: 3.76s
250:	total: 1.91s	remaining: 3.59s
300:	total: 2.28s	remaining: 3.19s
350:	total: 2.63s	remaining: 2.79s
400:	total: 2.98s	remaining: 2.4s
450:	total: 3.33s	remaining: 2.01s
500:	total: 3.69s	remaining: 1.64s
550:	total: 4.04s	remaining: 1.26s
600:	total: 4.45s	remaining: 903ms
650:	total: 4.81s	remaining: 532ms
700:	total: 5.16s	remaining: 162ms
722:	total: 5.33s	remaining: 0us
0:	total: 8.24ms	remaining: 5.95s
50:	total: 349ms	remaining: 4.6s
100:	total: 685ms	remaining: 4.22s
150:	total: 1.12s	remaining: 4.24s
200:	total: 1.74s	remaining: 4.52s
250:	total: 2.15s	remaining: 4.04s
300:	total: 2.8s	remaining: 3.93s
350:	total: 3.33s	remaining: 3.53s
400:	total: 3.8s	remaining: 3.05s
450:	total: 4.28s	remaining: 2.58s
500:	total: 4.67s	remaining: 2.07s
550:	total: 5.06s	remaining: 1.58s
600:	total: 5.51s	remaining: 1.12s
650:	total: 5.95s	remaining: 658ms
700:	total: 6.36s	remaining: 200ms
722:	total: 6.53s	remaining: 0us

[I 2025-11-24 20:17:28,988] Trial 38 finished with value: 0.7121769572066758 and parameters: {'weight_pos': 8.932271481631192, 'iterations': 723, 'learning_rate': 0.20714370611004412, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.043251129800299826, 'bagging_temperature': 0.42577451888457013, 'rsm': 0.7055370895577395, 'min_data_in_leaf': 31, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

0:	learn: 0.7995119	total: 20.5ms	remaining: 16.4s
50:	learn: 0.9205817	total: 968ms	remaining: 14.3s
100:	learn: 0.9633299	total: 1.96s	remaining: 13.6s
150:	learn: 0.9937858	total: 3.08s	remaining: 13.3s
200:	learn: 0.9992595	total: 4.2s	remaining: 12.6s
250:	learn: 0.9998942	total: 5.45s	remaining: 12s
300:	learn: 1.0000000	total: 6.78s	remaining: 11.3s
350:	learn: 1.0000000	total: 7.82s	remaining: 10s
400:	learn: 1.0000000	total: 8.79s	remaining: 8.79s
450:	learn: 1.0000000	total: 10.1s	remaining: 7.85s
500:	learn: 1.0000000	total: 11s	remaining: 6.63s
550:	learn: 1.0000000	total: 12.1s	remaining: 5.51s
600:	learn: 1.0000000	total: 13.2s	remaining: 4.42s
650:	learn: 1.0000000	total: 14.4s	remaining: 3.35s
700:	learn: 1.0000000	total: 15.6s	remaining: 2.25s
750:	learn: 1.0000000	total: 16.7s	remaining: 1.13s
800:	learn: 1.0000000	total: 17.7s	remaining: 22.2ms
801:	learn: 1.0000000	total: 17.8s	remaining: 0us
0:	learn: 0.7978643	total: 13.4ms	remaining: 10.7s
50:	learn: 0.9275506	total: 1.07s	remaining: 15.7s
100:	learn: 0.9641261	total: 2.05s	remaining: 14.3s
150:	learn: 0.9931511	total: 2.89s	remaining: 12.4s
200:	learn: 0.9987949	total: 3.81s	remaining: 11.4s
250:	learn: 1.0000000	total: 4.85s	remaining: 10.6s
300:	learn: 1.0000000	total: 5.89s	remaining: 9.81s
350:	learn: 1.0000000	total: 7.05s	remaining: 9.05s
400:	learn: 1.0000000	total: 8.2s	remaining: 8.2s
450:	learn: 1.0000000	total: 9.32s	remaining: 7.25s
500:	learn: 1.0000000	total: 10.3s	remaining: 6.18s
550:	learn: 1.0000000	total: 11.3s	remaining: 5.15s
600:	learn: 1.0000000	total: 12.2s	remaining: 4.09s
650:	learn: 1.0000000	total: 13.2s	remaining: 3.05s
700:	learn: 1.0000000	total: 14.2s	remaining: 2.04s
750:	learn: 1.0000000	total: 15.3s	remaining: 1.04s
800:	learn: 1.0000000	total: 16.7s	remaining: 20.8ms
801:	learn: 1.0000000	total: 16.7s	remaining: 0us
0:	learn: 0.7971785	total: 15.2ms	remaining: 12.2s
50:	learn: 0.9194638	total: 1.17s	remaining: 17.2s
100:	learn: 0.9650225	total: 2.6s	remaining: 18s
150:	learn: 0.9914214	total: 3.87s	remaining: 16.7s
200:	learn: 0.9986477	total: 4.9s	remaining: 14.6s
250:	learn: 1.0000000	total: 5.79s	remaining: 12.7s
300:	learn: 1.0000000	total: 6.72s	remaining: 11.2s
350:	learn: 1.0000000	total: 7.62s	remaining: 9.79s
400:	learn: 1.0000000	total: 8.56s	remaining: 8.56s
450:	learn: 1.0000000	total: 9.82s	remaining: 7.64s
500:	learn: 1.0000000	total: 11.1s	remaining: 6.65s
550:	learn: 1.0000000	total: 12.1s	remaining: 5.53s
600:	learn: 1.0000000	total: 13.2s	remaining: 4.4s
650:	learn: 1.0000000	total: 14.1s	remaining: 3.28s
700:	learn: 1.0000000	total: 15.3s	remaining: 2.2s
750:	learn: 1.0000000	total: 16.3s	remaining: 1.11s
800:	learn: 1.0000000	total: 17.3s	remaining: 21.6ms
801:	learn: 1.0000000	total: 17.3s	remaining: 0us
0:	learn: 0.8218512	total: 13ms	remaining: 10.4s
50:	learn: 0.9199055	total: 1.03s	remaining: 15.2s
100:	learn: 0.9591944	total: 2.27s	remaining: 15.8s
150:	learn: 0.9918217	total: 3.23s	remaining: 13.9s
200:	learn: 0.9993238	total: 4.44s	remaining: 13.3s
250:	learn: 0.9998942	total: 5.53s	remaining: 12.1s
300:	learn: 1.0000000	total: 6.71s	remaining: 11.2s
350:	learn: 1.0000000	total: 7.93s	remaining: 10.2s
400:	learn: 1.0000000	total: 8.98s	remaining: 8.98s
450:	learn: 1.0000000	total: 10.1s	remaining: 7.85s
500:	learn: 1.0000000	total: 11.3s	remaining: 6.79s
550:	learn: 1.0000000	total: 12.7s	remaining: 5.79s
600:	learn: 1.0000000	total: 14s	remaining: 4.67s
650:	learn: 1.0000000	total: 15.1s	remaining: 3.5s
700:	learn: 1.0000000	total: 16.2s	remaining: 2.33s
750:	learn: 1.0000000	total: 17.3s	remaining: 1.17s
800:	learn: 1.0000000	total: 18.3s	remaining: 22.9ms
801:	learn: 1.0000000	total: 18.3s	remaining: 0us
0:	learn: 0.8040607	total: 15.4ms	remaining: 12.3s
50:	learn: 0.9188563	total: 986ms	remaining: 14.5s
100:	learn: 0.9612414	total: 2.05s	remaining: 14.2s
150:	learn: 0.9920747	total: 3.06s	remaining: 13.2s
200:	learn: 0.9984361	total: 4.31s	remaining: 12.9s
250:	learn: 0.9997884	total: 5.28s	remaining: 11.6s
300:	learn: 1.0000000	total: 6.24s	remaining: 10.4s
350:	learn: 1.0000000	total: 7.42s	remaining: 9.54s
400:	learn: 1.0000000	total: 8.53s	remaining: 8.53s
450:	learn: 1.0000000	total: 9.57s	remaining: 7.45s
500:	learn: 1.0000000	total: 10.6s	remaining: 6.36s
550:	learn: 1.0000000	total: 11.6s	remaining: 5.3s
600:	learn: 1.0000000	total: 12.8s	remaining: 4.3s
650:	learn: 1.0000000	total: 14.5s	remaining: 3.37s
700:	learn: 1.0000000	total: 15.6s	remaining: 2.25s
750:	learn: 1.0000000	total: 16.8s	remaining: 1.14s

[I 2025-11-24 20:18:58,456] Trial 39 finished with value: 0.680538089319204 and parameters: {'weight_pos': 2.391839826634759, 'iterations': 802, 'learning_rate': 0.07953991418832555, 'depth': 9, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.013757876449999757, 'bagging_temperature': 0.5504247351407371, 'rsm': 0.25029657414890893, 'min_data_in_leaf': 21, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

800:	learn: 1.0000000	total: 18.1s	remaining: 22.6ms
801:	learn: 1.0000000	total: 18.1s	remaining: 0us
0:	total: 5.6ms	remaining: 2.39s
50:	total: 242ms	remaining: 1.78s
100:	total: 464ms	remaining: 1.5s
150:	total: 679ms	remaining: 1.24s
200:	total: 897ms	remaining: 1.01s
250:	total: 1.11s	remaining: 782ms
300:	total: 1.33s	remaining: 555ms
350:	total: 1.55s	remaining: 336ms
400:	total: 1.78s	remaining: 116ms
426:	total: 1.9s	remaining: 0us
0:	total: 5.11ms	remaining: 2.17s
50:	total: 217ms	remaining: 1.6s
100:	total: 430ms	remaining: 1.39s
150:	total: 643ms	remaining: 1.17s
200:	total: 860ms	remaining: 967ms
250:	total: 1.07s	remaining: 752ms
300:	total: 1.29s	remaining: 539ms
350:	total: 1.51s	remaining: 326ms
400:	total: 1.72s	remaining: 111ms
426:	total: 1.84s	remaining: 0us
0:	total: 5.3ms	remaining: 2.26s
50:	total: 272ms	remaining: 2s
100:	total: 617ms	remaining: 1.99s
150:	total: 881ms	remaining: 1.61s
200:	total: 1.29s	remaining: 1.46s
250:	total: 1.56s	remaining: 1.1s
300:	total: 1.77s	remaining: 743ms
350:	total: 1.99s	remaining: 431ms
400:	total: 2.24s	remaining: 145ms
426:	total: 2.4s	remaining: 0us
0:	total: 5.91ms	remaining: 2.52s
50:	total: 246ms	remaining: 1.81s
100:	total: 475ms	remaining: 1.53s
150:	total: 696ms	remaining: 1.27s
200:	total: 930ms	remaining: 1.04s
250:	total: 1.19s	remaining: 833ms
300:	total: 1.41s	remaining: 592ms
350:	total: 1.65s	remaining: 357ms
400:	total: 1.86s	remaining: 121ms
426:	total: 1.97s	remaining: 0us
0:	total: 5.26ms	remaining: 2.24s
50:	total: 253ms	remaining: 1.86s
100:	total: 524ms	remaining: 1.69s
150:	total: 755ms	remaining: 1.38s
200:	total: 971ms	remaining: 1.09s
250:	total: 1.19s	remaining: 833ms
300:	total: 1.41s	remaining: 589ms
350:	total: 1.62s	remaining: 350ms

[I 2025-11-24 20:19:09,069] Trial 40 finished with value: 0.6682155800441357 and parameters: {'weight_pos': 1.3078727460589015, 'iterations': 427, 'learning_rate': 0.03098757325413451, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.001939619127008184, 'bagging_temperature': 0.6914652261152349, 'rsm': 0.32659900922712387, 'min_data_in_leaf': 65, 'leaf_estimation_iterations': 7}. Best is trial 16 with value: 0.7404863910277388.

400:	total: 1.83s	remaining: 119ms
426:	total: 1.94s	remaining: 0us
0:	total: 4.35ms	remaining: 3.27s
50:	total: 194ms	remaining: 2.67s
100:	total: 403ms	remaining: 2.6s
150:	total: 600ms	remaining: 2.39s
200:	total: 798ms	remaining: 2.2s
250:	total: 993ms	remaining: 1.99s
300:	total: 1.19s	remaining: 1.8s
350:	total: 1.4s	remaining: 1.6s
400:	total: 1.6s	remaining: 1.41s
450:	total: 1.8s	remaining: 1.21s
500:	total: 2s	remaining: 1.01s
550:	total: 2.2s	remaining: 809ms
600:	total: 2.4s	remaining: 611ms
650:	total: 2.59s	remaining: 410ms
700:	total: 2.79s	remaining: 211ms
750:	total: 3s	remaining: 12ms
753:	total: 3.01s	remaining: 0us
0:	total: 5.64ms	remaining: 4.25s
50:	total: 201ms	remaining: 2.77s
100:	total: 440ms	remaining: 2.84s
150:	total: 652ms	remaining: 2.6s
200:	total: 863ms	remaining: 2.38s
250:	total: 1.06s	remaining: 2.12s
300:	total: 1.46s	remaining: 2.19s
350:	total: 1.7s	remaining: 1.95s
400:	total: 1.9s	remaining: 1.67s
450:	total: 2.1s	remaining: 1.41s
500:	total: 2.3s	remaining: 1.16s
550:	total: 2.5s	remaining: 922ms
600:	total: 2.7s	remaining: 688ms
650:	total: 2.99s	remaining: 474ms
700:	total: 3.21s	remaining: 243ms
750:	total: 3.43s	remaining: 13.7ms
753:	total: 3.44s	remaining: 0us
0:	total: 3.87ms	remaining: 2.91s
50:	total: 197ms	remaining: 2.71s
100:	total: 402ms	remaining: 2.6s
150:	total: 609ms	remaining: 2.43s
200:	total: 809ms	remaining: 2.23s
250:	total: 1.01s	remaining: 2.03s
300:	total: 1.21s	remaining: 1.82s
350:	total: 1.42s	remaining: 1.62s
400:	total: 1.63s	remaining: 1.43s
450:	total: 1.84s	remaining: 1.23s
500:	total: 2.05s	remaining: 1.03s
550:	total: 2.25s	remaining: 831ms
600:	total: 2.46s	remaining: 627ms
650:	total: 2.66s	remaining: 421ms
700:	total: 2.89s	remaining: 219ms
750:	total: 3.1s	remaining: 12.4ms
753:	total: 3.12s	remaining: 0us
0:	total: 3.98ms	remaining: 3s
50:	total: 190ms	remaining: 2.62s
100:	total: 379ms	remaining: 2.45s
150:	total: 567ms	remaining: 2.26s
200:	total: 753ms	remaining: 2.07s
250:	total: 941ms	remaining: 1.88s
300:	total: 1.15s	remaining: 1.73s
350:	total: 1.33s	remaining: 1.53s
400:	total: 1.53s	remaining: 1.35s
450:	total: 1.72s	remaining: 1.16s
500:	total: 1.92s	remaining: 968ms
550:	total: 2.12s	remaining: 779ms
600:	total: 2.32s	remaining: 591ms
650:	total: 2.51s	remaining: 397ms
700:	total: 2.7s	remaining: 204ms
750:	total: 2.89s	remaining: 11.6ms
753:	total: 2.9s	remaining: 0us
0:	total: 3.87ms	remaining: 2.91s
50:	total: 185ms	remaining: 2.55s
100:	total: 363ms	remaining: 2.35s
150:	total: 538ms	remaining: 2.15s
200:	total: 779ms	remaining: 2.14s
250:	total: 967ms	remaining: 1.94s
300:	total: 1.16s	remaining: 1.75s
350:	total: 1.5s	remaining: 1.73s
400:	total: 1.78s	remaining: 1.56s
450:	total: 1.98s	remaining: 1.33s
500:	total: 2.18s	remaining: 1.1s
550:	total: 2.39s	remaining: 881ms
600:	total: 2.59s	remaining: 659ms
650:	total: 2.79s	remaining: 441ms
700:	total: 2.99s	remaining: 226ms

[I 2025-11-24 20:19:25,452] Trial 41 finished with value: 0.6223533085278202 and parameters: {'weight_pos': 19.805617495523837, 'iterations': 754, 'learning_rate': 0.050182989724789726, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.00022645693960582702, 'bagging_temperature': 0.5760504931421147, 'rsm': 0.20625405838167288, 'min_data_in_leaf': 44, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

750:	total: 3.22s	remaining: 12.9ms
753:	total: 3.23s	remaining: 0us
0:	total: 5.56ms	remaining: 3.11s
50:	total: 213ms	remaining: 2.13s
100:	total: 437ms	remaining: 1.99s
150:	total: 636ms	remaining: 1.73s
200:	total: 836ms	remaining: 1.5s
250:	total: 1.04s	remaining: 1.29s
300:	total: 1.24s	remaining: 1.07s
350:	total: 1.45s	remaining: 865ms
400:	total: 1.66s	remaining: 663ms
450:	total: 1.87s	remaining: 455ms
500:	total: 2.08s	remaining: 249ms
550:	total: 2.29s	remaining: 41.6ms
560:	total: 2.33s	remaining: 0us
0:	total: 3.88ms	remaining: 2.17s
50:	total: 198ms	remaining: 1.98s
100:	total: 407ms	remaining: 1.85s
150:	total: 611ms	remaining: 1.66s
200:	total: 817ms	remaining: 1.46s
250:	total: 1s	remaining: 1.24s
300:	total: 1.24s	remaining: 1.07s
350:	total: 1.45s	remaining: 870ms
400:	total: 1.67s	remaining: 666ms
450:	total: 1.91s	remaining: 466ms
500:	total: 2.19s	remaining: 262ms
550:	total: 2.44s	remaining: 44.3ms
560:	total: 2.48s	remaining: 0us
0:	total: 5.29ms	remaining: 2.96s
50:	total: 257ms	remaining: 2.57s
100:	total: 495ms	remaining: 2.25s
150:	total: 718ms	remaining: 1.95s
200:	total: 948ms	remaining: 1.7s
250:	total: 1.15s	remaining: 1.43s
300:	total: 1.35s	remaining: 1.17s
350:	total: 1.57s	remaining: 941ms
400:	total: 1.79s	remaining: 714ms
450:	total: 1.99s	remaining: 484ms
500:	total: 2.2s	remaining: 264ms
550:	total: 2.52s	remaining: 45.8ms
560:	total: 2.57s	remaining: 0us
0:	total: 5.35ms	remaining: 3s
50:	total: 397ms	remaining: 3.96s
100:	total: 658ms	remaining: 3s
150:	total: 866ms	remaining: 2.35s
200:	total: 1.07s	remaining: 1.91s
250:	total: 1.26s	remaining: 1.56s
300:	total: 1.49s	remaining: 1.28s
350:	total: 1.75s	remaining: 1.05s
400:	total: 1.97s	remaining: 786ms
450:	total: 2.19s	remaining: 535ms
500:	total: 2.4s	remaining: 287ms
550:	total: 2.62s	remaining: 47.6ms
560:	total: 2.67s	remaining: 0us
0:	total: 4.38ms	remaining: 2.45s
50:	total: 204ms	remaining: 2.04s
100:	total: 421ms	remaining: 1.92s
150:	total: 642ms	remaining: 1.74s
200:	total: 846ms	remaining: 1.51s
250:	total: 1.05s	remaining: 1.29s
300:	total: 1.24s	remaining: 1.07s
350:	total: 1.43s	remaining: 858ms
400:	total: 1.63s	remaining: 651ms
450:	total: 1.85s	remaining: 451ms
500:	total: 2.06s	remaining: 246ms

[I 2025-11-24 20:19:38,427] Trial 42 finished with value: 0.7250951195992471 and parameters: {'weight_pos': 2.933238088353507, 'iterations': 561, 'learning_rate': 0.04858022214134421, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.00013219309989594556, 'bagging_temperature': 0.641810601179915, 'rsm': 0.20935316045904467, 'min_data_in_leaf': 50, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

550:	total: 2.27s	remaining: 41.2ms
560:	total: 2.31s	remaining: 0us
0:	total: 4.56ms	remaining: 3.83s
50:	total: 211ms	remaining: 3.27s
100:	total: 408ms	remaining: 2.99s
150:	total: 599ms	remaining: 2.74s
200:	total: 781ms	remaining: 2.49s
250:	total: 973ms	remaining: 2.29s
300:	total: 1.18s	remaining: 2.13s
350:	total: 1.38s	remaining: 1.93s
400:	total: 1.57s	remaining: 1.73s
450:	total: 1.76s	remaining: 1.52s
500:	total: 1.94s	remaining: 1.32s
550:	total: 2.12s	remaining: 1.12s
600:	total: 2.31s	remaining: 926ms
650:	total: 2.51s	remaining: 736ms
700:	total: 2.7s	remaining: 543ms
750:	total: 2.89s	remaining: 350ms
800:	total: 3.1s	remaining: 159ms
841:	total: 3.29s	remaining: 0us
0:	total: 7.85ms	remaining: 6.61s
50:	total: 289ms	remaining: 4.49s
100:	total: 511ms	remaining: 3.75s
150:	total: 793ms	remaining: 3.63s
200:	total: 1.05s	remaining: 3.35s
250:	total: 1.38s	remaining: 3.26s
300:	total: 1.92s	remaining: 3.44s
350:	total: 2.16s	remaining: 3.03s
400:	total: 2.4s	remaining: 2.63s
450:	total: 2.63s	remaining: 2.28s
500:	total: 2.84s	remaining: 1.93s
550:	total: 3.04s	remaining: 1.61s
600:	total: 3.25s	remaining: 1.3s
650:	total: 3.46s	remaining: 1.01s
700:	total: 3.66s	remaining: 737ms
750:	total: 3.87s	remaining: 469ms
800:	total: 4.1s	remaining: 210ms
841:	total: 4.27s	remaining: 0us
0:	total: 6.3ms	remaining: 5.3s
50:	total: 218ms	remaining: 3.38s
100:	total: 441ms	remaining: 3.23s
150:	total: 636ms	remaining: 2.91s
200:	total: 856ms	remaining: 2.73s
250:	total: 1.06s	remaining: 2.5s
300:	total: 1.29s	remaining: 2.31s
350:	total: 1.5s	remaining: 2.1s
400:	total: 1.7s	remaining: 1.87s
450:	total: 1.91s	remaining: 1.66s
500:	total: 2.11s	remaining: 1.44s
550:	total: 2.32s	remaining: 1.23s
600:	total: 2.53s	remaining: 1.01s
650:	total: 2.72s	remaining: 799ms
700:	total: 2.91s	remaining: 586ms
750:	total: 3.11s	remaining: 377ms
800:	total: 3.31s	remaining: 170ms
841:	total: 3.47s	remaining: 0us
0:	total: 4.81ms	remaining: 4.05s
50:	total: 206ms	remaining: 3.19s
100:	total: 403ms	remaining: 2.96s
150:	total: 592ms	remaining: 2.71s
200:	total: 786ms	remaining: 2.51s
250:	total: 988ms	remaining: 2.33s
300:	total: 1.29s	remaining: 2.31s
350:	total: 1.51s	remaining: 2.11s
400:	total: 1.7s	remaining: 1.87s
450:	total: 1.9s	remaining: 1.65s
500:	total: 2.1s	remaining: 1.43s
550:	total: 2.29s	remaining: 1.21s
600:	total: 2.49s	remaining: 997ms
650:	total: 2.69s	remaining: 790ms
700:	total: 2.88s	remaining: 580ms
750:	total: 3.08s	remaining: 373ms
800:	total: 3.32s	remaining: 170ms
841:	total: 3.55s	remaining: 0us
0:	total: 11.2ms	remaining: 9.46s
50:	total: 254ms	remaining: 3.94s
100:	total: 446ms	remaining: 3.27s
150:	total: 633ms	remaining: 2.9s
200:	total: 839ms	remaining: 2.67s
250:	total: 1.05s	remaining: 2.48s
300:	total: 1.25s	remaining: 2.25s
350:	total: 1.45s	remaining: 2.03s
400:	total: 1.64s	remaining: 1.81s
450:	total: 1.84s	remaining: 1.6s
500:	total: 2.04s	remaining: 1.39s
550:	total: 2.25s	remaining: 1.19s
600:	total: 2.44s	remaining: 979ms
650:	total: 2.64s	remaining: 776ms
700:	total: 2.84s	remaining: 571ms
750:	total: 3.04s	remaining: 369ms

[I 2025-11-24 20:19:57,176] Trial 43 finished with value: 0.7324158299563226 and parameters: {'weight_pos': 2.36240102913168, 'iterations': 842, 'learning_rate': 0.05640420214571367, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.3303907648385026e-05, 'bagging_temperature': 0.3066447702594953, 'rsm': 0.37221415170877525, 'min_data_in_leaf': 37, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

800:	total: 3.24s	remaining: 166ms
841:	total: 3.4s	remaining: 0us
0:	total: 5.08ms	remaining: 4.83s
50:	total: 199ms	remaining: 3.51s
100:	total: 399ms	remaining: 3.35s
150:	total: 616ms	remaining: 3.27s
200:	total: 824ms	remaining: 3.08s
250:	total: 1.03s	remaining: 2.87s
300:	total: 1.24s	remaining: 2.68s
350:	total: 1.44s	remaining: 2.47s
400:	total: 1.65s	remaining: 2.27s
450:	total: 1.86s	remaining: 2.07s
500:	total: 2.06s	remaining: 1.85s
550:	total: 2.27s	remaining: 1.64s
600:	total: 2.47s	remaining: 1.44s
650:	total: 2.68s	remaining: 1.23s
700:	total: 2.88s	remaining: 1.03s
750:	total: 3.09s	remaining: 823ms
800:	total: 3.3s	remaining: 617ms
850:	total: 3.5s	remaining: 411ms
900:	total: 3.7s	remaining: 205ms
950:	total: 3.9s	remaining: 0us
0:	total: 4.79ms	remaining: 4.55s
50:	total: 202ms	remaining: 3.56s
100:	total: 408ms	remaining: 3.44s
150:	total: 608ms	remaining: 3.22s
200:	total: 803ms	remaining: 3s
250:	total: 997ms	remaining: 2.78s
300:	total: 1.21s	remaining: 2.61s
350:	total: 1.42s	remaining: 2.43s
400:	total: 1.71s	remaining: 2.34s
450:	total: 1.95s	remaining: 2.17s
500:	total: 2.4s	remaining: 2.16s
550:	total: 2.72s	remaining: 1.97s
600:	total: 2.93s	remaining: 1.71s
650:	total: 3.14s	remaining: 1.45s
700:	total: 3.35s	remaining: 1.2s
750:	total: 3.61s	remaining: 962ms
800:	total: 3.86s	remaining: 723ms
850:	total: 4.08s	remaining: 480ms
900:	total: 4.31s	remaining: 239ms
950:	total: 4.53s	remaining: 0us
0:	total: 5.26ms	remaining: 5s
50:	total: 231ms	remaining: 4.08s
100:	total: 445ms	remaining: 3.74s
150:	total: 670ms	remaining: 3.55s
200:	total: 878ms	remaining: 3.28s
250:	total: 1.09s	remaining: 3.05s
300:	total: 1.3s	remaining: 2.8s
350:	total: 1.53s	remaining: 2.62s
400:	total: 1.77s	remaining: 2.42s
450:	total: 2s	remaining: 2.21s
500:	total: 2.21s	remaining: 1.98s
550:	total: 2.41s	remaining: 1.75s
600:	total: 2.62s	remaining: 1.52s
650:	total: 2.82s	remaining: 1.3s
700:	total: 3.03s	remaining: 1.08s
750:	total: 3.23s	remaining: 861ms
800:	total: 3.46s	remaining: 648ms
850:	total: 3.67s	remaining: 431ms
900:	total: 3.87s	remaining: 215ms
950:	total: 4.08s	remaining: 0us
0:	total: 7.07ms	remaining: 6.72s
50:	total: 255ms	remaining: 4.5s
100:	total: 453ms	remaining: 3.81s
150:	total: 644ms	remaining: 3.41s
200:	total: 837ms	remaining: 3.12s
250:	total: 1.03s	remaining: 2.88s
300:	total: 1.23s	remaining: 2.65s
350:	total: 1.43s	remaining: 2.44s
400:	total: 1.63s	remaining: 2.24s
450:	total: 1.84s	remaining: 2.04s
500:	total: 2.04s	remaining: 1.83s
550:	total: 2.23s	remaining: 1.62s
600:	total: 2.43s	remaining: 1.42s
650:	total: 2.64s	remaining: 1.22s
700:	total: 2.85s	remaining: 1.01s
750:	total: 3.08s	remaining: 819ms
800:	total: 3.45s	remaining: 647ms
850:	total: 3.77s	remaining: 443ms
900:	total: 3.98s	remaining: 221ms
950:	total: 4.18s	remaining: 0us
0:	total: 6.34ms	remaining: 6.03s
50:	total: 208ms	remaining: 3.68s
100:	total: 413ms	remaining: 3.47s
150:	total: 609ms	remaining: 3.23s
200:	total: 819ms	remaining: 3.06s
250:	total: 1.02s	remaining: 2.83s
300:	total: 1.22s	remaining: 2.63s
350:	total: 1.44s	remaining: 2.47s
400:	total: 1.64s	remaining: 2.26s
450:	total: 1.85s	remaining: 2.05s
500:	total: 2.06s	remaining: 1.85s
550:	total: 2.27s	remaining: 1.65s
600:	total: 2.48s	remaining: 1.44s
650:	total: 2.68s	remaining: 1.23s
700:	total: 2.88s	remaining: 1.03s
750:	total: 3.09s	remaining: 822ms
800:	total: 3.37s	remaining: 631ms
850:	total: 3.59s	remaining: 422ms
900:	total: 3.8s	remaining: 211ms

[I 2025-11-24 20:20:18,596] Trial 44 finished with value: 0.7161857635322433 and parameters: {'weight_pos': 3.2717037619030163, 'iterations': 951, 'learning_rate': 0.05792962774603884, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.0635102013678916e-05, 'bagging_temperature': 0.3027417162674707, 'rsm': 0.385711714771319, 'min_data_in_leaf': 37, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 4.02s	remaining: 0us
0:	total: 4.93ms	remaining: 660ms
50:	total: 170ms	remaining: 279ms
100:	total: 328ms	remaining: 111ms
134:	total: 437ms	remaining: 0us
0:	total: 4.8ms	remaining: 643ms
50:	total: 169ms	remaining: 279ms
100:	total: 335ms	remaining: 113ms
134:	total: 446ms	remaining: 0us
0:	total: 3.73ms	remaining: 499ms
50:	total: 175ms	remaining: 289ms
100:	total: 338ms	remaining: 114ms
134:	total: 454ms	remaining: 0us
0:	total: 4.27ms	remaining: 572ms
50:	total: 208ms	remaining: 342ms
100:	total: 388ms	remaining: 131ms
134:	total: 516ms	remaining: 0us
0:	total: 4.57ms	remaining: 612ms
50:	total: 199ms	remaining: 328ms
100:	total: 383ms	remaining: 129ms

[I 2025-11-24 20:20:21,359] Trial 45 finished with value: 0.6118655868581122 and parameters: {'weight_pos': 1.763397106541513, 'iterations': 135, 'learning_rate': 0.03565480001917899, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 4.2258272534077555e-05, 'bagging_temperature': 0.2757945117679139, 'rsm': 0.9234868273172188, 'min_data_in_leaf': 13, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

134:	total: 517ms	remaining: 0us
0:	learn: 0.8051981	total: 18.3ms	remaining: 16.1s
50:	learn: 0.8792570	total: 380ms	remaining: 6.19s
100:	learn: 0.9090137	total: 730ms	remaining: 5.65s
150:	learn: 0.9379721	total: 1.1s	remaining: 5.33s
200:	learn: 0.9581179	total: 1.49s	remaining: 5.05s
250:	learn: 0.9696640	total: 1.88s	remaining: 4.73s
300:	learn: 0.9755794	total: 2.46s	remaining: 4.75s
350:	learn: 0.9811396	total: 2.84s	remaining: 4.3s
400:	learn: 0.9865891	total: 3.25s	remaining: 3.9s
450:	learn: 0.9904433	total: 3.65s	remaining: 3.49s
500:	learn: 0.9926153	total: 4.03s	remaining: 3.08s
550:	learn: 0.9946135	total: 4.45s	remaining: 2.68s
600:	learn: 0.9964379	total: 4.86s	remaining: 2.28s
650:	learn: 0.9974805	total: 5.64s	remaining: 2.01s
700:	learn: 0.9984362	total: 6.09s	remaining: 1.58s
750:	learn: 0.9992181	total: 6.5s	remaining: 1.14s
800:	learn: 0.9997394	total: 7.01s	remaining: 718ms
850:	learn: 0.9998262	total: 7.44s	remaining: 280ms
882:	learn: 0.9998262	total: 7.75s	remaining: 0us
0:	learn: 0.8030337	total: 13.4ms	remaining: 11.8s
50:	learn: 0.8762313	total: 512ms	remaining: 8.35s
100:	learn: 0.9079547	total: 1.09s	remaining: 8.44s
150:	learn: 0.9329809	total: 1.53s	remaining: 7.43s
200:	learn: 0.9511764	total: 2.06s	remaining: 6.99s
250:	learn: 0.9643015	total: 2.65s	remaining: 6.69s
300:	learn: 0.9728546	total: 3.38s	remaining: 6.53s
350:	learn: 0.9784464	total: 4.29s	remaining: 6.5s
400:	learn: 0.9842434	total: 4.96s	remaining: 5.96s
450:	learn: 0.9882398	total: 5.54s	remaining: 5.3s
500:	learn: 0.9914858	total: 6.33s	remaining: 4.83s
550:	learn: 0.9940053	total: 6.88s	remaining: 4.14s
600:	learn: 0.9952216	total: 7.61s	remaining: 3.57s
650:	learn: 0.9967855	total: 8.1s	remaining: 2.89s
700:	learn: 0.9982624	total: 8.64s	remaining: 2.24s
750:	learn: 0.9987837	total: 9.16s	remaining: 1.61s
800:	learn: 0.9992181	total: 9.7s	remaining: 993ms
850:	learn: 0.9996525	total: 10.2s	remaining: 384ms
882:	learn: 0.9999131	total: 10.5s	remaining: 0us
0:	learn: 0.7992211	total: 9.26ms	remaining: 8.17s
50:	learn: 0.8756471	total: 433ms	remaining: 7.06s
100:	learn: 0.9000425	total: 907ms	remaining: 7.02s
150:	learn: 0.9291431	total: 1.38s	remaining: 6.69s
200:	learn: 0.9485940	total: 1.85s	remaining: 6.28s
250:	learn: 0.9633068	total: 2.32s	remaining: 5.85s
300:	learn: 0.9747660	total: 2.81s	remaining: 5.43s
350:	learn: 0.9813449	total: 3.41s	remaining: 5.17s
400:	learn: 0.9867075	total: 4.11s	remaining: 4.93s
450:	learn: 0.9897482	total: 4.67s	remaining: 4.47s
500:	learn: 0.9926153	total: 5.1s	remaining: 3.89s
550:	learn: 0.9941791	total: 5.55s	remaining: 3.34s
600:	learn: 0.9960036	total: 6.05s	remaining: 2.84s
650:	learn: 0.9976543	total: 6.58s	remaining: 2.34s
700:	learn: 0.9982624	total: 7.14s	remaining: 1.85s
750:	learn: 0.9987837	total: 7.68s	remaining: 1.35s
800:	learn: 0.9992181	total: 8.25s	remaining: 845ms
850:	learn: 0.9994787	total: 8.76s	remaining: 329ms
882:	learn: 0.9998262	total: 9.05s	remaining: 0us
0:	learn: 0.7000854	total: 8.66ms	remaining: 7.64s
50:	learn: 0.8849419	total: 422ms	remaining: 6.88s
100:	learn: 0.9082078	total: 861ms	remaining: 6.67s
150:	learn: 0.9357460	total: 1.28s	remaining: 6.21s
200:	learn: 0.9541303	total: 1.66s	remaining: 5.63s
250:	learn: 0.9665528	total: 2.05s	remaining: 5.17s
300:	learn: 0.9741818	total: 2.46s	remaining: 4.76s
350:	learn: 0.9819530	total: 2.87s	remaining: 4.36s
400:	learn: 0.9862416	total: 3.29s	remaining: 3.95s
450:	learn: 0.9904433	total: 3.75s	remaining: 3.59s
500:	learn: 0.9928759	total: 4.36s	remaining: 3.33s
550:	learn: 0.9955692	total: 4.86s	remaining: 2.93s
600:	learn: 0.9967855	total: 5.32s	remaining: 2.5s
650:	learn: 0.9979149	total: 5.77s	remaining: 2.06s
700:	learn: 0.9988706	total: 6.18s	remaining: 1.6s
750:	learn: 0.9993050	total: 6.6s	remaining: 1.16s
800:	learn: 0.9995656	total: 7.04s	remaining: 720ms
850:	learn: 0.9995656	total: 7.59s	remaining: 285ms
882:	learn: 0.9997394	total: 7.87s	remaining: 0us
0:	learn: 0.8019849	total: 8.02ms	remaining: 7.08s
50:	learn: 0.8758208	total: 391ms	remaining: 6.37s
100:	learn: 0.9044481	total: 794ms	remaining: 6.15s
150:	learn: 0.9299641	total: 1.23s	remaining: 5.95s
200:	learn: 0.9504184	total: 1.62s	remaining: 5.5s
250:	learn: 0.9642624	total: 2.02s	remaining: 5.1s
300:	learn: 0.9742447	total: 2.45s	remaining: 4.74s
350:	learn: 0.9806184	total: 2.86s	remaining: 4.34s
400:	learn: 0.9854597	total: 3.32s	remaining: 3.99s
450:	learn: 0.9885005	total: 3.84s	remaining: 3.68s
500:	learn: 0.9920625	total: 4.39s	remaining: 3.35s
550:	learn: 0.9944951	total: 4.82s	remaining: 2.9s
600:	learn: 0.9964379	total: 5.24s	remaining: 2.46s
650:	learn: 0.9977411	total: 5.65s	remaining: 2.01s
700:	learn: 0.9981755	total: 6.25s	remaining: 1.62s
750:	learn: 0.9988706	total: 6.77s	remaining: 1.19s
800:	learn: 0.9993050	total: 7.33s	remaining: 751ms
850:	learn: 0.9995656	total: 7.8s	remaining: 293ms

[I 2025-11-24 20:21:05,868] Trial 46 finished with value: 0.712028567630974 and parameters: {'weight_pos': 4.362282487992516, 'iterations': 883, 'learning_rate': 0.07825649726116178, 'depth': 6, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 6.305444928810636e-05, 'bagging_temperature': 0.38432732250159213, 'rsm': 0.303231131961172, 'min_data_in_leaf': 23, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

882:	learn: 0.9998262	total: 8.19s	remaining: 0us
0:	total: 5.04ms	remaining: 4.19s
50:	total: 182ms	remaining: 2.79s
100:	total: 367ms	remaining: 2.66s
150:	total: 542ms	remaining: 2.44s
200:	total: 733ms	remaining: 2.3s
250:	total: 922ms	remaining: 2.13s
300:	total: 1.11s	remaining: 1.96s
350:	total: 1.3s	remaining: 1.79s
400:	total: 1.54s	remaining: 1.66s
450:	total: 1.88s	remaining: 1.58s
500:	total: 2.13s	remaining: 1.41s
550:	total: 2.34s	remaining: 1.2s
600:	total: 2.54s	remaining: 975ms
650:	total: 2.74s	remaining: 763ms
700:	total: 2.94s	remaining: 549ms
750:	total: 3.14s	remaining: 339ms
800:	total: 3.34s	remaining: 129ms
831:	total: 3.47s	remaining: 0us
0:	total: 4.77ms	remaining: 3.96s
50:	total: 224ms	remaining: 3.43s
100:	total: 424ms	remaining: 3.07s
150:	total: 614ms	remaining: 2.77s
200:	total: 801ms	remaining: 2.51s
250:	total: 988ms	remaining: 2.29s
300:	total: 1.18s	remaining: 2.07s
350:	total: 1.36s	remaining: 1.86s
400:	total: 1.56s	remaining: 1.68s
450:	total: 1.75s	remaining: 1.47s
500:	total: 1.93s	remaining: 1.27s
550:	total: 2.13s	remaining: 1.09s
600:	total: 2.34s	remaining: 900ms
650:	total: 2.54s	remaining: 706ms
700:	total: 2.74s	remaining: 512ms
750:	total: 2.93s	remaining: 316ms
800:	total: 3.13s	remaining: 121ms
831:	total: 3.26s	remaining: 0us
0:	total: 6.59ms	remaining: 5.48s
50:	total: 188ms	remaining: 2.88s
100:	total: 366ms	remaining: 2.65s
150:	total: 555ms	remaining: 2.5s
200:	total: 1.01s	remaining: 3.17s
250:	total: 1.26s	remaining: 2.93s
300:	total: 1.59s	remaining: 2.8s
350:	total: 2.02s	remaining: 2.76s
400:	total: 2.31s	remaining: 2.48s
450:	total: 2.53s	remaining: 2.13s
500:	total: 2.76s	remaining: 1.82s
550:	total: 3.14s	remaining: 1.6s
600:	total: 3.39s	remaining: 1.3s
650:	total: 3.59s	remaining: 997ms
700:	total: 3.78s	remaining: 706ms
750:	total: 3.97s	remaining: 429ms
800:	total: 4.17s	remaining: 161ms
831:	total: 4.29s	remaining: 0us
0:	total: 5.26ms	remaining: 4.37s
50:	total: 179ms	remaining: 2.74s
100:	total: 362ms	remaining: 2.62s
150:	total: 541ms	remaining: 2.44s
200:	total: 734ms	remaining: 2.3s
250:	total: 913ms	remaining: 2.11s
300:	total: 1.09s	remaining: 1.92s
350:	total: 1.26s	remaining: 1.73s
400:	total: 1.45s	remaining: 1.55s
450:	total: 1.63s	remaining: 1.37s
500:	total: 1.81s	remaining: 1.19s
550:	total: 1.99s	remaining: 1.01s
600:	total: 2.16s	remaining: 832ms
650:	total: 2.34s	remaining: 652ms
700:	total: 2.52s	remaining: 472ms
750:	total: 2.75s	remaining: 297ms
800:	total: 2.94s	remaining: 114ms
831:	total: 3.06s	remaining: 0us
0:	total: 4.42ms	remaining: 3.68s
50:	total: 179ms	remaining: 2.73s
100:	total: 357ms	remaining: 2.58s
150:	total: 538ms	remaining: 2.43s
200:	total: 727ms	remaining: 2.28s
250:	total: 911ms	remaining: 2.11s
300:	total: 1.08s	remaining: 1.91s
350:	total: 1.25s	remaining: 1.72s
400:	total: 1.43s	remaining: 1.54s
450:	total: 1.6s	remaining: 1.35s
500:	total: 1.78s	remaining: 1.17s
550:	total: 1.96s	remaining: 1000ms
600:	total: 2.14s	remaining: 823ms
650:	total: 2.32s	remaining: 646ms
700:	total: 2.5s	remaining: 467ms
750:	total: 2.67s	remaining: 288ms
800:	total: 2.85s	remaining: 110ms

[I 2025-11-24 20:21:23,651] Trial 47 finished with value: 0.7135208736110169 and parameters: {'weight_pos': 1.3472378972938586, 'iterations': 832, 'learning_rate': 0.04314713868952738, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.4409862844911876e-05, 'bagging_temperature': 0.3509454570940055, 'rsm': 0.5122799083888087, 'min_data_in_leaf': 28, 'leaf_estimation_iterations': 1}. Best is trial 16 with value: 0.7404863910277388.

831:	total: 2.97s	remaining: 0us
0:	total: 19.8ms	remaining: 13.9s
50:	total: 434ms	remaining: 5.55s
100:	total: 760ms	remaining: 4.53s
150:	total: 1.16s	remaining: 4.24s
200:	total: 1.49s	remaining: 3.73s
250:	total: 1.84s	remaining: 3.32s
300:	total: 2.18s	remaining: 2.92s
350:	total: 2.59s	remaining: 2.6s
400:	total: 3.01s	remaining: 2.28s
450:	total: 3.39s	remaining: 1.9s
500:	total: 3.78s	remaining: 1.53s
550:	total: 4.4s	remaining: 1.22s
600:	total: 4.8s	remaining: 822ms
650:	total: 5.15s	remaining: 420ms
700:	total: 5.49s	remaining: 23.5ms
703:	total: 5.5s	remaining: 0us
0:	total: 9.49ms	remaining: 6.67s
50:	total: 421ms	remaining: 5.39s
100:	total: 794ms	remaining: 4.74s
150:	total: 1.12s	remaining: 4.1s
200:	total: 1.46s	remaining: 3.65s
250:	total: 1.78s	remaining: 3.22s
300:	total: 2.11s	remaining: 2.83s
350:	total: 2.46s	remaining: 2.47s
400:	total: 2.83s	remaining: 2.14s
450:	total: 3.2s	remaining: 1.8s
500:	total: 3.59s	remaining: 1.46s
550:	total: 3.97s	remaining: 1.1s
600:	total: 4.68s	remaining: 802ms
650:	total: 5.12s	remaining: 417ms
700:	total: 5.71s	remaining: 24.4ms
703:	total: 5.73s	remaining: 0us
0:	total: 9.7ms	remaining: 6.82s
50:	total: 438ms	remaining: 5.61s
100:	total: 991ms	remaining: 5.92s
150:	total: 1.47s	remaining: 5.39s
200:	total: 1.87s	remaining: 4.68s
250:	total: 2.22s	remaining: 4.01s
300:	total: 2.58s	remaining: 3.45s
350:	total: 2.99s	remaining: 3.01s
400:	total: 3.38s	remaining: 2.55s
450:	total: 3.79s	remaining: 2.13s
500:	total: 4.25s	remaining: 1.72s
550:	total: 4.84s	remaining: 1.34s
600:	total: 5.26s	remaining: 902ms
650:	total: 5.65s	remaining: 460ms
700:	total: 9.32s	remaining: 39.9ms
703:	total: 9.42s	remaining: 0us
0:	total: 9.36ms	remaining: 6.58s
50:	total: 874ms	remaining: 11.2s
100:	total: 1.75s	remaining: 10.5s
150:	total: 2.33s	remaining: 8.54s
200:	total: 2.83s	remaining: 7.07s
250:	total: 3.26s	remaining: 5.88s
300:	total: 3.68s	remaining: 4.93s
350:	total: 4.07s	remaining: 4.09s
400:	total: 4.46s	remaining: 3.37s
450:	total: 4.83s	remaining: 2.71s
500:	total: 5.21s	remaining: 2.11s
550:	total: 5.62s	remaining: 1.56s
600:	total: 6.05s	remaining: 1.04s
650:	total: 6.57s	remaining: 535ms
700:	total: 7.02s	remaining: 30.1ms
703:	total: 7.08s	remaining: 0us
0:	total: 18ms	remaining: 12.6s
50:	total: 435ms	remaining: 5.56s
100:	total: 1.03s	remaining: 6.13s
150:	total: 1.63s	remaining: 5.96s
200:	total: 2.07s	remaining: 5.18s
250:	total: 2.53s	remaining: 4.56s
300:	total: 3.03s	remaining: 4.06s
350:	total: 3.4s	remaining: 3.42s
400:	total: 3.87s	remaining: 2.92s
450:	total: 4.29s	remaining: 2.41s
500:	total: 4.73s	remaining: 1.92s
550:	total: 5.14s	remaining: 1.43s
600:	total: 5.57s	remaining: 955ms
650:	total: 5.92s	remaining: 482ms

[I 2025-11-24 20:21:58,759] Trial 48 finished with value: 0.7182613876280199 and parameters: {'weight_pos': 2.182502297020021, 'iterations': 704, 'learning_rate': 0.05916074233271699, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0004287229418264295, 'bagging_temperature': 0.1947235322636519, 'rsm': 0.3530343773602795, 'min_data_in_leaf': 39, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

700:	total: 6.26s	remaining: 26.8ms
703:	total: 6.28s	remaining: 0us
0:	total: 4.97ms	remaining: 4.8s
50:	total: 204ms	remaining: 3.66s
100:	total: 419ms	remaining: 3.59s
150:	total: 669ms	remaining: 3.61s
200:	total: 876ms	remaining: 3.34s
250:	total: 1.12s	remaining: 3.19s
300:	total: 1.33s	remaining: 2.95s
350:	total: 1.59s	remaining: 2.78s
400:	total: 1.83s	remaining: 2.58s
450:	total: 2.09s	remaining: 2.4s
500:	total: 2.31s	remaining: 2.14s
550:	total: 2.53s	remaining: 1.91s
600:	total: 2.81s	remaining: 1.71s
650:	total: 3.01s	remaining: 1.46s
700:	total: 3.24s	remaining: 1.23s
750:	total: 3.46s	remaining: 995ms
800:	total: 3.69s	remaining: 765ms
850:	total: 3.92s	remaining: 534ms
900:	total: 4.23s	remaining: 310ms
950:	total: 4.57s	remaining: 76.9ms
966:	total: 4.72s	remaining: 0us
0:	total: 26.2ms	remaining: 25.3s
50:	total: 444ms	remaining: 7.98s
100:	total: 657ms	remaining: 5.64s
150:	total: 895ms	remaining: 4.84s
200:	total: 1.21s	remaining: 4.6s
250:	total: 1.74s	remaining: 4.95s
300:	total: 1.97s	remaining: 4.35s
350:	total: 2.17s	remaining: 3.81s
400:	total: 2.39s	remaining: 3.37s
450:	total: 2.6s	remaining: 2.97s
500:	total: 2.83s	remaining: 2.63s
550:	total: 3.09s	remaining: 2.34s
600:	total: 3.33s	remaining: 2.03s
650:	total: 3.61s	remaining: 1.75s
700:	total: 3.86s	remaining: 1.46s
750:	total: 4.12s	remaining: 1.19s
800:	total: 4.33s	remaining: 897ms
850:	total: 4.54s	remaining: 620ms
900:	total: 4.77s	remaining: 350ms
950:	total: 4.99s	remaining: 84ms
966:	total: 5.09s	remaining: 0us
0:	total: 5.4ms	remaining: 5.22s
50:	total: 205ms	remaining: 3.68s
100:	total: 463ms	remaining: 3.97s
150:	total: 672ms	remaining: 3.63s
200:	total: 876ms	remaining: 3.34s
250:	total: 1.13s	remaining: 3.22s
300:	total: 1.39s	remaining: 3.08s
350:	total: 1.62s	remaining: 2.85s
400:	total: 1.9s	remaining: 2.69s
450:	total: 2.13s	remaining: 2.44s
500:	total: 2.35s	remaining: 2.18s
550:	total: 2.63s	remaining: 1.99s
600:	total: 2.86s	remaining: 1.74s
650:	total: 3.15s	remaining: 1.53s
700:	total: 3.4s	remaining: 1.29s
750:	total: 3.68s	remaining: 1.06s
800:	total: 3.98s	remaining: 824ms
850:	total: 4.25s	remaining: 580ms
900:	total: 4.63s	remaining: 340ms
950:	total: 4.96s	remaining: 83.5ms
966:	total: 5.04s	remaining: 0us
0:	total: 14.1ms	remaining: 13.7s
50:	total: 262ms	remaining: 4.7s
100:	total: 475ms	remaining: 4.08s
150:	total: 692ms	remaining: 3.74s
200:	total: 917ms	remaining: 3.49s
250:	total: 1.28s	remaining: 3.66s
300:	total: 1.53s	remaining: 3.39s
350:	total: 1.81s	remaining: 3.17s
400:	total: 2.04s	remaining: 2.88s
450:	total: 2.29s	remaining: 2.63s
500:	total: 2.51s	remaining: 2.33s
550:	total: 2.73s	remaining: 2.06s
600:	total: 2.96s	remaining: 1.8s
650:	total: 3.21s	remaining: 1.56s
700:	total: 3.44s	remaining: 1.3s
750:	total: 3.69s	remaining: 1.06s
800:	total: 3.92s	remaining: 812ms
850:	total: 4.16s	remaining: 567ms
900:	total: 4.37s	remaining: 320ms
950:	total: 4.61s	remaining: 77.6ms
966:	total: 4.7s	remaining: 0us
0:	total: 5.6ms	remaining: 5.41s
50:	total: 228ms	remaining: 4.09s
100:	total: 573ms	remaining: 4.91s
150:	total: 782ms	remaining: 4.22s
200:	total: 1s	remaining: 3.81s
250:	total: 1.26s	remaining: 3.61s
300:	total: 1.52s	remaining: 3.38s
350:	total: 1.8s	remaining: 3.16s
400:	total: 2.04s	remaining: 2.88s
450:	total: 2.27s	remaining: 2.6s
500:	total: 2.48s	remaining: 2.31s
550:	total: 2.75s	remaining: 2.08s
600:	total: 2.96s	remaining: 1.8s
650:	total: 3.16s	remaining: 1.53s
700:	total: 3.37s	remaining: 1.28s
750:	total: 3.6s	remaining: 1.03s
800:	total: 3.85s	remaining: 798ms
850:	total: 4.07s	remaining: 555ms
900:	total: 4.27s	remaining: 313ms

[I 2025-11-24 20:22:24,235] Trial 49 finished with value: 0.6807540166818852 and parameters: {'weight_pos': 4.00391028033206, 'iterations': 967, 'learning_rate': 0.016050505430117278, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.2029388131371015e-05, 'bagging_temperature': 0.4343303763411003, 'rsm': 0.4078326151903719, 'min_data_in_leaf': 17, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 4.83s	remaining: 81.3ms
966:	total: 4.9s	remaining: 0us
0:	total: 17.2ms	remaining: 11.1s
50:	total: 746ms	remaining: 8.73s
100:	total: 1.38s	remaining: 7.46s
150:	total: 2.27s	remaining: 7.46s
200:	total: 3.02s	remaining: 6.72s
250:	total: 3.74s	remaining: 5.92s
300:	total: 4.42s	remaining: 5.1s
350:	total: 5.13s	remaining: 4.34s
400:	total: 5.86s	remaining: 3.61s
450:	total: 6.62s	remaining: 2.89s
500:	total: 7.34s	remaining: 2.15s
550:	total: 8.06s	remaining: 1.42s
600:	total: 8.84s	remaining: 691ms
647:	total: 9.75s	remaining: 0us
0:	total: 18.5ms	remaining: 12s
50:	total: 706ms	remaining: 8.27s
100:	total: 1.4s	remaining: 7.61s
150:	total: 2.32s	remaining: 7.65s
200:	total: 3.39s	remaining: 7.53s
250:	total: 4.24s	remaining: 6.71s
300:	total: 5.07s	remaining: 5.84s
350:	total: 5.82s	remaining: 4.92s
400:	total: 6.67s	remaining: 4.11s
450:	total: 7.62s	remaining: 3.33s
500:	total: 8.54s	remaining: 2.51s
550:	total: 9.4s	remaining: 1.65s
600:	total: 10.4s	remaining: 812ms
647:	total: 11.3s	remaining: 0us
0:	total: 10.8ms	remaining: 6.99s
50:	total: 935ms	remaining: 10.9s
100:	total: 1.71s	remaining: 9.24s
150:	total: 2.46s	remaining: 8.11s
200:	total: 3.25s	remaining: 7.23s
250:	total: 3.99s	remaining: 6.31s
300:	total: 4.75s	remaining: 5.48s
350:	total: 5.58s	remaining: 4.72s
400:	total: 6.37s	remaining: 3.92s
450:	total: 7.08s	remaining: 3.09s
500:	total: 7.82s	remaining: 2.29s
550:	total: 8.91s	remaining: 1.57s
600:	total: 9.67s	remaining: 757ms
647:	total: 10.4s	remaining: 0us
0:	total: 16.1ms	remaining: 10.4s
50:	total: 806ms	remaining: 9.43s
100:	total: 1.48s	remaining: 8.04s
150:	total: 2.18s	remaining: 7.17s
200:	total: 3.13s	remaining: 6.97s
250:	total: 3.92s	remaining: 6.2s
300:	total: 4.77s	remaining: 5.5s
350:	total: 5.49s	remaining: 4.65s
400:	total: 6.31s	remaining: 3.89s
450:	total: 7.14s	remaining: 3.12s
500:	total: 8.15s	remaining: 2.39s
550:	total: 8.95s	remaining: 1.58s
600:	total: 9.73s	remaining: 761ms
647:	total: 10.6s	remaining: 0us
0:	total: 14.8ms	remaining: 9.58s
50:	total: 830ms	remaining: 9.71s
100:	total: 1.6s	remaining: 8.68s
150:	total: 2.31s	remaining: 7.61s
200:	total: 3.06s	remaining: 6.81s
250:	total: 3.75s	remaining: 5.93s
300:	total: 4.47s	remaining: 5.15s
350:	total: 5.2s	remaining: 4.4s
400:	total: 5.92s	remaining: 3.65s
450:	total: 6.84s	remaining: 2.99s
500:	total: 7.61s	remaining: 2.23s
550:	total: 8.36s	remaining: 1.47s
600:	total: 9.49s	remaining: 742ms

[I 2025-11-24 20:23:17,700] Trial 50 finished with value: 0.7234568206741303 and parameters: {'weight_pos': 5.75205783843143, 'iterations': 648, 'learning_rate': 0.07295311163218775, 'depth': 7, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0008982267398242977, 'bagging_temperature': 0.9934295037313892, 'rsm': 0.47226577123452157, 'min_data_in_leaf': 46, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

647:	total: 10.5s	remaining: 0us
0:	total: 5.65ms	remaining: 4.47s
50:	total: 227ms	remaining: 3.3s
100:	total: 436ms	remaining: 2.98s
150:	total: 640ms	remaining: 2.72s
200:	total: 854ms	remaining: 2.51s
250:	total: 1.07s	remaining: 2.31s
300:	total: 1.3s	remaining: 2.12s
350:	total: 1.56s	remaining: 1.96s
400:	total: 1.83s	remaining: 1.79s
450:	total: 2.08s	remaining: 1.58s
500:	total: 2.29s	remaining: 1.33s
550:	total: 2.53s	remaining: 1.11s
600:	total: 2.77s	remaining: 885ms
650:	total: 3.02s	remaining: 660ms
700:	total: 3.45s	remaining: 453ms
750:	total: 3.7s	remaining: 207ms
792:	total: 3.9s	remaining: 0us
0:	total: 4.18ms	remaining: 3.31s
50:	total: 226ms	remaining: 3.29s
100:	total: 453ms	remaining: 3.1s
150:	total: 731ms	remaining: 3.11s
200:	total: 981ms	remaining: 2.89s
250:	total: 1.23s	remaining: 2.66s
300:	total: 1.45s	remaining: 2.37s
350:	total: 1.7s	remaining: 2.14s
400:	total: 2.16s	remaining: 2.11s
450:	total: 2.44s	remaining: 1.85s
500:	total: 2.66s	remaining: 1.55s
550:	total: 2.92s	remaining: 1.28s
600:	total: 3.13s	remaining: 1s
650:	total: 3.35s	remaining: 732ms
700:	total: 3.56s	remaining: 468ms
750:	total: 3.8s	remaining: 212ms
792:	total: 4.02s	remaining: 0us
0:	total: 4.47ms	remaining: 3.54s
50:	total: 224ms	remaining: 3.25s
100:	total: 441ms	remaining: 3.02s
150:	total: 699ms	remaining: 2.97s
200:	total: 913ms	remaining: 2.69s
250:	total: 1.13s	remaining: 2.44s
300:	total: 1.35s	remaining: 2.21s
350:	total: 1.57s	remaining: 1.98s
400:	total: 1.83s	remaining: 1.79s
450:	total: 2.07s	remaining: 1.57s
500:	total: 2.3s	remaining: 1.34s
550:	total: 2.54s	remaining: 1.12s
600:	total: 2.76s	remaining: 882ms
650:	total: 2.99s	remaining: 652ms
700:	total: 3.22s	remaining: 423ms
750:	total: 3.45s	remaining: 193ms
792:	total: 3.71s	remaining: 0us
0:	total: 5.14ms	remaining: 4.07s
50:	total: 255ms	remaining: 3.7s
100:	total: 506ms	remaining: 3.47s
150:	total: 757ms	remaining: 3.22s
200:	total: 995ms	remaining: 2.93s
250:	total: 1.22s	remaining: 2.64s
300:	total: 1.45s	remaining: 2.37s
350:	total: 1.68s	remaining: 2.11s
400:	total: 1.92s	remaining: 1.88s
450:	total: 2.16s	remaining: 1.64s
500:	total: 2.38s	remaining: 1.39s
550:	total: 2.62s	remaining: 1.15s
600:	total: 2.84s	remaining: 909ms
650:	total: 3.1s	remaining: 677ms
700:	total: 3.36s	remaining: 441ms
750:	total: 3.66s	remaining: 204ms
792:	total: 4.05s	remaining: 0us
0:	total: 4.44ms	remaining: 3.51s
50:	total: 215ms	remaining: 3.12s
100:	total: 421ms	remaining: 2.88s
150:	total: 663ms	remaining: 2.82s
200:	total: 940ms	remaining: 2.77s
250:	total: 1.19s	remaining: 2.56s
300:	total: 1.42s	remaining: 2.32s
350:	total: 1.64s	remaining: 2.06s
400:	total: 1.88s	remaining: 1.83s
450:	total: 2.13s	remaining: 1.61s
500:	total: 2.34s	remaining: 1.36s
550:	total: 2.82s	remaining: 1.24s
600:	total: 3.03s	remaining: 969ms
650:	total: 3.29s	remaining: 717ms
700:	total: 3.52s	remaining: 462ms
750:	total: 3.74s	remaining: 209ms

[I 2025-11-24 20:23:38,127] Trial 51 finished with value: 0.7353786242228001 and parameters: {'weight_pos': 2.49885731660869, 'iterations': 793, 'learning_rate': 0.05249326547179733, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.00012345283027286714, 'bagging_temperature': 0.534471469558303, 'rsm': 0.24768907429405668, 'min_data_in_leaf': 57, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

792:	total: 3.94s	remaining: 0us
0:	total: 9.44ms	remaining: 7.49s
50:	total: 239ms	remaining: 3.48s
100:	total: 459ms	remaining: 3.15s
150:	total: 714ms	remaining: 3.04s
200:	total: 993ms	remaining: 2.93s
250:	total: 1.44s	remaining: 3.1s
300:	total: 1.82s	remaining: 2.99s
350:	total: 2.24s	remaining: 2.83s
400:	total: 2.63s	remaining: 2.58s
450:	total: 2.9s	remaining: 2.2s
500:	total: 3.15s	remaining: 1.84s
550:	total: 3.4s	remaining: 1.5s
600:	total: 3.66s	remaining: 1.18s
650:	total: 3.93s	remaining: 864ms
700:	total: 4.18s	remaining: 555ms
750:	total: 4.46s	remaining: 255ms
793:	total: 4.65s	remaining: 0us
0:	total: 4.86ms	remaining: 3.85s
50:	total: 221ms	remaining: 3.23s
100:	total: 434ms	remaining: 2.98s
150:	total: 930ms	remaining: 3.96s
200:	total: 1.41s	remaining: 4.15s
250:	total: 1.85s	remaining: 4s
300:	total: 2.18s	remaining: 3.56s
350:	total: 2.43s	remaining: 3.07s
400:	total: 2.7s	remaining: 2.65s
450:	total: 2.92s	remaining: 2.22s
500:	total: 3.21s	remaining: 1.88s
550:	total: 3.4s	remaining: 1.5s
600:	total: 3.58s	remaining: 1.15s
650:	total: 3.87s	remaining: 851ms
700:	total: 4.38s	remaining: 581ms
750:	total: 4.58s	remaining: 262ms
793:	total: 4.74s	remaining: 0us
0:	total: 4.62ms	remaining: 3.66s
50:	total: 198ms	remaining: 2.88s
100:	total: 373ms	remaining: 2.56s
150:	total: 581ms	remaining: 2.47s
200:	total: 780ms	remaining: 2.3s
250:	total: 967ms	remaining: 2.09s
300:	total: 1.15s	remaining: 1.88s
350:	total: 1.33s	remaining: 1.68s
400:	total: 1.52s	remaining: 1.49s
450:	total: 1.71s	remaining: 1.3s
500:	total: 1.9s	remaining: 1.11s
550:	total: 2.09s	remaining: 921ms
600:	total: 2.28s	remaining: 734ms
650:	total: 2.48s	remaining: 544ms
700:	total: 2.67s	remaining: 354ms
750:	total: 2.87s	remaining: 164ms
793:	total: 3.04s	remaining: 0us
0:	total: 4.11ms	remaining: 3.25s
50:	total: 183ms	remaining: 2.67s
100:	total: 388ms	remaining: 2.66s
150:	total: 569ms	remaining: 2.42s
200:	total: 760ms	remaining: 2.24s
250:	total: 946ms	remaining: 2.05s
300:	total: 1.12s	remaining: 1.84s
350:	total: 1.3s	remaining: 1.64s
400:	total: 1.48s	remaining: 1.45s
450:	total: 1.68s	remaining: 1.27s
500:	total: 1.86s	remaining: 1.08s
550:	total: 2.04s	remaining: 902ms
600:	total: 2.23s	remaining: 716ms
650:	total: 2.41s	remaining: 529ms
700:	total: 2.63s	remaining: 349ms
750:	total: 3.01s	remaining: 173ms
793:	total: 3.22s	remaining: 0us
0:	total: 4.32ms	remaining: 3.43s
50:	total: 179ms	remaining: 2.6s
100:	total: 354ms	remaining: 2.43s
150:	total: 531ms	remaining: 2.26s
200:	total: 719ms	remaining: 2.12s
250:	total: 909ms	remaining: 1.97s
300:	total: 1.09s	remaining: 1.79s
350:	total: 1.27s	remaining: 1.6s
400:	total: 1.46s	remaining: 1.43s
450:	total: 1.64s	remaining: 1.25s
500:	total: 1.82s	remaining: 1.06s
550:	total: 2s	remaining: 883ms
600:	total: 2.21s	remaining: 708ms
650:	total: 2.41s	remaining: 530ms
700:	total: 2.64s	remaining: 351ms
750:	total: 2.82s	remaining: 161ms

[I 2025-11-24 20:23:57,423] Trial 52 finished with value: 0.7094998105185082 and parameters: {'weight_pos': 2.9664367077712637, 'iterations': 794, 'learning_rate': 0.039115765499958335, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 34.182011566324064, 'bagging_temperature': 0.1819839892881347, 'rsm': 0.2642879576658759, 'min_data_in_leaf': 59, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

793:	total: 3s	remaining: 0us
0:	total: 4.62ms	remaining: 4.21s
50:	total: 195ms	remaining: 3.3s
100:	total: 383ms	remaining: 3.08s
150:	total: 590ms	remaining: 2.98s
200:	total: 768ms	remaining: 2.72s
250:	total: 953ms	remaining: 2.51s
300:	total: 1.14s	remaining: 2.31s
350:	total: 1.33s	remaining: 2.13s
400:	total: 1.52s	remaining: 1.94s
450:	total: 1.78s	remaining: 1.82s
500:	total: 2.01s	remaining: 1.65s
550:	total: 2.23s	remaining: 1.46s
600:	total: 2.44s	remaining: 1.26s
650:	total: 2.65s	remaining: 1.07s
700:	total: 2.87s	remaining: 867ms
750:	total: 3.06s	remaining: 661ms
800:	total: 3.28s	remaining: 458ms
850:	total: 3.49s	remaining: 254ms
900:	total: 3.71s	remaining: 49.4ms
912:	total: 3.76s	remaining: 0us
0:	total: 4.7ms	remaining: 4.29s
50:	total: 197ms	remaining: 3.32s
100:	total: 389ms	remaining: 3.13s
150:	total: 582ms	remaining: 2.94s
200:	total: 765ms	remaining: 2.71s
250:	total: 957ms	remaining: 2.52s
300:	total: 1.14s	remaining: 2.32s
350:	total: 1.33s	remaining: 2.13s
400:	total: 1.53s	remaining: 1.96s
450:	total: 1.72s	remaining: 1.76s
500:	total: 1.92s	remaining: 1.58s
550:	total: 2.11s	remaining: 1.39s
600:	total: 2.48s	remaining: 1.29s
650:	total: 2.71s	remaining: 1.09s
700:	total: 2.9s	remaining: 876ms
750:	total: 3.09s	remaining: 667ms
800:	total: 3.29s	remaining: 460ms
850:	total: 3.58s	remaining: 261ms
900:	total: 3.83s	remaining: 51ms
912:	total: 3.88s	remaining: 0us
0:	total: 4.51ms	remaining: 4.12s
50:	total: 230ms	remaining: 3.88s
100:	total: 418ms	remaining: 3.36s
150:	total: 610ms	remaining: 3.08s
200:	total: 801ms	remaining: 2.84s
250:	total: 987ms	remaining: 2.6s
300:	total: 1.18s	remaining: 2.4s
350:	total: 1.37s	remaining: 2.2s
400:	total: 1.57s	remaining: 2.01s
450:	total: 1.79s	remaining: 1.83s
500:	total: 2.04s	remaining: 1.67s
550:	total: 2.25s	remaining: 1.48s
600:	total: 2.45s	remaining: 1.27s
650:	total: 2.7s	remaining: 1.09s
700:	total: 2.95s	remaining: 891ms
750:	total: 3.17s	remaining: 684ms
800:	total: 3.38s	remaining: 473ms
850:	total: 3.59s	remaining: 262ms
900:	total: 3.79s	remaining: 50.4ms
912:	total: 3.83s	remaining: 0us
0:	total: 4.3ms	remaining: 3.92s
50:	total: 225ms	remaining: 3.81s
100:	total: 491ms	remaining: 3.95s
150:	total: 708ms	remaining: 3.57s
200:	total: 919ms	remaining: 3.25s
250:	total: 1.11s	remaining: 2.93s
300:	total: 1.3s	remaining: 2.64s
350:	total: 1.58s	remaining: 2.54s
400:	total: 1.78s	remaining: 2.28s
450:	total: 1.98s	remaining: 2.03s
500:	total: 2.32s	remaining: 1.91s
550:	total: 2.66s	remaining: 1.75s
600:	total: 3s	remaining: 1.56s
650:	total: 3.32s	remaining: 1.33s
700:	total: 3.58s	remaining: 1.08s
750:	total: 3.79s	remaining: 819ms
800:	total: 3.99s	remaining: 558ms
850:	total: 4.19s	remaining: 306ms
900:	total: 4.62s	remaining: 61.5ms
912:	total: 4.68s	remaining: 0us
0:	total: 5.07ms	remaining: 4.63s
50:	total: 206ms	remaining: 3.49s
100:	total: 413ms	remaining: 3.32s
150:	total: 647ms	remaining: 3.27s
200:	total: 843ms	remaining: 2.99s
250:	total: 1.03s	remaining: 2.73s
300:	total: 1.26s	remaining: 2.56s
350:	total: 1.45s	remaining: 2.32s
400:	total: 1.68s	remaining: 2.14s
450:	total: 1.88s	remaining: 1.92s
500:	total: 2.06s	remaining: 1.69s
550:	total: 2.25s	remaining: 1.48s
600:	total: 2.45s	remaining: 1.27s
650:	total: 2.64s	remaining: 1.06s
700:	total: 2.83s	remaining: 855ms
750:	total: 3.02s	remaining: 651ms
800:	total: 3.21s	remaining: 449ms
850:	total: 3.44s	remaining: 251ms
900:	total: 3.63s	remaining: 48.4ms

[I 2025-11-24 20:24:17,943] Trial 53 finished with value: 0.7189948108613116 and parameters: {'weight_pos': 1.8277557688430608, 'iterations': 913, 'learning_rate': 0.06455181142863213, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.03571442198905461, 'bagging_temperature': 0.49985352904082386, 'rsm': 0.1583656333479957, 'min_data_in_leaf': 55, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

912:	total: 3.68s	remaining: 0us
0:	total: 5ms	remaining: 1.62s
50:	total: 206ms	remaining: 1.1s
100:	total: 418ms	remaining: 922ms
150:	total: 613ms	remaining: 702ms
200:	total: 826ms	remaining: 506ms
250:	total: 1.04s	remaining: 303ms
300:	total: 1.25s	remaining: 95.6ms
323:	total: 1.35s	remaining: 0us
0:	total: 5.16ms	remaining: 1.67s
50:	total: 207ms	remaining: 1.11s
100:	total: 403ms	remaining: 889ms
150:	total: 599ms	remaining: 687ms
200:	total: 836ms	remaining: 511ms
250:	total: 1.04s	remaining: 303ms
300:	total: 1.25s	remaining: 95.2ms
323:	total: 1.35s	remaining: 0us
0:	total: 4.43ms	remaining: 1.43s
50:	total: 202ms	remaining: 1.08s
100:	total: 451ms	remaining: 995ms
150:	total: 651ms	remaining: 745ms
200:	total: 848ms	remaining: 519ms
250:	total: 1.04s	remaining: 303ms
300:	total: 1.33s	remaining: 102ms
323:	total: 1.45s	remaining: 0us
0:	total: 5.85ms	remaining: 1.89s
50:	total: 311ms	remaining: 1.67s
100:	total: 596ms	remaining: 1.32s
150:	total: 799ms	remaining: 915ms
200:	total: 1s	remaining: 613ms
250:	total: 1.21s	remaining: 352ms
300:	total: 1.58s	remaining: 120ms
323:	total: 1.7s	remaining: 0us
0:	total: 4.73ms	remaining: 1.53s
50:	total: 205ms	remaining: 1.09s
100:	total: 400ms	remaining: 884ms
150:	total: 637ms	remaining: 729ms
200:	total: 861ms	remaining: 527ms
250:	total: 1.08s	remaining: 313ms

[I 2025-11-24 20:24:25,664] Trial 54 finished with value: 0.7021831064982283 and parameters: {'weight_pos': 2.5292595652184904, 'iterations': 324, 'learning_rate': 0.03396321165491372, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 10.713601144730596, 'bagging_temperature': 0.5216855718204749, 'rsm': 0.3516039627110073, 'min_data_in_leaf': 64, 'leaf_estimation_iterations': 2}. Best is trial 16 with value: 0.7404863910277388.

300:	total: 1.32s	remaining: 101ms
323:	total: 1.43s	remaining: 0us
0:	total: 5.28ms	remaining: 4.5s
50:	total: 203ms	remaining: 3.2s
100:	total: 446ms	remaining: 3.32s
150:	total: 631ms	remaining: 2.94s
200:	total: 830ms	remaining: 2.69s
250:	total: 1.03s	remaining: 2.46s
300:	total: 1.21s	remaining: 2.22s
350:	total: 1.45s	remaining: 2.08s
400:	total: 1.66s	remaining: 1.87s
450:	total: 1.85s	remaining: 1.65s
500:	total: 2.04s	remaining: 1.44s
550:	total: 2.31s	remaining: 1.26s
600:	total: 2.56s	remaining: 1.07s
650:	total: 2.82s	remaining: 875ms
700:	total: 3.05s	remaining: 662ms
750:	total: 3.27s	remaining: 445ms
800:	total: 3.48s	remaining: 226ms
850:	total: 3.69s	remaining: 8.66ms
852:	total: 3.69s	remaining: 0us
0:	total: 4.83ms	remaining: 4.11s
50:	total: 206ms	remaining: 3.24s
100:	total: 401ms	remaining: 2.99s
150:	total: 601ms	remaining: 2.79s
200:	total: 882ms	remaining: 2.86s
250:	total: 1.15s	remaining: 2.75s
300:	total: 1.37s	remaining: 2.52s
350:	total: 1.57s	remaining: 2.25s
400:	total: 1.76s	remaining: 1.98s
450:	total: 1.95s	remaining: 1.73s
500:	total: 2.19s	remaining: 1.54s
550:	total: 2.4s	remaining: 1.31s
600:	total: 2.6s	remaining: 1.09s
650:	total: 2.79s	remaining: 867ms
700:	total: 3.07s	remaining: 665ms
750:	total: 3.31s	remaining: 450ms
800:	total: 3.52s	remaining: 229ms
850:	total: 3.71s	remaining: 8.73ms
852:	total: 3.72s	remaining: 0us
0:	total: 5.12ms	remaining: 4.36s
50:	total: 182ms	remaining: 2.87s
100:	total: 523ms	remaining: 3.89s
150:	total: 958ms	remaining: 4.45s
200:	total: 1.24s	remaining: 4.03s
250:	total: 1.47s	remaining: 3.54s
300:	total: 1.72s	remaining: 3.15s
350:	total: 1.94s	remaining: 2.78s
400:	total: 2.15s	remaining: 2.43s
450:	total: 2.37s	remaining: 2.11s
500:	total: 2.58s	remaining: 1.81s
550:	total: 2.8s	remaining: 1.54s
600:	total: 3.04s	remaining: 1.27s
650:	total: 3.25s	remaining: 1.01s
700:	total: 3.47s	remaining: 753ms
750:	total: 3.67s	remaining: 499ms
800:	total: 3.86s	remaining: 250ms
850:	total: 4.04s	remaining: 9.5ms
852:	total: 4.05s	remaining: 0us
0:	total: 4.47ms	remaining: 3.81s
50:	total: 240ms	remaining: 3.77s
100:	total: 456ms	remaining: 3.4s
150:	total: 666ms	remaining: 3.09s
200:	total: 862ms	remaining: 2.79s
250:	total: 1.06s	remaining: 2.54s
300:	total: 1.37s	remaining: 2.51s
350:	total: 1.58s	remaining: 2.27s
400:	total: 1.78s	remaining: 2s
450:	total: 1.98s	remaining: 1.76s
500:	total: 2.23s	remaining: 1.57s
550:	total: 2.42s	remaining: 1.33s
600:	total: 2.63s	remaining: 1.1s
650:	total: 2.82s	remaining: 877ms
700:	total: 3.02s	remaining: 655ms
750:	total: 3.22s	remaining: 438ms
800:	total: 3.44s	remaining: 224ms
850:	total: 3.64s	remaining: 8.56ms
852:	total: 3.65s	remaining: 0us
0:	total: 6.04ms	remaining: 5.14s
50:	total: 204ms	remaining: 3.21s
100:	total: 407ms	remaining: 3.03s
150:	total: 633ms	remaining: 2.94s
200:	total: 857ms	remaining: 2.78s
250:	total: 1.08s	remaining: 2.6s
300:	total: 1.31s	remaining: 2.41s
350:	total: 1.53s	remaining: 2.19s
400:	total: 1.72s	remaining: 1.94s
450:	total: 1.93s	remaining: 1.72s
500:	total: 2.12s	remaining: 1.49s
550:	total: 2.3s	remaining: 1.26s
600:	total: 2.66s	remaining: 1.11s
650:	total: 2.88s	remaining: 893ms
700:	total: 3.06s	remaining: 664ms
750:	total: 3.25s	remaining: 442ms
800:	total: 3.45s	remaining: 224ms

[I 2025-11-24 20:24:45,000] Trial 55 finished with value: 0.7323978123356316 and parameters: {'weight_pos': 2.2411676292729497, 'iterations': 853, 'learning_rate': 0.04625521682488633, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 7.616678561037393e-05, 'bagging_temperature': 0.6124449355368776, 'rsm': 0.4505730564468017, 'min_data_in_leaf': 40, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

850:	total: 3.63s	remaining: 8.54ms
852:	total: 3.64s	remaining: 0us
0:	total: 4.84ms	remaining: 4.1s
50:	total: 184ms	remaining: 2.88s
100:	total: 368ms	remaining: 2.72s
150:	total: 554ms	remaining: 2.56s
200:	total: 736ms	remaining: 2.37s
250:	total: 932ms	remaining: 2.22s
300:	total: 1.13s	remaining: 2.06s
350:	total: 1.32s	remaining: 1.87s
400:	total: 1.51s	remaining: 1.68s
450:	total: 1.7s	remaining: 1.49s
500:	total: 1.88s	remaining: 1.3s
550:	total: 2.06s	remaining: 1.11s
600:	total: 2.24s	remaining: 920ms
650:	total: 2.42s	remaining: 733ms
700:	total: 2.66s	remaining: 557ms
750:	total: 2.94s	remaining: 379ms
800:	total: 3.14s	remaining: 184ms
847:	total: 3.32s	remaining: 0us
0:	total: 4.39ms	remaining: 3.72s
50:	total: 192ms	remaining: 3s
100:	total: 380ms	remaining: 2.81s
150:	total: 570ms	remaining: 2.63s
200:	total: 762ms	remaining: 2.45s
250:	total: 952ms	remaining: 2.26s
300:	total: 1.14s	remaining: 2.07s
350:	total: 1.33s	remaining: 1.88s
400:	total: 1.52s	remaining: 1.7s
450:	total: 1.71s	remaining: 1.5s
500:	total: 1.9s	remaining: 1.31s
550:	total: 2.08s	remaining: 1.12s
600:	total: 2.27s	remaining: 935ms
650:	total: 2.46s	remaining: 746ms
700:	total: 2.65s	remaining: 556ms
750:	total: 2.84s	remaining: 367ms
800:	total: 3.03s	remaining: 178ms
847:	total: 3.21s	remaining: 0us
0:	total: 4.2ms	remaining: 3.56s
50:	total: 195ms	remaining: 3.04s
100:	total: 381ms	remaining: 2.82s
150:	total: 577ms	remaining: 2.66s
200:	total: 771ms	remaining: 2.48s
250:	total: 960ms	remaining: 2.28s
300:	total: 1.17s	remaining: 2.12s
350:	total: 1.39s	remaining: 1.96s
400:	total: 1.58s	remaining: 1.76s
450:	total: 1.76s	remaining: 1.55s
500:	total: 2.28s	remaining: 1.58s
550:	total: 2.53s	remaining: 1.36s
600:	total: 2.76s	remaining: 1.13s
650:	total: 2.95s	remaining: 894ms
700:	total: 3.15s	remaining: 661ms
750:	total: 3.39s	remaining: 437ms
800:	total: 3.59s	remaining: 211ms
847:	total: 3.78s	remaining: 0us
0:	total: 5.38ms	remaining: 4.56s
50:	total: 193ms	remaining: 3.02s
100:	total: 394ms	remaining: 2.92s
150:	total: 694ms	remaining: 3.2s
200:	total: 912ms	remaining: 2.93s
250:	total: 1.11s	remaining: 2.65s
300:	total: 1.3s	remaining: 2.37s
350:	total: 1.49s	remaining: 2.11s
400:	total: 1.78s	remaining: 1.98s
450:	total: 2.09s	remaining: 1.84s
500:	total: 2.42s	remaining: 1.68s
550:	total: 2.66s	remaining: 1.43s
600:	total: 2.87s	remaining: 1.18s
650:	total: 3.07s	remaining: 929ms
700:	total: 3.27s	remaining: 685ms
750:	total: 3.47s	remaining: 449ms
800:	total: 3.7s	remaining: 217ms
847:	total: 3.9s	remaining: 0us
0:	total: 4.93ms	remaining: 4.18s
50:	total: 215ms	remaining: 3.35s
100:	total: 409ms	remaining: 3.03s
150:	total: 618ms	remaining: 2.85s
200:	total: 817ms	remaining: 2.63s
250:	total: 998ms	remaining: 2.37s
300:	total: 1.18s	remaining: 2.15s
350:	total: 1.37s	remaining: 1.94s
400:	total: 1.56s	remaining: 1.73s
450:	total: 1.75s	remaining: 1.54s
500:	total: 1.97s	remaining: 1.37s
550:	total: 2.18s	remaining: 1.18s
600:	total: 2.38s	remaining: 980ms
650:	total: 2.58s	remaining: 781ms
700:	total: 2.77s	remaining: 581ms
750:	total: 2.97s	remaining: 383ms
800:	total: 3.18s	remaining: 187ms
847:	total: 3.36s	remaining: 0us

[I 2025-11-24 20:25:03,136] Trial 56 finished with value: 0.727719772711964 and parameters: {'weight_pos': 3.17967928399771, 'iterations': 848, 'learning_rate': 0.05381857723623614, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 7.842790022165103e-05, 'bagging_temperature': 0.6806338053334912, 'rsm': 0.44876866922666625, 'min_data_in_leaf': 72, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

0:	learn: 0.8381060	total: 5.32ms	remaining: 3.15s
50:	learn: 0.8451533	total: 185ms	remaining: 1.97s
100:	learn: 0.8679688	total: 369ms	remaining: 1.8s
150:	learn: 0.8797598	total: 730ms	remaining: 2.14s
200:	learn: 0.8918074	total: 958ms	remaining: 1.87s
250:	learn: 0.8979611	total: 1.16s	remaining: 1.58s
300:	learn: 0.9030450	total: 1.36s	remaining: 1.33s
350:	learn: 0.9086967	total: 1.6s	remaining: 1.11s
400:	learn: 0.9116955	total: 1.86s	remaining: 897ms
450:	learn: 0.9147802	total: 2.09s	remaining: 663ms
500:	learn: 0.9180712	total: 2.34s	remaining: 434ms
550:	learn: 0.9199667	total: 2.6s	remaining: 203ms
593:	learn: 0.9217929	total: 2.87s	remaining: 0us
0:	learn: 0.8381060	total: 5.5ms	remaining: 3.26s
50:	learn: 0.8418969	total: 208ms	remaining: 2.21s
100:	learn: 0.8653326	total: 457ms	remaining: 2.23s
150:	learn: 0.8787245	total: 679ms	remaining: 1.99s
200:	learn: 0.8893251	total: 897ms	remaining: 1.75s
250:	learn: 0.8974424	total: 1.12s	remaining: 1.53s
300:	learn: 0.9000808	total: 1.33s	remaining: 1.3s
350:	learn: 0.9056812	total: 1.53s	remaining: 1.06s
400:	learn: 0.9098514	total: 1.73s	remaining: 832ms
450:	learn: 0.9134359	total: 1.97s	remaining: 623ms
500:	learn: 0.9167961	total: 2.21s	remaining: 411ms
550:	learn: 0.9173651	total: 2.43s	remaining: 190ms
593:	learn: 0.9214828	total: 2.66s	remaining: 0us
0:	learn: 0.8381060	total: 6.28ms	remaining: 3.72s
50:	learn: 0.8481521	total: 221ms	remaining: 2.35s
100:	learn: 0.8657811	total: 430ms	remaining: 2.1s
150:	learn: 0.8777941	total: 665ms	remaining: 1.95s
200:	learn: 0.8880667	total: 884ms	remaining: 1.73s
250:	learn: 0.8936180	total: 1.09s	remaining: 1.49s
300:	learn: 0.8983572	total: 1.3s	remaining: 1.27s
350:	learn: 0.9010982	total: 1.51s	remaining: 1.04s
400:	learn: 0.9056823	total: 1.71s	remaining: 825ms
450:	learn: 0.9098692	total: 1.92s	remaining: 609ms
500:	learn: 0.9130744	total: 2.12s	remaining: 394ms
550:	learn: 0.9146943	total: 2.34s	remaining: 182ms
593:	learn: 0.9163309	total: 2.52s	remaining: 0us
0:	learn: 0.8381060	total: 4.8ms	remaining: 2.84s
50:	learn: 0.8495299	total: 207ms	remaining: 2.2s
100:	learn: 0.8699859	total: 406ms	remaining: 1.98s
150:	learn: 0.8818962	total: 620ms	remaining: 1.82s
200:	learn: 0.8945105	total: 937ms	remaining: 1.83s
250:	learn: 0.9002682	total: 1.17s	remaining: 1.59s
300:	learn: 0.9051803	total: 1.44s	remaining: 1.4s
350:	learn: 0.9092132	total: 1.74s	remaining: 1.21s
400:	learn: 0.9136590	total: 1.97s	remaining: 948ms
450:	learn: 0.9164514	total: 2.37s	remaining: 752ms
500:	learn: 0.9187953	total: 2.63s	remaining: 488ms
550:	learn: 0.9220685	total: 2.84s	remaining: 222ms
593:	learn: 0.9255481	total: 3.02s	remaining: 0us
0:	learn: 0.8381060	total: 5.65ms	remaining: 3.35s
50:	learn: 0.8486341	total: 251ms	remaining: 2.67s
100:	learn: 0.8679688	total: 479ms	remaining: 2.34s
150:	learn: 0.8796371	total: 700ms	remaining: 2.05s
200:	learn: 0.8894947	total: 924ms	remaining: 1.81s
250:	learn: 0.8967507	total: 1.13s	remaining: 1.54s
300:	learn: 0.9015255	total: 1.35s	remaining: 1.31s
350:	learn: 0.9061442	total: 1.55s	remaining: 1.07s
400:	learn: 0.9097632	total: 1.75s	remaining: 841ms
450:	learn: 0.9140026	total: 1.96s	remaining: 621ms
500:	learn: 0.9161736	total: 2.27s	remaining: 421ms
550:	learn: 0.9202746	total: 2.47s	remaining: 193ms
593:	learn: 0.9217048	total: 2.66s	remaining: 0us

[I 2025-11-24 20:25:17,386] Trial 57 finished with value: 0.6757807190592423 and parameters: {'weight_pos': 1.2870366218800346, 'iterations': 594, 'learning_rate': 0.024127892491304533, 'depth': 3, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 2.2296090192003522e-05, 'bagging_temperature': 0.6014102681557811, 'rsm': 0.5531753793768366, 'min_data_in_leaf': 40, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 4.96ms	remaining: 3.99s
50:	total: 182ms	remaining: 2.69s
100:	total: 342ms	remaining: 2.39s
150:	total: 506ms	remaining: 2.2s
200:	total: 810ms	remaining: 2.44s
250:	total: 1.09s	remaining: 2.41s
300:	total: 1.31s	remaining: 2.21s
350:	total: 1.52s	remaining: 1.98s
400:	total: 1.79s	remaining: 1.81s
450:	total: 2.04s	remaining: 1.61s
500:	total: 2.28s	remaining: 1.39s
550:	total: 2.47s	remaining: 1.15s
600:	total: 2.65s	remaining: 908ms
650:	total: 2.83s	remaining: 679ms
700:	total: 3.01s	remaining: 455ms
750:	total: 3.19s	remaining: 238ms
800:	total: 3.38s	remaining: 25.3ms
806:	total: 3.4s	remaining: 0us
0:	total: 4.73ms	remaining: 3.81s
50:	total: 184ms	remaining: 2.73s
100:	total: 366ms	remaining: 2.56s
150:	total: 544ms	remaining: 2.37s
200:	total: 725ms	remaining: 2.19s
250:	total: 939ms	remaining: 2.08s
300:	total: 1.14s	remaining: 1.91s
350:	total: 1.31s	remaining: 1.7s
400:	total: 1.48s	remaining: 1.5s
450:	total: 1.65s	remaining: 1.3s
500:	total: 1.86s	remaining: 1.14s
550:	total: 2.06s	remaining: 957ms
600:	total: 2.24s	remaining: 766ms
650:	total: 2.41s	remaining: 577ms
700:	total: 2.58s	remaining: 391ms
750:	total: 2.95s	remaining: 220ms
800:	total: 3.16s	remaining: 23.7ms
806:	total: 3.18s	remaining: 0us
0:	total: 4.14ms	remaining: 3.33s
50:	total: 191ms	remaining: 2.83s
100:	total: 357ms	remaining: 2.5s
150:	total: 531ms	remaining: 2.31s
200:	total: 707ms	remaining: 2.13s
250:	total: 887ms	remaining: 1.96s
300:	total: 1.05s	remaining: 1.77s
350:	total: 1.22s	remaining: 1.59s
400:	total: 1.39s	remaining: 1.41s
450:	total: 1.56s	remaining: 1.23s
500:	total: 1.72s	remaining: 1.05s
550:	total: 1.9s	remaining: 883ms
600:	total: 2.07s	remaining: 710ms
650:	total: 2.25s	remaining: 539ms
700:	total: 2.44s	remaining: 369ms
750:	total: 2.62s	remaining: 195ms
800:	total: 2.85s	remaining: 21.3ms
806:	total: 2.87s	remaining: 0us
0:	total: 4.59ms	remaining: 3.7s
50:	total: 176ms	remaining: 2.6s
100:	total: 351ms	remaining: 2.45s
150:	total: 521ms	remaining: 2.26s
200:	total: 734ms	remaining: 2.21s
250:	total: 946ms	remaining: 2.1s
300:	total: 1.21s	remaining: 2.03s
350:	total: 1.4s	remaining: 1.82s
400:	total: 1.61s	remaining: 1.63s
450:	total: 1.83s	remaining: 1.44s
500:	total: 2.04s	remaining: 1.24s
550:	total: 2.24s	remaining: 1.04s
600:	total: 2.45s	remaining: 839ms
650:	total: 2.66s	remaining: 637ms
700:	total: 2.87s	remaining: 433ms
750:	total: 3.06s	remaining: 228ms
800:	total: 3.26s	remaining: 24.4ms
806:	total: 3.28s	remaining: 0us
0:	total: 4.57ms	remaining: 3.69s
50:	total: 208ms	remaining: 3.08s
100:	total: 426ms	remaining: 2.98s
150:	total: 673ms	remaining: 2.92s
200:	total: 867ms	remaining: 2.61s
250:	total: 1.06s	remaining: 2.35s
300:	total: 1.25s	remaining: 2.1s
350:	total: 1.43s	remaining: 1.86s
400:	total: 1.6s	remaining: 1.62s
450:	total: 1.78s	remaining: 1.41s
500:	total: 1.94s	remaining: 1.19s
550:	total: 2.13s	remaining: 989ms
600:	total: 2.32s	remaining: 795ms
650:	total: 2.49s	remaining: 597ms
700:	total: 2.67s	remaining: 403ms
750:	total: 2.83s	remaining: 211ms

[I 2025-11-24 20:25:33,831] Trial 58 finished with value: 0.7121226721230534 and parameters: {'weight_pos': 1.6365450596811162, 'iterations': 807, 'learning_rate': 0.02774184945204503, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.00019763612005596395, 'bagging_temperature': 0.4806157491228341, 'rsm': 0.30543854174263485, 'min_data_in_leaf': 81, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

800:	total: 3.04s	remaining: 22.8ms
806:	total: 3.1s	remaining: 0us
0:	total: 2.67ms	remaining: 1.98s
50:	total: 319ms	remaining: 4.32s
100:	total: 615ms	remaining: 3.9s
150:	total: 908ms	remaining: 3.55s
200:	total: 1.28s	remaining: 3.45s
250:	total: 1.6s	remaining: 3.13s
300:	total: 1.91s	remaining: 2.8s
350:	total: 2.25s	remaining: 2.51s
400:	total: 2.58s	remaining: 2.19s
450:	total: 2.94s	remaining: 1.89s
500:	total: 3.26s	remaining: 1.57s
550:	total: 3.6s	remaining: 1.25s
600:	total: 3.93s	remaining: 921ms
650:	total: 4.29s	remaining: 599ms
700:	total: 4.64s	remaining: 272ms
741:	total: 4.91s	remaining: 0us
0:	total: 2.4ms	remaining: 1.78s
50:	total: 269ms	remaining: 3.65s
100:	total: 558ms	remaining: 3.54s
150:	total: 848ms	remaining: 3.32s
200:	total: 1.15s	remaining: 3.09s
250:	total: 1.45s	remaining: 2.83s
300:	total: 1.74s	remaining: 2.55s
350:	total: 2.05s	remaining: 2.28s
400:	total: 2.36s	remaining: 2s
450:	total: 2.65s	remaining: 1.71s
500:	total: 3s	remaining: 1.44s
550:	total: 3.35s	remaining: 1.16s
600:	total: 3.74s	remaining: 877ms
650:	total: 4.14s	remaining: 579ms
700:	total: 4.51s	remaining: 264ms
741:	total: 5.18s	remaining: 0us
0:	total: 4.9ms	remaining: 3.63s
50:	total: 492ms	remaining: 6.66s
100:	total: 917ms	remaining: 5.82s
150:	total: 1.3s	remaining: 5.08s
200:	total: 1.63s	remaining: 4.39s
250:	total: 1.95s	remaining: 3.81s
300:	total: 2.28s	remaining: 3.34s
350:	total: 2.61s	remaining: 2.91s
400:	total: 2.94s	remaining: 2.5s
450:	total: 3.29s	remaining: 2.12s
500:	total: 3.66s	remaining: 1.76s
550:	total: 3.99s	remaining: 1.38s
600:	total: 4.32s	remaining: 1.01s
650:	total: 4.7s	remaining: 657ms
700:	total: 5.1s	remaining: 298ms
741:	total: 5.48s	remaining: 0us
0:	total: 3.88ms	remaining: 2.88s
50:	total: 410ms	remaining: 5.55s
100:	total: 768ms	remaining: 4.88s
150:	total: 1.1s	remaining: 4.3s
200:	total: 1.43s	remaining: 3.84s
250:	total: 1.75s	remaining: 3.43s
300:	total: 2.07s	remaining: 3.03s
350:	total: 2.38s	remaining: 2.65s
400:	total: 2.71s	remaining: 2.3s
450:	total: 3.06s	remaining: 1.98s
500:	total: 3.56s	remaining: 1.71s
550:	total: 4.14s	remaining: 1.44s
600:	total: 4.58s	remaining: 1.07s
650:	total: 4.9s	remaining: 685ms
700:	total: 5.23s	remaining: 306ms
741:	total: 5.5s	remaining: 0us
0:	total: 3.73ms	remaining: 2.76s
50:	total: 309ms	remaining: 4.18s
100:	total: 619ms	remaining: 3.93s
150:	total: 940ms	remaining: 3.68s
200:	total: 1.24s	remaining: 3.34s
250:	total: 1.55s	remaining: 3.03s
300:	total: 1.85s	remaining: 2.72s
350:	total: 2.16s	remaining: 2.4s
400:	total: 2.46s	remaining: 2.1s
450:	total: 2.79s	remaining: 1.8s
500:	total: 3.11s	remaining: 1.5s
550:	total: 3.48s	remaining: 1.21s
600:	total: 3.81s	remaining: 894ms
650:	total: 4.13s	remaining: 577ms
700:	total: 4.44s	remaining: 260ms

[I 2025-11-24 20:26:00,277] Trial 59 finished with value: 0.5849396450763187 and parameters: {'weight_pos': 49.71209836617597, 'iterations': 742, 'learning_rate': 0.041242802724226715, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.0003546276146674842, 'bagging_temperature': 0.6196897604887425, 'rsm': 0.6361845909096808, 'min_data_in_leaf': 53, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

741:	total: 4.71s	remaining: 0us
0:	total: 6.11ms	remaining: 4.15s
50:	total: 231ms	remaining: 2.84s
100:	total: 479ms	remaining: 2.75s
150:	total: 723ms	remaining: 2.53s
200:	total: 959ms	remaining: 2.29s
250:	total: 1.21s	remaining: 2.06s
300:	total: 1.46s	remaining: 1.84s
350:	total: 1.71s	remaining: 1.6s
400:	total: 1.96s	remaining: 1.36s
450:	total: 2.2s	remaining: 1.12s
500:	total: 2.53s	remaining: 903ms
550:	total: 2.82s	remaining: 660ms
600:	total: 3.11s	remaining: 409ms
650:	total: 3.76s	remaining: 167ms
679:	total: 3.91s	remaining: 0us
0:	total: 5.57ms	remaining: 3.78s
50:	total: 243ms	remaining: 3s
100:	total: 490ms	remaining: 2.81s
150:	total: 788ms	remaining: 2.76s
200:	total: 1.03s	remaining: 2.44s
250:	total: 1.28s	remaining: 2.18s
300:	total: 1.52s	remaining: 1.91s
350:	total: 1.76s	remaining: 1.65s
400:	total: 2.01s	remaining: 1.4s
450:	total: 2.24s	remaining: 1.14s
500:	total: 2.48s	remaining: 886ms
550:	total: 2.71s	remaining: 635ms
600:	total: 2.94s	remaining: 387ms
650:	total: 3.2s	remaining: 143ms
679:	total: 3.34s	remaining: 0us
0:	total: 8.59ms	remaining: 5.83s
50:	total: 240ms	remaining: 2.96s
100:	total: 485ms	remaining: 2.78s
150:	total: 755ms	remaining: 2.64s
200:	total: 1.05s	remaining: 2.49s
250:	total: 1.29s	remaining: 2.21s
300:	total: 1.53s	remaining: 1.92s
350:	total: 1.79s	remaining: 1.68s
400:	total: 2.03s	remaining: 1.41s
450:	total: 2.27s	remaining: 1.15s
500:	total: 2.5s	remaining: 895ms
550:	total: 2.74s	remaining: 642ms
600:	total: 2.98s	remaining: 391ms
650:	total: 3.23s	remaining: 144ms
679:	total: 3.37s	remaining: 0us
0:	total: 5.98ms	remaining: 4.06s
50:	total: 229ms	remaining: 2.82s
100:	total: 460ms	remaining: 2.64s
150:	total: 688ms	remaining: 2.41s
200:	total: 979ms	remaining: 2.33s
250:	total: 1.22s	remaining: 2.08s
300:	total: 1.46s	remaining: 1.84s
350:	total: 1.7s	remaining: 1.59s
400:	total: 1.94s	remaining: 1.35s
450:	total: 2.18s	remaining: 1.11s
500:	total: 2.55s	remaining: 913ms
550:	total: 3s	remaining: 702ms
600:	total: 3.38s	remaining: 444ms
650:	total: 3.65s	remaining: 163ms
679:	total: 3.8s	remaining: 0us
0:	total: 6.54ms	remaining: 4.44s
50:	total: 252ms	remaining: 3.11s
100:	total: 495ms	remaining: 2.84s
150:	total: 731ms	remaining: 2.56s
200:	total: 1.02s	remaining: 2.44s
250:	total: 1.27s	remaining: 2.18s
300:	total: 1.52s	remaining: 1.92s
350:	total: 1.76s	remaining: 1.65s
400:	total: 1.99s	remaining: 1.39s
450:	total: 2.22s	remaining: 1.13s
500:	total: 2.45s	remaining: 875ms
550:	total: 2.68s	remaining: 628ms
600:	total: 2.91s	remaining: 383ms

[I 2025-11-24 20:26:18,510] Trial 60 finished with value: 0.6336792564476175 and parameters: {'weight_pos': 8.15969948783037, 'iterations': 680, 'learning_rate': 0.033575593474718425, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 8.835119991028531e-05, 'bagging_temperature': 0.3359085059735716, 'rsm': 0.8099142671514457, 'min_data_in_leaf': 26, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

650:	total: 3.16s	remaining: 141ms
679:	total: 3.29s	remaining: 0us
0:	total: 6.56ms	remaining: 6.02s
50:	total: 306ms	remaining: 5.21s
100:	total: 613ms	remaining: 4.96s
150:	total: 900ms	remaining: 4.57s
200:	total: 1.19s	remaining: 4.26s
250:	total: 1.49s	remaining: 3.97s
300:	total: 1.8s	remaining: 3.69s
350:	total: 2.13s	remaining: 3.44s
400:	total: 2.44s	remaining: 3.14s
450:	total: 2.77s	remaining: 2.87s
500:	total: 3.14s	remaining: 2.62s
550:	total: 3.46s	remaining: 2.3s
600:	total: 3.78s	remaining: 2s
650:	total: 4.09s	remaining: 1.68s
700:	total: 4.41s	remaining: 1.36s
750:	total: 4.73s	remaining: 1.05s
800:	total: 5.06s	remaining: 739ms
850:	total: 5.6s	remaining: 441ms
900:	total: 5.92s	remaining: 112ms
917:	total: 6.03s	remaining: 0us
0:	total: 6.89ms	remaining: 6.32s
50:	total: 297ms	remaining: 5.04s
100:	total: 601ms	remaining: 4.86s
150:	total: 916ms	remaining: 4.65s
200:	total: 1.25s	remaining: 4.44s
250:	total: 1.57s	remaining: 4.17s
300:	total: 1.9s	remaining: 3.89s
350:	total: 2.25s	remaining: 3.63s
400:	total: 2.59s	remaining: 3.33s
450:	total: 2.91s	remaining: 3.01s
500:	total: 3.24s	remaining: 2.7s
550:	total: 3.56s	remaining: 2.37s
600:	total: 3.88s	remaining: 2.04s
650:	total: 4.29s	remaining: 1.76s
700:	total: 4.62s	remaining: 1.43s
750:	total: 4.93s	remaining: 1.1s
800:	total: 5.35s	remaining: 782ms
850:	total: 5.91s	remaining: 465ms
900:	total: 6.32s	remaining: 119ms
917:	total: 6.45s	remaining: 0us
0:	total: 7.56ms	remaining: 6.93s
50:	total: 320ms	remaining: 5.45s
100:	total: 673ms	remaining: 5.44s
150:	total: 1.09s	remaining: 5.56s
200:	total: 1.49s	remaining: 5.31s
250:	total: 1.79s	remaining: 4.75s
300:	total: 2.1s	remaining: 4.29s
350:	total: 2.6s	remaining: 4.19s
400:	total: 2.94s	remaining: 3.79s
450:	total: 3.26s	remaining: 3.38s
500:	total: 3.61s	remaining: 3.01s
550:	total: 3.95s	remaining: 2.63s
600:	total: 4.26s	remaining: 2.25s
650:	total: 4.57s	remaining: 1.87s
700:	total: 4.9s	remaining: 1.52s
750:	total: 5.23s	remaining: 1.16s
800:	total: 5.53s	remaining: 808ms
850:	total: 5.83s	remaining: 459ms
900:	total: 6.15s	remaining: 116ms
917:	total: 6.25s	remaining: 0us
0:	total: 8.33ms	remaining: 7.64s
50:	total: 469ms	remaining: 7.97s
100:	total: 787ms	remaining: 6.37s
150:	total: 1.09s	remaining: 5.56s
200:	total: 1.41s	remaining: 5.04s
250:	total: 1.72s	remaining: 4.56s
300:	total: 2.06s	remaining: 4.22s
350:	total: 2.37s	remaining: 3.82s
400:	total: 2.7s	remaining: 3.48s
450:	total: 3.03s	remaining: 3.14s
500:	total: 3.35s	remaining: 2.79s
550:	total: 3.67s	remaining: 2.44s
600:	total: 4s	remaining: 2.11s
650:	total: 4.33s	remaining: 1.77s
700:	total: 4.64s	remaining: 1.44s
750:	total: 4.97s	remaining: 1.1s
800:	total: 5.29s	remaining: 773ms
850:	total: 5.61s	remaining: 442ms
900:	total: 6.09s	remaining: 115ms
917:	total: 6.28s	remaining: 0us
0:	total: 7.58ms	remaining: 6.95s
50:	total: 319ms	remaining: 5.42s
100:	total: 632ms	remaining: 5.11s
150:	total: 947ms	remaining: 4.81s
200:	total: 1.29s	remaining: 4.6s
250:	total: 1.62s	remaining: 4.32s
300:	total: 1.97s	remaining: 4.04s
350:	total: 2.32s	remaining: 3.75s
400:	total: 2.69s	remaining: 3.47s
450:	total: 3.05s	remaining: 3.16s
500:	total: 3.4s	remaining: 2.83s
550:	total: 3.72s	remaining: 2.48s
600:	total: 4.04s	remaining: 2.13s
650:	total: 4.35s	remaining: 1.78s
700:	total: 4.68s	remaining: 1.45s
750:	total: 5.01s	remaining: 1.11s
800:	total: 5.34s	remaining: 780ms
850:	total: 5.65s	remaining: 445ms

[I 2025-11-24 20:26:50,384] Trial 61 finished with value: 0.7349146648249685 and parameters: {'weight_pos': 2.0961173232556276, 'iterations': 918, 'learning_rate': 0.046179182700535754, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.1154236400728657, 'bagging_temperature': 0.5461275175905421, 'rsm': 0.421231309858886, 'min_data_in_leaf': 33, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 5.97s	remaining: 113ms
917:	total: 6.08s	remaining: 0us
0:	total: 6.76ms	remaining: 3.39s
50:	total: 259ms	remaining: 2.3s
100:	total: 525ms	remaining: 2.09s
150:	total: 782ms	remaining: 1.82s
200:	total: 1.04s	remaining: 1.56s
250:	total: 1.29s	remaining: 1.29s
300:	total: 1.55s	remaining: 1.04s
350:	total: 1.81s	remaining: 783ms
400:	total: 2.07s	remaining: 526ms
450:	total: 2.33s	remaining: 268ms
500:	total: 2.59s	remaining: 10.3ms
502:	total: 2.6s	remaining: 0us
0:	total: 7.1ms	remaining: 3.57s
50:	total: 254ms	remaining: 2.25s
100:	total: 508ms	remaining: 2.02s
150:	total: 958ms	remaining: 2.23s
200:	total: 1.27s	remaining: 1.91s
250:	total: 1.53s	remaining: 1.54s
300:	total: 1.79s	remaining: 1.2s
350:	total: 2.06s	remaining: 893ms
400:	total: 2.32s	remaining: 590ms
450:	total: 2.6s	remaining: 300ms
500:	total: 2.9s	remaining: 11.6ms
502:	total: 2.91s	remaining: 0us
0:	total: 6.2ms	remaining: 3.11s
50:	total: 270ms	remaining: 2.4s
100:	total: 523ms	remaining: 2.08s
150:	total: 772ms	remaining: 1.8s
200:	total: 1.03s	remaining: 1.54s
250:	total: 1.28s	remaining: 1.28s
300:	total: 1.52s	remaining: 1.02s
350:	total: 1.77s	remaining: 767ms
400:	total: 2.02s	remaining: 514ms
450:	total: 2.28s	remaining: 263ms
500:	total: 2.53s	remaining: 10.1ms
502:	total: 2.54s	remaining: 0us
0:	total: 5.53ms	remaining: 2.77s
50:	total: 260ms	remaining: 2.3s
100:	total: 518ms	remaining: 2.06s
150:	total: 802ms	remaining: 1.87s
200:	total: 1.06s	remaining: 1.59s
250:	total: 1.3s	remaining: 1.3s
300:	total: 1.57s	remaining: 1.05s
350:	total: 1.82s	remaining: 789ms
400:	total: 2.08s	remaining: 529ms
450:	total: 2.34s	remaining: 270ms
500:	total: 2.62s	remaining: 10.4ms
502:	total: 2.63s	remaining: 0us
0:	total: 7.19ms	remaining: 3.61s
50:	total: 249ms	remaining: 2.21s
100:	total: 504ms	remaining: 2.01s
150:	total: 779ms	remaining: 1.82s
200:	total: 1.03s	remaining: 1.54s
250:	total: 1.3s	remaining: 1.31s
300:	total: 1.56s	remaining: 1.05s
350:	total: 1.82s	remaining: 789ms
400:	total: 2.08s	remaining: 528ms
450:	total: 2.6s	remaining: 300ms

[I 2025-11-24 20:27:04,413] Trial 62 finished with value: 0.7261250807650089 and parameters: {'weight_pos': 1.9656294062703583, 'iterations': 503, 'learning_rate': 0.04622804994411007, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.4501907543537165, 'bagging_temperature': 0.545331714355479, 'rsm': 0.5210992815693145, 'min_data_in_leaf': 30, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

500:	total: 2.88s	remaining: 11.5ms
502:	total: 2.89s	remaining: 0us
0:	total: 5.05ms	remaining: 4.43s
50:	total: 283ms	remaining: 4.58s
100:	total: 605ms	remaining: 4.65s
150:	total: 875ms	remaining: 4.21s
200:	total: 1.16s	remaining: 3.9s
250:	total: 1.46s	remaining: 3.65s
300:	total: 1.77s	remaining: 3.39s
350:	total: 2.07s	remaining: 3.11s
400:	total: 2.37s	remaining: 2.82s
450:	total: 2.68s	remaining: 2.54s
500:	total: 2.98s	remaining: 2.24s
550:	total: 3.28s	remaining: 1.95s
600:	total: 3.58s	remaining: 1.65s
650:	total: 3.88s	remaining: 1.35s
700:	total: 4.2s	remaining: 1.06s
750:	total: 4.48s	remaining: 758ms
800:	total: 4.77s	remaining: 458ms
850:	total: 5.13s	remaining: 163ms
877:	total: 5.29s	remaining: 0us
0:	total: 8.48ms	remaining: 7.44s
50:	total: 285ms	remaining: 4.62s
100:	total: 566ms	remaining: 4.36s
150:	total: 838ms	remaining: 4.03s
200:	total: 1.14s	remaining: 3.83s
250:	total: 1.43s	remaining: 3.58s
300:	total: 1.71s	remaining: 3.27s
350:	total: 1.98s	remaining: 2.98s
400:	total: 2.26s	remaining: 2.69s
450:	total: 2.55s	remaining: 2.41s
500:	total: 2.83s	remaining: 2.13s
550:	total: 3.11s	remaining: 1.84s
600:	total: 3.4s	remaining: 1.57s
650:	total: 3.73s	remaining: 1.3s
700:	total: 4.24s	remaining: 1.07s
750:	total: 4.56s	remaining: 772ms
800:	total: 5.06s	remaining: 486ms
850:	total: 5.49s	remaining: 174ms
877:	total: 5.71s	remaining: 0us
0:	total: 7.5ms	remaining: 6.57s
50:	total: 357ms	remaining: 5.79s
100:	total: 706ms	remaining: 5.43s
150:	total: 1.02s	remaining: 4.93s
200:	total: 1.32s	remaining: 4.44s
250:	total: 1.63s	remaining: 4.08s
300:	total: 1.94s	remaining: 3.73s
350:	total: 2.26s	remaining: 3.39s
400:	total: 2.56s	remaining: 3.05s
450:	total: 2.87s	remaining: 2.71s
500:	total: 3.16s	remaining: 2.38s
550:	total: 3.46s	remaining: 2.05s
600:	total: 3.75s	remaining: 1.73s
650:	total: 4.09s	remaining: 1.43s
700:	total: 4.42s	remaining: 1.11s
750:	total: 4.71s	remaining: 797ms
800:	total: 5.01s	remaining: 482ms
850:	total: 5.34s	remaining: 169ms
877:	total: 5.5s	remaining: 0us
0:	total: 9.26ms	remaining: 8.12s
50:	total: 446ms	remaining: 7.23s
100:	total: 737ms	remaining: 5.67s
150:	total: 1.01s	remaining: 4.89s
200:	total: 1.31s	remaining: 4.41s
250:	total: 1.61s	remaining: 4.03s
300:	total: 1.92s	remaining: 3.67s
350:	total: 2.2s	remaining: 3.3s
400:	total: 2.69s	remaining: 3.2s
450:	total: 3.05s	remaining: 2.89s
500:	total: 3.36s	remaining: 2.53s
550:	total: 3.65s	remaining: 2.16s
600:	total: 3.96s	remaining: 1.83s
650:	total: 4.25s	remaining: 1.48s
700:	total: 4.54s	remaining: 1.15s
750:	total: 4.86s	remaining: 823ms
800:	total: 5.17s	remaining: 497ms
850:	total: 5.49s	remaining: 174ms
877:	total: 5.65s	remaining: 0us
0:	total: 5.7ms	remaining: 5s
50:	total: 310ms	remaining: 5.02s
100:	total: 599ms	remaining: 4.61s
150:	total: 909ms	remaining: 4.37s
200:	total: 1.21s	remaining: 4.08s
250:	total: 1.5s	remaining: 3.75s
300:	total: 1.79s	remaining: 3.43s
350:	total: 2.08s	remaining: 3.12s
400:	total: 2.36s	remaining: 2.81s
450:	total: 2.69s	remaining: 2.54s
500:	total: 2.96s	remaining: 2.23s
550:	total: 3.25s	remaining: 1.93s
600:	total: 3.56s	remaining: 1.64s
650:	total: 3.89s	remaining: 1.36s
700:	total: 4.21s	remaining: 1.06s
750:	total: 4.51s	remaining: 762ms
800:	total: 4.82s	remaining: 463ms

[I 2025-11-24 20:27:32,505] Trial 63 finished with value: 0.7361121487875515 and parameters: {'weight_pos': 2.720787888737355, 'iterations': 878, 'learning_rate': 0.06875616265477431, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.6366941003870714, 'bagging_temperature': 0.4148608082377011, 'rsm': 0.5859406559305091, 'min_data_in_leaf': 35, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

850:	total: 5.12s	remaining: 162ms
877:	total: 5.28s	remaining: 0us
0:	total: 10.5ms	remaining: 10.1s
50:	total: 519ms	remaining: 9.33s
100:	total: 1.01s	remaining: 8.7s
150:	total: 1.81s	remaining: 9.77s
200:	total: 2.3s	remaining: 8.77s
250:	total: 2.82s	remaining: 8.06s
300:	total: 3.3s	remaining: 7.31s
350:	total: 3.79s	remaining: 6.66s
400:	total: 4.31s	remaining: 6.1s
450:	total: 4.82s	remaining: 5.53s
500:	total: 5.35s	remaining: 4.98s
550:	total: 5.97s	remaining: 4.52s
600:	total: 6.5s	remaining: 3.97s
650:	total: 7s	remaining: 3.41s
700:	total: 7.54s	remaining: 2.87s
750:	total: 8.05s	remaining: 2.33s
800:	total: 8.55s	remaining: 1.78s
850:	total: 9.04s	remaining: 1.24s
900:	total: 9.53s	remaining: 708ms
950:	total: 10s	remaining: 179ms
967:	total: 10.2s	remaining: 0us
0:	total: 10.9ms	remaining: 10.6s
50:	total: 477ms	remaining: 8.57s
100:	total: 1.14s	remaining: 9.78s
150:	total: 1.67s	remaining: 9.02s
200:	total: 2.14s	remaining: 8.17s
250:	total: 2.59s	remaining: 7.41s
300:	total: 3.06s	remaining: 6.78s
350:	total: 3.53s	remaining: 6.21s
400:	total: 4.02s	remaining: 5.68s
450:	total: 4.51s	remaining: 5.17s
500:	total: 5.06s	remaining: 4.71s
550:	total: 5.57s	remaining: 4.22s
600:	total: 6.11s	remaining: 3.73s
650:	total: 6.64s	remaining: 3.23s
700:	total: 7.19s	remaining: 2.74s
750:	total: 7.68s	remaining: 2.22s
800:	total: 8.17s	remaining: 1.7s
850:	total: 8.66s	remaining: 1.19s
900:	total: 9.21s	remaining: 685ms
950:	total: 9.71s	remaining: 174ms
967:	total: 9.88s	remaining: 0us
0:	total: 9.15ms	remaining: 8.85s
50:	total: 477ms	remaining: 8.57s
100:	total: 1.1s	remaining: 9.42s
150:	total: 1.59s	remaining: 8.61s
200:	total: 2.15s	remaining: 8.21s
250:	total: 2.63s	remaining: 7.53s
300:	total: 3.15s	remaining: 6.98s
350:	total: 3.63s	remaining: 6.39s
400:	total: 4.12s	remaining: 5.83s
450:	total: 4.68s	remaining: 5.37s
500:	total: 5.36s	remaining: 5s
550:	total: 5.86s	remaining: 4.44s
600:	total: 6.37s	remaining: 3.89s
650:	total: 6.99s	remaining: 3.4s
700:	total: 7.59s	remaining: 2.89s
750:	total: 8.13s	remaining: 2.35s
800:	total: 8.66s	remaining: 1.81s
850:	total: 9.18s	remaining: 1.26s
900:	total: 9.69s	remaining: 720ms
950:	total: 10.2s	remaining: 183ms
967:	total: 10.4s	remaining: 0us
0:	total: 10ms	remaining: 9.68s
50:	total: 804ms	remaining: 14.5s
100:	total: 1.28s	remaining: 11s
150:	total: 2.03s	remaining: 11s
200:	total: 2.6s	remaining: 9.93s
250:	total: 3.13s	remaining: 8.95s
300:	total: 3.67s	remaining: 8.13s
350:	total: 4.19s	remaining: 7.37s
400:	total: 4.7s	remaining: 6.65s
450:	total: 5.29s	remaining: 6.06s
500:	total: 5.8s	remaining: 5.41s
550:	total: 6.62s	remaining: 5.01s
600:	total: 7.25s	remaining: 4.42s
650:	total: 7.79s	remaining: 3.79s
700:	total: 8.3s	remaining: 3.16s
750:	total: 8.79s	remaining: 2.54s
800:	total: 9.31s	remaining: 1.94s
850:	total: 9.81s	remaining: 1.35s
900:	total: 10.6s	remaining: 785ms
950:	total: 11.2s	remaining: 199ms
967:	total: 11.3s	remaining: 0us
0:	total: 12.2ms	remaining: 11.8s
50:	total: 556ms	remaining: 9.99s
100:	total: 1.28s	remaining: 11s
150:	total: 1.83s	remaining: 9.9s
200:	total: 2.37s	remaining: 9.03s
250:	total: 2.9s	remaining: 8.28s
300:	total: 3.44s	remaining: 7.63s
350:	total: 3.96s	remaining: 6.97s
400:	total: 4.46s	remaining: 6.31s
450:	total: 5.06s	remaining: 5.8s
500:	total: 5.6s	remaining: 5.22s
550:	total: 6.13s	remaining: 4.64s
600:	total: 6.64s	remaining: 4.05s
650:	total: 7.18s	remaining: 3.49s
700:	total: 7.71s	remaining: 2.94s
750:	total: 8.26s	remaining: 2.38s
800:	total: 9.01s	remaining: 1.88s
850:	total: 9.54s	remaining: 1.31s
900:	total: 10.1s	remaining: 749ms
950:	total: 10.6s	remaining: 189ms

[I 2025-11-24 20:28:25,956] Trial 64 finished with value: 0.7279218905310828 and parameters: {'weight_pos': 2.7111493244421534, 'iterations': 968, 'learning_rate': 0.07019020579764891, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.3868331356969128, 'bagging_temperature': 0.39998376185583906, 'rsm': 0.9935756120761047, 'min_data_in_leaf': 34, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

967:	total: 10.9s	remaining: 0us
0:	total: 9.7ms	remaining: 8.94s
50:	total: 317ms	remaining: 5.41s
100:	total: 651ms	remaining: 5.29s
150:	total: 1.01s	remaining: 5.16s
200:	total: 1.36s	remaining: 4.88s
250:	total: 1.69s	remaining: 4.52s
300:	total: 2.07s	remaining: 4.27s
350:	total: 2.49s	remaining: 4.04s
400:	total: 2.85s	remaining: 3.7s
450:	total: 3.16s	remaining: 3.3s
500:	total: 3.48s	remaining: 2.92s
550:	total: 3.85s	remaining: 2.59s
600:	total: 4.18s	remaining: 2.23s
650:	total: 4.48s	remaining: 1.87s
700:	total: 4.84s	remaining: 1.52s
750:	total: 5.15s	remaining: 1.17s
800:	total: 5.48s	remaining: 828ms
850:	total: 5.8s	remaining: 484ms
900:	total: 6.12s	remaining: 143ms
921:	total: 6.25s	remaining: 0us
0:	total: 8.07ms	remaining: 7.44s
50:	total: 321ms	remaining: 5.47s
100:	total: 656ms	remaining: 5.33s
150:	total: 973ms	remaining: 4.97s
200:	total: 1.3s	remaining: 4.67s
250:	total: 1.87s	remaining: 5s
300:	total: 2.2s	remaining: 4.53s
350:	total: 2.52s	remaining: 4.1s
400:	total: 2.89s	remaining: 3.76s
450:	total: 3.25s	remaining: 3.39s
500:	total: 3.6s	remaining: 3.02s
550:	total: 3.96s	remaining: 2.67s
600:	total: 4.37s	remaining: 2.33s
650:	total: 4.75s	remaining: 1.98s
700:	total: 5.31s	remaining: 1.68s
750:	total: 5.79s	remaining: 1.32s
800:	total: 6.18s	remaining: 934ms
850:	total: 6.51s	remaining: 543ms
900:	total: 6.83s	remaining: 159ms
921:	total: 6.97s	remaining: 0us
0:	total: 8.63ms	remaining: 7.95s
50:	total: 340ms	remaining: 5.8s
100:	total: 662ms	remaining: 5.38s
150:	total: 970ms	remaining: 4.95s
200:	total: 1.32s	remaining: 4.72s
250:	total: 1.62s	remaining: 4.33s
300:	total: 1.95s	remaining: 4.01s
350:	total: 2.25s	remaining: 3.67s
400:	total: 2.6s	remaining: 3.38s
450:	total: 2.91s	remaining: 3.04s
500:	total: 3.21s	remaining: 2.7s
550:	total: 3.6s	remaining: 2.42s
600:	total: 3.96s	remaining: 2.11s
650:	total: 4.62s	remaining: 1.92s
700:	total: 5.05s	remaining: 1.59s
750:	total: 5.48s	remaining: 1.25s
800:	total: 5.82s	remaining: 879ms
850:	total: 6.16s	remaining: 514ms
900:	total: 6.52s	remaining: 152ms
921:	total: 6.65s	remaining: 0us
0:	total: 9.07ms	remaining: 8.36s
50:	total: 319ms	remaining: 5.44s
100:	total: 646ms	remaining: 5.25s
150:	total: 979ms	remaining: 5s
200:	total: 1.29s	remaining: 4.62s
250:	total: 1.59s	remaining: 4.25s
300:	total: 1.92s	remaining: 3.95s
350:	total: 2.21s	remaining: 3.6s
400:	total: 2.51s	remaining: 3.26s
450:	total: 2.81s	remaining: 2.93s
500:	total: 3.13s	remaining: 2.63s
550:	total: 3.48s	remaining: 2.34s
600:	total: 3.81s	remaining: 2.04s
650:	total: 4.15s	remaining: 1.73s
700:	total: 4.59s	remaining: 1.45s
750:	total: 5.07s	remaining: 1.15s
800:	total: 5.45s	remaining: 823ms
850:	total: 5.8s	remaining: 484ms
900:	total: 6.12s	remaining: 143ms
921:	total: 6.26s	remaining: 0us
0:	total: 15.3ms	remaining: 14.1s
50:	total: 346ms	remaining: 5.91s
100:	total: 663ms	remaining: 5.39s
150:	total: 969ms	remaining: 4.95s
200:	total: 1.47s	remaining: 5.27s
250:	total: 1.78s	remaining: 4.76s
300:	total: 2.1s	remaining: 4.32s
350:	total: 2.41s	remaining: 3.92s
400:	total: 2.74s	remaining: 3.56s
450:	total: 3.05s	remaining: 3.19s
500:	total: 3.37s	remaining: 2.83s
550:	total: 3.79s	remaining: 2.55s
600:	total: 4.19s	remaining: 2.24s
650:	total: 4.65s	remaining: 1.94s
700:	total: 5.1s	remaining: 1.61s
750:	total: 5.47s	remaining: 1.25s
800:	total: 5.84s	remaining: 882ms
850:	total: 6.17s	remaining: 515ms

[I 2025-11-24 20:28:59,433] Trial 65 finished with value: 0.7246357838840585 and parameters: {'weight_pos': 1.5441649497641494, 'iterations': 922, 'learning_rate': 0.05348569662433085, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.4924815366152831, 'bagging_temperature': 0.4565959961432259, 'rsm': 0.712434865784831, 'min_data_in_leaf': 47, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 6.52s	remaining: 152ms
921:	total: 6.65s	remaining: 0us
0:	total: 6.77ms	remaining: 6.03s
50:	total: 237ms	remaining: 3.9s
100:	total: 522ms	remaining: 4.08s
150:	total: 806ms	remaining: 3.95s
200:	total: 1.03s	remaining: 3.54s
250:	total: 1.26s	remaining: 3.22s
300:	total: 1.5s	remaining: 2.93s
350:	total: 1.76s	remaining: 2.71s
400:	total: 2s	remaining: 2.44s
450:	total: 2.24s	remaining: 2.19s
500:	total: 2.56s	remaining: 1.99s
550:	total: 2.81s	remaining: 1.73s
600:	total: 3.06s	remaining: 1.48s
650:	total: 3.33s	remaining: 1.23s
700:	total: 3.59s	remaining: 973ms
750:	total: 3.82s	remaining: 713ms
800:	total: 4.07s	remaining: 457ms
850:	total: 4.5s	remaining: 212ms
890:	total: 4.84s	remaining: 0us
0:	total: 8.59ms	remaining: 7.64s
50:	total: 341ms	remaining: 5.62s
100:	total: 668ms	remaining: 5.23s
150:	total: 955ms	remaining: 4.68s
200:	total: 1.23s	remaining: 4.23s
250:	total: 1.5s	remaining: 3.81s
300:	total: 1.75s	remaining: 3.43s
350:	total: 1.99s	remaining: 3.06s
400:	total: 2.3s	remaining: 2.81s
450:	total: 2.57s	remaining: 2.51s
500:	total: 2.81s	remaining: 2.18s
550:	total: 3.09s	remaining: 1.91s
600:	total: 3.34s	remaining: 1.61s
650:	total: 3.58s	remaining: 1.32s
700:	total: 3.84s	remaining: 1.04s
750:	total: 4.09s	remaining: 763ms
800:	total: 4.39s	remaining: 494ms
850:	total: 4.7s	remaining: 221ms
890:	total: 4.9s	remaining: 0us
0:	total: 6.13ms	remaining: 5.46s
50:	total: 241ms	remaining: 3.97s
100:	total: 462ms	remaining: 3.62s
150:	total: 689ms	remaining: 3.38s
200:	total: 912ms	remaining: 3.13s
250:	total: 1.14s	remaining: 2.9s
300:	total: 1.39s	remaining: 2.72s
350:	total: 1.69s	remaining: 2.6s
400:	total: 1.92s	remaining: 2.35s
450:	total: 2.16s	remaining: 2.11s
500:	total: 2.41s	remaining: 1.88s
550:	total: 2.66s	remaining: 1.64s
600:	total: 2.91s	remaining: 1.4s
650:	total: 3.18s	remaining: 1.17s
700:	total: 3.59s	remaining: 974ms
750:	total: 4.09s	remaining: 762ms
800:	total: 4.86s	remaining: 546ms
850:	total: 5.13s	remaining: 241ms
890:	total: 5.34s	remaining: 0us
0:	total: 6.45ms	remaining: 5.74s
50:	total: 268ms	remaining: 4.42s
100:	total: 518ms	remaining: 4.05s
150:	total: 753ms	remaining: 3.69s
200:	total: 979ms	remaining: 3.36s
250:	total: 1.3s	remaining: 3.32s
300:	total: 1.58s	remaining: 3.1s
350:	total: 1.82s	remaining: 2.81s
400:	total: 2.08s	remaining: 2.54s
450:	total: 2.31s	remaining: 2.26s
500:	total: 2.66s	remaining: 2.07s
550:	total: 2.93s	remaining: 1.81s
600:	total: 3.16s	remaining: 1.53s
650:	total: 3.4s	remaining: 1.25s
700:	total: 3.63s	remaining: 983ms
750:	total: 3.89s	remaining: 726ms
800:	total: 4.14s	remaining: 465ms
850:	total: 4.39s	remaining: 207ms
890:	total: 4.59s	remaining: 0us
0:	total: 6.95ms	remaining: 6.19s
50:	total: 232ms	remaining: 3.83s
100:	total: 464ms	remaining: 3.63s
150:	total: 689ms	remaining: 3.38s
200:	total: 937ms	remaining: 3.22s
250:	total: 1.17s	remaining: 2.98s
300:	total: 1.4s	remaining: 2.75s
350:	total: 1.68s	remaining: 2.58s
400:	total: 1.9s	remaining: 2.32s
450:	total: 2.13s	remaining: 2.08s
500:	total: 2.36s	remaining: 1.84s
550:	total: 2.58s	remaining: 1.59s
600:	total: 2.81s	remaining: 1.35s
650:	total: 3.03s	remaining: 1.12s
700:	total: 3.25s	remaining: 880ms
750:	total: 3.47s	remaining: 647ms
800:	total: 3.69s	remaining: 415ms
850:	total: 4.04s	remaining: 190ms

[I 2025-11-24 20:29:24,287] Trial 66 finished with value: 0.7172421082445738 and parameters: {'weight_pos': 5.111771990470104, 'iterations': 891, 'learning_rate': 0.06339781945141933, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 5.482038810356322, 'bagging_temperature': 0.26368376669023286, 'rsm': 0.23734391428743873, 'min_data_in_leaf': 37, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

890:	total: 4.38s	remaining: 0us
0:	total: 11.1ms	remaining: 9.73s
50:	total: 589ms	remaining: 9.51s
100:	total: 1.19s	remaining: 9.14s
150:	total: 1.74s	remaining: 8.32s
200:	total: 2.38s	remaining: 7.97s
250:	total: 2.91s	remaining: 7.23s
300:	total: 3.45s	remaining: 6.59s
350:	total: 3.98s	remaining: 5.94s
400:	total: 4.48s	remaining: 5.3s
450:	total: 4.99s	remaining: 4.69s
500:	total: 5.49s	remaining: 4.1s
550:	total: 5.98s	remaining: 3.52s
600:	total: 6.5s	remaining: 2.96s
650:	total: 7.21s	remaining: 2.48s
700:	total: 8.26s	remaining: 2.05s
750:	total: 8.87s	remaining: 1.46s
800:	total: 9.74s	remaining: 900ms
850:	total: 10.3s	remaining: 292ms
874:	total: 10.6s	remaining: 0us
0:	total: 9.59ms	remaining: 8.38s
50:	total: 520ms	remaining: 8.41s
100:	total: 1.05s	remaining: 8.08s
150:	total: 1.63s	remaining: 7.83s
200:	total: 2.18s	remaining: 7.3s
250:	total: 2.67s	remaining: 6.64s
300:	total: 3.18s	remaining: 6.06s
350:	total: 3.81s	remaining: 5.69s
400:	total: 4.61s	remaining: 5.45s
450:	total: 5.24s	remaining: 4.93s
500:	total: 5.91s	remaining: 4.41s
550:	total: 6.53s	remaining: 3.84s
600:	total: 7.25s	remaining: 3.31s
650:	total: 7.83s	remaining: 2.69s
700:	total: 8.39s	remaining: 2.08s
750:	total: 9.27s	remaining: 1.53s
800:	total: 9.82s	remaining: 907ms
850:	total: 10.4s	remaining: 292ms
874:	total: 10.6s	remaining: 0us
0:	total: 14.9ms	remaining: 13.1s
50:	total: 688ms	remaining: 11.1s
100:	total: 2.02s	remaining: 15.4s
150:	total: 2.62s	remaining: 12.6s
200:	total: 3.16s	remaining: 10.6s
250:	total: 3.7s	remaining: 9.19s
300:	total: 4.23s	remaining: 8.06s
350:	total: 4.87s	remaining: 7.27s
400:	total: 5.46s	remaining: 6.45s
450:	total: 6.47s	remaining: 6.08s
500:	total: 7.02s	remaining: 5.24s
550:	total: 7.6s	remaining: 4.47s
600:	total: 8.46s	remaining: 3.85s
650:	total: 9.06s	remaining: 3.12s
700:	total: 9.69s	remaining: 2.4s
750:	total: 10.2s	remaining: 1.69s
800:	total: 10.8s	remaining: 1s
850:	total: 11.4s	remaining: 320ms
874:	total: 11.7s	remaining: 0us
0:	total: 9.88ms	remaining: 8.64s
50:	total: 721ms	remaining: 11.6s
100:	total: 1.26s	remaining: 9.63s
150:	total: 1.75s	remaining: 8.37s
200:	total: 2.25s	remaining: 7.55s
250:	total: 2.81s	remaining: 6.99s
300:	total: 3.37s	remaining: 6.42s
350:	total: 3.88s	remaining: 5.8s
400:	total: 4.54s	remaining: 5.37s
450:	total: 5.4s	remaining: 5.07s
500:	total: 6.41s	remaining: 4.79s
550:	total: 7.03s	remaining: 4.13s
600:	total: 7.63s	remaining: 3.48s
650:	total: 8.22s	remaining: 2.83s
700:	total: 8.79s	remaining: 2.18s
750:	total: 9.54s	remaining: 1.57s
800:	total: 10.2s	remaining: 946ms
850:	total: 11.1s	remaining: 314ms
874:	total: 11.4s	remaining: 0us
0:	total: 11.1ms	remaining: 9.71s
50:	total: 576ms	remaining: 9.31s
100:	total: 1.06s	remaining: 8.14s
150:	total: 1.55s	remaining: 7.42s
200:	total: 2.01s	remaining: 6.75s
250:	total: 2.51s	remaining: 6.24s
300:	total: 2.99s	remaining: 5.71s
350:	total: 3.47s	remaining: 5.18s
400:	total: 3.93s	remaining: 4.65s
450:	total: 4.62s	remaining: 4.34s
500:	total: 5.17s	remaining: 3.86s
550:	total: 5.69s	remaining: 3.35s
600:	total: 6.17s	remaining: 2.81s
650:	total: 6.66s	remaining: 2.29s
700:	total: 7.22s	remaining: 1.79s
750:	total: 7.74s	remaining: 1.28s
800:	total: 8.21s	remaining: 758ms
850:	total: 8.66s	remaining: 244ms

[I 2025-11-24 20:30:18,465] Trial 67 finished with value: 0.7308938294136691 and parameters: {'weight_pos': 3.5138336302096906, 'iterations': 875, 'learning_rate': 0.09637644891624118, 'depth': 6, 'eval_metric': 'AUC', 'l2_leaf_reg': 12.860521185649205, 'bagging_temperature': 0.5430208364856134, 'rsm': 0.598862701295826, 'min_data_in_leaf': 26, 'leaf_estimation_iterations': 3}. Best is trial 16 with value: 0.7404863910277388.

874:	total: 8.9s	remaining: 0us
0:	total: 3.31ms	remaining: 3.26s
50:	total: 165ms	remaining: 3.03s
100:	total: 326ms	remaining: 2.86s
150:	total: 484ms	remaining: 2.68s
200:	total: 638ms	remaining: 2.49s
250:	total: 793ms	remaining: 2.33s
300:	total: 941ms	remaining: 2.14s
350:	total: 1.1s	remaining: 1.99s
400:	total: 1.25s	remaining: 1.83s
450:	total: 1.4s	remaining: 1.67s
500:	total: 1.56s	remaining: 1.51s
550:	total: 1.71s	remaining: 1.36s
600:	total: 1.87s	remaining: 1.2s
650:	total: 2.02s	remaining: 1.04s
700:	total: 2.19s	remaining: 893ms
750:	total: 2.35s	remaining: 738ms
800:	total: 2.5s	remaining: 581ms
850:	total: 2.67s	remaining: 427ms
900:	total: 2.83s	remaining: 270ms
950:	total: 2.99s	remaining: 113ms
986:	total: 3.11s	remaining: 0us
0:	total: 3.73ms	remaining: 3.67s
50:	total: 168ms	remaining: 3.08s
100:	total: 326ms	remaining: 2.86s
150:	total: 521ms	remaining: 2.89s
200:	total: 680ms	remaining: 2.66s
250:	total: 839ms	remaining: 2.46s
300:	total: 993ms	remaining: 2.26s
350:	total: 1.15s	remaining: 2.08s
400:	total: 1.3s	remaining: 1.89s
450:	total: 1.45s	remaining: 1.72s
500:	total: 1.6s	remaining: 1.56s
550:	total: 1.76s	remaining: 1.4s
600:	total: 1.93s	remaining: 1.24s
650:	total: 2.38s	remaining: 1.23s
700:	total: 2.57s	remaining: 1.05s
750:	total: 2.73s	remaining: 859ms
800:	total: 2.89s	remaining: 671ms
850:	total: 3.05s	remaining: 487ms
900:	total: 3.2s	remaining: 305ms
950:	total: 3.37s	remaining: 127ms
986:	total: 3.48s	remaining: 0us
0:	total: 3.65ms	remaining: 3.6s
50:	total: 158ms	remaining: 2.9s
100:	total: 310ms	remaining: 2.72s
150:	total: 464ms	remaining: 2.57s
200:	total: 619ms	remaining: 2.42s
250:	total: 777ms	remaining: 2.28s
300:	total: 936ms	remaining: 2.13s
350:	total: 1.1s	remaining: 2s
400:	total: 1.27s	remaining: 1.86s
450:	total: 1.43s	remaining: 1.7s
500:	total: 1.6s	remaining: 1.55s
550:	total: 1.76s	remaining: 1.39s
600:	total: 1.93s	remaining: 1.24s
650:	total: 2.08s	remaining: 1.07s
700:	total: 2.26s	remaining: 923ms
750:	total: 2.42s	remaining: 762ms
800:	total: 2.59s	remaining: 601ms
850:	total: 2.75s	remaining: 439ms
900:	total: 2.92s	remaining: 279ms
950:	total: 3.09s	remaining: 117ms
986:	total: 3.2s	remaining: 0us
0:	total: 3.87ms	remaining: 3.81s
50:	total: 167ms	remaining: 3.07s
100:	total: 326ms	remaining: 2.86s
150:	total: 478ms	remaining: 2.65s
200:	total: 645ms	remaining: 2.52s
250:	total: 806ms	remaining: 2.36s
300:	total: 959ms	remaining: 2.19s
350:	total: 1.13s	remaining: 2.05s
400:	total: 1.28s	remaining: 1.88s
450:	total: 1.46s	remaining: 1.73s
500:	total: 1.62s	remaining: 1.57s
550:	total: 1.78s	remaining: 1.41s
600:	total: 1.94s	remaining: 1.25s
650:	total: 2.1s	remaining: 1.08s
700:	total: 2.26s	remaining: 924ms
750:	total: 2.43s	remaining: 764ms
800:	total: 2.61s	remaining: 606ms
850:	total: 2.78s	remaining: 445ms
900:	total: 3.27s	remaining: 312ms
950:	total: 3.58s	remaining: 136ms
986:	total: 3.82s	remaining: 0us
0:	total: 6.28ms	remaining: 6.2s
50:	total: 258ms	remaining: 4.74s
100:	total: 432ms	remaining: 3.79s
150:	total: 598ms	remaining: 3.31s
200:	total: 782ms	remaining: 3.06s
250:	total: 948ms	remaining: 2.78s
300:	total: 1.1s	remaining: 2.5s
350:	total: 1.44s	remaining: 2.61s
400:	total: 1.61s	remaining: 2.35s
450:	total: 1.78s	remaining: 2.12s
500:	total: 1.96s	remaining: 1.9s
550:	total: 2.12s	remaining: 1.68s
600:	total: 2.34s	remaining: 1.5s
650:	total: 2.54s	remaining: 1.31s
700:	total: 2.71s	remaining: 1.1s
750:	total: 2.88s	remaining: 905ms
800:	total: 3.1s	remaining: 720ms
850:	total: 3.29s	remaining: 526ms
900:	total: 3.48s	remaining: 332ms
950:	total: 3.71s	remaining: 141ms
986:	total: 3.86s	remaining: 0us

[I 2025-11-24 20:30:36,595] Trial 68 finished with value: 0.7244446198915173 and parameters: {'weight_pos': 2.027221642154383, 'iterations': 987, 'learning_rate': 0.03790438209847653, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.3283206145635906, 'bagging_temperature': 0.42367446158749356, 'rsm': 0.17187524051887348, 'min_data_in_leaf': 57, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 49.1ms	remaining: 40.2s
50:	total: 1.41s	remaining: 21.2s
100:	total: 2.73s	remaining: 19.4s
150:	total: 4.36s	remaining: 19.3s
200:	total: 5.6s	remaining: 17.2s
250:	total: 6.93s	remaining: 15.7s
300:	total: 8.94s	remaining: 15.4s
350:	total: 10.2s	remaining: 13.6s
400:	total: 11.5s	remaining: 12s
450:	total: 12.7s	remaining: 10.4s
500:	total: 14s	remaining: 8.88s
550:	total: 15.2s	remaining: 7.38s
600:	total: 16.5s	remaining: 5.98s
650:	total: 17.9s	remaining: 4.63s
700:	total: 19.3s	remaining: 3.25s
750:	total: 20.8s	remaining: 1.88s
800:	total: 22s	remaining: 495ms
818:	total: 22.6s	remaining: 0us
0:	total: 35.9ms	remaining: 29.4s
50:	total: 1.32s	remaining: 19.9s
100:	total: 2.66s	remaining: 18.9s
150:	total: 4.01s	remaining: 17.7s
200:	total: 5.62s	remaining: 17.3s
250:	total: 6.88s	remaining: 15.6s
300:	total: 8.76s	remaining: 15.1s
350:	total: 10.5s	remaining: 14.1s
400:	total: 12.1s	remaining: 12.6s
450:	total: 13.5s	remaining: 11s
500:	total: 15.3s	remaining: 9.69s
550:	total: 16.7s	remaining: 8.13s
600:	total: 18.8s	remaining: 6.83s
650:	total: 20.1s	remaining: 5.2s
700:	total: 21.7s	remaining: 3.65s
750:	total: 23.1s	remaining: 2.09s
800:	total: 24.6s	remaining: 552ms
818:	total: 25.1s	remaining: 0us
0:	total: 28ms	remaining: 22.9s
50:	total: 1.12s	remaining: 16.9s
100:	total: 2.38s	remaining: 16.9s
150:	total: 3.51s	remaining: 15.5s
200:	total: 4.63s	remaining: 14.3s
250:	total: 5.79s	remaining: 13.1s
300:	total: 7s	remaining: 12s
350:	total: 8.21s	remaining: 10.9s
400:	total: 9.69s	remaining: 10.1s
450:	total: 10.9s	remaining: 8.91s
500:	total: 12.2s	remaining: 7.75s
550:	total: 13.4s	remaining: 6.53s
600:	total: 14.8s	remaining: 5.36s
650:	total: 16s	remaining: 4.12s
700:	total: 17.3s	remaining: 2.92s
750:	total: 18.6s	remaining: 1.69s
800:	total: 20.3s	remaining: 457ms
818:	total: 20.8s	remaining: 0us
0:	total: 6.32ms	remaining: 5.17s
50:	total: 1.64s	remaining: 24.7s
100:	total: 2.93s	remaining: 20.8s
150:	total: 4.29s	remaining: 19s
200:	total: 5.61s	remaining: 17.2s
250:	total: 6.87s	remaining: 15.6s
300:	total: 8.83s	remaining: 15.2s
350:	total: 10.2s	remaining: 13.6s
400:	total: 11.6s	remaining: 12.1s
450:	total: 13.8s	remaining: 11.3s
500:	total: 15.3s	remaining: 9.69s
550:	total: 16.8s	remaining: 8.18s
600:	total: 18.6s	remaining: 6.74s
650:	total: 20s	remaining: 5.16s
700:	total: 21.5s	remaining: 3.62s
750:	total: 22.8s	remaining: 2.07s
800:	total: 24.6s	remaining: 553ms
818:	total: 25.2s	remaining: 0us
0:	total: 28.2ms	remaining: 23.1s
50:	total: 1.15s	remaining: 17.4s
100:	total: 3.11s	remaining: 22.1s
150:	total: 4.86s	remaining: 21.5s
200:	total: 6.33s	remaining: 19.5s
250:	total: 7.66s	remaining: 17.3s
300:	total: 8.88s	remaining: 15.3s
350:	total: 10.3s	remaining: 13.8s
400:	total: 11.9s	remaining: 12.4s
450:	total: 13.3s	remaining: 10.9s
500:	total: 14.6s	remaining: 9.29s
550:	total: 16s	remaining: 7.78s
600:	total: 17.3s	remaining: 6.29s
650:	total: 18.7s	remaining: 4.82s
700:	total: 20.1s	remaining: 3.38s
750:	total: 21.4s	remaining: 1.94s
800:	total: 23.1s	remaining: 518ms

[I 2025-11-24 20:32:35,294] Trial 69 finished with value: 0.6996961300044571 and parameters: {'weight_pos': 2.5585579492361705, 'iterations': 819, 'learning_rate': 0.07500271983480088, 'depth': 11, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.27287078083199573, 'bagging_temperature': 0.46451490382415744, 'rsm': 0.3492330986450133, 'min_data_in_leaf': 31, 'leaf_estimation_iterations': 1}. Best is trial 16 with value: 0.7404863910277388.

818:	total: 23.6s	remaining: 0us
0:	learn: 0.8608082	total: 4.8ms	remaining: 4.28s
50:	learn: 0.8800932	total: 175ms	remaining: 2.88s
100:	learn: 0.9063605	total: 346ms	remaining: 2.71s
150:	learn: 0.9190846	total: 509ms	remaining: 2.5s
200:	learn: 0.9296461	total: 665ms	remaining: 2.29s
250:	learn: 0.9381789	total: 819ms	remaining: 2.09s
300:	learn: 0.9450544	total: 980ms	remaining: 1.93s
350:	learn: 0.9512536	total: 1.13s	remaining: 1.75s
400:	learn: 0.9547201	total: 1.28s	remaining: 1.57s
450:	learn: 0.9602528	total: 1.45s	remaining: 1.42s
500:	learn: 0.9639093	total: 1.6s	remaining: 1.26s
550:	learn: 0.9685278	total: 1.76s	remaining: 1.09s
600:	learn: 0.9712989	total: 1.92s	remaining: 932ms
650:	learn: 0.9741746	total: 2.07s	remaining: 770ms
700:	learn: 0.9774790	total: 2.23s	remaining: 610ms
750:	learn: 0.9803835	total: 2.4s	remaining: 454ms
800:	learn: 0.9818405	total: 2.56s	remaining: 294ms
850:	learn: 0.9849828	total: 2.71s	remaining: 134ms
892:	learn: 0.9861540	total: 2.86s	remaining: 0us
0:	learn: 0.8608082	total: 3.41ms	remaining: 3.04s
50:	learn: 0.8819222	total: 158ms	remaining: 2.61s
100:	learn: 0.9058375	total: 308ms	remaining: 2.42s
150:	learn: 0.9192563	total: 470ms	remaining: 2.31s
200:	learn: 0.9289124	total: 622ms	remaining: 2.14s
250:	learn: 0.9385502	total: 780ms	remaining: 1.99s
300:	learn: 0.9453593	total: 946ms	remaining: 1.86s
350:	learn: 0.9512919	total: 1.11s	remaining: 1.71s
400:	learn: 0.9562817	total: 1.26s	remaining: 1.55s
450:	learn: 0.9616906	total: 1.42s	remaining: 1.39s
500:	learn: 0.9651092	total: 1.59s	remaining: 1.24s
550:	learn: 0.9685278	total: 1.76s	remaining: 1.09s
600:	learn: 0.9703752	total: 1.91s	remaining: 930ms
650:	learn: 0.9733747	total: 2.08s	remaining: 773ms
700:	learn: 0.9759933	total: 2.25s	remaining: 616ms
750:	learn: 0.9779836	total: 2.4s	remaining: 454ms
800:	learn: 0.9806022	total: 2.56s	remaining: 294ms
850:	learn: 0.9841541	total: 2.72s	remaining: 134ms
892:	learn: 0.9850874	total: 2.85s	remaining: 0us
0:	learn: 0.8608082	total: 4.21ms	remaining: 3.76s
50:	learn: 0.8830839	total: 159ms	remaining: 2.63s
100:	learn: 0.9043334	total: 316ms	remaining: 2.48s
150:	learn: 0.9159430	total: 461ms	remaining: 2.27s
200:	learn: 0.9265420	total: 621ms	remaining: 2.14s
250:	learn: 0.9350270	total: 772ms	remaining: 1.98s
300:	learn: 0.9423591	total: 928ms	remaining: 1.82s
350:	learn: 0.9487492	total: 1.09s	remaining: 1.68s
400:	learn: 0.9525869	total: 1.26s	remaining: 1.55s
450:	learn: 0.9581100	total: 1.46s	remaining: 1.43s
500:	learn: 0.9631285	total: 1.63s	remaining: 1.27s
550:	learn: 0.9671945	total: 1.79s	remaining: 1.11s
600:	learn: 0.9694611	total: 1.98s	remaining: 964ms
650:	learn: 0.9740413	total: 2.23s	remaining: 831ms
700:	learn: 0.9773265	total: 2.48s	remaining: 680ms
750:	learn: 0.9799548	total: 3.04s	remaining: 575ms
800:	learn: 0.9813926	total: 3.28s	remaining: 376ms
850:	learn: 0.9829829	total: 3.45s	remaining: 170ms
892:	learn: 0.9846779	total: 3.6s	remaining: 0us
0:	learn: 0.8608082	total: 4.36ms	remaining: 3.89s
50:	learn: 0.8846167	total: 163ms	remaining: 2.7s
100:	learn: 0.9086271	total: 353ms	remaining: 2.76s
150:	learn: 0.9231507	total: 518ms	remaining: 2.54s
200:	learn: 0.9338455	total: 684ms	remaining: 2.35s
250:	learn: 0.9425499	total: 841ms	remaining: 2.15s
300:	learn: 0.9474638	total: 992ms	remaining: 1.95s
350:	learn: 0.9527674	total: 1.15s	remaining: 1.78s
400:	learn: 0.9565005	total: 1.31s	remaining: 1.61s
450:	learn: 0.9612428	total: 1.48s	remaining: 1.45s
500:	learn: 0.9654421	total: 1.65s	remaining: 1.29s
550:	learn: 0.9687561	total: 1.82s	remaining: 1.13s
600:	learn: 0.9740221	total: 1.98s	remaining: 961ms
650:	learn: 0.9757458	total: 2.15s	remaining: 799ms
700:	learn: 0.9779932	total: 2.31s	remaining: 631ms
750:	learn: 0.9808402	total: 2.47s	remaining: 468ms
800:	learn: 0.9828496	total: 2.63s	remaining: 302ms
850:	learn: 0.9848208	total: 2.8s	remaining: 138ms
892:	learn: 0.9866682	total: 2.94s	remaining: 0us
0:	learn: 0.8608082	total: 5.11ms	remaining: 4.56s
50:	learn: 0.8890069	total: 158ms	remaining: 2.61s
100:	learn: 0.9085026	total: 316ms	remaining: 2.47s
150:	learn: 0.9182552	total: 467ms	remaining: 2.29s
200:	learn: 0.9285507	total: 626ms	remaining: 2.15s
250:	learn: 0.9365407	total: 776ms	remaining: 1.99s
300:	learn: 0.9435399	total: 933ms	remaining: 1.83s
350:	learn: 0.9492538	total: 1.09s	remaining: 1.68s
400:	learn: 0.9564909	total: 1.24s	remaining: 1.52s
450:	learn: 0.9607286	total: 1.39s	remaining: 1.36s
500:	learn: 0.9638997	total: 1.55s	remaining: 1.21s
550:	learn: 0.9675658	total: 1.71s	remaining: 1.06s
600:	learn: 0.9707081	total: 1.87s	remaining: 909ms
650:	learn: 0.9739934	total: 2.03s	remaining: 756ms
700:	learn: 0.9763837	total: 2.19s	remaining: 600ms
750:	learn: 0.9784977	total: 2.35s	remaining: 444ms
800:	learn: 0.9806214	total: 2.51s	remaining: 288ms
850:	learn: 0.9832496	total: 2.66s	remaining: 131ms

[I 2025-11-24 20:32:50,972] Trial 70 finished with value: 0.6946984620722473 and parameters: {'weight_pos': 1.0773735935024404, 'iterations': 893, 'learning_rate': 0.05459937180539694, 'depth': 5, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 0.10389258681125184, 'bagging_temperature': 0.23118421609041412, 'rsm': 0.07464149313783475, 'min_data_in_leaf': 97, 'leaf_estimation_iterations': 4}. Best is trial 16 with value: 0.7404863910277388.

892:	learn: 0.9850778	total: 2.79s	remaining: 0us
0:	total: 5.07ms	remaining: 4.29s
50:	total: 175ms	remaining: 2.73s
100:	total: 347ms	remaining: 2.57s
150:	total: 523ms	remaining: 2.41s
200:	total: 747ms	remaining: 2.4s
250:	total: 930ms	remaining: 2.21s
300:	total: 1.12s	remaining: 2.03s
350:	total: 1.32s	remaining: 1.86s
400:	total: 1.5s	remaining: 1.67s
450:	total: 1.71s	remaining: 1.5s
500:	total: 1.88s	remaining: 1.3s
550:	total: 2.06s	remaining: 1.11s
600:	total: 2.24s	remaining: 917ms
650:	total: 2.42s	remaining: 730ms
700:	total: 2.62s	remaining: 546ms
750:	total: 2.92s	remaining: 373ms
800:	total: 3.24s	remaining: 186ms
846:	total: 3.42s	remaining: 0us
0:	total: 4.52ms	remaining: 3.82s
50:	total: 207ms	remaining: 3.23s
100:	total: 405ms	remaining: 2.99s
150:	total: 598ms	remaining: 2.75s
200:	total: 808ms	remaining: 2.6s
250:	total: 1.16s	remaining: 2.75s
300:	total: 1.41s	remaining: 2.55s
350:	total: 1.63s	remaining: 2.31s
400:	total: 1.85s	remaining: 2.05s
450:	total: 2.04s	remaining: 1.79s
500:	total: 2.25s	remaining: 1.55s
550:	total: 2.46s	remaining: 1.32s
600:	total: 2.67s	remaining: 1.09s
650:	total: 2.88s	remaining: 868ms
700:	total: 3.09s	remaining: 643ms
750:	total: 3.29s	remaining: 421ms
800:	total: 3.49s	remaining: 201ms
846:	total: 3.68s	remaining: 0us
0:	total: 10.1ms	remaining: 8.55s
50:	total: 205ms	remaining: 3.2s
100:	total: 407ms	remaining: 3.01s
150:	total: 593ms	remaining: 2.73s
200:	total: 782ms	remaining: 2.51s
250:	total: 965ms	remaining: 2.29s
300:	total: 1.15s	remaining: 2.08s
350:	total: 1.34s	remaining: 1.9s
400:	total: 1.59s	remaining: 1.77s
450:	total: 1.79s	remaining: 1.57s
500:	total: 1.98s	remaining: 1.37s
550:	total: 2.22s	remaining: 1.19s
600:	total: 2.44s	remaining: 1s
650:	total: 2.68s	remaining: 806ms
700:	total: 2.88s	remaining: 601ms
750:	total: 3.1s	remaining: 396ms
800:	total: 3.29s	remaining: 189ms
846:	total: 3.49s	remaining: 0us
0:	total: 5.49ms	remaining: 4.65s
50:	total: 230ms	remaining: 3.58s
100:	total: 472ms	remaining: 3.49s
150:	total: 714ms	remaining: 3.29s
200:	total: 949ms	remaining: 3.05s
250:	total: 1.16s	remaining: 2.75s
300:	total: 1.34s	remaining: 2.44s
350:	total: 1.55s	remaining: 2.19s
400:	total: 1.75s	remaining: 1.95s
450:	total: 2.06s	remaining: 1.81s
500:	total: 2.36s	remaining: 1.63s
550:	total: 2.56s	remaining: 1.37s
600:	total: 2.76s	remaining: 1.13s
650:	total: 3.07s	remaining: 925ms
700:	total: 3.34s	remaining: 695ms
750:	total: 3.61s	remaining: 461ms
800:	total: 3.84s	remaining: 220ms
846:	total: 4.03s	remaining: 0us
0:	total: 5.45ms	remaining: 4.61s
50:	total: 198ms	remaining: 3.09s
100:	total: 402ms	remaining: 2.97s
150:	total: 618ms	remaining: 2.85s
200:	total: 815ms	remaining: 2.62s
250:	total: 1s	remaining: 2.38s
300:	total: 1.2s	remaining: 2.18s
350:	total: 1.39s	remaining: 1.97s
400:	total: 1.58s	remaining: 1.75s
450:	total: 1.77s	remaining: 1.55s
500:	total: 1.95s	remaining: 1.34s
550:	total: 2.13s	remaining: 1.14s
600:	total: 2.38s	remaining: 976ms
650:	total: 2.59s	remaining: 780ms
700:	total: 2.78s	remaining: 579ms
750:	total: 2.97s	remaining: 379ms
800:	total: 3.15s	remaining: 181ms

[I 2025-11-24 20:33:09,517] Trial 71 finished with value: 0.7285997996922055 and parameters: {'weight_pos': 2.7814112760500196, 'iterations': 847, 'learning_rate': 0.04431298015190682, 'depth': 3, 'eval_metric': 'AUC', 'l2_leaf_reg': 5.052281620481922, 'bagging_temperature': 0.5037429080506488, 'rsm': 0.41640471088291514, 'min_data_in_leaf': 40, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

846:	total: 3.34s	remaining: 0us
0:	total: 8.3ms	remaining: 7.71s
50:	total: 272ms	remaining: 4.68s
100:	total: 534ms	remaining: 4.38s
150:	total: 784ms	remaining: 4.04s
200:	total: 1.03s	remaining: 3.75s
250:	total: 1.29s	remaining: 3.48s
300:	total: 1.54s	remaining: 3.22s
350:	total: 1.83s	remaining: 3.01s
400:	total: 2.1s	remaining: 2.77s
450:	total: 2.36s	remaining: 2.51s
500:	total: 2.64s	remaining: 2.26s
550:	total: 2.9s	remaining: 2s
600:	total: 3.16s	remaining: 1.73s
650:	total: 3.43s	remaining: 1.47s
700:	total: 3.69s	remaining: 1.21s
750:	total: 3.96s	remaining: 944ms
800:	total: 4.35s	remaining: 700ms
850:	total: 4.71s	remaining: 438ms
900:	total: 4.98s	remaining: 160ms
929:	total: 5.13s	remaining: 0us
0:	total: 5.81ms	remaining: 5.4s
50:	total: 258ms	remaining: 4.45s
100:	total: 521ms	remaining: 4.27s
150:	total: 777ms	remaining: 4.01s
200:	total: 1.07s	remaining: 3.87s
250:	total: 1.32s	remaining: 3.57s
300:	total: 1.63s	remaining: 3.41s
350:	total: 1.94s	remaining: 3.19s
400:	total: 2.21s	remaining: 2.92s
450:	total: 2.47s	remaining: 2.63s
500:	total: 2.75s	remaining: 2.36s
550:	total: 3.03s	remaining: 2.09s
600:	total: 3.3s	remaining: 1.81s
650:	total: 3.59s	remaining: 1.54s
700:	total: 3.85s	remaining: 1.26s
750:	total: 4.11s	remaining: 979ms
800:	total: 4.38s	remaining: 705ms
850:	total: 4.64s	remaining: 431ms
900:	total: 4.91s	remaining: 158ms
929:	total: 5.06s	remaining: 0us
0:	total: 6.59ms	remaining: 6.13s
50:	total: 256ms	remaining: 4.41s
100:	total: 504ms	remaining: 4.13s
150:	total: 761ms	remaining: 3.93s
200:	total: 1.01s	remaining: 3.66s
250:	total: 1.26s	remaining: 3.4s
300:	total: 1.51s	remaining: 3.15s
350:	total: 1.76s	remaining: 2.9s
400:	total: 2.02s	remaining: 2.66s
450:	total: 2.28s	remaining: 2.42s
500:	total: 2.56s	remaining: 2.19s
550:	total: 2.85s	remaining: 1.96s
600:	total: 3.14s	remaining: 1.72s
650:	total: 3.42s	remaining: 1.47s
700:	total: 3.68s	remaining: 1.2s
750:	total: 4.16s	remaining: 992ms
800:	total: 4.47s	remaining: 720ms
850:	total: 4.79s	remaining: 444ms
900:	total: 5.07s	remaining: 163ms
929:	total: 5.23s	remaining: 0us
0:	total: 7.13ms	remaining: 6.63s
50:	total: 268ms	remaining: 4.61s
100:	total: 565ms	remaining: 4.64s
150:	total: 889ms	remaining: 4.59s
200:	total: 1.2s	remaining: 4.35s
250:	total: 1.48s	remaining: 3.99s
300:	total: 1.74s	remaining: 3.63s
350:	total: 2.03s	remaining: 3.34s
400:	total: 2.4s	remaining: 3.16s
450:	total: 2.68s	remaining: 2.85s
500:	total: 3.28s	remaining: 2.81s
550:	total: 3.71s	remaining: 2.56s
600:	total: 4.52s	remaining: 2.48s
650:	total: 4.95s	remaining: 2.12s
700:	total: 5.26s	remaining: 1.72s
750:	total: 5.55s	remaining: 1.32s
800:	total: 5.84s	remaining: 940ms
850:	total: 6.13s	remaining: 569ms
900:	total: 6.41s	remaining: 206ms
929:	total: 6.58s	remaining: 0us
0:	total: 6.36ms	remaining: 5.91s
50:	total: 265ms	remaining: 4.57s
100:	total: 545ms	remaining: 4.47s
150:	total: 850ms	remaining: 4.38s
200:	total: 1.12s	remaining: 4.05s
250:	total: 1.39s	remaining: 3.75s
300:	total: 1.64s	remaining: 3.43s
350:	total: 2.1s	remaining: 3.47s
400:	total: 2.47s	remaining: 3.26s
450:	total: 2.78s	remaining: 2.95s
500:	total: 3.08s	remaining: 2.64s
550:	total: 3.34s	remaining: 2.3s
600:	total: 3.6s	remaining: 1.97s
650:	total: 3.89s	remaining: 1.67s
700:	total: 4.17s	remaining: 1.36s
750:	total: 4.44s	remaining: 1.06s
800:	total: 4.74s	remaining: 763ms
850:	total: 5s	remaining: 464ms

[I 2025-11-24 20:33:37,654] Trial 72 finished with value: 0.7402170548646861 and parameters: {'weight_pos': 2.1705401698619795, 'iterations': 930, 'learning_rate': 0.05069327980761378, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.509358106395195, 'bagging_temperature': 0.5650585525516543, 'rsm': 0.47329369404954447, 'min_data_in_leaf': 41, 'leaf_estimation_iterations': 5}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 5.26s	remaining: 169ms
929:	total: 5.43s	remaining: 0us
0:	total: 5.96ms	remaining: 5.55s
50:	total: 283ms	remaining: 4.88s
100:	total: 556ms	remaining: 4.57s
150:	total: 841ms	remaining: 4.34s
200:	total: 1.11s	remaining: 4.03s
250:	total: 1.38s	remaining: 3.74s
300:	total: 1.67s	remaining: 3.49s
350:	total: 1.95s	remaining: 3.22s
400:	total: 2.23s	remaining: 2.95s
450:	total: 2.52s	remaining: 2.68s
500:	total: 2.8s	remaining: 2.4s
550:	total: 3.08s	remaining: 2.12s
600:	total: 3.35s	remaining: 1.84s
650:	total: 3.62s	remaining: 1.56s
700:	total: 3.9s	remaining: 1.28s
750:	total: 4.17s	remaining: 999ms
800:	total: 4.43s	remaining: 720ms
850:	total: 4.72s	remaining: 443ms
900:	total: 5s	remaining: 166ms
930:	total: 5.29s	remaining: 0us
0:	total: 14.1ms	remaining: 13.1s
50:	total: 375ms	remaining: 6.47s
100:	total: 824ms	remaining: 6.77s
150:	total: 1.28s	remaining: 6.63s
200:	total: 1.6s	remaining: 5.81s
250:	total: 1.9s	remaining: 5.13s
300:	total: 2.19s	remaining: 4.58s
350:	total: 2.48s	remaining: 4.09s
400:	total: 2.78s	remaining: 3.67s
450:	total: 3.1s	remaining: 3.3s
500:	total: 3.39s	remaining: 2.91s
550:	total: 3.69s	remaining: 2.55s
600:	total: 4s	remaining: 2.19s
650:	total: 4.28s	remaining: 1.84s
700:	total: 4.62s	remaining: 1.52s
750:	total: 4.92s	remaining: 1.18s
800:	total: 5.21s	remaining: 846ms
850:	total: 5.5s	remaining: 517ms
900:	total: 5.82s	remaining: 194ms
930:	total: 6.01s	remaining: 0us
0:	total: 6.34ms	remaining: 5.9s
50:	total: 266ms	remaining: 4.59s
100:	total: 535ms	remaining: 4.4s
150:	total: 818ms	remaining: 4.22s
200:	total: 1.11s	remaining: 4.02s
250:	total: 1.4s	remaining: 3.81s
300:	total: 1.68s	remaining: 3.52s
350:	total: 1.95s	remaining: 3.22s
400:	total: 2.25s	remaining: 2.97s
450:	total: 2.56s	remaining: 2.73s
500:	total: 2.92s	remaining: 2.5s
550:	total: 3.2s	remaining: 2.2s
600:	total: 3.47s	remaining: 1.91s
650:	total: 3.75s	remaining: 1.61s
700:	total: 4.03s	remaining: 1.32s
750:	total: 4.31s	remaining: 1.03s
800:	total: 4.71s	remaining: 764ms
850:	total: 5.04s	remaining: 474ms
900:	total: 5.33s	remaining: 178ms
930:	total: 5.5s	remaining: 0us
0:	total: 6.52ms	remaining: 6.07s
50:	total: 301ms	remaining: 5.2s
100:	total: 584ms	remaining: 4.8s
150:	total: 853ms	remaining: 4.41s
200:	total: 1.12s	remaining: 4.06s
250:	total: 1.48s	remaining: 4.01s
300:	total: 1.76s	remaining: 3.68s
350:	total: 2.05s	remaining: 3.38s
400:	total: 2.33s	remaining: 3.08s
450:	total: 2.6s	remaining: 2.77s
500:	total: 2.89s	remaining: 2.48s
550:	total: 3.17s	remaining: 2.19s
600:	total: 3.46s	remaining: 1.9s
650:	total: 3.75s	remaining: 1.61s
700:	total: 4.03s	remaining: 1.32s
750:	total: 4.31s	remaining: 1.03s
800:	total: 4.6s	remaining: 746ms
850:	total: 4.88s	remaining: 459ms
900:	total: 5.17s	remaining: 172ms
930:	total: 5.37s	remaining: 0us
0:	total: 5.91ms	remaining: 5.49s
50:	total: 270ms	remaining: 4.67s
100:	total: 542ms	remaining: 4.45s
150:	total: 801ms	remaining: 4.14s
200:	total: 1.08s	remaining: 3.94s
250:	total: 1.38s	remaining: 3.73s
300:	total: 1.65s	remaining: 3.46s
350:	total: 1.94s	remaining: 3.21s
400:	total: 2.22s	remaining: 2.93s
450:	total: 2.54s	remaining: 2.7s
500:	total: 2.85s	remaining: 2.45s
550:	total: 3.16s	remaining: 2.18s
600:	total: 3.83s	remaining: 2.1s
650:	total: 4.47s	remaining: 1.92s
700:	total: 4.91s	remaining: 1.61s
750:	total: 5.37s	remaining: 1.29s
800:	total: 5.72s	remaining: 929ms
850:	total: 6.12s	remaining: 575ms
900:	total: 6.44s	remaining: 214ms
930:	total: 6.61s	remaining: 0us

[I 2025-11-24 20:34:07,147] Trial 73 finished with value: 0.7330762418918175 and parameters: {'weight_pos': 2.3141753135452356, 'iterations': 931, 'learning_rate': 0.06636229303826373, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.181888503317127, 'bagging_temperature': 0.5725441050002539, 'rsm': 0.48245747426621627, 'min_data_in_leaf': 44, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 7.93ms	remaining: 7.39s
50:	total: 332ms	remaining: 5.73s
100:	total: 633ms	remaining: 5.21s
150:	total: 928ms	remaining: 4.8s
200:	total: 1.22s	remaining: 4.42s
250:	total: 1.51s	remaining: 4.1s
300:	total: 1.79s	remaining: 3.75s
350:	total: 2.07s	remaining: 3.42s
400:	total: 2.4s	remaining: 3.18s
450:	total: 2.69s	remaining: 2.87s
500:	total: 2.97s	remaining: 2.55s
550:	total: 3.25s	remaining: 2.25s
600:	total: 3.53s	remaining: 1.94s
650:	total: 3.82s	remaining: 1.65s
700:	total: 4.1s	remaining: 1.35s
750:	total: 4.38s	remaining: 1.06s
800:	total: 4.67s	remaining: 763ms
850:	total: 4.94s	remaining: 470ms
900:	total: 5.31s	remaining: 183ms
931:	total: 5.48s	remaining: 0us
0:	total: 6.93ms	remaining: 6.46s
50:	total: 267ms	remaining: 4.61s
100:	total: 531ms	remaining: 4.37s
150:	total: 795ms	remaining: 4.11s
200:	total: 1.12s	remaining: 4.06s
250:	total: 1.46s	remaining: 3.97s
300:	total: 1.73s	remaining: 3.62s
350:	total: 2.01s	remaining: 3.33s
400:	total: 2.33s	remaining: 3.09s
450:	total: 2.62s	remaining: 2.79s
500:	total: 2.9s	remaining: 2.49s
550:	total: 3.17s	remaining: 2.19s
600:	total: 3.45s	remaining: 1.9s
650:	total: 3.74s	remaining: 1.61s
700:	total: 4.07s	remaining: 1.34s
750:	total: 4.35s	remaining: 1.05s
800:	total: 4.63s	remaining: 758ms
850:	total: 4.92s	remaining: 468ms
900:	total: 5.21s	remaining: 179ms
931:	total: 5.38s	remaining: 0us
0:	total: 6.55ms	remaining: 6.09s
50:	total: 303ms	remaining: 5.23s
100:	total: 574ms	remaining: 4.72s
150:	total: 845ms	remaining: 4.37s
200:	total: 1.11s	remaining: 4.05s
250:	total: 1.4s	remaining: 3.79s
300:	total: 1.68s	remaining: 3.52s
350:	total: 1.94s	remaining: 3.21s
400:	total: 2.21s	remaining: 2.93s
450:	total: 2.49s	remaining: 2.66s
500:	total: 2.77s	remaining: 2.38s
550:	total: 3.05s	remaining: 2.11s
600:	total: 3.39s	remaining: 1.87s
650:	total: 3.67s	remaining: 1.58s
700:	total: 3.94s	remaining: 1.3s
750:	total: 4.23s	remaining: 1.02s
800:	total: 4.49s	remaining: 735ms
850:	total: 4.82s	remaining: 459ms
900:	total: 5.17s	remaining: 178ms
931:	total: 5.41s	remaining: 0us
0:	total: 35.5ms	remaining: 33s
50:	total: 506ms	remaining: 8.73s
100:	total: 798ms	remaining: 6.57s
150:	total: 1.09s	remaining: 5.64s
200:	total: 1.39s	remaining: 5.07s
250:	total: 1.71s	remaining: 4.64s
300:	total: 2.04s	remaining: 4.28s
350:	total: 2.36s	remaining: 3.91s
400:	total: 2.7s	remaining: 3.57s
450:	total: 3.06s	remaining: 3.26s
500:	total: 3.39s	remaining: 2.91s
550:	total: 3.76s	remaining: 2.6s
600:	total: 4.19s	remaining: 2.31s
650:	total: 4.69s	remaining: 2.02s
700:	total: 5.15s	remaining: 1.7s
750:	total: 5.59s	remaining: 1.35s
800:	total: 5.98s	remaining: 978ms
850:	total: 6.29s	remaining: 598ms
900:	total: 6.6s	remaining: 227ms
931:	total: 6.79s	remaining: 0us
0:	total: 6.51ms	remaining: 6.06s
50:	total: 294ms	remaining: 5.08s
100:	total: 576ms	remaining: 4.74s
150:	total: 847ms	remaining: 4.38s
200:	total: 1.11s	remaining: 4.05s
250:	total: 1.38s	remaining: 3.75s
300:	total: 1.65s	remaining: 3.46s
350:	total: 1.92s	remaining: 3.18s
400:	total: 2.21s	remaining: 2.93s
450:	total: 2.53s	remaining: 2.7s
500:	total: 2.94s	remaining: 2.52s
550:	total: 3.62s	remaining: 2.5s
600:	total: 3.96s	remaining: 2.18s
650:	total: 4.28s	remaining: 1.85s
700:	total: 4.56s	remaining: 1.5s
750:	total: 4.86s	remaining: 1.17s
800:	total: 5.18s	remaining: 847ms
850:	total: 5.51s	remaining: 525ms
900:	total: 5.84s	remaining: 201ms

[I 2025-11-24 20:34:37,001] Trial 74 finished with value: 0.7328392280978864 and parameters: {'weight_pos': 1.7713182373842071, 'iterations': 932, 'learning_rate': 0.06610513031739175, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.285403722801085, 'bagging_temperature': 0.5680098398035837, 'rsm': 0.4860892399383839, 'min_data_in_leaf': 44, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

931:	total: 6.08s	remaining: 0us
0:	total: 8.2ms	remaining: 7.53s
50:	total: 538ms	remaining: 9.17s
100:	total: 938ms	remaining: 7.6s
150:	total: 1.32s	remaining: 6.71s
200:	total: 1.71s	remaining: 6.11s
250:	total: 2.08s	remaining: 5.55s
300:	total: 2.48s	remaining: 5.11s
350:	total: 2.9s	remaining: 4.7s
400:	total: 3.5s	remaining: 4.53s
450:	total: 3.94s	remaining: 4.1s
500:	total: 4.34s	remaining: 3.63s
550:	total: 4.76s	remaining: 3.19s
600:	total: 5.21s	remaining: 2.77s
650:	total: 5.65s	remaining: 2.33s
700:	total: 6.14s	remaining: 1.92s
750:	total: 6.71s	remaining: 1.51s
800:	total: 7.42s	remaining: 1.1s
850:	total: 7.82s	remaining: 634ms
900:	total: 8.24s	remaining: 174ms
919:	total: 8.4s	remaining: 0us
0:	total: 9.25ms	remaining: 8.5s
50:	total: 389ms	remaining: 6.63s
100:	total: 773ms	remaining: 6.27s
150:	total: 1.14s	remaining: 5.8s
200:	total: 1.53s	remaining: 5.48s
250:	total: 1.9s	remaining: 5.07s
300:	total: 2.27s	remaining: 4.67s
350:	total: 2.66s	remaining: 4.31s
400:	total: 3.04s	remaining: 3.94s
450:	total: 3.43s	remaining: 3.57s
500:	total: 3.81s	remaining: 3.18s
550:	total: 4.18s	remaining: 2.8s
600:	total: 4.55s	remaining: 2.42s
650:	total: 4.95s	remaining: 2.04s
700:	total: 5.35s	remaining: 1.67s
750:	total: 5.81s	remaining: 1.31s
800:	total: 6.27s	remaining: 931ms
850:	total: 6.79s	remaining: 550ms
900:	total: 7.63s	remaining: 161ms
919:	total: 7.79s	remaining: 0us
0:	total: 7.53ms	remaining: 6.92s
50:	total: 517ms	remaining: 8.8s
100:	total: 989ms	remaining: 8.02s
150:	total: 1.38s	remaining: 7.05s
200:	total: 1.78s	remaining: 6.36s
250:	total: 2.2s	remaining: 5.86s
300:	total: 2.62s	remaining: 5.38s
350:	total: 3.09s	remaining: 5.01s
400:	total: 3.6s	remaining: 4.66s
450:	total: 4.09s	remaining: 4.25s
500:	total: 4.54s	remaining: 3.79s
550:	total: 4.96s	remaining: 3.32s
600:	total: 5.37s	remaining: 2.85s
650:	total: 6.21s	remaining: 2.57s
700:	total: 6.91s	remaining: 2.16s
750:	total: 7.74s	remaining: 1.74s
800:	total: 8.45s	remaining: 1.25s
850:	total: 9.06s	remaining: 735ms
900:	total: 9.57s	remaining: 202ms
919:	total: 9.75s	remaining: 0us
0:	total: 8.22ms	remaining: 7.56s
50:	total: 446ms	remaining: 7.61s
100:	total: 1.42s	remaining: 11.5s
150:	total: 2.33s	remaining: 11.9s
200:	total: 3.13s	remaining: 11.2s
250:	total: 3.65s	remaining: 9.74s
300:	total: 4.13s	remaining: 8.5s
350:	total: 4.6s	remaining: 7.46s
400:	total: 5.11s	remaining: 6.61s
450:	total: 5.59s	remaining: 5.82s
500:	total: 5.99s	remaining: 5.01s
550:	total: 6.41s	remaining: 4.29s
600:	total: 6.81s	remaining: 3.62s
650:	total: 7.3s	remaining: 3.02s
700:	total: 7.66s	remaining: 2.39s
750:	total: 8.13s	remaining: 1.83s
800:	total: 8.7s	remaining: 1.29s
850:	total: 9.16s	remaining: 743ms
900:	total: 9.6s	remaining: 202ms
919:	total: 9.75s	remaining: 0us
0:	total: 7.8ms	remaining: 7.17s
50:	total: 378ms	remaining: 6.44s
100:	total: 899ms	remaining: 7.29s
150:	total: 1.28s	remaining: 6.51s
200:	total: 1.62s	remaining: 5.8s
250:	total: 1.99s	remaining: 5.31s
300:	total: 2.35s	remaining: 4.84s
350:	total: 2.77s	remaining: 4.48s
400:	total: 3.18s	remaining: 4.12s
450:	total: 3.64s	remaining: 3.79s
500:	total: 4.06s	remaining: 3.39s
550:	total: 4.43s	remaining: 2.96s
600:	total: 4.79s	remaining: 2.54s
650:	total: 5.2s	remaining: 2.15s
700:	total: 5.61s	remaining: 1.75s
750:	total: 6.04s	remaining: 1.36s
800:	total: 6.46s	remaining: 959ms
850:	total: 6.88s	remaining: 558ms

[I 2025-11-24 20:35:20,884] Trial 75 finished with value: 0.7234740339495548 and parameters: {'weight_pos': 1.697871051719843, 'iterations': 920, 'learning_rate': 0.08473203714639677, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.4920390411741757, 'bagging_temperature': 0.5327419464319773, 'rsm': 0.4973292755016637, 'min_data_in_leaf': 45, 'leaf_estimation_iterations': 7}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 7.25s	remaining: 153ms
919:	total: 7.4s	remaining: 0us
0:	total: 7.1ms	remaining: 6.68s
50:	total: 292ms	remaining: 5.09s
100:	total: 681ms	remaining: 5.67s
150:	total: 985ms	remaining: 5.16s
200:	total: 1.31s	remaining: 4.82s
250:	total: 1.69s	remaining: 4.66s
300:	total: 2.05s	remaining: 4.37s
350:	total: 2.34s	remaining: 3.95s
400:	total: 2.64s	remaining: 3.56s
450:	total: 3.01s	remaining: 3.27s
500:	total: 3.39s	remaining: 2.98s
550:	total: 3.69s	remaining: 2.62s
600:	total: 3.97s	remaining: 2.25s
650:	total: 4.29s	remaining: 1.92s
700:	total: 4.59s	remaining: 1.58s
750:	total: 4.88s	remaining: 1.24s
800:	total: 5.21s	remaining: 918ms
850:	total: 5.52s	remaining: 590ms
900:	total: 5.82s	remaining: 265ms
941:	total: 6.04s	remaining: 0us
0:	total: 6.39ms	remaining: 6.02s
50:	total: 322ms	remaining: 5.62s
100:	total: 769ms	remaining: 6.41s
150:	total: 1.24s	remaining: 6.48s
200:	total: 1.63s	remaining: 5.99s
250:	total: 1.94s	remaining: 5.33s
300:	total: 2.24s	remaining: 4.76s
350:	total: 2.54s	remaining: 4.29s
400:	total: 2.85s	remaining: 3.85s
450:	total: 3.17s	remaining: 3.45s
500:	total: 3.46s	remaining: 3.04s
550:	total: 3.75s	remaining: 2.66s
600:	total: 4.04s	remaining: 2.29s
650:	total: 4.34s	remaining: 1.94s
700:	total: 4.61s	remaining: 1.59s
750:	total: 4.92s	remaining: 1.25s
800:	total: 5.23s	remaining: 921ms
850:	total: 5.55s	remaining: 593ms
900:	total: 5.87s	remaining: 267ms
941:	total: 6.11s	remaining: 0us
0:	total: 6.73ms	remaining: 6.33s
50:	total: 280ms	remaining: 4.89s
100:	total: 598ms	remaining: 4.98s
150:	total: 1.07s	remaining: 5.6s
200:	total: 1.4s	remaining: 5.16s
250:	total: 1.7s	remaining: 4.69s
300:	total: 2.08s	remaining: 4.42s
350:	total: 2.38s	remaining: 4.01s
400:	total: 2.67s	remaining: 3.61s
450:	total: 2.99s	remaining: 3.26s
500:	total: 3.34s	remaining: 2.94s
550:	total: 3.7s	remaining: 2.63s
600:	total: 4.04s	remaining: 2.29s
650:	total: 4.45s	remaining: 1.99s
700:	total: 4.76s	remaining: 1.64s
750:	total: 5.06s	remaining: 1.29s
800:	total: 5.41s	remaining: 953ms
850:	total: 5.78s	remaining: 618ms
900:	total: 6.23s	remaining: 284ms
941:	total: 6.71s	remaining: 0us
0:	total: 9.02ms	remaining: 8.49s
50:	total: 363ms	remaining: 6.34s
100:	total: 705ms	remaining: 5.87s
150:	total: 1s	remaining: 5.26s
200:	total: 1.39s	remaining: 5.13s
250:	total: 1.71s	remaining: 4.7s
300:	total: 2.14s	remaining: 4.57s
350:	total: 2.54s	remaining: 4.28s
400:	total: 2.97s	remaining: 4.01s
450:	total: 3.39s	remaining: 3.69s
500:	total: 3.93s	remaining: 3.46s
550:	total: 4.28s	remaining: 3.03s
600:	total: 4.59s	remaining: 2.6s
650:	total: 4.87s	remaining: 2.18s
700:	total: 5.21s	remaining: 1.79s
750:	total: 5.61s	remaining: 1.43s
800:	total: 6.04s	remaining: 1.06s
850:	total: 6.37s	remaining: 681ms
900:	total: 6.68s	remaining: 304ms
941:	total: 6.92s	remaining: 0us
0:	total: 7.95ms	remaining: 7.49s
50:	total: 298ms	remaining: 5.21s
100:	total: 642ms	remaining: 5.35s
150:	total: 936ms	remaining: 4.9s
200:	total: 1.23s	remaining: 4.52s
250:	total: 1.51s	remaining: 4.17s
300:	total: 1.8s	remaining: 3.84s
350:	total: 2.1s	remaining: 3.53s
400:	total: 2.38s	remaining: 3.21s
450:	total: 2.67s	remaining: 2.91s
500:	total: 2.98s	remaining: 2.62s
550:	total: 3.33s	remaining: 2.36s
600:	total: 3.66s	remaining: 2.08s
650:	total: 3.97s	remaining: 1.77s
700:	total: 4.25s	remaining: 1.46s
750:	total: 4.54s	remaining: 1.15s
800:	total: 4.85s	remaining: 855ms
850:	total: 5.28s	remaining: 565ms
900:	total: 5.72s	remaining: 260ms

[I 2025-11-24 20:35:53,566] Trial 76 finished with value: 0.7091203161862626 and parameters: {'weight_pos': 1.176379048469208, 'iterations': 942, 'learning_rate': 0.10340078369715636, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.8846729738171296, 'bagging_temperature': 0.6713573446388696, 'rsm': 0.5441183799306973, 'min_data_in_leaf': 41, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

941:	total: 6.08s	remaining: 0us
0:	total: 10.9ms	remaining: 10.7s
50:	total: 617ms	remaining: 11.2s
100:	total: 1.01s	remaining: 8.72s
150:	total: 1.37s	remaining: 7.47s
200:	total: 1.72s	remaining: 6.63s
250:	total: 2.08s	remaining: 5.99s
300:	total: 2.45s	remaining: 5.48s
350:	total: 2.87s	remaining: 5.1s
400:	total: 3.3s	remaining: 4.72s
450:	total: 3.73s	remaining: 4.33s
500:	total: 4.28s	remaining: 4.05s
550:	total: 4.75s	remaining: 3.65s
600:	total: 5.13s	remaining: 3.19s
650:	total: 5.51s	remaining: 2.74s
700:	total: 5.9s	remaining: 2.31s
750:	total: 6.3s	remaining: 1.88s
800:	total: 6.7s	remaining: 1.46s
850:	total: 7.07s	remaining: 1.03s
900:	total: 7.46s	remaining: 612ms
950:	total: 7.85s	remaining: 198ms
974:	total: 8.13s	remaining: 0us
0:	total: 6.93ms	remaining: 6.75s
50:	total: 369ms	remaining: 6.69s
100:	total: 724ms	remaining: 6.26s
150:	total: 1.15s	remaining: 6.27s
200:	total: 1.53s	remaining: 5.88s
250:	total: 1.91s	remaining: 5.5s
300:	total: 2.55s	remaining: 5.72s
350:	total: 2.92s	remaining: 5.19s
400:	total: 3.32s	remaining: 4.76s
450:	total: 3.7s	remaining: 4.3s
500:	total: 4.07s	remaining: 3.85s
550:	total: 4.43s	remaining: 3.41s
600:	total: 4.8s	remaining: 2.98s
650:	total: 5.16s	remaining: 2.57s
700:	total: 5.56s	remaining: 2.17s
750:	total: 5.95s	remaining: 1.77s
800:	total: 6.36s	remaining: 1.38s
850:	total: 6.82s	remaining: 994ms
900:	total: 7.22s	remaining: 593ms
950:	total: 7.83s	remaining: 198ms
974:	total: 8.23s	remaining: 0us
0:	total: 15.3ms	remaining: 14.9s
50:	total: 834ms	remaining: 15.1s
100:	total: 1.49s	remaining: 12.9s
150:	total: 1.88s	remaining: 10.3s
200:	total: 2.25s	remaining: 8.67s
250:	total: 2.62s	remaining: 7.56s
300:	total: 3.03s	remaining: 6.78s
350:	total: 3.41s	remaining: 6.06s
400:	total: 4.01s	remaining: 5.74s
450:	total: 4.38s	remaining: 5.09s
500:	total: 4.75s	remaining: 4.49s
550:	total: 5.12s	remaining: 3.94s
600:	total: 5.5s	remaining: 3.42s
650:	total: 5.87s	remaining: 2.92s
700:	total: 6.24s	remaining: 2.44s
750:	total: 6.64s	remaining: 1.98s
800:	total: 7.03s	remaining: 1.53s
850:	total: 7.48s	remaining: 1.09s
900:	total: 8.31s	remaining: 683ms
950:	total: 8.72s	remaining: 220ms
974:	total: 8.9s	remaining: 0us
0:	total: 10ms	remaining: 9.76s
50:	total: 378ms	remaining: 6.85s
100:	total: 749ms	remaining: 6.48s
150:	total: 1.22s	remaining: 6.66s
200:	total: 1.64s	remaining: 6.33s
250:	total: 2.02s	remaining: 5.82s
300:	total: 2.37s	remaining: 5.3s
350:	total: 2.72s	remaining: 4.84s
400:	total: 3.1s	remaining: 4.43s
450:	total: 3.82s	remaining: 4.44s
500:	total: 4.26s	remaining: 4.03s
550:	total: 5.12s	remaining: 3.94s
600:	total: 5.63s	remaining: 3.51s
650:	total: 6.01s	remaining: 2.99s
700:	total: 6.39s	remaining: 2.5s
750:	total: 6.77s	remaining: 2.02s
800:	total: 7.13s	remaining: 1.55s
850:	total: 7.51s	remaining: 1.09s
900:	total: 7.89s	remaining: 648ms
950:	total: 8.26s	remaining: 209ms
974:	total: 8.47s	remaining: 0us
0:	total: 7.92ms	remaining: 7.72s
50:	total: 354ms	remaining: 6.4s
100:	total: 766ms	remaining: 6.63s
150:	total: 1.12s	remaining: 6.1s
200:	total: 1.5s	remaining: 5.76s
250:	total: 1.86s	remaining: 5.38s
300:	total: 2.21s	remaining: 4.96s
350:	total: 2.58s	remaining: 4.58s
400:	total: 2.96s	remaining: 4.23s
450:	total: 3.31s	remaining: 3.84s
500:	total: 3.68s	remaining: 3.48s
550:	total: 4.08s	remaining: 3.14s
600:	total: 4.49s	remaining: 2.79s
650:	total: 4.93s	remaining: 2.45s
700:	total: 5.39s	remaining: 2.11s
750:	total: 5.86s	remaining: 1.75s
800:	total: 6.9s	remaining: 1.5s
850:	total: 7.37s	remaining: 1.07s
900:	total: 7.78s	remaining: 639ms
950:	total: 8.17s	remaining: 206ms
974:	total: 8.36s	remaining: 0us

[I 2025-11-24 20:36:36,453] Trial 77 finished with value: 0.7254657856713892 and parameters: {'weight_pos': 1.862073604020575, 'iterations': 975, 'learning_rate': 0.06353853322111519, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 4.1690833221053785, 'bagging_temperature': 0.7236285598184726, 'rsm': 0.4798133334531835, 'min_data_in_leaf': 24, 'leaf_estimation_iterations': 7}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 58.3ms	remaining: 58s
50:	total: 1.64s	remaining: 30.3s
100:	total: 3.11s	remaining: 27.6s
150:	total: 4.59s	remaining: 25.7s
200:	total: 6.12s	remaining: 24.2s
250:	total: 8.15s	remaining: 24.2s
300:	total: 10.1s	remaining: 23.2s
350:	total: 12s	remaining: 22.1s
400:	total: 14.3s	remaining: 21.2s
450:	total: 15.9s	remaining: 19.2s
500:	total: 17.6s	remaining: 17.4s
550:	total: 19.2s	remaining: 15.5s
600:	total: 21s	remaining: 13.8s
650:	total: 22.6s	remaining: 12s
700:	total: 24.2s	remaining: 10.2s
750:	total: 25.7s	remaining: 8.39s
800:	total: 27.3s	remaining: 6.64s
850:	total: 29.1s	remaining: 4.95s
900:	total: 30.6s	remaining: 3.22s
950:	total: 32.1s	remaining: 1.52s
995:	total: 33.6s	remaining: 0us
0:	total: 10.7ms	remaining: 10.7s
50:	total: 1.53s	remaining: 28.4s
100:	total: 3.08s	remaining: 27.3s
150:	total: 4.62s	remaining: 25.9s
200:	total: 6.06s	remaining: 24s
250:	total: 7.68s	remaining: 22.8s
300:	total: 9.83s	remaining: 22.7s
350:	total: 11.4s	remaining: 21s
400:	total: 12.9s	remaining: 19.1s
450:	total: 14.6s	remaining: 17.6s
500:	total: 16.4s	remaining: 16.2s
550:	total: 17.9s	remaining: 14.4s
600:	total: 19.6s	remaining: 12.8s
650:	total: 22.2s	remaining: 11.8s
700:	total: 23.9s	remaining: 10.1s
750:	total: 25.5s	remaining: 8.31s
800:	total: 27.1s	remaining: 6.61s
850:	total: 28.7s	remaining: 4.89s
900:	total: 30.3s	remaining: 3.19s
950:	total: 31.8s	remaining: 1.51s
995:	total: 33.2s	remaining: 0us
0:	total: 9.87ms	remaining: 9.82s
50:	total: 1.73s	remaining: 32s
100:	total: 3.25s	remaining: 28.8s
150:	total: 5.66s	remaining: 31.7s
200:	total: 7.86s	remaining: 31.1s
250:	total: 9.57s	remaining: 28.4s
300:	total: 11.6s	remaining: 26.8s
350:	total: 13.9s	remaining: 25.6s
400:	total: 15.5s	remaining: 23s
450:	total: 17.2s	remaining: 20.8s
500:	total: 18.9s	remaining: 18.6s
550:	total: 20.7s	remaining: 16.8s
600:	total: 22.3s	remaining: 14.7s
650:	total: 23.9s	remaining: 12.7s
700:	total: 25.4s	remaining: 10.7s
750:	total: 27.3s	remaining: 8.91s
800:	total: 29.1s	remaining: 7.08s
850:	total: 31.3s	remaining: 5.33s
900:	total: 33s	remaining: 3.48s
950:	total: 34.7s	remaining: 1.64s
995:	total: 36.3s	remaining: 0us
0:	total: 24.3ms	remaining: 24.2s
50:	total: 1.74s	remaining: 32.2s
100:	total: 3.42s	remaining: 30.3s
150:	total: 5.33s	remaining: 29.9s
200:	total: 6.87s	remaining: 27.2s
250:	total: 8.41s	remaining: 25s
300:	total: 10s	remaining: 23.2s
350:	total: 11.7s	remaining: 21.5s
400:	total: 13.3s	remaining: 19.7s
450:	total: 15.1s	remaining: 18.2s
500:	total: 16.8s	remaining: 16.6s
550:	total: 18.4s	remaining: 14.9s
600:	total: 20.1s	remaining: 13.2s
650:	total: 21.7s	remaining: 11.5s
700:	total: 23.4s	remaining: 9.83s
750:	total: 25.5s	remaining: 8.32s
800:	total: 27.8s	remaining: 6.76s
850:	total: 29.5s	remaining: 5.03s
900:	total: 31.1s	remaining: 3.28s
950:	total: 32.6s	remaining: 1.54s
995:	total: 34.1s	remaining: 0us
0:	total: 9.13ms	remaining: 9.09s
50:	total: 1.61s	remaining: 29.8s
100:	total: 3.14s	remaining: 27.9s
150:	total: 4.75s	remaining: 26.6s
200:	total: 6.36s	remaining: 25.2s
250:	total: 7.82s	remaining: 23.2s
300:	total: 9.45s	remaining: 21.8s
350:	total: 11.1s	remaining: 20.4s
400:	total: 12.7s	remaining: 18.8s
450:	total: 14.2s	remaining: 17.2s
500:	total: 15.7s	remaining: 15.5s
550:	total: 17.2s	remaining: 13.9s
600:	total: 18.7s	remaining: 12.3s
650:	total: 20.4s	remaining: 10.8s
700:	total: 22.1s	remaining: 9.31s
750:	total: 23.9s	remaining: 7.79s
800:	total: 25.5s	remaining: 6.2s
850:	total: 27.3s	remaining: 4.64s
900:	total: 29.4s	remaining: 3.1s
950:	total: 31.6s	remaining: 1.5s

[I 2025-11-24 20:39:28,622] Trial 78 finished with value: 0.6976195856340693 and parameters: {'weight_pos': 1.4850210638052022, 'iterations': 996, 'learning_rate': 0.06833737173606741, 'depth': 9, 'eval_metric': 'AUC', 'l2_leaf_reg': 1.8264978964512695, 'bagging_temperature': 0.4810344761031781, 'rsm': 0.6564576912740883, 'min_data_in_leaf': 36, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

995:	total: 33.1s	remaining: 0us
0:	total: 14.7ms	remaining: 13.8s
50:	total: 290ms	remaining: 5.05s
100:	total: 581ms	remaining: 4.82s
150:	total: 863ms	remaining: 4.5s
200:	total: 1.15s	remaining: 4.21s
250:	total: 1.46s	remaining: 4.01s
300:	total: 1.76s	remaining: 3.74s
350:	total: 2.07s	remaining: 3.47s
400:	total: 2.44s	remaining: 3.27s
450:	total: 2.8s	remaining: 3.03s
500:	total: 3.15s	remaining: 2.75s
550:	total: 3.5s	remaining: 2.46s
600:	total: 3.82s	remaining: 2.15s
650:	total: 4.18s	remaining: 1.85s
700:	total: 4.5s	remaining: 1.53s
750:	total: 4.81s	remaining: 1.2s
800:	total: 5.13s	remaining: 883ms
850:	total: 5.7s	remaining: 589ms
900:	total: 6.03s	remaining: 254ms
938:	total: 6.28s	remaining: 0us
0:	total: 6.17ms	remaining: 5.79s
50:	total: 298ms	remaining: 5.18s
100:	total: 604ms	remaining: 5.01s
150:	total: 924ms	remaining: 4.82s
200:	total: 1.23s	remaining: 4.53s
250:	total: 1.55s	remaining: 4.25s
300:	total: 1.83s	remaining: 3.89s
350:	total: 2.13s	remaining: 3.57s
400:	total: 2.43s	remaining: 3.25s
450:	total: 2.74s	remaining: 2.96s
500:	total: 3.04s	remaining: 2.66s
550:	total: 3.34s	remaining: 2.35s
600:	total: 3.66s	remaining: 2.06s
650:	total: 3.95s	remaining: 1.75s
700:	total: 4.25s	remaining: 1.44s
750:	total: 4.62s	remaining: 1.16s
800:	total: 5.13s	remaining: 883ms
850:	total: 5.56s	remaining: 575ms
900:	total: 5.93s	remaining: 250ms
938:	total: 6.21s	remaining: 0us
0:	total: 8.37ms	remaining: 7.85s
50:	total: 346ms	remaining: 6.03s
100:	total: 684ms	remaining: 5.68s
150:	total: 1.02s	remaining: 5.3s
200:	total: 1.35s	remaining: 4.97s
250:	total: 1.68s	remaining: 4.6s
300:	total: 2s	remaining: 4.23s
350:	total: 2.32s	remaining: 3.88s
400:	total: 3s	remaining: 4.02s
450:	total: 3.52s	remaining: 3.81s
500:	total: 3.92s	remaining: 3.43s
550:	total: 4.25s	remaining: 3s
600:	total: 4.59s	remaining: 2.58s
650:	total: 4.9s	remaining: 2.17s
700:	total: 5.24s	remaining: 1.78s
750:	total: 5.59s	remaining: 1.4s
800:	total: 5.93s	remaining: 1.02s
850:	total: 6.28s	remaining: 650ms
900:	total: 6.61s	remaining: 279ms
938:	total: 6.87s	remaining: 0us
0:	total: 6.73ms	remaining: 6.31s
50:	total: 357ms	remaining: 6.22s
100:	total: 687ms	remaining: 5.7s
150:	total: 1.02s	remaining: 5.34s
200:	total: 1.34s	remaining: 4.93s
250:	total: 1.66s	remaining: 4.56s
300:	total: 1.98s	remaining: 4.2s
350:	total: 2.31s	remaining: 3.87s
400:	total: 2.64s	remaining: 3.54s
450:	total: 2.99s	remaining: 3.23s
500:	total: 3.32s	remaining: 2.9s
550:	total: 3.65s	remaining: 2.57s
600:	total: 3.97s	remaining: 2.23s
650:	total: 4.29s	remaining: 1.9s
700:	total: 4.62s	remaining: 1.57s
750:	total: 4.96s	remaining: 1.24s
800:	total: 5.28s	remaining: 910ms
850:	total: 5.75s	remaining: 595ms
900:	total: 6.13s	remaining: 259ms
938:	total: 6.4s	remaining: 0us
0:	total: 7.17ms	remaining: 6.73s
50:	total: 324ms	remaining: 5.65s
100:	total: 647ms	remaining: 5.37s
150:	total: 968ms	remaining: 5.05s
200:	total: 1.28s	remaining: 4.7s
250:	total: 1.59s	remaining: 4.37s
300:	total: 1.92s	remaining: 4.08s
350:	total: 2.25s	remaining: 3.77s
400:	total: 2.58s	remaining: 3.46s
450:	total: 2.91s	remaining: 3.15s
500:	total: 3.23s	remaining: 2.82s
550:	total: 3.56s	remaining: 2.5s
600:	total: 3.9s	remaining: 2.19s
650:	total: 4.22s	remaining: 1.87s
700:	total: 4.54s	remaining: 1.54s
750:	total: 4.86s	remaining: 1.22s
800:	total: 5.19s	remaining: 894ms
850:	total: 5.51s	remaining: 570ms
900:	total: 5.84s	remaining: 246ms

[I 2025-11-24 20:40:01,180] Trial 79 finished with value: 0.7271831961266495 and parameters: {'weight_pos': 3.0908851777932367, 'iterations': 939, 'learning_rate': 0.05051327985932259, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.4034714824642446, 'bagging_temperature': 0.5831002907074251, 'rsm': 0.5872214829450506, 'min_data_in_leaf': 33, 'leaf_estimation_iterations': 6}. Best is trial 16 with value: 0.7404863910277388.

938:	total: 6.08s	remaining: 0us
0:	total: 7.44ms	remaining: 6.74s
50:	total: 320ms	remaining: 5.36s
100:	total: 629ms	remaining: 5.02s
150:	total: 926ms	remaining: 4.63s
200:	total: 1.21s	remaining: 4.25s
250:	total: 1.51s	remaining: 3.94s
300:	total: 1.81s	remaining: 3.63s
350:	total: 2.1s	remaining: 3.33s
400:	total: 2.42s	remaining: 3.04s
450:	total: 2.74s	remaining: 2.76s
500:	total: 3.24s	remaining: 2.62s
550:	total: 3.55s	remaining: 2.29s
600:	total: 3.87s	remaining: 1.96s
650:	total: 4.19s	remaining: 1.64s
700:	total: 4.51s	remaining: 1.32s
750:	total: 4.85s	remaining: 1s
800:	total: 5.25s	remaining: 689ms
850:	total: 5.67s	remaining: 367ms
900:	total: 6.06s	remaining: 33.6ms
905:	total: 6.1s	remaining: 0us
0:	total: 8.37ms	remaining: 7.58s
50:	total: 335ms	remaining: 5.61s
100:	total: 648ms	remaining: 5.17s
150:	total: 950ms	remaining: 4.75s
200:	total: 1.28s	remaining: 4.48s
250:	total: 1.59s	remaining: 4.15s
300:	total: 1.9s	remaining: 3.81s
350:	total: 2.24s	remaining: 3.55s
400:	total: 2.56s	remaining: 3.22s
450:	total: 2.86s	remaining: 2.89s
500:	total: 3.19s	remaining: 2.58s
550:	total: 3.56s	remaining: 2.29s
600:	total: 3.86s	remaining: 1.96s
650:	total: 4.17s	remaining: 1.63s
700:	total: 4.48s	remaining: 1.31s
750:	total: 4.78s	remaining: 987ms
800:	total: 5.08s	remaining: 665ms
850:	total: 5.38s	remaining: 348ms
900:	total: 5.69s	remaining: 31.6ms
905:	total: 5.71s	remaining: 0us
0:	total: 7.43ms	remaining: 6.72s
50:	total: 288ms	remaining: 4.83s
100:	total: 580ms	remaining: 4.62s
150:	total: 1.04s	remaining: 5.22s
200:	total: 1.41s	remaining: 4.96s
250:	total: 1.77s	remaining: 4.61s
300:	total: 2.08s	remaining: 4.17s
350:	total: 2.38s	remaining: 3.76s
400:	total: 2.67s	remaining: 3.37s
450:	total: 2.96s	remaining: 2.99s
500:	total: 3.27s	remaining: 2.65s
550:	total: 3.61s	remaining: 2.32s
600:	total: 3.94s	remaining: 2s
650:	total: 4.24s	remaining: 1.66s
700:	total: 4.58s	remaining: 1.34s
750:	total: 4.92s	remaining: 1.02s
800:	total: 5.27s	remaining: 691ms
850:	total: 5.62s	remaining: 363ms
900:	total: 6s	remaining: 33.3ms
905:	total: 6.04s	remaining: 0us
0:	total: 7.99ms	remaining: 7.23s
50:	total: 362ms	remaining: 6.07s
100:	total: 698ms	remaining: 5.57s
150:	total: 1.23s	remaining: 6.17s
200:	total: 1.68s	remaining: 5.91s
250:	total: 2.01s	remaining: 5.24s
300:	total: 2.33s	remaining: 4.68s
350:	total: 2.64s	remaining: 4.17s
400:	total: 2.95s	remaining: 3.72s
450:	total: 3.31s	remaining: 3.33s
500:	total: 3.64s	remaining: 2.94s
550:	total: 3.97s	remaining: 2.56s
600:	total: 4.29s	remaining: 2.17s
650:	total: 4.83s	remaining: 1.89s
700:	total: 5.22s	remaining: 1.53s
750:	total: 5.57s	remaining: 1.15s
800:	total: 5.95s	remaining: 780ms
850:	total: 6.35s	remaining: 410ms
900:	total: 6.7s	remaining: 37.2ms
905:	total: 6.73s	remaining: 0us
0:	total: 8.13ms	remaining: 7.36s
50:	total: 385ms	remaining: 6.45s
100:	total: 719ms	remaining: 5.73s
150:	total: 1.05s	remaining: 5.24s
200:	total: 1.4s	remaining: 4.92s
250:	total: 1.72s	remaining: 4.5s
300:	total: 2.02s	remaining: 4.05s
350:	total: 2.34s	remaining: 3.7s
400:	total: 2.65s	remaining: 3.34s
450:	total: 2.95s	remaining: 2.97s
500:	total: 3.26s	remaining: 2.64s
550:	total: 3.58s	remaining: 2.31s
600:	total: 3.89s	remaining: 1.97s
650:	total: 4.19s	remaining: 1.64s
700:	total: 4.48s	remaining: 1.31s
750:	total: 4.77s	remaining: 984ms
800:	total: 5.07s	remaining: 665ms
850:	total: 5.38s	remaining: 347ms

[I 2025-11-24 20:40:32,258] Trial 80 finished with value: 0.7341022491692379 and parameters: {'weight_pos': 2.0325250008665505, 'iterations': 906, 'learning_rate': 0.03960222553648234, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 7.368806617525244, 'bagging_temperature': 0.5606320882138383, 'rsm': 0.4337335469898383, 'min_data_in_leaf': 53, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 5.72s	remaining: 31.8ms
905:	total: 5.76s	remaining: 0us
0:	total: 7.48ms	remaining: 6.83s
50:	total: 298ms	remaining: 5.05s
100:	total: 589ms	remaining: 4.74s
150:	total: 867ms	remaining: 4.38s
200:	total: 1.14s	remaining: 4.03s
250:	total: 1.41s	remaining: 3.73s
300:	total: 1.78s	remaining: 3.62s
350:	total: 2.19s	remaining: 3.52s
400:	total: 2.48s	remaining: 3.18s
450:	total: 2.77s	remaining: 2.84s
500:	total: 3.12s	remaining: 2.57s
550:	total: 3.57s	remaining: 2.35s
600:	total: 4.05s	remaining: 2.11s
650:	total: 4.6s	remaining: 1.86s
700:	total: 5.06s	remaining: 1.54s
750:	total: 5.45s	remaining: 1.18s
800:	total: 5.89s	remaining: 831ms
850:	total: 6.32s	remaining: 468ms
900:	total: 6.63s	remaining: 95.7ms
913:	total: 6.71s	remaining: 0us
0:	total: 7.51ms	remaining: 6.86s
50:	total: 306ms	remaining: 5.17s
100:	total: 596ms	remaining: 4.8s
150:	total: 884ms	remaining: 4.47s
200:	total: 1.17s	remaining: 4.14s
250:	total: 1.45s	remaining: 3.83s
300:	total: 1.73s	remaining: 3.53s
350:	total: 2.01s	remaining: 3.23s
400:	total: 2.3s	remaining: 2.94s
450:	total: 2.58s	remaining: 2.65s
500:	total: 2.88s	remaining: 2.38s
550:	total: 3.19s	remaining: 2.1s
600:	total: 3.47s	remaining: 1.81s
650:	total: 3.75s	remaining: 1.51s
700:	total: 4.03s	remaining: 1.22s
750:	total: 4.31s	remaining: 936ms
800:	total: 4.6s	remaining: 649ms
850:	total: 5.05s	remaining: 374ms
900:	total: 5.4s	remaining: 77.9ms
913:	total: 5.48s	remaining: 0us
0:	total: 7.14ms	remaining: 6.51s
50:	total: 274ms	remaining: 4.63s
100:	total: 545ms	remaining: 4.39s
150:	total: 824ms	remaining: 4.17s
200:	total: 1.11s	remaining: 3.93s
250:	total: 1.38s	remaining: 3.64s
300:	total: 1.82s	remaining: 3.71s
350:	total: 2.14s	remaining: 3.43s
400:	total: 2.42s	remaining: 3.09s
450:	total: 2.71s	remaining: 2.79s
500:	total: 3s	remaining: 2.47s
550:	total: 3.28s	remaining: 2.16s
600:	total: 3.55s	remaining: 1.85s
650:	total: 3.83s	remaining: 1.55s
700:	total: 4.13s	remaining: 1.25s
750:	total: 4.41s	remaining: 958ms
800:	total: 4.69s	remaining: 661ms
850:	total: 4.97s	remaining: 368ms
900:	total: 5.26s	remaining: 76ms
913:	total: 5.34s	remaining: 0us
0:	total: 9.33ms	remaining: 8.52s
50:	total: 283ms	remaining: 4.79s
100:	total: 595ms	remaining: 4.79s
150:	total: 883ms	remaining: 4.46s
200:	total: 1.2s	remaining: 4.25s
250:	total: 1.5s	remaining: 3.96s
300:	total: 1.78s	remaining: 3.62s
350:	total: 2.08s	remaining: 3.34s
400:	total: 2.38s	remaining: 3.04s
450:	total: 2.68s	remaining: 2.75s
500:	total: 3s	remaining: 2.47s
550:	total: 3.29s	remaining: 2.17s
600:	total: 3.59s	remaining: 1.87s
650:	total: 4.04s	remaining: 1.63s
700:	total: 4.41s	remaining: 1.34s
750:	total: 4.7s	remaining: 1.02s
800:	total: 4.99s	remaining: 704ms
850:	total: 5.28s	remaining: 391ms
900:	total: 5.58s	remaining: 80.5ms
913:	total: 5.66s	remaining: 0us
0:	total: 7.28ms	remaining: 6.64s
50:	total: 278ms	remaining: 4.71s
100:	total: 575ms	remaining: 4.63s
150:	total: 860ms	remaining: 4.35s
200:	total: 1.14s	remaining: 4.06s
250:	total: 1.41s	remaining: 3.73s
300:	total: 1.7s	remaining: 3.45s
350:	total: 1.98s	remaining: 3.17s
400:	total: 2.26s	remaining: 2.89s
450:	total: 2.53s	remaining: 2.6s
500:	total: 2.83s	remaining: 2.34s
550:	total: 3.13s	remaining: 2.06s
600:	total: 3.42s	remaining: 1.78s
650:	total: 3.71s	remaining: 1.5s
700:	total: 3.99s	remaining: 1.21s
750:	total: 4.28s	remaining: 928ms
800:	total: 4.56s	remaining: 644ms
850:	total: 4.85s	remaining: 359ms

[I 2025-11-24 20:41:01,328] Trial 81 finished with value: 0.7302353415799748 and parameters: {'weight_pos': 2.040287571792902, 'iterations': 914, 'learning_rate': 0.040392507724266585, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 18.1811318061571, 'bagging_temperature': 0.5567945187665231, 'rsm': 0.43493019305244807, 'min_data_in_leaf': 52, 'leaf_estimation_iterations': 7}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 5.16s	remaining: 74.4ms
913:	total: 5.24s	remaining: 0us
0:	total: 17.2ms	remaining: 16.6s
50:	total: 416ms	remaining: 7.43s
100:	total: 782ms	remaining: 6.68s
150:	total: 1.21s	remaining: 6.5s
200:	total: 1.66s	remaining: 6.28s
250:	total: 2.1s	remaining: 5.95s
300:	total: 2.48s	remaining: 5.46s
350:	total: 3.17s	remaining: 5.53s
400:	total: 3.73s	remaining: 5.23s
450:	total: 4.41s	remaining: 5s
500:	total: 5.01s	remaining: 4.62s
550:	total: 5.52s	remaining: 4.12s
600:	total: 5.95s	remaining: 3.58s
650:	total: 6.37s	remaining: 3.05s
700:	total: 6.8s	remaining: 2.54s
750:	total: 7.23s	remaining: 2.04s
800:	total: 7.66s	remaining: 1.55s
850:	total: 8.09s	remaining: 1.06s
900:	total: 8.5s	remaining: 585ms
950:	total: 8.86s	remaining: 112ms
962:	total: 8.95s	remaining: 0us
0:	total: 7.06ms	remaining: 6.79s
50:	total: 446ms	remaining: 7.97s
100:	total: 900ms	remaining: 7.68s
150:	total: 1.26s	remaining: 6.78s
200:	total: 1.63s	remaining: 6.16s
250:	total: 2.01s	remaining: 5.7s
300:	total: 2.37s	remaining: 5.22s
350:	total: 2.74s	remaining: 4.77s
400:	total: 3.08s	remaining: 4.31s
450:	total: 3.47s	remaining: 3.94s
500:	total: 3.99s	remaining: 3.68s
550:	total: 4.35s	remaining: 3.26s
600:	total: 4.7s	remaining: 2.83s
650:	total: 5.08s	remaining: 2.44s
700:	total: 5.47s	remaining: 2.04s
750:	total: 5.83s	remaining: 1.64s
800:	total: 6.21s	remaining: 1.25s
850:	total: 6.56s	remaining: 864ms
900:	total: 6.91s	remaining: 476ms
950:	total: 7.27s	remaining: 91.7ms
962:	total: 7.35s	remaining: 0us
0:	total: 5.39ms	remaining: 5.19s
50:	total: 336ms	remaining: 6s
100:	total: 678ms	remaining: 5.79s
150:	total: 1.01s	remaining: 5.41s
200:	total: 1.33s	remaining: 5.04s
250:	total: 1.66s	remaining: 4.71s
300:	total: 2.02s	remaining: 4.43s
350:	total: 2.4s	remaining: 4.18s
400:	total: 2.77s	remaining: 3.89s
450:	total: 3.16s	remaining: 3.58s
500:	total: 3.53s	remaining: 3.26s
550:	total: 3.91s	remaining: 2.93s
600:	total: 4.28s	remaining: 2.58s
650:	total: 4.64s	remaining: 2.22s
700:	total: 4.98s	remaining: 1.86s
750:	total: 5.32s	remaining: 1.5s
800:	total: 5.64s	remaining: 1.14s
850:	total: 6.02s	remaining: 792ms
900:	total: 6.53s	remaining: 450ms
950:	total: 6.88s	remaining: 86.8ms
962:	total: 6.98s	remaining: 0us
0:	total: 7.25ms	remaining: 6.98s
50:	total: 336ms	remaining: 6.02s
100:	total: 650ms	remaining: 5.55s
150:	total: 970ms	remaining: 5.22s
200:	total: 1.3s	remaining: 4.92s
250:	total: 1.64s	remaining: 4.64s
300:	total: 1.98s	remaining: 4.35s
350:	total: 2.31s	remaining: 4.02s
400:	total: 2.62s	remaining: 3.67s
450:	total: 2.94s	remaining: 3.34s
500:	total: 3.27s	remaining: 3.02s
550:	total: 3.6s	remaining: 2.69s
600:	total: 3.92s	remaining: 2.36s
650:	total: 4.26s	remaining: 2.04s
700:	total: 4.59s	remaining: 1.72s
750:	total: 4.93s	remaining: 1.39s
800:	total: 5.26s	remaining: 1.06s
850:	total: 5.6s	remaining: 738ms
900:	total: 5.93s	remaining: 408ms
950:	total: 6.27s	remaining: 79.1ms
962:	total: 6.35s	remaining: 0us
0:	total: 6.1ms	remaining: 5.87s
50:	total: 322ms	remaining: 5.76s
100:	total: 683ms	remaining: 5.83s
150:	total: 1.18s	remaining: 6.34s
200:	total: 1.64s	remaining: 6.21s
250:	total: 2.05s	remaining: 5.81s
300:	total: 2.57s	remaining: 5.65s
350:	total: 3.03s	remaining: 5.29s
400:	total: 3.37s	remaining: 4.72s
450:	total: 3.7s	remaining: 4.2s
500:	total: 4.03s	remaining: 3.72s
550:	total: 4.41s	remaining: 3.29s
600:	total: 4.79s	remaining: 2.88s
650:	total: 5.3s	remaining: 2.54s
700:	total: 5.9s	remaining: 2.21s
750:	total: 6.28s	remaining: 1.77s
800:	total: 6.62s	remaining: 1.34s
850:	total: 6.94s	remaining: 914ms
900:	total: 7.27s	remaining: 500ms

[I 2025-11-24 20:41:39,401] Trial 82 finished with value: 0.7276240415451966 and parameters: {'weight_pos': 2.667066300676739, 'iterations': 963, 'learning_rate': 0.0326890024070761, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 6.928633394508049, 'bagging_temperature': 0.6209769297839087, 'rsm': 0.5392159301531402, 'min_data_in_leaf': 51, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 7.59s	remaining: 95.8ms
962:	total: 7.67s	remaining: 0us
0:	total: 7.97ms	remaining: 6.93s
50:	total: 373ms	remaining: 6s
100:	total: 728ms	remaining: 5.54s
150:	total: 1.09s	remaining: 5.18s
200:	total: 1.47s	remaining: 4.88s
250:	total: 1.84s	remaining: 4.54s
300:	total: 2.23s	remaining: 4.22s
350:	total: 2.6s	remaining: 3.85s
400:	total: 2.98s	remaining: 3.49s
450:	total: 3.37s	remaining: 3.13s
500:	total: 3.77s	remaining: 2.78s
550:	total: 4.16s	remaining: 2.41s
600:	total: 4.6s	remaining: 2.06s
650:	total: 5.14s	remaining: 1.73s
700:	total: 5.53s	remaining: 1.33s
750:	total: 5.92s	remaining: 938ms
800:	total: 6.31s	remaining: 544ms
850:	total: 6.7s	remaining: 150ms
869:	total: 6.84s	remaining: 0us
0:	total: 8.54ms	remaining: 7.42s
50:	total: 400ms	remaining: 6.43s
100:	total: 776ms	remaining: 5.91s
150:	total: 1.16s	remaining: 5.53s
200:	total: 1.55s	remaining: 5.17s
250:	total: 1.95s	remaining: 4.81s
300:	total: 2.4s	remaining: 4.55s
350:	total: 3.07s	remaining: 4.54s
400:	total: 3.66s	remaining: 4.28s
450:	total: 4.07s	remaining: 3.78s
500:	total: 4.47s	remaining: 3.29s
550:	total: 4.87s	remaining: 2.82s
600:	total: 5.29s	remaining: 2.37s
650:	total: 5.7s	remaining: 1.92s
700:	total: 6.09s	remaining: 1.47s
750:	total: 6.5s	remaining: 1.03s
800:	total: 6.91s	remaining: 595ms
850:	total: 7.31s	remaining: 163ms
869:	total: 7.46s	remaining: 0us
0:	total: 12.8ms	remaining: 11.1s
50:	total: 587ms	remaining: 9.43s
100:	total: 983ms	remaining: 7.49s
150:	total: 1.36s	remaining: 6.46s
200:	total: 1.74s	remaining: 5.79s
250:	total: 2.12s	remaining: 5.22s
300:	total: 2.5s	remaining: 4.73s
350:	total: 2.88s	remaining: 4.26s
400:	total: 3.25s	remaining: 3.8s
450:	total: 3.62s	remaining: 3.37s
500:	total: 4s	remaining: 2.95s
550:	total: 4.37s	remaining: 2.53s
600:	total: 4.77s	remaining: 2.13s
650:	total: 5.16s	remaining: 1.74s
700:	total: 5.54s	remaining: 1.34s
750:	total: 5.93s	remaining: 940ms
800:	total: 6.33s	remaining: 545ms
850:	total: 6.71s	remaining: 150ms
869:	total: 6.85s	remaining: 0us
0:	total: 7.79ms	remaining: 6.77s
50:	total: 372ms	remaining: 5.97s
100:	total: 746ms	remaining: 5.68s
150:	total: 1.11s	remaining: 5.28s
200:	total: 1.47s	remaining: 4.9s
250:	total: 1.86s	remaining: 4.6s
300:	total: 2.33s	remaining: 4.4s
350:	total: 2.78s	remaining: 4.11s
400:	total: 3.73s	remaining: 4.36s
450:	total: 4.29s	remaining: 3.99s
500:	total: 4.75s	remaining: 3.5s
550:	total: 5.28s	remaining: 3.06s
600:	total: 5.7s	remaining: 2.55s
650:	total: 6.11s	remaining: 2.06s
700:	total: 6.5s	remaining: 1.57s
750:	total: 6.88s	remaining: 1.09s
800:	total: 7.29s	remaining: 628ms
850:	total: 7.68s	remaining: 171ms
869:	total: 7.83s	remaining: 0us
0:	total: 7.68ms	remaining: 6.67s
50:	total: 369ms	remaining: 5.93s
100:	total: 983ms	remaining: 7.49s
150:	total: 1.41s	remaining: 6.7s
200:	total: 1.93s	remaining: 6.44s
250:	total: 2.52s	remaining: 6.22s
300:	total: 3.06s	remaining: 5.78s
350:	total: 3.48s	remaining: 5.14s
400:	total: 3.92s	remaining: 4.59s
450:	total: 4.38s	remaining: 4.07s
500:	total: 4.81s	remaining: 3.54s
550:	total: 5.76s	remaining: 3.33s
600:	total: 6.3s	remaining: 2.82s
650:	total: 6.75s	remaining: 2.27s
700:	total: 7.2s	remaining: 1.73s
750:	total: 7.62s	remaining: 1.21s
800:	total: 8.04s	remaining: 693ms
850:	total: 8.48s	remaining: 189ms
869:	total: 8.65s	remaining: 0us

[I 2025-11-24 20:42:17,799] Trial 83 finished with value: 0.7161632533297185 and parameters: {'weight_pos': 3.9330474462954763, 'iterations': 870, 'learning_rate': 0.05048154153864975, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 0.9091597805299332, 'bagging_temperature': 0.5691530359960699, 'rsm': 0.46471509683208617, 'min_data_in_leaf': 43, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 11.2ms	remaining: 10.4s
50:	total: 586ms	remaining: 10.2s
100:	total: 1.17s	remaining: 9.67s
150:	total: 1.76s	remaining: 9.14s
200:	total: 2.38s	remaining: 8.69s
250:	total: 3.06s	remaining: 8.34s
300:	total: 3.66s	remaining: 7.7s
350:	total: 4.24s	remaining: 7.05s
400:	total: 4.86s	remaining: 6.46s
450:	total: 5.64s	remaining: 6.04s
500:	total: 6.54s	remaining: 5.66s
550:	total: 7.25s	remaining: 5.04s
600:	total: 7.85s	remaining: 4.35s
650:	total: 8.48s	remaining: 3.69s
700:	total: 9.15s	remaining: 3.04s
750:	total: 9.74s	remaining: 2.37s
800:	total: 10.3s	remaining: 1.71s
850:	total: 10.9s	remaining: 1.06s
900:	total: 11.5s	remaining: 420ms
933:	total: 11.9s	remaining: 0us
0:	total: 10.2ms	remaining: 9.54s
50:	total: 569ms	remaining: 9.84s
100:	total: 1.15s	remaining: 9.47s
150:	total: 1.74s	remaining: 9.03s
200:	total: 2.32s	remaining: 8.45s
250:	total: 2.94s	remaining: 7.99s
300:	total: 3.67s	remaining: 7.73s
350:	total: 4.42s	remaining: 7.34s
400:	total: 5.03s	remaining: 6.69s
450:	total: 5.6s	remaining: 6s
500:	total: 6.22s	remaining: 5.37s
550:	total: 6.86s	remaining: 4.77s
600:	total: 7.44s	remaining: 4.12s
650:	total: 8s	remaining: 3.48s
700:	total: 8.56s	remaining: 2.85s
750:	total: 9.12s	remaining: 2.22s
800:	total: 9.7s	remaining: 1.61s
850:	total: 10.3s	remaining: 1s
900:	total: 10.8s	remaining: 396ms
933:	total: 11.2s	remaining: 0us
0:	total: 11.8ms	remaining: 11s
50:	total: 562ms	remaining: 9.72s
100:	total: 1.13s	remaining: 9.29s
150:	total: 1.68s	remaining: 8.7s
200:	total: 2.24s	remaining: 8.18s
250:	total: 2.95s	remaining: 8.03s
300:	total: 3.6s	remaining: 7.57s
350:	total: 4.19s	remaining: 6.97s
400:	total: 4.74s	remaining: 6.3s
450:	total: 5.3s	remaining: 5.67s
500:	total: 5.88s	remaining: 5.08s
550:	total: 6.45s	remaining: 4.48s
600:	total: 7.02s	remaining: 3.89s
650:	total: 7.6s	remaining: 3.31s
700:	total: 8.18s	remaining: 2.72s
750:	total: 8.79s	remaining: 2.14s
800:	total: 9.55s	remaining: 1.58s
850:	total: 10.2s	remaining: 996ms
900:	total: 10.8s	remaining: 396ms
933:	total: 11.2s	remaining: 0us
0:	total: 10.7ms	remaining: 9.96s
50:	total: 555ms	remaining: 9.62s
100:	total: 1.14s	remaining: 9.37s
150:	total: 2s	remaining: 10.4s
200:	total: 2.8s	remaining: 10.2s
250:	total: 3.38s	remaining: 9.21s
300:	total: 3.95s	remaining: 8.31s
350:	total: 4.64s	remaining: 7.71s
400:	total: 5.27s	remaining: 7s
450:	total: 5.99s	remaining: 6.41s
500:	total: 6.56s	remaining: 5.67s
550:	total: 7.36s	remaining: 5.12s
600:	total: 8.03s	remaining: 4.45s
650:	total: 8.7s	remaining: 3.78s
700:	total: 9.33s	remaining: 3.1s
750:	total: 9.98s	remaining: 2.43s
800:	total: 10.6s	remaining: 1.76s
850:	total: 11.2s	remaining: 1.09s
900:	total: 12s	remaining: 440ms
933:	total: 12.5s	remaining: 0us
0:	total: 13.1ms	remaining: 12.2s
50:	total: 628ms	remaining: 10.9s
100:	total: 1.27s	remaining: 10.5s
150:	total: 1.94s	remaining: 10.1s
200:	total: 2.55s	remaining: 9.31s
250:	total: 3.15s	remaining: 8.56s
300:	total: 3.72s	remaining: 7.82s
350:	total: 4.32s	remaining: 7.17s
400:	total: 4.94s	remaining: 6.56s
450:	total: 5.52s	remaining: 5.91s
500:	total: 6.19s	remaining: 5.35s
550:	total: 6.78s	remaining: 4.71s
600:	total: 7.34s	remaining: 4.07s
650:	total: 7.93s	remaining: 3.45s
700:	total: 8.57s	remaining: 2.85s
750:	total: 9.58s	remaining: 2.33s
800:	total: 10.3s	remaining: 1.71s
850:	total: 10.9s	remaining: 1.06s
900:	total: 11.5s	remaining: 420ms

[I 2025-11-24 20:43:17,275] Trial 84 finished with value: 0.720144482074227 and parameters: {'weight_pos': 1.376941813982629, 'iterations': 934, 'learning_rate': 0.036087969326232094, 'depth': 6, 'eval_metric': 'AUC', 'l2_leaf_reg': 2.99212482380936, 'bagging_temperature': 0.5064849094120618, 'rsm': 0.5719835172811369, 'min_data_in_leaf': 62, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

933:	total: 11.8s	remaining: 0us
0:	total: 7.79ms	remaining: 7.01s
50:	total: 320ms	remaining: 5.34s
100:	total: 639ms	remaining: 5.06s
150:	total: 946ms	remaining: 4.7s
200:	total: 1.25s	remaining: 4.35s
250:	total: 1.57s	remaining: 4.07s
300:	total: 1.88s	remaining: 3.75s
350:	total: 2.19s	remaining: 3.43s
400:	total: 2.5s	remaining: 3.12s
450:	total: 2.83s	remaining: 2.82s
500:	total: 3.14s	remaining: 2.51s
550:	total: 3.47s	remaining: 2.21s
600:	total: 3.79s	remaining: 1.89s
650:	total: 4.13s	remaining: 1.58s
700:	total: 4.45s	remaining: 1.27s
750:	total: 4.79s	remaining: 956ms
800:	total: 5.13s	remaining: 640ms
850:	total: 5.49s	remaining: 322ms
900:	total: 5.8s	remaining: 0us
0:	total: 6.55ms	remaining: 5.89s
50:	total: 323ms	remaining: 5.39s
100:	total: 677ms	remaining: 5.36s
150:	total: 1.21s	remaining: 6.02s
200:	total: 1.86s	remaining: 6.48s
250:	total: 2.39s	remaining: 6.2s
300:	total: 2.87s	remaining: 5.72s
350:	total: 3.31s	remaining: 5.19s
400:	total: 3.74s	remaining: 4.66s
450:	total: 4.11s	remaining: 4.1s
500:	total: 4.44s	remaining: 3.54s
550:	total: 4.76s	remaining: 3.02s
600:	total: 5.08s	remaining: 2.53s
650:	total: 5.38s	remaining: 2.07s
700:	total: 5.7s	remaining: 1.63s
750:	total: 6s	remaining: 1.2s
800:	total: 6.3s	remaining: 787ms
850:	total: 6.6s	remaining: 388ms
900:	total: 6.91s	remaining: 0us
0:	total: 6.8ms	remaining: 6.12s
50:	total: 308ms	remaining: 5.14s
100:	total: 592ms	remaining: 4.69s
150:	total: 892ms	remaining: 4.43s
200:	total: 1.19s	remaining: 4.16s
250:	total: 1.49s	remaining: 3.86s
300:	total: 1.81s	remaining: 3.6s
350:	total: 2.12s	remaining: 3.32s
400:	total: 2.42s	remaining: 3.01s
450:	total: 2.73s	remaining: 2.72s
500:	total: 3.03s	remaining: 2.42s
550:	total: 3.34s	remaining: 2.12s
600:	total: 3.65s	remaining: 1.82s
650:	total: 4.17s	remaining: 1.6s
700:	total: 4.55s	remaining: 1.3s
750:	total: 4.92s	remaining: 983ms
800:	total: 5.27s	remaining: 658ms
850:	total: 5.63s	remaining: 331ms
900:	total: 5.98s	remaining: 0us
0:	total: 6.7ms	remaining: 6.03s
50:	total: 355ms	remaining: 5.91s
100:	total: 716ms	remaining: 5.67s
150:	total: 1.06s	remaining: 5.26s
200:	total: 1.4s	remaining: 4.89s
250:	total: 1.74s	remaining: 4.5s
300:	total: 2.07s	remaining: 4.12s
350:	total: 2.38s	remaining: 3.73s
400:	total: 2.71s	remaining: 3.38s
450:	total: 3.01s	remaining: 3s
500:	total: 3.39s	remaining: 2.71s
550:	total: 3.82s	remaining: 2.43s
600:	total: 4.27s	remaining: 2.13s
650:	total: 4.71s	remaining: 1.81s
700:	total: 5.17s	remaining: 1.48s
750:	total: 5.71s	remaining: 1.14s
800:	total: 6.2s	remaining: 774ms
850:	total: 6.63s	remaining: 390ms
900:	total: 6.99s	remaining: 0us
0:	total: 10.3ms	remaining: 9.31s
50:	total: 326ms	remaining: 5.44s
100:	total: 869ms	remaining: 6.88s
150:	total: 1.26s	remaining: 6.24s
200:	total: 1.57s	remaining: 5.47s
250:	total: 1.87s	remaining: 4.84s
300:	total: 2.17s	remaining: 4.32s
350:	total: 2.46s	remaining: 3.86s
400:	total: 2.77s	remaining: 3.45s
450:	total: 3.08s	remaining: 3.07s
500:	total: 3.39s	remaining: 2.71s
550:	total: 3.71s	remaining: 2.35s
600:	total: 4.03s	remaining: 2.01s
650:	total: 4.37s	remaining: 1.68s
700:	total: 4.68s	remaining: 1.34s
750:	total: 4.98s	remaining: 995ms
800:	total: 5.29s	remaining: 660ms
850:	total: 5.59s	remaining: 329ms

[I 2025-11-24 20:43:49,519] Trial 85 finished with value: 0.7333387787139203 and parameters: {'weight_pos': 2.301220783901146, 'iterations': 901, 'learning_rate': 0.05979121033439775, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 16.30371119333364, 'bagging_temperature': 0.44343763586634377, 'rsm': 0.4977041484237514, 'min_data_in_leaf': 69, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

900:	total: 5.89s	remaining: 0us
0:	total: 6.91ms	remaining: 6.2s
50:	total: 275ms	remaining: 4.58s
100:	total: 551ms	remaining: 4.34s
150:	total: 831ms	remaining: 4.11s
200:	total: 1.13s	remaining: 3.93s
250:	total: 1.42s	remaining: 3.65s
300:	total: 1.7s	remaining: 3.37s
350:	total: 2s	remaining: 3.12s
400:	total: 2.32s	remaining: 2.88s
450:	total: 2.61s	remaining: 2.59s
500:	total: 2.91s	remaining: 2.31s
550:	total: 3.19s	remaining: 2.01s
600:	total: 3.48s	remaining: 1.72s
650:	total: 3.76s	remaining: 1.43s
700:	total: 4.05s	remaining: 1.14s
750:	total: 4.36s	remaining: 853ms
800:	total: 4.79s	remaining: 580ms
850:	total: 5.12s	remaining: 283ms
897:	total: 5.5s	remaining: 0us
0:	total: 12.5ms	remaining: 11.2s
50:	total: 438ms	remaining: 7.28s
100:	total: 792ms	remaining: 6.25s
150:	total: 1.08s	remaining: 5.36s
200:	total: 1.4s	remaining: 4.84s
250:	total: 1.69s	remaining: 4.35s
300:	total: 1.99s	remaining: 3.94s
350:	total: 2.27s	remaining: 3.53s
400:	total: 2.55s	remaining: 3.16s
450:	total: 2.83s	remaining: 2.81s
500:	total: 3.11s	remaining: 2.46s
550:	total: 3.4s	remaining: 2.14s
600:	total: 3.69s	remaining: 1.83s
650:	total: 3.97s	remaining: 1.51s
700:	total: 4.25s	remaining: 1.19s
750:	total: 4.53s	remaining: 887ms
800:	total: 4.82s	remaining: 584ms
850:	total: 5.11s	remaining: 282ms
897:	total: 5.39s	remaining: 0us
0:	total: 7.62ms	remaining: 6.83s
50:	total: 293ms	remaining: 4.87s
100:	total: 568ms	remaining: 4.48s
150:	total: 845ms	remaining: 4.18s
200:	total: 1.13s	remaining: 3.93s
250:	total: 1.41s	remaining: 3.64s
300:	total: 1.69s	remaining: 3.34s
350:	total: 1.97s	remaining: 3.06s
400:	total: 2.26s	remaining: 2.8s
450:	total: 2.54s	remaining: 2.52s
500:	total: 2.82s	remaining: 2.23s
550:	total: 3.1s	remaining: 1.95s
600:	total: 3.51s	remaining: 1.73s
650:	total: 3.86s	remaining: 1.47s
700:	total: 4.19s	remaining: 1.18s
750:	total: 4.49s	remaining: 880ms
800:	total: 4.91s	remaining: 595ms
850:	total: 5.32s	remaining: 294ms
897:	total: 5.68s	remaining: 0us
0:	total: 7.43ms	remaining: 6.67s
50:	total: 298ms	remaining: 4.96s
100:	total: 599ms	remaining: 4.72s
150:	total: 903ms	remaining: 4.47s
200:	total: 1.2s	remaining: 4.15s
250:	total: 1.55s	remaining: 4s
300:	total: 1.86s	remaining: 3.7s
350:	total: 2.16s	remaining: 3.37s
400:	total: 2.47s	remaining: 3.06s
450:	total: 2.76s	remaining: 2.73s
500:	total: 3.11s	remaining: 2.46s
550:	total: 3.45s	remaining: 2.17s
600:	total: 3.77s	remaining: 1.86s
650:	total: 4.08s	remaining: 1.55s
700:	total: 4.39s	remaining: 1.24s
750:	total: 4.7s	remaining: 921ms
800:	total: 5.15s	remaining: 624ms
850:	total: 5.45s	remaining: 301ms
897:	total: 5.77s	remaining: 0us
0:	total: 7.32ms	remaining: 6.56s
50:	total: 282ms	remaining: 4.69s
100:	total: 643ms	remaining: 5.07s
150:	total: 944ms	remaining: 4.67s
200:	total: 1.22s	remaining: 4.24s
250:	total: 1.51s	remaining: 3.89s
300:	total: 1.95s	remaining: 3.87s
350:	total: 2.25s	remaining: 3.51s
400:	total: 2.55s	remaining: 3.16s
450:	total: 2.83s	remaining: 2.81s
500:	total: 3.18s	remaining: 2.52s
550:	total: 3.48s	remaining: 2.19s
600:	total: 3.78s	remaining: 1.87s
650:	total: 4.09s	remaining: 1.55s
700:	total: 4.38s	remaining: 1.23s
750:	total: 4.68s	remaining: 916ms
800:	total: 4.97s	remaining: 601ms
850:	total: 5.27s	remaining: 291ms

[I 2025-11-24 20:44:18,104] Trial 86 finished with value: 0.7360520842917309 and parameters: {'weight_pos': 2.3810216774816833, 'iterations': 898, 'learning_rate': 0.05957606042024536, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 29.53331280801191, 'bagging_temperature': 0.41718210644140874, 'rsm': 0.4355121763721055, 'min_data_in_leaf': 48, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

897:	total: 5.55s	remaining: 0us
0:	learn: 0.8220159	total: 36.9ms	remaining: 33s
50:	learn: 0.8713295	total: 1.26s	remaining: 20.9s
100:	learn: 0.8914969	total: 2.4s	remaining: 18.9s
150:	learn: 0.9054156	total: 3.84s	remaining: 18.9s
200:	learn: 0.9142067	total: 5.1s	remaining: 17.6s
250:	learn: 0.9300297	total: 6.54s	remaining: 16.8s
300:	learn: 0.9428526	total: 7.87s	remaining: 15.5s
350:	learn: 0.9508018	total: 9.38s	remaining: 14.5s
400:	learn: 0.9564981	total: 10.8s	remaining: 13.3s
450:	learn: 0.9645838	total: 12.2s	remaining: 12s
500:	learn: 0.9678377	total: 13.4s	remaining: 10.6s
550:	learn: 0.9733862	total: 14.9s	remaining: 9.3s
600:	learn: 0.9768297	total: 16.4s	remaining: 8.04s
650:	learn: 0.9792415	total: 17.8s	remaining: 6.67s
700:	learn: 0.9806635	total: 19.2s	remaining: 5.32s
750:	learn: 0.9827380	total: 20.5s	remaining: 3.92s
800:	learn: 0.9844862	total: 21.8s	remaining: 2.55s
850:	learn: 0.9868450	total: 23.1s	remaining: 1.19s
894:	learn: 0.9878878	total: 24.2s	remaining: 0us
0:	learn: 0.8197601	total: 19ms	remaining: 17s
50:	learn: 0.8695813	total: 1.18s	remaining: 19.5s
100:	learn: 0.8947784	total: 2.49s	remaining: 19.6s
150:	learn: 0.9030985	total: 3.73s	remaining: 18.4s
200:	learn: 0.9153414	total: 4.96s	remaining: 17.1s
250:	learn: 0.9300073	total: 6.11s	remaining: 15.7s
300:	learn: 0.9412940	total: 7.31s	remaining: 14.4s
350:	learn: 0.9455906	total: 8.52s	remaining: 13.2s
400:	learn: 0.9540332	total: 9.82s	remaining: 12.1s
450:	learn: 0.9589405	total: 11.1s	remaining: 10.9s
500:	learn: 0.9672577	total: 12.5s	remaining: 9.84s
550:	learn: 0.9712700	total: 13.8s	remaining: 8.6s
600:	learn: 0.9765341	total: 15.1s	remaining: 7.38s
650:	learn: 0.9784301	total: 16.7s	remaining: 6.25s
700:	learn: 0.9808837	total: 17.9s	remaining: 4.97s
750:	learn: 0.9831478	total: 19.2s	remaining: 3.69s
800:	learn: 0.9847594	total: 20.5s	remaining: 2.41s
850:	learn: 0.9871182	total: 22.1s	remaining: 1.14s
894:	learn: 0.9884455	total: 23.4s	remaining: 0us
0:	learn: 0.8145261	total: 27.4ms	remaining: 24.5s
50:	learn: 0.8680198	total: 1.34s	remaining: 22.1s
100:	learn: 0.8952106	total: 2.54s	remaining: 20s
150:	learn: 0.9043504	total: 3.86s	remaining: 19s
200:	learn: 0.9151100	total: 5.07s	remaining: 17.5s
250:	learn: 0.9270184	total: 6.58s	remaining: 16.9s
300:	learn: 0.9381573	total: 8.12s	remaining: 16s
350:	learn: 0.9477375	total: 9.55s	remaining: 14.8s
400:	learn: 0.9560017	total: 10.8s	remaining: 13.3s
450:	learn: 0.9669733	total: 12.1s	remaining: 11.9s
500:	learn: 0.9716380	total: 13.4s	remaining: 10.5s
550:	learn: 0.9756921	total: 14.7s	remaining: 9.16s
600:	learn: 0.9793781	total: 15.9s	remaining: 7.78s
650:	learn: 0.9821691	total: 17.2s	remaining: 6.45s
700:	learn: 0.9850438	total: 19s	remaining: 5.26s
750:	learn: 0.9870346	total: 20.5s	remaining: 3.93s
800:	learn: 0.9887829	total: 21.8s	remaining: 2.56s
850:	learn: 0.9899205	total: 23.4s	remaining: 1.21s
894:	learn: 0.9902997	total: 24.7s	remaining: 0us
0:	learn: 0.8224934	total: 20.6ms	remaining: 18.4s
50:	learn: 0.8698322	total: 1.31s	remaining: 21.7s
100:	learn: 0.8928965	total: 2.51s	remaining: 19.7s
150:	learn: 0.9076042	total: 4.02s	remaining: 19.8s
200:	learn: 0.9194597	total: 5.31s	remaining: 18.3s
250:	learn: 0.9333784	total: 6.74s	remaining: 17.3s
300:	learn: 0.9450024	total: 8.03s	remaining: 15.8s
350:	learn: 0.9549200	total: 9.6s	remaining: 14.9s
400:	learn: 0.9622892	total: 11s	remaining: 13.5s
450:	learn: 0.9672383	total: 12.3s	remaining: 12.1s
500:	learn: 0.9724606	total: 13.7s	remaining: 10.8s
550:	learn: 0.9767042	total: 15s	remaining: 9.36s
600:	learn: 0.9803679	total: 16.3s	remaining: 7.96s
650:	learn: 0.9831478	total: 17.5s	remaining: 6.57s
700:	learn: 0.9853700	total: 18.8s	remaining: 5.19s
750:	learn: 0.9859388	total: 20s	remaining: 3.83s
800:	learn: 0.9877400	total: 21.2s	remaining: 2.49s
850:	learn: 0.9891621	total: 22.5s	remaining: 1.16s
894:	learn: 0.9899205	total: 23.9s	remaining: 0us
0:	learn: 0.8268908	total: 24.3ms	remaining: 21.7s
50:	learn: 0.8704651	total: 1.2s	remaining: 19.9s
100:	learn: 0.8901555	total: 2.42s	remaining: 19s
150:	learn: 0.8997163	total: 3.61s	remaining: 17.8s
200:	learn: 0.9145188	total: 4.94s	remaining: 17.1s
250:	learn: 0.9271969	total: 6.26s	remaining: 16.1s
300:	learn: 0.9396099	total: 7.47s	remaining: 14.7s
350:	learn: 0.9489811	total: 8.64s	remaining: 13.4s
400:	learn: 0.9589935	total: 10s	remaining: 12.4s
450:	learn: 0.9635746	total: 11.4s	remaining: 11.2s
500:	learn: 0.9694381	total: 12.7s	remaining: 9.99s
550:	learn: 0.9746604	total: 14.3s	remaining: 8.91s
600:	learn: 0.9783353	total: 15.6s	remaining: 7.64s
650:	learn: 0.9818847	total: 16.9s	remaining: 6.33s
700:	learn: 0.9841070	total: 18.1s	remaining: 5.01s
750:	learn: 0.9872242	total: 19.6s	remaining: 3.76s
800:	learn: 0.9884566	total: 21.1s	remaining: 2.48s
850:	learn: 0.9902049	total: 22.5s	remaining: 1.16s

[I 2025-11-24 20:46:18,961] Trial 87 finished with value: 0.7316129292556235 and parameters: {'weight_pos': 3.440998825016459, 'iterations': 895, 'learning_rate': 0.04321217494051573, 'depth': 8, 'eval_metric': 'Accuracy', 'l2_leaf_reg': 32.102526159660954, 'bagging_temperature': 0.39656848264330125, 'rsm': 0.9480706200392178, 'min_data_in_leaf': 71, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

894:	learn: 0.9912895	total: 23.6s	remaining: 0us
0:	total: 7.1ms	remaining: 6.21s
50:	total: 344ms	remaining: 5.56s
100:	total: 703ms	remaining: 5.39s
150:	total: 1.02s	remaining: 4.91s
200:	total: 1.37s	remaining: 4.59s
250:	total: 1.74s	remaining: 4.33s
300:	total: 2.11s	remaining: 4.03s
350:	total: 2.46s	remaining: 3.67s
400:	total: 2.81s	remaining: 3.32s
450:	total: 3.16s	remaining: 2.97s
500:	total: 3.53s	remaining: 2.63s
550:	total: 3.89s	remaining: 2.29s
600:	total: 4.26s	remaining: 1.94s
650:	total: 4.63s	remaining: 1.59s
700:	total: 5.01s	remaining: 1.24s
750:	total: 5.61s	remaining: 925ms
800:	total: 6s	remaining: 555ms
850:	total: 6.39s	remaining: 180ms
874:	total: 6.57s	remaining: 0us
0:	total: 9.82ms	remaining: 8.58s
50:	total: 358ms	remaining: 5.79s
100:	total: 749ms	remaining: 5.74s
150:	total: 1.15s	remaining: 5.5s
200:	total: 1.52s	remaining: 5.11s
250:	total: 1.97s	remaining: 4.91s
300:	total: 2.36s	remaining: 4.5s
350:	total: 2.73s	remaining: 4.08s
400:	total: 3.1s	remaining: 3.66s
450:	total: 3.49s	remaining: 3.28s
500:	total: 3.9s	remaining: 2.91s
550:	total: 4.31s	remaining: 2.54s
600:	total: 4.72s	remaining: 2.15s
650:	total: 5.13s	remaining: 1.76s
700:	total: 5.54s	remaining: 1.38s
750:	total: 5.93s	remaining: 979ms
800:	total: 6.38s	remaining: 589ms
850:	total: 6.82s	remaining: 192ms
874:	total: 7.04s	remaining: 0us
0:	total: 10.7ms	remaining: 9.37s
50:	total: 419ms	remaining: 6.77s
100:	total: 843ms	remaining: 6.46s
150:	total: 1.27s	remaining: 6.08s
200:	total: 1.72s	remaining: 5.78s
250:	total: 2.16s	remaining: 5.37s
300:	total: 2.59s	remaining: 4.94s
350:	total: 2.98s	remaining: 4.46s
400:	total: 3.36s	remaining: 3.98s
450:	total: 3.78s	remaining: 3.56s
500:	total: 4.16s	remaining: 3.11s
550:	total: 4.54s	remaining: 2.67s
600:	total: 5.01s	remaining: 2.28s
650:	total: 5.45s	remaining: 1.88s
700:	total: 5.85s	remaining: 1.45s
750:	total: 6.28s	remaining: 1.04s
800:	total: 6.72s	remaining: 620ms
850:	total: 7.25s	remaining: 205ms
874:	total: 7.48s	remaining: 0us
0:	total: 8.31ms	remaining: 7.27s
50:	total: 363ms	remaining: 5.87s
100:	total: 730ms	remaining: 5.59s
150:	total: 1.08s	remaining: 5.19s
200:	total: 1.48s	remaining: 4.95s
250:	total: 1.84s	remaining: 4.58s
300:	total: 2.23s	remaining: 4.26s
350:	total: 2.63s	remaining: 3.93s
400:	total: 3.05s	remaining: 3.6s
450:	total: 3.43s	remaining: 3.23s
500:	total: 3.88s	remaining: 2.9s
550:	total: 4.3s	remaining: 2.53s
600:	total: 4.72s	remaining: 2.15s
650:	total: 5.13s	remaining: 1.77s
700:	total: 5.74s	remaining: 1.43s
750:	total: 6.31s	remaining: 1.04s
800:	total: 6.76s	remaining: 625ms
850:	total: 7.26s	remaining: 205ms
874:	total: 7.51s	remaining: 0us
0:	total: 10.9ms	remaining: 9.49s
50:	total: 637ms	remaining: 10.3s
100:	total: 1.29s	remaining: 9.91s
150:	total: 1.7s	remaining: 8.15s
200:	total: 2.1s	remaining: 7.04s
250:	total: 2.54s	remaining: 6.31s
300:	total: 2.96s	remaining: 5.64s
350:	total: 3.34s	remaining: 4.99s
400:	total: 3.77s	remaining: 4.45s
450:	total: 4.19s	remaining: 3.94s
500:	total: 4.61s	remaining: 3.44s
550:	total: 5.02s	remaining: 2.95s
600:	total: 5.45s	remaining: 2.48s
650:	total: 5.88s	remaining: 2.02s
700:	total: 6.26s	remaining: 1.55s
750:	total: 6.67s	remaining: 1.1s
800:	total: 7.1s	remaining: 656ms
850:	total: 7.48s	remaining: 211ms
874:	total: 7.66s	remaining: 0us

[I 2025-11-24 20:46:56,045] Trial 88 finished with value: 0.6112684409444397 and parameters: {'weight_pos': 22.8405552370728, 'iterations': 875, 'learning_rate': 0.049665924056646264, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 19.653724387281898, 'bagging_temperature': 0.35733368233145035, 'rsm': 0.421262530886623, 'min_data_in_leaf': 80, 'leaf_estimation_iterations': 10}. Best is trial 16 with value: 0.7404863910277388.

0:	total: 1.94ms	remaining: 1.75s
50:	total: 150ms	remaining: 2.5s
100:	total: 279ms	remaining: 2.21s
150:	total: 384ms	remaining: 1.91s
200:	total: 470ms	remaining: 1.64s
250:	total: 554ms	remaining: 1.44s
300:	total: 639ms	remaining: 1.27s
350:	total: 725ms	remaining: 1.14s
400:	total: 813ms	remaining: 1.02s
450:	total: 897ms	remaining: 897ms
500:	total: 979ms	remaining: 784ms
550:	total: 1.07s	remaining: 680ms
600:	total: 1.16s	remaining: 579ms
650:	total: 1.24s	remaining: 477ms
700:	total: 1.32s	remaining: 379ms
750:	total: 1.4s	remaining: 282ms
800:	total: 1.49s	remaining: 188ms
850:	total: 1.57s	remaining: 94.1ms
900:	total: 1.65s	remaining: 1.83ms
901:	total: 1.65s	remaining: 0us
0:	total: 1.77ms	remaining: 1.59s
50:	total: 96.3ms	remaining: 1.61s
100:	total: 184ms	remaining: 1.46s
150:	total: 270ms	remaining: 1.34s
200:	total: 354ms	remaining: 1.24s
250:	total: 436ms	remaining: 1.13s
300:	total: 528ms	remaining: 1.05s
350:	total: 613ms	remaining: 963ms
400:	total: 698ms	remaining: 872ms
450:	total: 781ms	remaining: 781ms
500:	total: 862ms	remaining: 690ms
550:	total: 947ms	remaining: 603ms
600:	total: 1.03s	remaining: 519ms
650:	total: 1.12s	remaining: 431ms
700:	total: 1.2s	remaining: 345ms
750:	total: 1.29s	remaining: 259ms
800:	total: 1.37s	remaining: 173ms
850:	total: 1.46s	remaining: 87.5ms
900:	total: 1.54s	remaining: 1.71ms
901:	total: 1.54s	remaining: 0us
0:	total: 1.82ms	remaining: 1.64s
50:	total: 88.6ms	remaining: 1.48s
100:	total: 177ms	remaining: 1.41s
150:	total: 258ms	remaining: 1.28s
200:	total: 343ms	remaining: 1.2s
250:	total: 429ms	remaining: 1.11s
300:	total: 515ms	remaining: 1.03s
350:	total: 602ms	remaining: 944ms
400:	total: 688ms	remaining: 860ms
450:	total: 776ms	remaining: 776ms
500:	total: 858ms	remaining: 687ms
550:	total: 947ms	remaining: 604ms
600:	total: 1.03s	remaining: 518ms
650:	total: 1.12s	remaining: 431ms
700:	total: 1.2s	remaining: 345ms
750:	total: 1.28s	remaining: 258ms
800:	total: 1.37s	remaining: 173ms
850:	total: 1.46s	remaining: 87.2ms
900:	total: 1.54s	remaining: 1.71ms
901:	total: 1.54s	remaining: 0us
0:	total: 1.87ms	remaining: 1.68s
50:	total: 88.1ms	remaining: 1.47s
100:	total: 175ms	remaining: 1.39s
150:	total: 258ms	remaining: 1.28s
200:	total: 341ms	remaining: 1.19s
250:	total: 424ms	remaining: 1.1s
300:	total: 506ms	remaining: 1.01s
350:	total: 590ms	remaining: 926ms
400:	total: 679ms	remaining: 848ms
450:	total: 765ms	remaining: 765ms
500:	total: 848ms	remaining: 679ms
550:	total: 939ms	remaining: 598ms
600:	total: 1.03s	remaining: 514ms
650:	total: 1.11s	remaining: 428ms
700:	total: 1.2s	remaining: 344ms
750:	total: 1.28s	remaining: 257ms
800:	total: 1.36s	remaining: 172ms
850:	total: 1.45s	remaining: 87.1ms
900:	total: 1.54s	remaining: 1.71ms
901:	total: 1.54s	remaining: 0us
0:	total: 1.76ms	remaining: 1.59s
50:	total: 87.4ms	remaining: 1.46s
100:	total: 176ms	remaining: 1.4s
150:	total: 261ms	remaining: 1.3s
200:	total: 346ms	remaining: 1.21s
250:	total: 428ms	remaining: 1.11s
300:	total: 514ms	remaining: 1.02s
350:	total: 602ms	remaining: 945ms
400:	total: 688ms	remaining: 859ms
450:	total: 772ms	remaining: 772ms
500:	total: 861ms	remaining: 689ms
550:	total: 951ms	remaining: 606ms
600:	total: 1.03s	remaining: 519ms
650:	total: 1.12s	remaining: 433ms
700:	total: 1.22s	remaining: 348ms
750:	total: 1.3s	remaining: 261ms

[I 2025-11-24 20:47:04,532] Trial 89 finished with value: 0.3983142595331176 and parameters: {'weight_pos': 2.1022530625919997, 'iterations': 902, 'learning_rate': 0.02923174221310168, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 48.535009870620264, 'bagging_temperature': 0.4252019948843203, 'rsm': 0.0055610871771997195, 'min_data_in_leaf': 56, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

800:	total: 1.39s	remaining: 175ms
850:	total: 1.47s	remaining: 88.2ms
900:	total: 1.55s	remaining: 1.72ms
901:	total: 1.55s	remaining: 0us
0:	total: 6.3ms	remaining: 5.11s
50:	total: 262ms	remaining: 3.92s
100:	total: 532ms	remaining: 3.75s
150:	total: 995ms	remaining: 4.36s
200:	total: 2.81s	remaining: 8.56s
250:	total: 4.43s	remaining: 9.93s
300:	total: 5.06s	remaining: 8.6s
350:	total: 5.35s	remaining: 7.04s
400:	total: 5.71s	remaining: 5.87s
450:	total: 6.05s	remaining: 4.86s
500:	total: 6.63s	remaining: 4.13s
550:	total: 7.03s	remaining: 3.34s
600:	total: 7.53s	remaining: 2.66s
650:	total: 7.94s	remaining: 1.98s
700:	total: 8.23s	remaining: 1.31s
750:	total: 8.51s	remaining: 703ms
800:	total: 8.81s	remaining: 132ms
812:	total: 8.87s	remaining: 0us
0:	total: 7.7ms	remaining: 6.25s
50:	total: 266ms	remaining: 3.98s
100:	total: 542ms	remaining: 3.82s
150:	total: 833ms	remaining: 3.65s
200:	total: 1.1s	remaining: 3.37s
250:	total: 1.38s	remaining: 3.08s
300:	total: 1.66s	remaining: 2.82s
350:	total: 1.94s	remaining: 2.56s
400:	total: 2.19s	remaining: 2.26s
450:	total: 2.48s	remaining: 1.99s
500:	total: 2.75s	remaining: 1.71s
550:	total: 3.07s	remaining: 1.46s
600:	total: 3.41s	remaining: 1.2s
650:	total: 3.77s	remaining: 939ms
700:	total: 4.07s	remaining: 650ms
750:	total: 4.34s	remaining: 359ms
800:	total: 4.74s	remaining: 71.1ms
812:	total: 4.83s	remaining: 0us
0:	total: 7.73ms	remaining: 6.28s
50:	total: 266ms	remaining: 3.98s
100:	total: 519ms	remaining: 3.66s
150:	total: 799ms	remaining: 3.5s
200:	total: 1.06s	remaining: 3.24s
250:	total: 1.33s	remaining: 2.98s
300:	total: 1.6s	remaining: 2.71s
350:	total: 1.85s	remaining: 2.44s
400:	total: 2.12s	remaining: 2.17s
450:	total: 2.4s	remaining: 1.93s
500:	total: 2.68s	remaining: 1.67s
550:	total: 2.95s	remaining: 1.4s
600:	total: 3.21s	remaining: 1.13s
650:	total: 3.48s	remaining: 865ms
700:	total: 3.74s	remaining: 598ms
750:	total: 4.01s	remaining: 331ms
800:	total: 4.32s	remaining: 64.7ms
812:	total: 4.39s	remaining: 0us
0:	total: 5.43ms	remaining: 4.41s
50:	total: 264ms	remaining: 3.94s
100:	total: 535ms	remaining: 3.77s
150:	total: 810ms	remaining: 3.55s
200:	total: 1.1s	remaining: 3.35s
250:	total: 1.4s	remaining: 3.14s
300:	total: 1.75s	remaining: 2.98s
350:	total: 2.08s	remaining: 2.74s
400:	total: 2.37s	remaining: 2.43s
450:	total: 2.65s	remaining: 2.12s
500:	total: 2.93s	remaining: 1.82s
550:	total: 3.21s	remaining: 1.52s
600:	total: 3.48s	remaining: 1.23s
650:	total: 3.77s	remaining: 937ms
700:	total: 4.04s	remaining: 646ms
750:	total: 4.33s	remaining: 357ms
800:	total: 4.61s	remaining: 69ms
812:	total: 4.68s	remaining: 0us
0:	total: 6.51ms	remaining: 5.29s
50:	total: 279ms	remaining: 4.17s
100:	total: 717ms	remaining: 5.06s
150:	total: 1.02s	remaining: 4.48s
200:	total: 1.29s	remaining: 3.92s
250:	total: 1.57s	remaining: 3.51s
300:	total: 1.87s	remaining: 3.19s
350:	total: 2.16s	remaining: 2.84s
400:	total: 2.47s	remaining: 2.54s
450:	total: 2.81s	remaining: 2.25s
500:	total: 3.12s	remaining: 1.94s
550:	total: 3.41s	remaining: 1.62s
600:	total: 3.68s	remaining: 1.3s
650:	total: 3.95s	remaining: 982ms
700:	total: 4.21s	remaining: 673ms
750:	total: 4.48s	remaining: 370ms

[I 2025-11-24 20:47:32,817] Trial 90 finished with value: 0.7282964182494756 and parameters: {'weight_pos': 2.9743651839755034, 'iterations': 813, 'learning_rate': 0.060402757373395885, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 11.655545324377773, 'bagging_temperature': 0.45376177608710355, 'rsm': 0.37175975469329536, 'min_data_in_leaf': 61, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

800:	total: 4.75s	remaining: 71.2ms
812:	total: 4.81s	remaining: 0us
0:	total: 8.52ms	remaining: 8.14s
50:	total: 293ms	remaining: 5.2s
100:	total: 589ms	remaining: 4.98s
150:	total: 964ms	remaining: 5.14s
200:	total: 1.31s	remaining: 4.94s
250:	total: 1.67s	remaining: 4.68s
300:	total: 2.02s	remaining: 4.4s
350:	total: 2.38s	remaining: 4.1s
400:	total: 2.7s	remaining: 3.74s
450:	total: 3.01s	remaining: 3.37s
500:	total: 3.32s	remaining: 3.01s
550:	total: 3.64s	remaining: 2.67s
600:	total: 3.98s	remaining: 2.35s
650:	total: 4.31s	remaining: 2.02s
700:	total: 4.63s	remaining: 1.69s
750:	total: 4.98s	remaining: 1.36s
800:	total: 5.36s	remaining: 1.04s
850:	total: 5.91s	remaining: 729ms
900:	total: 6.23s	remaining: 380ms
950:	total: 6.58s	remaining: 34.6ms
955:	total: 6.61s	remaining: 0us
0:	total: 6.54ms	remaining: 6.25s
50:	total: 450ms	remaining: 7.98s
100:	total: 797ms	remaining: 6.74s
150:	total: 1.16s	remaining: 6.16s
200:	total: 1.53s	remaining: 5.75s
250:	total: 1.93s	remaining: 5.41s
300:	total: 2.31s	remaining: 5.04s
350:	total: 2.74s	remaining: 4.73s
400:	total: 3.07s	remaining: 4.24s
450:	total: 3.38s	remaining: 3.79s
500:	total: 3.71s	remaining: 3.37s
550:	total: 4.04s	remaining: 2.97s
600:	total: 4.36s	remaining: 2.57s
650:	total: 4.66s	remaining: 2.18s
700:	total: 4.96s	remaining: 1.8s
750:	total: 5.26s	remaining: 1.43s
800:	total: 5.55s	remaining: 1.07s
850:	total: 5.86s	remaining: 723ms
900:	total: 6.2s	remaining: 378ms
950:	total: 6.51s	remaining: 34.3ms
955:	total: 6.55s	remaining: 0us
0:	total: 8.32ms	remaining: 7.95s
50:	total: 346ms	remaining: 6.14s
100:	total: 645ms	remaining: 5.46s
150:	total: 963ms	remaining: 5.13s
200:	total: 1.29s	remaining: 4.84s
250:	total: 1.63s	remaining: 4.57s
300:	total: 2.01s	remaining: 4.37s
350:	total: 2.4s	remaining: 4.13s
400:	total: 2.69s	remaining: 3.73s
450:	total: 3s	remaining: 3.36s
500:	total: 3.32s	remaining: 3.02s
550:	total: 3.63s	remaining: 2.67s
600:	total: 3.96s	remaining: 2.34s
650:	total: 4.28s	remaining: 2s
700:	total: 4.6s	remaining: 1.67s
750:	total: 4.91s	remaining: 1.34s
800:	total: 5.26s	remaining: 1.02s
850:	total: 5.57s	remaining: 688ms
900:	total: 5.89s	remaining: 360ms
950:	total: 6.21s	remaining: 32.6ms
955:	total: 6.24s	remaining: 0us
0:	total: 6.17ms	remaining: 5.89s
50:	total: 328ms	remaining: 5.83s
100:	total: 628ms	remaining: 5.31s
150:	total: 940ms	remaining: 5.01s
200:	total: 1.23s	remaining: 4.61s
250:	total: 1.53s	remaining: 4.31s
300:	total: 1.84s	remaining: 4s
350:	total: 2.13s	remaining: 3.67s
400:	total: 2.46s	remaining: 3.41s
450:	total: 2.78s	remaining: 3.11s
500:	total: 3.1s	remaining: 2.81s
550:	total: 3.42s	remaining: 2.52s
600:	total: 3.73s	remaining: 2.2s
650:	total: 4.06s	remaining: 1.9s
700:	total: 4.37s	remaining: 1.59s
750:	total: 4.7s	remaining: 1.28s
800:	total: 5.01s	remaining: 969ms
850:	total: 5.33s	remaining: 658ms
900:	total: 5.83s	remaining: 356ms
950:	total: 6.14s	remaining: 32.3ms
955:	total: 6.18s	remaining: 0us
0:	total: 6.81ms	remaining: 6.51s
50:	total: 289ms	remaining: 5.13s
100:	total: 577ms	remaining: 4.88s
150:	total: 875ms	remaining: 4.67s
200:	total: 1.22s	remaining: 4.58s
250:	total: 1.56s	remaining: 4.39s
300:	total: 1.86s	remaining: 4.06s
350:	total: 2.19s	remaining: 3.77s
400:	total: 2.48s	remaining: 3.44s
450:	total: 2.82s	remaining: 3.16s
500:	total: 3.13s	remaining: 2.84s
550:	total: 3.42s	remaining: 2.51s
600:	total: 3.72s	remaining: 2.2s
650:	total: 4.04s	remaining: 1.89s
700:	total: 4.32s	remaining: 1.57s
750:	total: 4.63s	remaining: 1.26s
800:	total: 4.95s	remaining: 959ms
850:	total: 5.3s	remaining: 654ms
900:	total: 5.61s	remaining: 343ms

[I 2025-11-24 20:48:05,123] Trial 91 finished with value: 0.7352807593133198 and parameters: {'weight_pos': 2.269150601006213, 'iterations': 956, 'learning_rate': 0.053779129885838446, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 8.819618504479536, 'bagging_temperature': 0.6557497449114532, 'rsm': 0.5215708469443368, 'min_data_in_leaf': 68, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 5.92s	remaining: 31.1ms
955:	total: 5.95s	remaining: 0us
0:	total: 6.53ms	remaining: 6.32s
50:	total: 291ms	remaining: 5.23s
100:	total: 580ms	remaining: 4.99s
150:	total: 888ms	remaining: 4.81s
200:	total: 1.2s	remaining: 4.6s
250:	total: 1.51s	remaining: 4.34s
300:	total: 1.81s	remaining: 4.02s
350:	total: 2.12s	remaining: 3.74s
400:	total: 2.42s	remaining: 3.43s
450:	total: 2.73s	remaining: 3.13s
500:	total: 3.12s	remaining: 2.92s
550:	total: 3.61s	remaining: 2.74s
600:	total: 3.92s	remaining: 2.4s
650:	total: 4.23s	remaining: 2.07s
700:	total: 4.58s	remaining: 1.75s
750:	total: 4.9s	remaining: 1.42s
800:	total: 5.44s	remaining: 1.14s
850:	total: 5.88s	remaining: 816ms
900:	total: 6.24s	remaining: 471ms
950:	total: 6.56s	remaining: 124ms
968:	total: 6.69s	remaining: 0us
0:	total: 8.81ms	remaining: 8.53s
50:	total: 388ms	remaining: 6.98s
100:	total: 707ms	remaining: 6.07s
150:	total: 1.02s	remaining: 5.55s
200:	total: 1.31s	remaining: 5s
250:	total: 1.59s	remaining: 4.56s
300:	total: 1.92s	remaining: 4.25s
350:	total: 2.22s	remaining: 3.91s
400:	total: 2.53s	remaining: 3.58s
450:	total: 2.86s	remaining: 3.28s
500:	total: 3.19s	remaining: 2.98s
550:	total: 3.49s	remaining: 2.65s
600:	total: 3.8s	remaining: 2.33s
650:	total: 4.11s	remaining: 2.01s
700:	total: 4.4s	remaining: 1.68s
750:	total: 4.71s	remaining: 1.37s
800:	total: 5.02s	remaining: 1.05s
850:	total: 5.31s	remaining: 737ms
900:	total: 5.61s	remaining: 424ms
950:	total: 5.92s	remaining: 112ms
968:	total: 6.03s	remaining: 0us
0:	total: 6.04ms	remaining: 5.84s
50:	total: 458ms	remaining: 8.24s
100:	total: 751ms	remaining: 6.45s
150:	total: 1.05s	remaining: 5.71s
200:	total: 1.35s	remaining: 5.17s
250:	total: 1.66s	remaining: 4.75s
300:	total: 1.95s	remaining: 4.34s
350:	total: 2.47s	remaining: 4.35s
400:	total: 5.03s	remaining: 7.13s
450:	total: 6.28s	remaining: 7.21s
500:	total: 6.7s	remaining: 6.25s
550:	total: 7.08s	remaining: 5.37s
600:	total: 7.45s	remaining: 4.56s
650:	total: 7.77s	remaining: 3.79s
700:	total: 8.1s	remaining: 3.1s
750:	total: 8.44s	remaining: 2.45s
800:	total: 8.76s	remaining: 1.84s
850:	total: 9.1s	remaining: 1.26s
900:	total: 9.41s	remaining: 711ms
950:	total: 9.73s	remaining: 184ms
968:	total: 9.85s	remaining: 0us
0:	total: 8.55ms	remaining: 8.28s
50:	total: 590ms	remaining: 10.6s
100:	total: 876ms	remaining: 7.53s
150:	total: 1.17s	remaining: 6.31s
200:	total: 1.47s	remaining: 5.61s
250:	total: 1.77s	remaining: 5.06s
300:	total: 2.05s	remaining: 4.56s
350:	total: 2.35s	remaining: 4.14s
400:	total: 2.72s	remaining: 3.85s
450:	total: 3.03s	remaining: 3.48s
500:	total: 3.34s	remaining: 3.12s
550:	total: 3.63s	remaining: 2.75s
600:	total: 3.95s	remaining: 2.42s
650:	total: 4.26s	remaining: 2.08s
700:	total: 4.59s	remaining: 1.75s
750:	total: 4.94s	remaining: 1.43s
800:	total: 5.27s	remaining: 1.1s
850:	total: 5.6s	remaining: 777ms
900:	total: 5.94s	remaining: 448ms
950:	total: 6.26s	remaining: 119ms
968:	total: 6.36s	remaining: 0us
0:	total: 6.17ms	remaining: 5.97s
50:	total: 300ms	remaining: 5.4s
100:	total: 592ms	remaining: 5.09s
150:	total: 888ms	remaining: 4.81s
200:	total: 1.24s	remaining: 4.74s
250:	total: 1.71s	remaining: 4.89s
300:	total: 2.12s	remaining: 4.7s
350:	total: 2.48s	remaining: 4.37s
400:	total: 2.85s	remaining: 4.04s
450:	total: 3.2s	remaining: 3.67s
500:	total: 3.52s	remaining: 3.29s
550:	total: 3.98s	remaining: 3.02s
600:	total: 4.34s	remaining: 2.66s
650:	total: 4.64s	remaining: 2.27s
700:	total: 4.93s	remaining: 1.88s
750:	total: 5.3s	remaining: 1.54s
800:	total: 5.65s	remaining: 1.18s
850:	total: 5.96s	remaining: 827ms
900:	total: 6.32s	remaining: 477ms

[I 2025-11-24 20:48:41,522] Trial 92 finished with value: 0.7344699342666724 and parameters: {'weight_pos': 2.442586848682487, 'iterations': 969, 'learning_rate': 0.05333977062958039, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 7.3967896261110795, 'bagging_temperature': 0.3708689395145764, 'rsm': 0.5149164753886696, 'min_data_in_leaf': 69, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 6.61s	remaining: 125ms
968:	total: 6.72s	remaining: 0us
0:	total: 6.96ms	remaining: 6.81s
50:	total: 285ms	remaining: 5.19s
100:	total: 589ms	remaining: 5.12s
150:	total: 914ms	remaining: 5.01s
200:	total: 1.22s	remaining: 4.7s
250:	total: 1.53s	remaining: 4.43s
300:	total: 1.87s	remaining: 4.22s
350:	total: 2.18s	remaining: 3.9s
400:	total: 2.49s	remaining: 3.59s
450:	total: 2.79s	remaining: 3.26s
500:	total: 3.11s	remaining: 2.97s
550:	total: 3.45s	remaining: 2.68s
600:	total: 3.76s	remaining: 2.37s
650:	total: 4.09s	remaining: 2.06s
700:	total: 4.39s	remaining: 1.74s
750:	total: 4.7s	remaining: 1.43s
800:	total: 5.04s	remaining: 1.12s
850:	total: 5.37s	remaining: 808ms
900:	total: 5.67s	remaining: 491ms
950:	total: 5.97s	remaining: 176ms
978:	total: 6.14s	remaining: 0us
0:	total: 6.31ms	remaining: 6.17s
50:	total: 290ms	remaining: 5.28s
100:	total: 796ms	remaining: 6.92s
150:	total: 1.09s	remaining: 5.97s
200:	total: 1.37s	remaining: 5.3s
250:	total: 1.7s	remaining: 4.92s
300:	total: 2.02s	remaining: 4.55s
350:	total: 2.31s	remaining: 4.13s
400:	total: 2.65s	remaining: 3.82s
450:	total: 2.94s	remaining: 3.45s
500:	total: 3.29s	remaining: 3.14s
550:	total: 3.63s	remaining: 2.82s
600:	total: 3.94s	remaining: 2.48s
650:	total: 4.26s	remaining: 2.15s
700:	total: 4.56s	remaining: 1.81s
750:	total: 4.87s	remaining: 1.48s
800:	total: 5.18s	remaining: 1.15s
850:	total: 5.52s	remaining: 831ms
900:	total: 5.83s	remaining: 505ms
950:	total: 6.14s	remaining: 181ms
978:	total: 6.3s	remaining: 0us
0:	total: 7.03ms	remaining: 6.88s
50:	total: 356ms	remaining: 6.48s
100:	total: 654ms	remaining: 5.69s
150:	total: 1000ms	remaining: 5.48s
200:	total: 1.38s	remaining: 5.33s
250:	total: 1.69s	remaining: 4.91s
300:	total: 2.01s	remaining: 4.53s
350:	total: 2.33s	remaining: 4.16s
400:	total: 2.64s	remaining: 3.8s
450:	total: 2.97s	remaining: 3.48s
500:	total: 3.27s	remaining: 3.12s
550:	total: 3.58s	remaining: 2.78s
600:	total: 3.94s	remaining: 2.48s
650:	total: 4.35s	remaining: 2.19s
700:	total: 4.66s	remaining: 1.85s
750:	total: 4.97s	remaining: 1.51s
800:	total: 5.27s	remaining: 1.17s
850:	total: 5.58s	remaining: 840ms
900:	total: 5.92s	remaining: 512ms
950:	total: 6.24s	remaining: 184ms
978:	total: 6.43s	remaining: 0us
0:	total: 7.69ms	remaining: 7.52s
50:	total: 297ms	remaining: 5.4s
100:	total: 605ms	remaining: 5.26s
150:	total: 907ms	remaining: 4.97s
200:	total: 1.21s	remaining: 4.7s
250:	total: 1.5s	remaining: 4.34s
300:	total: 1.81s	remaining: 4.08s
350:	total: 2.13s	remaining: 3.81s
400:	total: 2.5s	remaining: 3.61s
450:	total: 2.95s	remaining: 3.45s
500:	total: 3.27s	remaining: 3.12s
550:	total: 3.64s	remaining: 2.83s
600:	total: 3.95s	remaining: 2.48s
650:	total: 4.29s	remaining: 2.16s
700:	total: 4.64s	remaining: 1.84s
750:	total: 4.96s	remaining: 1.51s
800:	total: 5.28s	remaining: 1.17s
850:	total: 5.6s	remaining: 842ms
900:	total: 5.92s	remaining: 513ms
950:	total: 6.24s	remaining: 184ms
978:	total: 6.41s	remaining: 0us
0:	total: 7.03ms	remaining: 6.87s
50:	total: 286ms	remaining: 5.2s
100:	total: 588ms	remaining: 5.11s
150:	total: 1.01s	remaining: 5.52s
200:	total: 1.34s	remaining: 5.18s
250:	total: 1.65s	remaining: 4.79s
300:	total: 1.95s	remaining: 4.39s
350:	total: 2.25s	remaining: 4.02s
400:	total: 2.55s	remaining: 3.67s
450:	total: 2.91s	remaining: 3.4s
500:	total: 3.24s	remaining: 3.09s
550:	total: 3.56s	remaining: 2.77s
600:	total: 3.89s	remaining: 2.45s
650:	total: 4.19s	remaining: 2.11s
700:	total: 4.52s	remaining: 1.79s
750:	total: 4.87s	remaining: 1.48s
800:	total: 5.22s	remaining: 1.16s
850:	total: 5.55s	remaining: 834ms
900:	total: 5.86s	remaining: 507ms
950:	total: 6.2s	remaining: 183ms

[I 2025-11-24 20:49:14,028] Trial 93 finished with value: 0.7297049306982909 and parameters: {'weight_pos': 2.397592910342106, 'iterations': 979, 'learning_rate': 0.046766031310795965, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 8.420759163385698, 'bagging_temperature': 0.4084180439214733, 'rsm': 0.5187802151823577, 'min_data_in_leaf': 68, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

978:	total: 6.42s	remaining: 0us
0:	total: 6.32ms	remaining: 6.29s
50:	total: 316ms	remaining: 5.85s
100:	total: 644ms	remaining: 5.71s
150:	total: 1.01s	remaining: 5.67s
200:	total: 1.35s	remaining: 5.35s
250:	total: 1.7s	remaining: 5.05s
300:	total: 2.03s	remaining: 4.69s
350:	total: 2.36s	remaining: 4.34s
400:	total: 2.69s	remaining: 3.99s
450:	total: 3.01s	remaining: 3.64s
500:	total: 3.35s	remaining: 3.31s
550:	total: 3.68s	remaining: 2.97s
600:	total: 4.04s	remaining: 2.65s
650:	total: 4.58s	remaining: 2.43s
700:	total: 4.97s	remaining: 2.09s
750:	total: 5.33s	remaining: 1.74s
800:	total: 5.7s	remaining: 1.39s
850:	total: 6.09s	remaining: 1.04s
900:	total: 6.56s	remaining: 691ms
950:	total: 7s	remaining: 331ms
995:	total: 7.3s	remaining: 0us
0:	total: 8.19ms	remaining: 8.15s
50:	total: 309ms	remaining: 5.72s
100:	total: 651ms	remaining: 5.77s
150:	total: 959ms	remaining: 5.37s
200:	total: 1.29s	remaining: 5.12s
250:	total: 1.61s	remaining: 4.78s
300:	total: 1.95s	remaining: 4.51s
350:	total: 2.28s	remaining: 4.19s
400:	total: 2.62s	remaining: 3.88s
450:	total: 2.98s	remaining: 3.6s
500:	total: 3.31s	remaining: 3.27s
550:	total: 3.63s	remaining: 2.93s
600:	total: 3.99s	remaining: 2.62s
650:	total: 4.34s	remaining: 2.3s
700:	total: 4.66s	remaining: 1.96s
750:	total: 4.98s	remaining: 1.63s
800:	total: 5.33s	remaining: 1.3s
850:	total: 5.66s	remaining: 965ms
900:	total: 5.98s	remaining: 631ms
950:	total: 6.33s	remaining: 300ms
995:	total: 6.63s	remaining: 0us
0:	total: 14.7ms	remaining: 14.7s
50:	total: 472ms	remaining: 8.75s
100:	total: 819ms	remaining: 7.26s
150:	total: 1.13s	remaining: 6.35s
200:	total: 1.47s	remaining: 5.82s
250:	total: 1.84s	remaining: 5.47s
300:	total: 2.2s	remaining: 5.07s
350:	total: 2.54s	remaining: 4.66s
400:	total: 2.85s	remaining: 4.24s
450:	total: 3.16s	remaining: 3.82s
500:	total: 3.51s	remaining: 3.46s
550:	total: 3.84s	remaining: 3.1s
600:	total: 4.18s	remaining: 2.75s
650:	total: 4.57s	remaining: 2.42s
700:	total: 4.94s	remaining: 2.08s
750:	total: 5.26s	remaining: 1.72s
800:	total: 5.63s	remaining: 1.37s
850:	total: 5.99s	remaining: 1.02s
900:	total: 6.33s	remaining: 668ms
950:	total: 6.67s	remaining: 316ms
995:	total: 6.99s	remaining: 0us
0:	total: 5.98ms	remaining: 5.95s
50:	total: 319ms	remaining: 5.91s
100:	total: 669ms	remaining: 5.92s
150:	total: 973ms	remaining: 5.45s
200:	total: 1.29s	remaining: 5.09s
250:	total: 1.61s	remaining: 4.78s
300:	total: 1.92s	remaining: 4.44s
350:	total: 2.25s	remaining: 4.13s
400:	total: 2.62s	remaining: 3.88s
450:	total: 3.17s	remaining: 3.83s
500:	total: 3.53s	remaining: 3.49s
550:	total: 3.92s	remaining: 3.17s
600:	total: 4.3s	remaining: 2.83s
650:	total: 4.68s	remaining: 2.48s
700:	total: 5.05s	remaining: 2.13s
750:	total: 5.42s	remaining: 1.77s
800:	total: 5.77s	remaining: 1.4s
850:	total: 6.12s	remaining: 1.04s
900:	total: 6.58s	remaining: 694ms
950:	total: 6.97s	remaining: 330ms
995:	total: 7.31s	remaining: 0us
0:	total: 5.91ms	remaining: 5.88s
50:	total: 311ms	remaining: 5.76s
100:	total: 678ms	remaining: 6.01s
150:	total: 1.11s	remaining: 6.23s
200:	total: 1.55s	remaining: 6.13s
250:	total: 1.88s	remaining: 5.59s
300:	total: 2.19s	remaining: 5.05s
350:	total: 2.5s	remaining: 4.58s
400:	total: 2.82s	remaining: 4.19s
450:	total: 3.15s	remaining: 3.81s
500:	total: 3.49s	remaining: 3.45s
550:	total: 3.82s	remaining: 3.09s
600:	total: 4.19s	remaining: 2.75s
650:	total: 4.56s	remaining: 2.42s
700:	total: 4.91s	remaining: 2.06s
750:	total: 5.28s	remaining: 1.72s
800:	total: 5.79s	remaining: 1.41s
850:	total: 6.13s	remaining: 1.04s
900:	total: 6.47s	remaining: 682ms
950:	total: 6.83s	remaining: 323ms

[I 2025-11-24 20:49:50,157] Trial 94 finished with value: 0.7285961667226103 and parameters: {'weight_pos': 1.9234557412461086, 'iterations': 996, 'learning_rate': 0.0795525836247871, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 32.3242407651313, 'bagging_temperature': 0.37522044503458957, 'rsm': 0.5664313409705458, 'min_data_in_leaf': 75, 'leaf_estimation_iterations': 8}. Best is trial 16 with value: 0.7404863910277388.

995:	total: 7.15s	remaining: 0us
0:	total: 7.48ms	remaining: 7.16s
50:	total: 350ms	remaining: 6.23s
100:	total: 699ms	remaining: 5.93s
150:	total: 1.04s	remaining: 5.54s
200:	total: 1.42s	remaining: 5.33s
250:	total: 1.8s	remaining: 5.06s
300:	total: 2.16s	remaining: 4.71s
350:	total: 2.52s	remaining: 4.37s
400:	total: 2.88s	remaining: 4.01s
450:	total: 3.25s	remaining: 3.66s
500:	total: 3.6s	remaining: 3.29s
550:	total: 3.98s	remaining: 2.94s
600:	total: 4.37s	remaining: 2.6s
650:	total: 4.75s	remaining: 2.24s
700:	total: 5.19s	remaining: 1.9s
750:	total: 5.55s	remaining: 1.53s
800:	total: 5.91s	remaining: 1.16s
850:	total: 6.27s	remaining: 789ms
900:	total: 6.66s	remaining: 421ms
950:	total: 7.04s	remaining: 51.9ms
957:	total: 7.1s	remaining: 0us
0:	total: 10.4ms	remaining: 9.93s
50:	total: 360ms	remaining: 6.4s
100:	total: 703ms	remaining: 5.96s
150:	total: 1.22s	remaining: 6.54s
200:	total: 1.56s	remaining: 5.88s
250:	total: 1.89s	remaining: 5.33s
300:	total: 2.25s	remaining: 4.91s
350:	total: 2.59s	remaining: 4.48s
400:	total: 2.95s	remaining: 4.1s
450:	total: 3.33s	remaining: 3.75s
500:	total: 3.67s	remaining: 3.35s
550:	total: 4.02s	remaining: 2.97s
600:	total: 4.37s	remaining: 2.6s
650:	total: 4.75s	remaining: 2.24s
700:	total: 5.1s	remaining: 1.87s
750:	total: 5.44s	remaining: 1.5s
800:	total: 5.78s	remaining: 1.13s
850:	total: 6.13s	remaining: 771ms
900:	total: 6.46s	remaining: 408ms
950:	total: 6.79s	remaining: 50ms
957:	total: 6.83s	remaining: 0us
0:	total: 6.46ms	remaining: 6.18s
50:	total: 356ms	remaining: 6.33s
100:	total: 713ms	remaining: 6.05s
150:	total: 1.08s	remaining: 5.77s
200:	total: 1.43s	remaining: 5.38s
250:	total: 1.79s	remaining: 5.04s
300:	total: 2.12s	remaining: 4.62s
350:	total: 2.45s	remaining: 4.23s
400:	total: 2.77s	remaining: 3.85s
450:	total: 3.11s	remaining: 3.5s
500:	total: 3.43s	remaining: 3.13s
550:	total: 3.85s	remaining: 2.84s
600:	total: 4.46s	remaining: 2.65s
650:	total: 4.87s	remaining: 2.29s
700:	total: 5.27s	remaining: 1.93s
750:	total: 5.61s	remaining: 1.55s
800:	total: 5.99s	remaining: 1.17s
850:	total: 6.4s	remaining: 805ms
900:	total: 6.73s	remaining: 426ms
950:	total: 7.1s	remaining: 52.3ms
957:	total: 7.16s	remaining: 0us
0:	total: 8.71ms	remaining: 8.33s
50:	total: 353ms	remaining: 6.27s
100:	total: 685ms	remaining: 5.81s
150:	total: 1.08s	remaining: 5.79s
200:	total: 1.42s	remaining: 5.34s
250:	total: 1.73s	remaining: 4.87s
300:	total: 2.05s	remaining: 4.48s
350:	total: 2.39s	remaining: 4.13s
400:	total: 2.75s	remaining: 3.82s
450:	total: 3.11s	remaining: 3.49s
500:	total: 3.43s	remaining: 3.13s
550:	total: 3.77s	remaining: 2.79s
600:	total: 4.13s	remaining: 2.45s
650:	total: 4.45s	remaining: 2.1s
700:	total: 4.79s	remaining: 1.75s
750:	total: 5.1s	remaining: 1.41s
800:	total: 5.43s	remaining: 1.06s
850:	total: 5.75s	remaining: 723ms
900:	total: 6.08s	remaining: 385ms
950:	total: 6.43s	remaining: 47.3ms
957:	total: 6.48s	remaining: 0us
0:	total: 14.2ms	remaining: 13.6s
50:	total: 450ms	remaining: 8.01s
100:	total: 772ms	remaining: 6.55s
150:	total: 1.07s	remaining: 5.73s
200:	total: 1.4s	remaining: 5.26s
250:	total: 1.71s	remaining: 4.82s
300:	total: 2.03s	remaining: 4.44s
350:	total: 2.37s	remaining: 4.09s
400:	total: 2.69s	remaining: 3.73s
450:	total: 3.01s	remaining: 3.38s
500:	total: 3.33s	remaining: 3.04s
550:	total: 3.65s	remaining: 2.7s
600:	total: 4s	remaining: 2.38s
650:	total: 4.33s	remaining: 2.04s
700:	total: 4.65s	remaining: 1.71s
750:	total: 4.97s	remaining: 1.37s
800:	total: 5.28s	remaining: 1.03s
850:	total: 5.6s	remaining: 704ms
900:	total: 5.92s	remaining: 374ms

[I 2025-11-24 20:50:24,772] Trial 95 finished with value: 0.7386083291648801 and parameters: {'weight_pos': 2.1997131932884666, 'iterations': 958, 'learning_rate': 0.05482460594322128, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 4.038313519640249, 'bagging_temperature': 0.4888942977614634, 'rsm': 0.6080297333192671, 'min_data_in_leaf': 77, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 6.26s	remaining: 46.1ms
957:	total: 6.31s	remaining: 0us
0:	total: 11.5ms	remaining: 11.1s
50:	total: 480ms	remaining: 8.55s
100:	total: 965ms	remaining: 8.2s
150:	total: 1.38s	remaining: 7.37s
200:	total: 1.79s	remaining: 6.74s
250:	total: 2.26s	remaining: 6.37s
300:	total: 2.66s	remaining: 5.81s
350:	total: 3.11s	remaining: 5.38s
400:	total: 3.65s	remaining: 5.08s
450:	total: 4.2s	remaining: 4.72s
500:	total: 4.7s	remaining: 4.3s
550:	total: 5.15s	remaining: 3.81s
600:	total: 5.57s	remaining: 3.31s
650:	total: 6.01s	remaining: 2.84s
700:	total: 6.43s	remaining: 2.37s
750:	total: 6.89s	remaining: 1.91s
800:	total: 7.32s	remaining: 1.44s
850:	total: 7.78s	remaining: 987ms
900:	total: 8.26s	remaining: 531ms
950:	total: 8.7s	remaining: 73.2ms
958:	total: 8.77s	remaining: 0us
0:	total: 9.6ms	remaining: 9.2s
50:	total: 417ms	remaining: 7.42s
100:	total: 827ms	remaining: 7.02s
150:	total: 1.28s	remaining: 6.85s
200:	total: 1.78s	remaining: 6.72s
250:	total: 2.25s	remaining: 6.36s
300:	total: 2.7s	remaining: 5.91s
350:	total: 3.15s	remaining: 5.46s
400:	total: 3.56s	remaining: 4.95s
450:	total: 3.97s	remaining: 4.47s
500:	total: 4.39s	remaining: 4.01s
550:	total: 4.99s	remaining: 3.7s
600:	total: 5.41s	remaining: 3.22s
650:	total: 5.82s	remaining: 2.75s
700:	total: 6.28s	remaining: 2.31s
750:	total: 6.8s	remaining: 1.88s
800:	total: 7.31s	remaining: 1.44s
850:	total: 7.8s	remaining: 990ms
900:	total: 8.25s	remaining: 531ms
950:	total: 8.74s	remaining: 73.5ms
958:	total: 8.81s	remaining: 0us
0:	total: 9.6ms	remaining: 9.19s
50:	total: 426ms	remaining: 7.59s
100:	total: 849ms	remaining: 7.21s
150:	total: 1.27s	remaining: 6.78s
200:	total: 1.68s	remaining: 6.32s
250:	total: 2.1s	remaining: 5.91s
300:	total: 2.51s	remaining: 5.49s
350:	total: 2.93s	remaining: 5.07s
400:	total: 3.48s	remaining: 4.83s
450:	total: 4.25s	remaining: 4.79s
500:	total: 4.79s	remaining: 4.38s
550:	total: 5.19s	remaining: 3.85s
600:	total: 5.69s	remaining: 3.39s
650:	total: 6.25s	remaining: 2.96s
700:	total: 6.66s	remaining: 2.45s
750:	total: 7.07s	remaining: 1.96s
800:	total: 7.5s	remaining: 1.48s
850:	total: 7.98s	remaining: 1.01s
900:	total: 8.41s	remaining: 542ms
950:	total: 8.94s	remaining: 75.2ms
958:	total: 9.05s	remaining: 0us
0:	total: 11.1ms	remaining: 10.6s
50:	total: 440ms	remaining: 7.84s
100:	total: 887ms	remaining: 7.53s
150:	total: 1.32s	remaining: 7.08s
200:	total: 1.73s	remaining: 6.51s
250:	total: 2.12s	remaining: 5.98s
300:	total: 2.53s	remaining: 5.52s
350:	total: 2.95s	remaining: 5.11s
400:	total: 3.41s	remaining: 4.74s
450:	total: 3.86s	remaining: 4.35s
500:	total: 4.44s	remaining: 4.06s
550:	total: 5.01s	remaining: 3.71s
600:	total: 5.62s	remaining: 3.35s
650:	total: 6.17s	remaining: 2.92s
700:	total: 6.91s	remaining: 2.54s
750:	total: 7.45s	remaining: 2.06s
800:	total: 7.99s	remaining: 1.58s
850:	total: 8.51s	remaining: 1.08s
900:	total: 9.03s	remaining: 581ms
950:	total: 9.51s	remaining: 80ms
958:	total: 9.59s	remaining: 0us
0:	total: 8.57ms	remaining: 8.21s
50:	total: 500ms	remaining: 8.89s
100:	total: 1.05s	remaining: 8.9s
150:	total: 1.58s	remaining: 8.46s
200:	total: 2.11s	remaining: 7.96s
250:	total: 2.62s	remaining: 7.39s
300:	total: 3.13s	remaining: 6.85s
350:	total: 3.62s	remaining: 6.28s
400:	total: 4.12s	remaining: 5.73s
450:	total: 4.65s	remaining: 5.23s
500:	total: 5.12s	remaining: 4.68s
550:	total: 5.58s	remaining: 4.13s
600:	total: 6.01s	remaining: 3.58s
650:	total: 6.44s	remaining: 3.05s
700:	total: 7.08s	remaining: 2.61s
750:	total: 7.51s	remaining: 2.08s
800:	total: 7.97s	remaining: 1.57s
850:	total: 8.46s	remaining: 1.07s
900:	total: 9.04s	remaining: 582ms

[I 2025-11-24 20:51:11,364] Trial 96 finished with value: 0.7255564867126102 and parameters: {'weight_pos': 1.650505776601916, 'iterations': 959, 'learning_rate': 0.05312517980607303, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 3.8957191609849806, 'bagging_temperature': 0.6457357888064275, 'rsm': 0.625643243549705, 'min_data_in_leaf': 78, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 9.47s	remaining: 79.7ms
958:	total: 9.54s	remaining: 0us
0:	total: 7.38ms	remaining: 7.11s
50:	total: 347ms	remaining: 6.2s
100:	total: 682ms	remaining: 5.83s
150:	total: 1.02s	remaining: 5.5s
200:	total: 1.43s	remaining: 5.44s
250:	total: 1.79s	remaining: 5.09s
300:	total: 2.13s	remaining: 4.68s
350:	total: 2.47s	remaining: 4.32s
400:	total: 2.84s	remaining: 3.98s
450:	total: 3.19s	remaining: 3.63s
500:	total: 3.56s	remaining: 3.29s
550:	total: 3.91s	remaining: 2.93s
600:	total: 4.3s	remaining: 2.6s
650:	total: 4.68s	remaining: 2.25s
700:	total: 5.03s	remaining: 1.89s
750:	total: 5.38s	remaining: 1.53s
800:	total: 5.74s	remaining: 1.17s
850:	total: 6.08s	remaining: 807ms
900:	total: 6.43s	remaining: 449ms
950:	total: 6.76s	remaining: 92.5ms
963:	total: 6.9s	remaining: 0us
0:	total: 30.7ms	remaining: 29.5s
50:	total: 445ms	remaining: 7.96s
100:	total: 777ms	remaining: 6.63s
150:	total: 1.1s	remaining: 5.92s
200:	total: 1.44s	remaining: 5.48s
250:	total: 1.78s	remaining: 5.05s
300:	total: 2.12s	remaining: 4.66s
350:	total: 2.45s	remaining: 4.28s
400:	total: 2.79s	remaining: 3.91s
450:	total: 3.11s	remaining: 3.54s
500:	total: 3.45s	remaining: 3.19s
550:	total: 3.79s	remaining: 2.84s
600:	total: 4.13s	remaining: 2.49s
650:	total: 4.5s	remaining: 2.16s
700:	total: 4.84s	remaining: 1.81s
750:	total: 5.2s	remaining: 1.47s
800:	total: 5.55s	remaining: 1.13s
850:	total: 5.89s	remaining: 782ms
900:	total: 6.23s	remaining: 436ms
950:	total: 6.78s	remaining: 92.7ms
963:	total: 6.91s	remaining: 0us
0:	total: 6.78ms	remaining: 6.53s
50:	total: 363ms	remaining: 6.49s
100:	total: 709ms	remaining: 6.06s
150:	total: 1.04s	remaining: 5.62s
200:	total: 1.39s	remaining: 5.27s
250:	total: 1.73s	remaining: 4.92s
300:	total: 2.06s	remaining: 4.55s
350:	total: 2.41s	remaining: 4.2s
400:	total: 2.85s	remaining: 4.01s
450:	total: 3.27s	remaining: 3.71s
500:	total: 3.59s	remaining: 3.32s
550:	total: 3.97s	remaining: 2.98s
600:	total: 4.34s	remaining: 2.62s
650:	total: 4.69s	remaining: 2.25s
700:	total: 5.06s	remaining: 1.9s
750:	total: 5.52s	remaining: 1.56s
800:	total: 5.94s	remaining: 1.21s
850:	total: 6.32s	remaining: 839ms
900:	total: 6.67s	remaining: 466ms
950:	total: 7.01s	remaining: 95.8ms
963:	total: 7.1s	remaining: 0us
0:	total: 7.2ms	remaining: 6.93s
50:	total: 367ms	remaining: 6.57s
100:	total: 745ms	remaining: 6.37s
150:	total: 1.1s	remaining: 5.93s
200:	total: 1.45s	remaining: 5.51s
250:	total: 1.8s	remaining: 5.11s
300:	total: 2.13s	remaining: 4.7s
350:	total: 2.51s	remaining: 4.39s
400:	total: 2.87s	remaining: 4.03s
450:	total: 3.37s	remaining: 3.83s
500:	total: 3.9s	remaining: 3.61s
550:	total: 4.3s	remaining: 3.23s
600:	total: 4.67s	remaining: 2.82s
650:	total: 5.01s	remaining: 2.41s
700:	total: 5.36s	remaining: 2.01s
750:	total: 5.95s	remaining: 1.69s
800:	total: 6.33s	remaining: 1.29s
850:	total: 6.7s	remaining: 890ms
900:	total: 7.08s	remaining: 495ms
950:	total: 7.45s	remaining: 102ms
963:	total: 7.55s	remaining: 0us
0:	total: 8.97ms	remaining: 8.64s
50:	total: 371ms	remaining: 6.63s
100:	total: 733ms	remaining: 6.26s
150:	total: 1.09s	remaining: 5.86s
200:	total: 1.48s	remaining: 5.62s
250:	total: 1.86s	remaining: 5.3s
300:	total: 2.28s	remaining: 5.01s
350:	total: 2.67s	remaining: 4.67s
400:	total: 3.05s	remaining: 4.29s
450:	total: 3.43s	remaining: 3.9s
500:	total: 3.77s	remaining: 3.49s
550:	total: 4.14s	remaining: 3.1s
600:	total: 4.49s	remaining: 2.71s
650:	total: 4.84s	remaining: 2.33s
700:	total: 5.21s	remaining: 1.95s
750:	total: 5.54s	remaining: 1.57s
800:	total: 5.91s	remaining: 1.2s
850:	total: 6.25s	remaining: 830ms
900:	total: 6.64s	remaining: 465ms

[I 2025-11-24 20:51:47,742] Trial 97 finished with value: 0.7280977303555678 and parameters: {'weight_pos': 2.499427038451261, 'iterations': 964, 'learning_rate': 0.03988017952242206, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 7.111659990990792, 'bagging_temperature': 0.47831876027554965, 'rsm': 0.667777342326534, 'min_data_in_leaf': 75, 'leaf_estimation_iterations': 10}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 7.02s	remaining: 96ms
963:	total: 7.11s	remaining: 0us
0:	total: 10.8ms	remaining: 10.3s
50:	total: 468ms	remaining: 8.29s
100:	total: 1.12s	remaining: 9.47s
150:	total: 1.48s	remaining: 7.88s
200:	total: 1.85s	remaining: 6.96s
250:	total: 2.2s	remaining: 6.18s
300:	total: 2.62s	remaining: 5.68s
350:	total: 3.07s	remaining: 5.29s
400:	total: 3.47s	remaining: 4.8s
450:	total: 3.89s	remaining: 4.34s
500:	total: 4.36s	remaining: 3.95s
550:	total: 4.72s	remaining: 3.46s
600:	total: 5.04s	remaining: 2.97s
650:	total: 5.36s	remaining: 2.5s
700:	total: 5.68s	remaining: 2.06s
750:	total: 5.98s	remaining: 1.63s
800:	total: 6.29s	remaining: 1.21s
850:	total: 6.6s	remaining: 807ms
900:	total: 6.9s	remaining: 414ms
950:	total: 7.21s	remaining: 30.3ms
954:	total: 7.23s	remaining: 0us
0:	total: 6.64ms	remaining: 6.34s
50:	total: 305ms	remaining: 5.41s
100:	total: 594ms	remaining: 5.02s
150:	total: 881ms	remaining: 4.69s
200:	total: 1.16s	remaining: 4.34s
250:	total: 1.47s	remaining: 4.11s
300:	total: 1.77s	remaining: 3.85s
350:	total: 2.07s	remaining: 3.56s
400:	total: 2.38s	remaining: 3.28s
450:	total: 2.69s	remaining: 3.01s
500:	total: 2.99s	remaining: 2.71s
550:	total: 3.44s	remaining: 2.53s
600:	total: 3.76s	remaining: 2.21s
650:	total: 4.05s	remaining: 1.89s
700:	total: 4.35s	remaining: 1.58s
750:	total: 4.64s	remaining: 1.26s
800:	total: 4.95s	remaining: 951ms
850:	total: 5.26s	remaining: 643ms
900:	total: 5.58s	remaining: 334ms
950:	total: 5.9s	remaining: 24.8ms
954:	total: 5.93s	remaining: 0us
0:	total: 5.76ms	remaining: 5.5s
50:	total: 299ms	remaining: 5.31s
100:	total: 573ms	remaining: 4.85s
150:	total: 873ms	remaining: 4.65s
200:	total: 1.15s	remaining: 4.33s
250:	total: 1.44s	remaining: 4.03s
300:	total: 1.75s	remaining: 3.8s
350:	total: 2.05s	remaining: 3.53s
400:	total: 2.38s	remaining: 3.29s
450:	total: 2.7s	remaining: 3.02s
500:	total: 3.05s	remaining: 2.76s
550:	total: 3.34s	remaining: 2.45s
600:	total: 3.63s	remaining: 2.14s
650:	total: 3.95s	remaining: 1.84s
700:	total: 4.25s	remaining: 1.54s
750:	total: 4.56s	remaining: 1.24s
800:	total: 4.86s	remaining: 934ms
850:	total: 5.16s	remaining: 631ms
900:	total: 5.45s	remaining: 327ms
950:	total: 5.76s	remaining: 24.2ms
954:	total: 5.79s	remaining: 0us
0:	total: 7.16ms	remaining: 6.83s
50:	total: 292ms	remaining: 5.17s
100:	total: 574ms	remaining: 4.86s
150:	total: 863ms	remaining: 4.59s
200:	total: 1.16s	remaining: 4.36s
250:	total: 1.62s	remaining: 4.55s
300:	total: 1.92s	remaining: 4.18s
350:	total: 2.23s	remaining: 3.83s
400:	total: 2.55s	remaining: 3.52s
450:	total: 2.85s	remaining: 3.19s
500:	total: 3.15s	remaining: 2.85s
550:	total: 3.46s	remaining: 2.53s
600:	total: 3.78s	remaining: 2.23s
650:	total: 4.17s	remaining: 1.95s
700:	total: 4.55s	remaining: 1.65s
750:	total: 4.85s	remaining: 1.32s
800:	total: 5.15s	remaining: 990ms
850:	total: 5.46s	remaining: 667ms
900:	total: 5.79s	remaining: 347ms
950:	total: 6.11s	remaining: 25.7ms
954:	total: 6.14s	remaining: 0us
0:	total: 6.64ms	remaining: 6.34s
50:	total: 309ms	remaining: 5.48s
100:	total: 592ms	remaining: 5s
150:	total: 882ms	remaining: 4.7s
200:	total: 1.18s	remaining: 4.44s
250:	total: 1.48s	remaining: 4.14s
300:	total: 1.77s	remaining: 3.84s
350:	total: 2.05s	remaining: 3.53s
400:	total: 2.34s	remaining: 3.23s
450:	total: 2.64s	remaining: 2.95s
500:	total: 2.94s	remaining: 2.66s
550:	total: 3.23s	remaining: 2.37s
600:	total: 3.52s	remaining: 2.08s
650:	total: 3.81s	remaining: 1.78s
700:	total: 4.11s	remaining: 1.49s
750:	total: 4.45s	remaining: 1.21s
800:	total: 4.74s	remaining: 912ms
850:	total: 5.12s	remaining: 626ms
900:	total: 5.48s	remaining: 328ms

[I 2025-11-24 20:52:19,195] Trial 98 finished with value: 0.735779528418887 and parameters: {'weight_pos': 2.1783686296122036, 'iterations': 955, 'learning_rate': 0.05601813234905895, 'depth': 4, 'eval_metric': 'AUC', 'l2_leaf_reg': 27.81360857404398, 'bagging_temperature': 0.8307929633009974, 'rsm': 0.6100440113010361, 'min_data_in_leaf': 87, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

950:	total: 5.78s	remaining: 24.3ms
954:	total: 5.8s	remaining: 0us
0:	total: 7.87ms	remaining: 7.71s
50:	total: 367ms	remaining: 6.69s
100:	total: 727ms	remaining: 6.33s
150:	total: 1.09s	remaining: 6.02s
200:	total: 1.47s	remaining: 5.71s
250:	total: 1.86s	remaining: 5.42s
300:	total: 2.24s	remaining: 5.07s
350:	total: 2.63s	remaining: 4.71s
400:	total: 3.02s	remaining: 4.37s
450:	total: 3.41s	remaining: 4s
500:	total: 3.79s	remaining: 3.63s
550:	total: 4.17s	remaining: 3.25s
600:	total: 4.57s	remaining: 2.89s
650:	total: 4.95s	remaining: 2.51s
700:	total: 5.34s	remaining: 2.13s
750:	total: 5.73s	remaining: 1.75s
800:	total: 6.16s	remaining: 1.38s
850:	total: 6.54s	remaining: 1000ms
900:	total: 6.97s	remaining: 619ms
950:	total: 7.36s	remaining: 232ms
980:	total: 7.6s	remaining: 0us
0:	total: 7.79ms	remaining: 7.63s
50:	total: 375ms	remaining: 6.83s
100:	total: 739ms	remaining: 6.43s
150:	total: 1.1s	remaining: 6.04s
200:	total: 1.57s	remaining: 6.1s
250:	total: 1.97s	remaining: 5.73s
300:	total: 2.34s	remaining: 5.29s
350:	total: 2.72s	remaining: 4.88s
400:	total: 3.09s	remaining: 4.46s
450:	total: 3.48s	remaining: 4.09s
500:	total: 3.85s	remaining: 3.69s
550:	total: 4.23s	remaining: 3.3s
600:	total: 4.6s	remaining: 2.91s
650:	total: 5.05s	remaining: 2.56s
700:	total: 5.46s	remaining: 2.18s
750:	total: 5.88s	remaining: 1.8s
800:	total: 6.28s	remaining: 1.41s
850:	total: 6.7s	remaining: 1.02s
900:	total: 7.14s	remaining: 634ms
950:	total: 7.52s	remaining: 237ms
980:	total: 7.75s	remaining: 0us
0:	total: 9.03ms	remaining: 8.84s
50:	total: 413ms	remaining: 7.52s
100:	total: 862ms	remaining: 7.51s
150:	total: 1.36s	remaining: 7.49s
200:	total: 2.13s	remaining: 8.26s
250:	total: 2.68s	remaining: 7.79s
300:	total: 3.15s	remaining: 7.11s
350:	total: 3.73s	remaining: 6.7s
400:	total: 4.19s	remaining: 6.06s
450:	total: 4.62s	remaining: 5.43s
500:	total: 5.03s	remaining: 4.82s
550:	total: 5.45s	remaining: 4.25s
600:	total: 5.88s	remaining: 3.72s
650:	total: 6.5s	remaining: 3.29s
700:	total: 6.97s	remaining: 2.78s
750:	total: 7.37s	remaining: 2.26s
800:	total: 7.77s	remaining: 1.75s
850:	total: 8.17s	remaining: 1.25s
900:	total: 8.58s	remaining: 762ms
950:	total: 9.03s	remaining: 285ms
980:	total: 9.28s	remaining: 0us
0:	total: 10.9ms	remaining: 10.7s
50:	total: 385ms	remaining: 7.01s
100:	total: 786ms	remaining: 6.84s
150:	total: 1.21s	remaining: 6.65s
200:	total: 1.61s	remaining: 6.27s
250:	total: 1.98s	remaining: 5.75s
300:	total: 2.39s	remaining: 5.39s
350:	total: 2.76s	remaining: 4.95s
400:	total: 3.13s	remaining: 4.53s
450:	total: 3.51s	remaining: 4.12s
500:	total: 3.89s	remaining: 3.73s
550:	total: 4.52s	remaining: 3.53s
600:	total: 4.91s	remaining: 3.11s
650:	total: 5.3s	remaining: 2.69s
700:	total: 5.69s	remaining: 2.27s
750:	total: 6.06s	remaining: 1.85s
800:	total: 6.46s	remaining: 1.45s
850:	total: 6.84s	remaining: 1.04s
900:	total: 7.3s	remaining: 648ms
950:	total: 7.9s	remaining: 249ms
980:	total: 8.3s	remaining: 0us
0:	total: 8.74ms	remaining: 8.56s
50:	total: 424ms	remaining: 7.73s
100:	total: 835ms	remaining: 7.28s
150:	total: 1.21s	remaining: 6.67s
200:	total: 1.63s	remaining: 6.33s
250:	total: 2.01s	remaining: 5.84s
300:	total: 2.41s	remaining: 5.45s
350:	total: 2.8s	remaining: 5.03s
400:	total: 3.17s	remaining: 4.59s
450:	total: 3.55s	remaining: 4.17s
500:	total: 3.95s	remaining: 3.79s
550:	total: 4.35s	remaining: 3.4s
600:	total: 4.72s	remaining: 2.99s
650:	total: 5.1s	remaining: 2.58s
700:	total: 5.64s	remaining: 2.25s
750:	total: 6.18s	remaining: 1.89s
800:	total: 6.58s	remaining: 1.48s
850:	total: 6.98s	remaining: 1.07s
900:	total: 7.37s	remaining: 655ms
950:	total: 7.75s	remaining: 245ms

[I 2025-11-24 20:53:00,863] Trial 99 finished with value: 0.7313288578880418 and parameters: {'weight_pos': 3.2330022549008297, 'iterations': 981, 'learning_rate': 0.058502394201555105, 'depth': 5, 'eval_metric': 'AUC', 'l2_leaf_reg': 23.10403362187623, 'bagging_temperature': 0.9132315226360548, 'rsm': 0.6058219303882414, 'min_data_in_leaf': 89, 'leaf_estimation_iterations': 9}. Best is trial 16 with value: 0.7404863910277388.

980:	total: 8.01s	remaining: 0us

{'weight_pos': 2.2251937977925387,
 'iterations': 990,
 'learning_rate': 0.043521575312755724,
 'depth': 5,
 'eval_metric': 'AUC',
 'l2_leaf_reg': 2.6361802237432617,
 'bagging_temperature': 0.9737877539995844,
 'rsm': 0.43468229033874983,
 'min_data_in_leaf': 31,
 'leaf_estimation_iterations': 3}

In [9]:
from home_works.machine_learning.final_project.util import split_train_test

X_train, X_test, y_train, y_test = split_train_test(X_final, y, balance_classes=False)

In [10]:
best_params

{'weight_pos': 2.2251937977925387,
 'iterations': 990,
 'learning_rate': 0.043521575312755724,
 'depth': 5,
 'eval_metric': 'AUC',
 'l2_leaf_reg': 2.6361802237432617,
 'bagging_temperature': 0.9737877539995844,
 'rsm': 0.43468229033874983,
 'min_data_in_leaf': 31,
 'leaf_estimation_iterations': 3}

In [12]:
from home_works.machine_learning.final_project.util import evaluate_model, split_train_test

best_params["class_weights"] = [1.0, best_params.pop("weight_pos")]
model = CatBoostClassifier(**best_params)

X_train, X_test, y_train, y_test = split_train_test(X_final, y)
evaluate_model(model, X_train, y_train, X_test, y_test, cat_cols=cat_cols)

ValueError: could not convert string to float: 'Qu0qrQKzJV'